### ISSUE TITLE
fmriprep anat placement is unintuitive with multiple sessions

### ISSUE THREAD

**Issue by IanEisenberg** [nipreps/fmriprep#1068]
fmriprep places T1w files in different places depending on the number of T1w images across sessions. If there are multiple T1w images, fmriprep averages them and creates a top level "anat" folder to store the average. When only one session has a T1w image, no top-level folder is created.

(folder structure if ses-1 and ses-2 had a T1w image):
- anat
- ses-1
  - anat
    - affine_transform.txt
- ses-2
  - anat
    - affine_transform.txt

(folder structure if only ses-1 had a T1w image):
- ses-1
  - anat
- ses-2

Considering that both sessions are referencing the same T1w image regardless, I think it'd make sense to move the T1w image to a top level anat folder in the second case.

**Comment by effigies** [comment]
Ah, this is going to be a function of the source filename. When there's only one, we don't bother manipulating it to find a "common" name. We should probably just always pop the session out.
