### ISSUE TITLE
Generate carpetplots even if MNI is not one of the output spaces

### ISSUE THREAD

**Issue by oesteban** [nipreps/fmriprep#1119]
Right now, as it needs an atlas to grab labels from, this output space is necessary.

**Comment by effigies** [comment]
We should consider making a separate `normalize` flag, that ensures the T1-MNI transform gets calculated, even if no outputs are in that space. AROMA, SyN-SDC and now carpetplots all require this transform to exist.

**Comment by effigies** [comment]
Actually, I guess if carpetplots are always produced, then it's even easier: don't ever disable T1w-MNI registration, even if we don't save the registered series as derivatives.

**Comment by oesteban** [comment]
That has been my temptation forever. But #808.

**Comment by effigies** [comment]
In that case, does it make sense to do EPI-MNI directly? The templates exist.

**Comment by oesteban** [comment]
True that.

**Comment by tsalo** [comment]
I believe MNI152NLin2009cAsym is automatically included as an internal transform target at this point, so I think this can be closed.

**Comment by effigies** [comment]
It is.
