### ISSUE TITLE
Allow choosing --aroma-melodic-dimensionality for each functional scan

### ISSUE THREAD

**Issue by czarrar** [nipreps/fmriprep#1205]
Is it possible to select the melodic dimensionality for each functional scan separately? This would especially be useful if the scans have very different timings and other parameters.

**Comment by effigies** [comment]
If each has a different task name, then you can use the `-t <task_name>` flag to run fMRIPrep separately for each task name, and you can use any parameters you like in these separate runs.

This may result in inconsistencies in the reports. Please let us know how this works out for you, and if there are any improvements that can be made in reporting, under these circumstances.

**Comment by effigies** [comment]
We're removing ICA-AROMA. This can be handled by a post-fMRIPrep tool.
