### ISSUE TITLE
Grand mean scaling

### ISSUE THREAD

**Issue by chrisgorgo** [nipreps/fmriprep#1210]
It would be beneficial to add grand mean scaling to all outputs:

From http://mindhive.mit.edu/node/71
> grand mean scaling: An analysis step in which the voxel values in every image are divided by the average global mean intensity of the whole session. This effectively removes any mean global differences in intensity between sessions. This is different than global scaling! This step makes a good deal of sense in fMRI, because differences between sessions can be substantial. By performing it at the first (within-subject) level, as well, it means you don't have to do it at the second (between-subject) level, since the between-subject differences are already removed as well. This step is performed by default by all the major analysis software packages.

**Comment by ilyaveer** [comment]
FSL standardly scales the time series around 10.000 after all preprocessing steps have been done (but likely before ICA-AROMA):

1) meanintensity=`fslstats prefiltered_func_data_st -k mask -p 50` (on the non-smoothed 4D image)

2) inscalefactor=`python -c "print((10000/$meanintensity))"`

3) fslmaths prefiltered_func_data_smooth -mul $inscalefactor filtered_func_data

**Comment by oesteban** [comment]
I think J. Power does a similar scaling (although it might be around 1000) so that BOLD changes can be read as percentage change.

**Comment by PaulZhutovsky** [comment]
I stumbled over this old issue and was wondering whether grand mean scaling is **not** applied by fmriprep before ICA-AROMA is run? Because the original [AROMA paper ](https://www.sciencedirect.com/science/article/pii/S1053811915001822#f0005) was suggesting to do so. 

Could you please clarify?

**Comment by ilyaveer** [comment]
As far as I understood, fmriprep has no grand mean scaling implemented yet. I'm not sure whether it is necessary to do this before ICA-AROMA per se, as the ICA is run on a single run/subject, but I think it would be most logical to do it before in any case.

**Comment by PaulZhutovsky** [comment]
Ok that is good to know. Maybe @maartenmennes could comment whether the grand mean scaling step is absolutely required before running ICA-AROMA?

**Comment by oesteban** [comment]
Pinging @rciric

**Comment by jdkent** [comment]
AFAIK grand mean scaling does not impact ICA-AROMA's performance, but since this has been a requested feature for while I can take a stab at it.

**Comment by effigies** [comment]
#1945 was closed because it was not clear that there's a use case where this can't be done post-fMRIPrep. We can reopen this if someone can make a good argument, but this is not planned at this time.
