### ISSUE TITLE
Rethink the BOLD workflow organization

### ISSUE THREAD

**Issue by effigies** [nipreps/fmriprep#1294]
Reviewing #1263, it's getting very hard to keep track of everything involved in the BOLD workflow. This makes me worry about maintainability and how easy it will be for new contributors to get going, or independent reviewers to assess the pipeline.

![img](https://fmriprep.readthedocs.io/en/latest/workflows-4.png)

Perhaps it would be better to move to the following organization:

1) Within-BOLD sub-workflow
* STC
* HMC
* SDC
* Multi-echo combination
2) BOLD-T1w sub-workflow
3) BOLD-MNI sub-workflow
4) BOLD-surface sub-workflow

These would connect as follows:

```
  1
  |
  2
 / \
3   4
```

Each sub-workflow would pass off a transform list and make available the appropriate intermediate data. So instead of T1w knowing whether SDC is to be applied, it would receive a BOLD series and a BOLD-BOLD transform list, to which it appends the BOLD-T1w transform and then applies. Similarly, as a tedana optimal combination BOLD series is, as currently implemented, already motion corrected and SDC'd, BOLD-T1w would get the optimal combination and an empty transform list, and thus only apply that correction. If we can get to the point where tedana can meaningfully be considered a transform, we can then begin sending deconstructed data/transforms again.

I think this abstraction will allow us to get away with a lot less `if`/`else` branching, and keep the decisions more localized. I think this separation will also help draw better lines in the documentation, which will benefit maintainers, contributors and reviewers.

Comments welcome, but especially @emdupre does this sound like it would be helpful, counterproductive, or neutral with respect to your efforts?

Also, I'm not sure when we'd have time to rearchitect this, but I want to start the conversation while my brain is here.

**Comment by emdupre** [comment]
I think spending some time re-thinking the workflow structure could be hugely valuable.

I share concerns about the current sustainability of and onboarding to the code base, as I feel like I have encountered both of those problems in trying to integrate ME-EPI. I'd like to see #1263 merged before a larger refactor-- selfishly, just since I've already spent so much time understanding the current architecture-- but think this would be hugely valuable for ongoing development.

And, on another personal note, I think a simplified structure would make me more comfortable offering support on e.g., NeuroStars, since at present I am often worried I don't fully understand some other aspect of the workflow(s) I have not modified directly.

**Comment by effigies** [comment]
>  I'd like to see #1263 merged before a larger refactor-- selfishly, just since I've already spent so much time understanding the current architecture

Absolutely.

**Comment by effigies** [comment]
I've looked into this a little. I think we're going to need to rethink how we do the reference image estimation, especially with the multiecho components.

Right now, multiecho uses the estimation of volumes to skip, but not the validated/xform-corrected BOLD image or reference image. So that's wasted computation on the one hand and a lack of validation on the other.

One complicating factor is that we'll need iterables over all echoes but non-steady-state detection on the shortest echo only. I think perhaps the way to do this is something like:

```Python
validation = pe.MapNode(ValidateImage(), iterfield='in_file', ...)
shortest_echo = pe.Node(Select(index=...), ...)
all_echoes = pe.Node(Select(), iterables=('index', range(len(bold_file))), ...)

workflow.connect(validation, 'out_file', shortest_echo, 'in_list')
workflow.connect(validation, 'out_file', all_echoes, 'in_list')
```

I think using this approach, we can reduce the number of `if multiecho` branchings we need, letting `all_echoes` be an iterable with only one entry.
