### ISSUE TITLE
Creating workflows is surprisingly slow

### ISSUE THREAD

**Issue by chrisgorgo** [nipreps/fmriprep#1415]
It takes 6-7 sec to create a workflow for a single bold run. This means that if I have a dataset with 10 subejcts, 2 sessions and 5 runs (ds000114) it will take almost 12 minutes until the combined workflow will start running.

I suspect that repetetive indexing via pybids might be the cause.

**Comment by oesteban** [comment]
@effigies is there a way that we can multithread pybids reusing an existing ProcessPool?

**Comment by effigies** [comment]
If bids-standard/pybids#285 is any indication, the bottleneck is actually a huge number of calls to `os.stat`, which isn't going to parallelize well, as filesystem syscalls will end up serialized by the kernel.
