### ISSUE TITLE
Convert metadata for sparsely acquired BOLD series

### ISSUE THREAD

**Issue by effigies** [nipreps/fmriprep#1549]
There are four ways to specify a sparse acquisition paradigm, and we need to handle them appropriately:

| Specification | Action needed |
|-|-|
| `RepetitionTime` + `SliceTiming` | Convert `SliceTiming` to `DelayTime` |
| `RepetitionTime` + `DelayTime` | Copy `DelayTime` to derivative BOLD |
| `VolumeTiming` + `SliceTiming` | Copy `VolumeTiming`, convert `SliceTiming` to `AcquisitionDuration` |
| `VolumeTiming` + `AcquisitionDuration` | Copy `VolumeTiming` and `AcquisitionDuration` |

Exactly one of `RepetitionTime` and `VolumeTiming` is required by the spec. If `VolumeTiming` is defined, then `SliceTiming` or `AcquisitionDuration` is required. If `RepetitionTime` does not require `SliceTiming` or `DelayTime`, in which case the acquisition is presumed continuous.

Relation between `SliceTiming`, `AcquisitionDuration` and `DelayTime`:

```Python
sorted_times = sorted(SliceTiming)
# Assuming constant slice-acquisition interval, add interval and final onset
AcquisitionDuration = (SliceTiming[1] - SliceTiming[0]) + SliceTiming[-1]
DelayTime = RepetitionTime - AcquisitionDuration
```

Note that `AcquisitionDuration` is mutually exclusive metadata with `RepetitionTime`, simply to reduce the number of valid ways of specifying sparse acquisition. Annoying, but important to be clear on.

More esoteric volume acquisition protocols, such as non-constant inter-slice intervals, are probably best left to future consideration.

Another thing to consider is whether conversions between these different forms should be packed into pybids, but that I think should be lower priority than just getting this working here.

Follow-up to #1384.

**Comment by oesteban** [comment]
I think fMRIPrep would not be able to process any data if `RepetitionTime` is not set, am I wrong?

**Comment by effigies** [comment]
Well, we should probably handle `VolumeTiming` cases eventually, but yeah, I guess for now we only need to consider the first two cases.

**Comment by effigies** [comment]
This is implemented, opening a new issue for handling non-RepetitionTime BOLD series.
