### ISSUE TITLE
Lesion masks in the input directory result in a crash triggered by bids-validator.

### ISSUE THREAD

**Issue by danlurie** [nipreps/fmriprep#1572]
We currently look for lesion masks in the `/anat` subdirectory of the BIDS raw data folder (https://fmriprep.readthedocs.io/en/stable/workflows.html#t1w-t2w-preprocessing). This now appears to cause `fmriprep` to crash on initialization because `bids-validator` does not recognize these files, as they are not strictly speaking included in the spec. 

At some point we should refactor the data scraper to look for the lesion masks somewhere else (after deciding the most appropriate place for them to live), but in the meantime one can use a .bidsignore to get around this. I'll add a note about this to the lesion preproc section of the docs.

(I know that the dataset is valid other than this issue.)

Update: Forgot to mention that this is version 1.3.2 running via Singularity.

**Comment by danlurie** [comment]
Just realized I could use a `.bidsignore` to get around this for now. I'll add a note about this to the lesion preproc section of the docs.

**Comment by oesteban** [comment]
Very looking forward to the updated docs! Thanks!

**Comment by effigies** [comment]
Bidsignore is mentioned in the docs.
