### ISSUE TITLE
Edge mask regressor

### ISSUE THREAD

**Issue by oesteban** [nipreps/fmriprep#1634]
Suggestion from Cesar Caballero: http://europepmc.org/articles/pmc4652211

**Comment by rciric** [comment]
Implementation should be straightforward: we'd basically just need to compute the edge mask as the difference between a dilated brain mask and the brain mask itself and submit this mask to another CompCor. The only potential point of confusion is:

> Finally, voxels from the resulting edge voxel mask intersecting with the subject's anatomy mask were excluded to ensure that the final edge voxel mask did not include voxel inside the brain incorrectly classified as “edge voxels.”

My interpretation is that they initially use the functional mask to produce an initial edge mask, and subsequently use the coregistration to transform the anatomical mask into the same space. They then refine the initial edge mask by removing any voxels in the transformed anatomical mask.

I only skimmed the paper, but I'm surprised by how high the FD-DVARS correlations are after GSR. The results on the whole are promising, and it'd be great to see if they can be replicated in a larger dataset with more rigorous benchmarks. In any case, I think this enhancement would be warranted given the relative ease of implementation.

**Comment by oesteban** [comment]
> My interpretation is that they initially use the functional mask to produce an initial edge mask, and subsequently use the coregistration to transform the anatomical mask into the same space. They then refine the initial edge mask by removing any voxels in the transformed anatomical mask.

I take the same from that paragraph. We can easily do this, as both masks are available. I would imagine we want to use the BOLD mask for when there are susceptibility distortions, and the anatomical mask for the reasons above. Instead of subtracting, starting from the union of those and then doing the dilation and subtraction should yield more stable results.
