### ISSUE TITLE
reports unsuccessful finish but exit code is 0

### ISSUE THREAD

**Issue by yarikoptic** [nipreps/fmriprep#1793]
My command was 
```
$> containers/scripts/singularity_cmd run containers/images/bids/bids-fmriprep--1.5.0.sing . 'derivatives/fmriprep-1.5.0/' participant --participant-label 'rid000001' -w derivatives/work --notrack --skull-strip-fixed-seed --ignore slicetiming --fs-license-file=containers/licenses/freesurfer --bold2t1w-dof 9 --output-spaces fsnative fsaverage fsaverage6 fsaverage5 anat func MNI152NLin2009cAsym --n_cpus 1 --nthreads 1 --omp-nthreads 12 2>&1 | tee manual-rerun1.log
```
(see https://github.com/poldracklab/fmriprep/issues/1787 for the setup, `sourcedata/` folder was removed to avoid that issue).

The ending looked like
```
...
  betas = np.linalg.lstsq(X, data.T)[0]
/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/contour.py:1173: UserWarning: No contour levels were found within the data range.
  warnings.warn("No contour levels were found"
Preprocessing did not finish successfully. Errors occurred while processing data from participants: rid000001 (4). Check the HTML reports for details.
containers/scripts/singularity_cmd run  . 'derivatives/fmriprep-1.5.0/'    -w  792.27s user 21.81s system 2% cpu 8:44:21.82 total
tee manual-rerun1.log  0.02s user 0.16s system 0% cpu 8:44:21.86 total
amanelis has logged off pts/0 from 128.147.28.63.
(dev3) 2 12863.....................................:Thu 26 Sep 2019 06:55:52 AM EDT:.
(git)smaug:/mnt/btrfs/datasets/datalad/crawl/labs/haxby/life[master]git
```
so I got back into the prompt and exit code from fmriprep invocation was 0 (not reported otherwise).  Full log is at http://www.onerussian.com/tmp/manual-rerun1.log

Here is the .html: http://www.onerussian.com/tmp/sub-rid000001.html which
<details>
<summary>shows errors</summary> 
<div id="errors">
    <h1 class="sub-report-title">Errors</h1>
    <ul>
        <li>
        <div class="nipype_error">
            Node Name: <a target="_self" onclick="toggle('/mnt/btrfs/datasets/datalad/crawl/labs/haxby/life/derivatives/fmriprep-150/fmriprep/sub-rid000001/log/20190926-021141_99cbb476-77bf-493a-8fb2-0670f8abe427/crash-20190926-093911-yoh-select_std-e28e2171-3b18-4837-8aa9-d65d186ff5aatxt_details_id');">fmriprep_wf.single_subject_rid000001_wf.func_preproc_task_life_acq_412vol_run_04_wf.carpetplot_wf.select_std</a><br>
            <div id="/mnt/btrfs/datasets/datalad/crawl/labs/haxby/life/derivatives/fmriprep-150/fmriprep/sub-rid000001/log/20190926-021141_99cbb476-77bf-493a-8fb2-0670f8abe427/crash-20190926-093911-yoh-select_std-e28e2171-3b18-4837-8aa9-d65d186ff5aatxt_details_id" style="display:none">
            File: <code>/mnt/btrfs/datasets/datalad/crawl/labs/haxby/life/derivatives/fmriprep-1.5.0/fmriprep/sub-rid000001/log/20190926-021141_99cbb476-77bf-493a-8fb2-0670f8abe427/crash-20190926-093911-yoh-select_std-e28e2171-3b18-4837-8aa9-d65d186ff5aa.txt</code><br>
            Working Directory: <code>/mnt/btrfs/datasets/datalad/crawl/labs/haxby/life/derivatives/work/fmriprep_wf/single_subject_rid000001_wf/func_preproc_task_life_acq_412vol_run_04_wf/carpetplot_wf/select_std</code><br>
            Inputs: <br>
            <ul>
                <li>key: <code>MNI152NLin2009cAsym</code></li>
                <li>keys: <code>['fsaverage', 'fsaverage6', 'fsaverage5', 'MNI152NLin2009cAsym']</code></li>
                <li>std2anat_xfm: <code>['/mnt/btrfs/datasets/datalad/crawl/labs/haxby/life/derivatives/work/fmriprep_wf/single_subject_rid000001_wf/anat_preproc_wf/anat_norm_wf/_template_MNI152NLin2009cAsym/registration/ants_t1_to_mniInverseComposite.h5']</code></li>
            </ul>
            <pre>Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 316, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 473, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 564, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 649, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 378, in run
    outputs = self.aggregate_outputs(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 455, in aggregate_outputs
    predicted_outputs = self._list_outputs()  # Predictions from _list_outputs
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/utility.py", line 152, in _list_outputs
    for k in self._fields}
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/utility.py", line 152, in <dictcomp>
    for k in self._fields}
IndexError: list index out of range</pre>
            </div>
        </div>
        </li>
        <li>
        <div class="nipype_error">
            Node Name: <a target="_self" onclick="toggle('/mnt/btrfs/datasets/datalad/crawl/labs/haxby/life/derivatives/fmriprep-150/fmriprep/sub-rid000001/log/20190926-021141_99cbb476-77bf-493a-8fb2-0670f8abe427/crash-20190926-093911-yoh-select_std-0f594992-0ee7-4792-8d75-6abba967243btxt_details_id');">fmriprep_wf.single_subject_rid000001_wf.func_preproc_task_life_acq_377vol_run_03_wf.carpetplot_wf.select_std</a><br>
            <div id="/mnt/btrfs/datasets/datalad/crawl/labs/haxby/life/derivatives/fmriprep-150/fmriprep/sub-rid000001/log/20190926-021141_99cbb476-77bf-493a-8fb2-0670f8abe427/crash-20190926-093911-yoh-select_std-0f594992-0ee7-4792-8d75-6abba967243btxt_details_id" style="display:none">
            File: <code>/mnt/btrfs/datasets/datalad/crawl/labs/haxby/life/derivatives/fmriprep-1.5.0/fmriprep/sub-rid000001/log/20190926-021141_99cbb476-77bf-493a-8fb2-0670f8abe427/crash-20190926-093911-yoh-select_std-0f594992-0ee7-4792-8d75-6abba967243b.txt</code><br>
            Working Directory: <code>/mnt/btrfs/datasets/datalad/crawl/labs/haxby/life/derivatives/work/fmriprep_wf/single_subject_rid000001_wf/func_preproc_task_life_acq_377vol_run_03_wf/carpetplot_wf/select_std</code><br>
            Inputs: <br>
            <ul>
                <li>key: <code>MNI152NLin2009cAsym</code></li>
                <li>keys: <code>['fsaverage', 'fsaverage6', 'fsaverage5', 'MNI152NLin2009cAsym']</code></li>
                <li>std2anat_xfm: <code>['/mnt/btrfs/datasets/datalad/crawl/labs/haxby/life/derivatives/work/fmriprep_wf/single_subject_rid000001_wf/anat_preproc_wf/anat_norm_wf/_template_MNI152NLin2009cAsym/registration/ants_t1_to_mniInverseComposite.h5']</code></li>
            </ul>
            <pre>Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 316, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 473, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 564, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 649, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 378, in run
    outputs = self.aggregate_outputs(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 455, in aggregate_outputs
    predicted_outputs = self._list_outputs()  # Predictions from _list_outputs
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/utility.py", line 152, in _list_outputs
    for k in self._fields}
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/utility.py", line 152, in <dictcomp>
    for k in self._fields}
IndexError: list index out of range</pre>
            </div>
        </div>
        </li>
        <li>
        <div class="nipype_error">
            Node Name: <a target="_self" onclick="toggle('/mnt/btrfs/datasets/datalad/crawl/labs/haxby/life/derivatives/fmriprep-150/fmriprep/sub-rid000001/log/20190926-021141_99cbb476-77bf-493a-8fb2-0670f8abe427/crash-20190926-093911-yoh-select_std-d92d6735-946c-4af0-af88-512b9020f3d9txt_details_id');">fmriprep_wf.single_subject_rid000001_wf.func_preproc_task_life_acq_374vol_run_01_wf.carpetplot_wf.select_std</a><br>
            <div id="/mnt/btrfs/datasets/datalad/crawl/labs/haxby/life/derivatives/fmriprep-150/fmriprep/sub-rid000001/log/20190926-021141_99cbb476-77bf-493a-8fb2-0670f8abe427/crash-20190926-093911-yoh-select_std-d92d6735-946c-4af0-af88-512b9020f3d9txt_details_id" style="display:none">
            File: <code>/mnt/btrfs/datasets/datalad/crawl/labs/haxby/life/derivatives/fmriprep-1.5.0/fmriprep/sub-rid000001/log/20190926-021141_99cbb476-77bf-493a-8fb2-0670f8abe427/crash-20190926-093911-yoh-select_std-d92d6735-946c-4af0-af88-512b9020f3d9.txt</code><br>
            Working Directory: <code>/mnt/btrfs/datasets/datalad/crawl/labs/haxby/life/derivatives/work/fmriprep_wf/single_subject_rid000001_wf/func_preproc_task_life_acq_374vol_run_01_wf/carpetplot_wf/select_std</code><br>
            Inputs: <br>
            <ul>
                <li>key: <code>MNI152NLin2009cAsym</code></li>
                <li>keys: <code>['fsaverage', 'fsaverage6', 'fsaverage5', 'MNI152NLin2009cAsym']</code></li>
                <li>std2anat_xfm: <code>['/mnt/btrfs/datasets/datalad/crawl/labs/haxby/life/derivatives/work/fmriprep_wf/single_subject_rid000001_wf/anat_preproc_wf/anat_norm_wf/_template_MNI152NLin2009cAsym/registration/ants_t1_to_mniInverseComposite.h5']</code></li>
            </ul>
            <pre>Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 316, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 473, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 564, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 649, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 378, in run
    outputs = self.aggregate_outputs(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 455, in aggregate_outputs
    predicted_outputs = self._list_outputs()  # Predictions from _list_outputs
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/utility.py", line 152, in _list_outputs
    for k in self._fields}
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/utility.py", line 152, in <dictcomp>
    for k in self._fields}
IndexError: list index out of range</pre>
            </div>
        </div>
        </li>
        <li>
        <div class="nipype_error">
            Node Name: <a target="_self" onclick="toggle('/mnt/btrfs/datasets/datalad/crawl/labs/haxby/life/derivatives/fmriprep-150/fmriprep/sub-rid000001/log/20190926-021141_99cbb476-77bf-493a-8fb2-0670f8abe427/crash-20190926-093911-yoh-select_std-fa2ad941-7dbe-46fa-9285-8e82ac3f608ctxt_details_id');">fmriprep_wf.single_subject_rid000001_wf.func_preproc_task_life_acq_346vol_run_02_wf.carpetplot_wf.select_std</a><br>
            <div id="/mnt/btrfs/datasets/datalad/crawl/labs/haxby/life/derivatives/fmriprep-150/fmriprep/sub-rid000001/log/20190926-021141_99cbb476-77bf-493a-8fb2-0670f8abe427/crash-20190926-093911-yoh-select_std-fa2ad941-7dbe-46fa-9285-8e82ac3f608ctxt_details_id" style="display:none">
            File: <code>/mnt/btrfs/datasets/datalad/crawl/labs/haxby/life/derivatives/fmriprep-1.5.0/fmriprep/sub-rid000001/log/20190926-021141_99cbb476-77bf-493a-8fb2-0670f8abe427/crash-20190926-093911-yoh-select_std-fa2ad941-7dbe-46fa-9285-8e82ac3f608c.txt</code><br>
            Working Directory: <code>/mnt/btrfs/datasets/datalad/crawl/labs/haxby/life/derivatives/work/fmriprep_wf/single_subject_rid000001_wf/func_preproc_task_life_acq_346vol_run_02_wf/carpetplot_wf/select_std</code><br>
            Inputs: <br>
            <ul>
                <li>key: <code>MNI152NLin2009cAsym</code></li>
                <li>keys: <code>['fsaverage', 'fsaverage6', 'fsaverage5', 'MNI152NLin2009cAsym']</code></li>
                <li>std2anat_xfm: <code>['/mnt/btrfs/datasets/datalad/crawl/labs/haxby/life/derivatives/work/fmriprep_wf/single_subject_rid000001_wf/anat_preproc_wf/anat_norm_wf/_template_MNI152NLin2009cAsym/registration/ants_t1_to_mniInverseComposite.h5']</code></li>
            </ul>
            <pre>Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 316, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 473, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 564, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 649, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 378, in run
    outputs = self.aggregate_outputs(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 455, in aggregate_outputs
    predicted_outputs = self._list_outputs()  # Predictions from _list_outputs
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/utility.py", line 152, in _list_outputs
    for k in self._fields}
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/utility.py", line 152, in <dictcomp>
    for k in self._fields}
IndexError: list index out of range</pre>
            </div>
        </div>
        </li>
    </ul>
</div>

</details>

seems to be all relating to the same

```
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 316, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 473, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 564, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 649, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 378, in run
    outputs = self.aggregate_outputs(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 455, in aggregate_outputs
    predicted_outputs = self._list_outputs()  # Predictions from _list_outputs
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/utility.py", line 152, in _list_outputs
    for k in self._fields}
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/utility.py", line 152, in 
    for k in self._fields}
IndexError: list index out of range
```

Should they be ignored or somehow mitigated?

**Comment by yarikoptic** [comment]
Never trusting anyone (including myself) I thought that the issue might be in our singularity shim script, 

<details>
<summary>but it seems to return error from underlying execution just fine</summary> 

```shell
$> containers/scripts/singularity_cmd run containers/images/bids/bids-fmriprep--1.5.0.sing lasjdl lkjasldkfjas aslkdjflskajf
usage: fmriprep [-h] [--version] [--skip_bids_validation]                                                                   
                [--participant_label PARTICIPANT_LABEL [PARTICIPANT_LABEL ...]]
                [-t TASK_ID] [--echo-idx ECHO_IDX] [--nthreads NTHREADS]
                [--omp-nthreads OMP_NTHREADS] [--mem_mb MEM_MB] [--low-mem]
                [--use-plugin USE_PLUGIN] [--anat-only] [--boilerplate]
                [--ignore-aroma-denoising-errors] [--error-on-aroma-warnings]
                [-v] [--debug]
                [--ignore {fieldmaps,slicetiming,sbref} [{fieldmaps,slicetiming,sbref} ...]]
                [--longitudinal] [--t2s-coreg]
                [--output-spaces OUTPUT_SPACES [OUTPUT_SPACES ...]]
                [--output-space {T1w,template,fsnative,fsaverage,fsaverage6,fsaverage5} [{T1w,template,fsnative,fsaverage,fsaverage6,fsaverage5} ...]]
                [--template {MNI152NLin2009cAsym}]
                [--template-resampling-grid TEMPLATE_RESAMPLING_GRID]
                [--bold2t1w-dof {6,9,12}] [--force-bbr] [--force-no-bbr]
                [--medial-surface-nan] [--dummy-scans DUMMY_SCANS]
                [--use-aroma]
                [--aroma-melodic-dimensionality AROMA_MELODIC_DIMENSIONALITY]
                [--return-all-components]
                [--fd-spike-threshold FD_SPIKE_THRESHOLD]
                [--dvars-spike-threshold DVARS_SPIKE_THRESHOLD]
                [--skull-strip-template SKULL_STRIP_TEMPLATE]
                [--skull-strip-fixed-seed] [--fmap-bspline] [--fmap-no-demean]
                [--use-syn-sdc] [--force-syn] [--fs-license-file PATH]
                [--no-submm-recon] [--cifti-output | --fs-no-reconall]
                [-w WORK_DIR] [--resource-monitor] [--reports-only]
                [--run-uuid RUN_UUID] [--write-graph] [--stop-on-first-crash]
                [--notrack] [--sloppy]
                bids_dir output_dir {participant}
fmriprep: error: argument analysis_level: invalid choice: 'aslkdjflskajf' (choose from 'participant')
containers/scripts/singularity_cmd run  lasjdl lkjasldkfjas aslkdjflskajf  3.21s user 2.27s system 92% cpu 5.918 total
(dev3) 2 12876 ->2.....................................:Thu 26 Sep 2019 09:03:17 AM EDT:.
(git)smaug:/mnt/btrfs/datasets/datalad/crawl/labs/haxby/life[master]git
```

see `->2` above

</details>

**Comment by yarikoptic** [comment]
ok, since it is of concern to `carpetplot_wf`, I will assume that I can live with that and will now run across all subjects ;)

**Comment by oesteban** [comment]
I'll leave this one open - zero should not be returned if an error condition happened.

That said, the carpetplot problem you hit was fixed with #1755.

**Comment by yarikoptic** [comment]
Thank you @oesteban!

**Comment by effigies** [comment]
This can be reopened if it's still happening, but it's doing nobody any good in a pile of >300 open issues.
