### ISSUE TITLE
improve ICA-AROMA documentation

### ISSUE THREAD

**Issue by jdkent** [nipreps/fmriprep#1804]
Make the process for ICA-AROMA clearer. Ex. what was done to the data before being passed through ICA-AROMA, what was done to the data after ICA-AROMA, and how does ICA-AROMA relate to the other confounds generated.

## sources to pull from
- [effigies comment](https://github.com/poldracklab/fmriprep/issues/817#issuecomment-535959014)
- [jdkent comment](https://github.com/poldracklab/fmriprep/issues/817#issuecomment-535964672)
- [neurostars post](https://neurostars.org/t/fmriprep-ica-aroma-filtering-including-wm-csf-etc-confounds-in-fsl-regfilt/3137/3?u=jdkent)

**Comment by jdkent** [comment]
Also [this section](https://fmriprep.readthedocs.io/en/1.5.0/workflows.html#ica-aroma) is out of date (using fmriprep outputs from before 1.2.0)

[pointed out on neurostars](https://neurostars.org/t/fmriprep-ica-aroma/5338?u=jdkent)

**Comment by oesteban** [comment]
@jdkent has this been addressed?

**Comment by jdkent** [comment]
not entirely yet no.

**Comment by FL33TW00D** [comment]
Another helpful source:
 https://sarenseeley.github.io/BIDS-fmriprep-MRIQC.html#are_confounds_in_the_confoundstsv_file_generated_after_ica-aroma_or_before
