### ISSUE TITLE
UNC infant atlas

### ISSUE THREAD

**Issue by ajdneuro12** [nipreps/fmriprep#1837]
Hello,

I saw the UNC infant atlases on template flow. Is this option working currently? I get an error when I specify 'UNCInfant' or 'UNCInfant:cohort-1' as an output space. Thank you so much for the developments related to infant imaging!

Best,
Alex

**Comment by oesteban** [comment]
Not yet. I'm working on it. Basically, I need to generate a low resolution version of the templates for it to be usable with fMRIPrep.

**Comment by effigies** [comment]
@mgxd Is this already what nibabies uses?

**Comment by mgxd** [comment]
Yes, this is already used as the default skullstripping template in https://github.com/nipreps/nibabies
