### ISSUE TITLE
Pare down top-level table-of-contents

### ISSUE THREAD

**Issue by effigies** [nipreps/fmriprep#1859]
Right now the top-level ToC is:

*    Installation
*    Usage Notes
*    Running fMRIPrep via Docker containers
*    Running fMRIPrep via Singularity containers
*    Processing pipeline details
*    Susceptibility Distortion Correction (SDC)
*    Outputs of fMRIPrep
*    Defining standard and nonstandard spaces where data will be resampled
*    FAQ, Tips, and Tricks
*    Contributing to FMRIPREP
*    Citing fMRIPrep
*    API
*    What’s new

This is a lot to look through, and a pretty serious mixing of broad categories and specific issues. This conversation began in #1802, which was an attempt to deal with a rash of permissions issues faced by Singularity users, mostly related to TemplateFlow. In https://github.com/poldracklab/fmriprep/pull/1802#issuecomment-538131273, it was decided to defer another round of reorganization until today.

I would propose the following top-level structure:

* Installing and Running
* Processing Pipeline Details
* Inputs, Outputs and Templates
* Contributing
* Citing
* FAQ
* API

Specifically, in the previous issue I proposed the following:

* Installing and Running 
  * [Installation](https://4192-53608443-gh.circle-artifacts.com/0/tmp/src/fmriprep/docs/_build/html/installation.html) (subpage)
    * pip install fmriprep
    * pip install fmriprep-docker
    * docker pull
    * docker build (might just link out to contributors)
    * Fetch singularity (I guess from docker hub)
    * Build singularity (`singularity build` and `docker2singularity`)
  * Running fMRIPrep (subpage - mostly just the current [usage notes](https://4192-53608443-gh.circle-artifacts.com/0/tmp/src/fmriprep/docs/_build/html/usage.html))
  * [Running fMRIPrep via Docker containers](https://4192-53608443-gh.circle-artifacts.com/0/tmp/src/fmriprep/docs/_build/html/docker.html) (subpage)
  * [Running fMRIPrep via Singularity containers](https://4192-53608443-gh.circle-artifacts.com/0/tmp/src/fmriprep/docs/_build/html/singularity.html) (subpage)
* Processing pipeline details
* ...

I can flesh this out further in comments, but I want to start this conversation now.

**Comment by effigies** [comment]
A full ToC:

* Installing and Running
  * [Installation](https://fmriprep.readthedocs.io/en/latest/installation.html) (subpage)
    * pip install fmriprep
    * pip install fmriprep-docker
    * docker pull
    * docker build (might just link out to contributors)
    * Fetch singularity (I guess from docker hub)
    * Build singularity (`singularity build` and `docker2singularity`)
  * Running fMRIPrep (subpage - mostly just the current [usage notes](https://fmriprep.readthedocs.io/en/latest/usage.html))
  * [Running fMRIPrep via Docker containers](https://fmriprep.readthedocs.io/en/latest/docker.html) (subpage)
  * [Running fMRIPrep via Singularity containers](https://fmriprep.readthedocs.io/en/latest/singularity.html) (subpage)
* Processing pipeline details
  * [Anatomical preprocessing](https://fmriprep.readthedocs.io/en/latest/workflows.html#t1w-t2w-preprocessing)
  * [BOLD preprocessing](https://fmriprep.readthedocs.io/en/latest/workflows.html#bold-preprocessing)
  * [Susceptibility distortion correction](https://fmriprep.readthedocs.io/en/latest/sdc.html)
* Inputs, Outputs and Templates
  * Inputs: BIDS, Pre-run FreeSurfer, touch on TemplateFlow (subpage)
  * [Outputs](https://fmriprep.readthedocs.io/en/latest/outputs.html) (subpage)
  * [Spaces and Templates](https://fmriprep.readthedocs.io/en/latest/spaces.html) (subpage)
* [Contributing](https://fmriprep.readthedocs.io/en/latest/contributors.html)
* [Citing](https://fmriprep.readthedocs.io/en/latest/citing.html)
* [FAQ](https://fmriprep.readthedocs.io/en/latest/faq.html)
* [API](https://fmriprep.readthedocs.io/en/latest/api/index.html)

**Comment by jdkent** [comment]
I agree with this overall structure. :+1: 

Side Note:
I think API has a lot of great information for users (the doc strings give good conceptual overviews of the workflows), but I'm afraid most will not think to look there (API connotes highly technical to me).

The solution I see would be to reference the API in other sections where appropriate to guide people to know how a workflow is constructed.

**Comment by oesteban** [comment]
I think with 21.x we should address this issue. After all, it doesn't really require generating new documentation, but rather reorganizing existing contents.

One large change w.r.t. when this was proposed is that many sections describing the execution of containers and community/contribution guidelines have been migrated to nipreps.org (cf. #2469).

I would propose the following, based on the latest draft from Chris:

- About/Home (landing page, doesn't have an entry in the menu)
  - README import (as it is now)
  - Licensing (I'll add this into #2325)
  - Citing/boilerplate (will require creating some specific subsection about boilerplates at nipreps.org).
- Installing and Running
    - Installation (subpage)
            pip install fmriprep
            pip install fmriprep-docker
            docker pull
            Other (links to nipreps.org, including docker build, fetch singularity and build singularity)
    - Running fMRIPrep (subpage - mostly just the current usage notes)
    - Running containers (subpage - mostly just like current docs after #2469 was merged)
- Processing pipeline details
    - Anatomical preprocessing
    - BOLD preprocessing
    - Susceptibility distortion correction
- Inputs, Outputs and Templates
    - Inputs: BIDS, Pre-run FreeSurfer, touch on TemplateFlow (subpage)
    - Outputs (subpage)
    - Spaces and Templates (subpage)
- FAQ
- Developers
    - Guidelines (link to nipreps, mostly just like current after #2469)
    - Dev environment  (link to nipreps, mostly just like current after #2469)
    - API

**Comment by effigies** [comment]
@oesteban Looks good. The homepage is linked to by the home button in the top left, so I don't know it's necessary to add a new link to the landing page:

![clickable_fmriprep](https://user-images.githubusercontent.com/83442/126539875-febac931-0177-41bb-8a2c-bc4aa956e349.png)

That said, it is a somewhat sad looking corner. Maybe we need a logo?

**Comment by oesteban** [comment]
> The homepage is linked to by the home button in the top left

Yup, I just wanted to be explicit about the contents of the landing page.



> Maybe we need a logo?

I've thought of this a thousand times. Maybe we can run a call for logos starting next roundup?

**Comment by effigies** [comment]
This is completed.
