### ISSUE TITLE
Unfold AROMA variants of confounds with ``--ica-aroma`` flag

### ISSUE THREAD

**Issue by oesteban** [nipreps/fmriprep#1905]
Comes from https://github.com/poldracklab/fmriprep/issues/1049#issuecomment-391382809

When the user requests running ICA-AROMA, most of the regressors in the confounds file should be recalculated if they plan to use the nonaggressively denoised outputs (is this completely correct?).

/cc @kfinc @jdkent @alexlicohen @satra

**Comment by jdkent** [comment]
terms that should be recalculated:
- csf
- white_matter
- global_signal
- std_dvars
- dvars
- t_comp_cor
- a_comp_cor   

terms not necessary to recalculate:
- non_steady_state_outlier 
- framewise_displacement
- trans_x
- trans_y
- trans_z
- rot_x
- rot_y
- rot_z
