### ISSUE TITLE
Handle single-volume BOLD series

### ISSUE THREAD

**Issue by effigies** [nipreps/fmriprep#1931]
Currently, single-volume BOLD series give inscrutable errors (#1924). We should either accept them or add an early check to reject/skip them.

I would suggest when creating the bold workflow, we simply read the header, and if it's single-volume raise a warning and return an empty workflow. There are likely too many places where we assume multiple volumes, and the cost/benefit of adding support seems high at the moment.

**Comment by oesteban** [comment]
What would be the objective of preprocessing single-volume BOLDs? I agree with the proposed solution (warning + empty workflow, if that means no nodes are added).

**Comment by oesteban** [comment]
Happened again - #2438.
