### ISSUE TITLE
Could not generate CITATION.html file

### ISSUE THREAD

**Issue by jawaltz** [nipreps/fmriprep#2040]
When I run fmriprep in singularity, fMRIPrep finished without errors, but it could not generate CITATION.html file (or the CITATION.tex). I'm wondering if this is due to an issue with the 'pandoc' command.

This is the command I ran:

---
singularity run --cleanenv /data/mprc_data2/singularity/fmriprep-20.0.2.simg ./bids-data ./ana participant --fs-no-reconall --fs-license-file /data/brutus_data0/freeware/freesurfer6.0.0/freesurfer/license.txt
---

And this is the error I got:

---
fMRIPrep finished without errors
Could not generate CITATION.html file:
pandoc -s --bibliography /usr/local/miniconda/lib/python3.7/site-packages/fmriprep/data/boilerplate.bib --filter pandoc-citeproc --metadata pagetitle="fMRIPrep citation boilerplate" /data/brutus_data19/jwaltz/CBRL-PC/mri/ana/fmriprep/logs/CITATION.md -o /data/brutus_data19/jwaltz/CBRL-PC/mri/ana/fmriprep/logs/CITATION.html
Could not generate CITATION.tex file:
pandoc -s --bibliography /usr/local/miniconda/lib/python3.7/site-packages/fmriprep/data/boilerplate.bib --natbib /data/brutus_data19/jwaltz/CBRL-PC/mri/ana/fmriprep/logs/CITATION.md -o /data/brutus_data19/jwaltz/CBRL-PC/mri/ana/fmriprep/logs/CITATION.tex
---

As far as I can tell, singularity can see both the input and output directories. It didn't seem to have a problem writing the 'CITATION.md' file to the '/data/brutus_data19/jwaltz/CBRL-PC/mri/ana/fmriprep/logs/' directory.

Thanks,

Jim Waltz

**Comment by oesteban** [comment]
- Did you get an html report for all the participants you are running? 
- Do them show any errors at the corresponding section? 
- How many participants do you have under the bids root?

**Comment by jawaltz** [comment]
**Did you get an html report for all the participants you are running?**

Yes, I would attach it, but html files are not supported. It looks great.

**Do them show any errors at the corresponding section?**

No errors. Seems to be a specific problem of the pandoc function.

**How many participants do you have under the bids root?**

One.

**We'll need the full output of fMRIPrep to check whether there were any previous errors.
[fmriprep-output.docx](https://github.com/poldracklab/fmriprep/files/4349129/fmriprep-output.docx)

**

Attached.

**Comment by jawaltz** [comment]
Hi-

I discovered the following:

If I run pandoc in the Singularity SHELL, it's fine; when it's run OUTSIDE of the shell, it can't find the pandoc command. 

If I run the fmriprep command through Singularity, 

> [jwaltz@mprc20 mri]$ singularity run --cleanenv /data/mprc_data2/singularity/fmriprep-20.0.2.simg ./bids-data ./ana participant --fs-no-reconall --fs-license-file /data/brutus_data0/freeware/freesurfer6.0.0/freesurfer/license.txt --longitudinal

it successfully completes fmriprep, but can't do anything AFTER that, because it is not in the Singularity shell:

> fMRIPrep finished without errors
> Could not generate CITATION.html file:
> pandoc -s --bibliography /usr/local/miniconda/lib/python3.7/site-packages/fmriprep/data/boilerplate.bib --filter pandoc-citeproc --metadata pagetitle="fMRIPrep citation boilerplate" /data/brutus_data19/jwaltz/CBRL-PC/mri/ana/fmriprep/logs/CITATION.md -o /data/brutus_data19/jwaltz/CBRL-PC/mri/ana/fmriprep/logs/CITATION.html
> Could not generate CITATION.tex file:
> pandoc -s --bibliography /usr/local/miniconda/lib/python3.7/site-packages/fmriprep/data/boilerplate.bib --natbib /data/brutus_data19/jwaltz/CBRL-PC/mri/ana/fmriprep/logs/CITATION.md -o /data/brutus_data19/jwaltz/CBRL-PC/mri/ana/fmriprep/logs/CITATION.tex

The pandoc commands must be added ON to the fmriprep command.

If I enter the Singularity shell and run the pandoc commands:

> [jwaltz@mprc20 mri]$ singularity shell  /data/mprc_data2/singularity/fmriprep-20.0.2.simg

> pandoc -s --bibliography /usr/local/miniconda/lib/python3.7/site-packages/fmriprep/data/boilerplate.bib --filter pandoc-citeproc --metadata pagetitle="fMRIPrep citation boilerplate" /data/brutus_data19/jwaltz/CBRL-PC/mri/ana/fmriprep/logs/CITATION.md -o /data/brutus_data19/jwaltz/CBRL-PC/mri/ana/fmriprep/logs/CITATION.html

> pandoc -s --bibliography /usr/local/miniconda/lib/python3.7/site-packages/fmriprep/data/boilerplate.bib --natbib /data/brutus_data19/jwaltz/CBRL-PC/mri/ana/fmriprep/logs/CITATION.md -o /data/brutus_data19/jwaltz/CBRL-PC/mri/ana/fmriprep/logs/CITATION.tex

I know this is not a super-big issue, but I still would like for fmriprep to finish cleanly.

Thanks,

Jim Waltz

**Comment by mgxd** [comment]
@jawaltz the warning will appear if it pandoc fails or the process takes longer than 10 seconds - my guess is the latter is happening. do you know how long the command takes to run when you shell in?

**Comment by effigies** [comment]
Closing as stale.
