### ISSUE TITLE
Best way quick testing of bids-app

### ISSUE THREAD

**Issue by yarikoptic** [nipreps/fmriprep#2173]
Given there is a bids app container, what could be a relatively basic quick test or tests setup to verify that it works more or less?
Asking for a friend: https://github.com/ReproNim/containers/tree/master/images/bids

**Comment by effigies** [comment]
Our tests are basically `--help` or a full run, so we don't really have that. But you could do something where you run it on a test dataset, and kill after some time, presuming correct running if it hasn't quit with an error code.

```Python
def _test_app(app_name, bids_root, out_root, analysis_level):
    app = subprocess.Popen([app_name, bids_root, out_root, analysis_level])
    time.sleep(some_reasonable_time)
    if app.poll():
        return app.returncode == 0
    app.terminate()
    app.wait()
    return True
```

Then you could have a wrapper check that at least one analysis level works:

```Python
def any_level(app_name, bids_root):
    for analysis_level in ('run', 'session', 'participant', 'group'):
        with tempfile.TemporaryDirectory() as out_root:
            if _test_run(app_name, bids_root, out_root, analysis_level):
                return True
    return False
```

IDK if that's the kind of thing you're looking for?

**Comment by yarikoptic** [comment]
Good ideas.. I will check options - may be there is some kind of a dry run mode, Which would establish workflow but not run?

**Comment by effigies** [comment]
Might be for some apps, but I don't think it can be assumed.

**Comment by oesteban** [comment]
Closing for the minimal activity - please reopen if needed!
