### ISSUE TITLE
Register structural and func to a standard template

### ISSUE THREAD

**Issue by StephDocTUM** [nipreps/fmriprep#2188]
Hi all,

I ran fmriprep with a single brain file and want to have my structural and functional (bold) registered to a standard template and do the same with my other subjects. I am mainly interested in the Volume space not surface
(So my structural and func are also congruent). Otherwise I cannot compare them.

But it seems to be that fmriprep does not register structural and anat to a standard template?

And then further process my data with ciftify.

Best,
Stephan

**Comment by effigies** [comment]
Hi Stephan, this is one of the main things fMRIPrep does, so I'm not sure I follow what the problem is. What command did you run?

**Comment by stephanwu89** [comment]
Sorry yes, it works now.

Another question: Can I also register it to an fsl template and not to an MNI template?
Because I cannot find a grey matter mask for an MNI template but for fsl for sure.
And I would need that to further process my data.

Best,
Stephan

**Comment by oesteban** [comment]
@stephanwu89 regarding how fMRIPrep handles standard and nonstandard output spaces, please check https://fmriprep.org/en/stable/spaces.html carefully first. Let us know if there's something unclear about that piece of documentation.

Regarding the grey matter mask - I don't think I follow the question.

**Comment by stephanwu89** [comment]
Thanks a lot I checked it.

Regarding the grey matter mask:
I meant, I am only interested in the voxels which are part of the grey matter and are supratentorial in the brain for further analysis in MNI space.
