### ISSUE TITLE
Fatal Python error: Segmentation fault

### ISSUE THREAD

**Issue by levchenkoegor** [nipreps/fmriprep#2241]
Hello!

I tried to run fMRIPrep on HPC using Singularity. At some point, it returns an error (after ~2 days of computing):

> [Node] Finished "fmriprep_wf.single_subject_OAS30003_wf.func_preproc_ses_d2669_task_rest_run_02_wf.bold_reference_wf.enhance_and_skullstr 
 p_bold_wf.skullstrip_first_dilate".
> Fatal Python error: Segmentation fault
> 
> Thread 0x00007f789ca9e700 (most recent call first):
>   File "/usr/local/miniconda/200820-18:48:23,235 nipype.workflow WARNING:
> 	 [Node] Error on "fmriprep_wf.single_subject_OAS30004_wf.func_preproc_ses_d1101_task_rest_run_01_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.norm" (/home/elevchenko/OASIS-3/work_fmriprep/controls/fmriprep_wf/single_subject_OAS30004_wf/func_preproc_ses_d1101_task_rest_run_01_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/norm)
> lib/python3.7/site-packages/nipype/utils/subprocess.py", line 190 in run_command
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 790 in _run_interface
>   File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/fixes.py", line 30 in _run_interface
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 397 in run
>   File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/itk.py", line 184 in _applytfms
>   File "/usr/local/miniconda/lib/python3.7/concurrent/futures/thread.py", line 57 in run
>   File "/usr/local/miniconda/lib/python3.7/concurrent/futures/thread.py", line 80 in _worker
>   File "/usr/local/miniconda/lib/python3.7/threading.py", line 865 in run
>   File "/usr/local/miniconda/lib/python3.7/threading.py", line 917 in _bootstrap_inner
>   File "/usr/local/miniconda/lib/python3.7/threading.py", line 885 in _bootstrap
> .
> .
> .
> Traceback (most recent call last):
>   File "/usr/local/miniconda/bin/fmriprep", line 10, in <module>
>     sys.exit(main())
>   File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 473, in main
>     packagename='fmriprep')
>   File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/reports/core.py", line 475, in generate_reports
>     for subject_label in subject_list
>   File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/reports/core.py", line 475, in <listcomp>
>     for subject_label in subject_list
>   File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/reports/core.py", line 462, in run_reports
>     subject_id=subject_label, packagename=packagename)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/reports/core.py", line 267, in __init__
>     self._load_config(Path(config))
>   File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/reports/core.py", line 286, in _load_config
>     self.index(settings['sections'])
>   File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/reports/core.py", line 298, in index
>     self.init_layout()
>   File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/reports/core.py", line 289, in init_layout
>     self.layout = BIDSLayout(self.root, config='figures', validate=False)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 230, in __init__
>     self._validate_root()
>   File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 460, in _validate_root
>     raise ValueError("BIDS root does not exist: %s" % self.root)
> ValueError: BIDS root does not exist: /home/elevchenko/OASIS-3/work_fmriprep/controls/reportlets/fmriprep/sub-OAS30005
> Sentry is attempting to send 4 pending error messages
> Waiting up to 2 seconds
> Press Ctrl-C to quit

I am pretty sure that sub-OAS30005 in my data and it was in the participant list. I use the next command to run fMRIPrep:

`singularity run --cleanenv ~/my_images/fmriprep-2007.simg ~/OASIS-3/raw_data/controls/ ~/OASIS-3/derivatives_fmriprep/controls/ participant --participant-label $(cat ~/OASIS-3/controls_list.txt) -w ~/OASIS-3/work_fmriprep/controls/ --fs-license-file ~/freesurfer_license.txt --fs-no-reconall --skip_bids_validation`

The file controls_list.txt you can find attached.
[controls_list.txt](https://github.com/poldracklab/fmriprep/files/5108694/controls_list.txt)

The whole log file is here.
[output_fmriprep_oasis_controls.txt](https://github.com/poldracklab/fmriprep/files/5108698/output_fmriprep_oasis_controls.txt)

It looks like that report for sub-OAS30005 should be in _/reportlets/_ folder, but it isn't. Do you have any ideas what the problem and what am I missing?

**Comment by effigies** [comment]
You're getting two errors:

1. short header read. This one typically indicates your working directory is out of space or you're on a network filesystem and the synchronization took too long. Re-running will typically resolve it, assuming space isn't the problem. 

```
200821-22:43:07,75 nipype.workflow ERROR:
	 Node flt_bbr failed to run on host cn-013.
200821-22:43:07,88 nipype.workflow ERROR:
	 Saving crash info to /home/elevchenko/OASIS-3/derivatives_fmriprep/controls_10subjs/fmriprep/sub-OAS30003/log/20200821-202124_a3cfc52a-29f4-4896-80bc-0c0d13e54346/crash-20200821-224307-elevchenko-flt_bbr-25a8c115-a317-49fd-89ac-042fcb2d66b6.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 792, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 723, in raise_exception
    ).format(**runtime.dictcopy())
RuntimeError: Command:
flirt -in /home/elevchenko/OASIS-3/work_fmriprep/controls_10subjs/fmriprep_wf/single_subject_OAS30003_wf/func_preproc_ses_d3731_task_rest_run_02_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/apply_mask/uni_xform_masked.nii.gz -ref /home/elevchenko/OASIS-3/work_fmriprep/controls_10subjs/fmriprep_wf/single_subject_OAS30003_wf/anat_preproc_wf/brain_extraction_wf/copy_xform/sub-OAS30003_ses-d2669_T1w_template_corrected_masked_xform.nii.gz -out uni_xform_masked_flirt.nii.gz -omat uni_xform_masked_flirt.mat -searchcost bbr -dof 6 -init /home/elevchenko/OASIS-3/work_fmriprep/controls_10subjs/fmriprep_wf/single_subject_OAS30003_wf/func_preproc_ses_d3731_task_rest_run_02_wf/bold_reg_wf/fsl_bbr_wf/flt_bbr_init/uni_xform_masked_flirt.mat -schedule /usr/share/fsl/5.0/etc/flirtsch/bbr.sch -wmseg /home/elevchenko/OASIS-3/work_fmriprep/controls_10subjs/fmriprep_wf/single_subject_OAS30003_wf/anat_preproc_wf/t1w_dseg/sub-OAS30003_ses-d2669_T1w_template_corrected_masked_xform_seg_wm.nii.gz
Standard output:

Standard error:
** ERROR (nifti_image_read): short header read '/home/elevchenko/OASIS-3/work_fmriprep/controls_10subjs/fmriprep_wf/single_subject_OAS30003_wf/anat_preproc_wf/t1w_dseg/sub-OAS30003_ses-d2669_T1w_template_corrected_masked_xform_seg_wm.nii.gz'
** ERROR: nifti_image_open(/home/elevchenko/OASIS-3/work_fmriprep/controls_10subjs/fmriprep_wf/single_subject_OAS30003_wf/anat_preproc_wf/t1w_dseg/sub-OAS30003_ses-d2669_T1w_template_corrected_masked_xform_seg_wm): bad header info
ERROR: failed to open file /home/elevchenko/OASIS-3/work_fmriprep/controls_10subjs/fmriprep_wf/single_subject_OAS30003_wf/anat_preproc_wf/t1w_dseg/sub-OAS30003_ses-d2669_T1w_template_corrected_masked_xform_seg_wm
Image Exception : #22 :: ERROR: Could not open image /home/elevchenko/OASIS-3/work_fmriprep/controls_10subjs/fmriprep_wf/single_subject_OAS30003_wf/anat_preproc_wf/t1w_dseg/sub-OAS30003_ses-d2669_T1w_template_corrected_masked_xform_seg_wm
terminate called after throwing an instance of 'RBD_COMMON::BaseException'
Aborted
Return code: 134
```

2. Citation boilerplate error. Unclear why this isn't working, but it's not terribly important. You can disable it with `--md-only-boilerplate`.

**Comment by levchenkoegor** [comment]
Just an update about this problem.

I think the main problem was not in fMRIPrep, but in the cluster at my university, because sometimes the connection to the node was lost and it caused problems in fMRIPrep processing.

I made a script that passes subject by subject to HPC with a delay - it worked well without any problems. It is not a solution to the problem, but I would say a general recommendation for me and others who are facing similar issues.

I guess the issue can be closed

**Comment by effigies** [comment]
Thanks for the report back. That is a frustrating situation... Please reopen (or open a new issue) if there is something we can do on our end.
