### ISSUE TITLE
Subject progress bar(s)

### ISSUE THREAD

**Issue by jrdalenberg** [nipreps/fmriprep#2262]
Since I often run preprocessing on one or a couple of subjects at a time, I often find it hard to estimate how long the analysis still takes at any given moment, especially with the large number of (parallel) processes taking place. Would it be possible to provide users with some feedback on the overall progress?

**Comment by effigies** [comment]
Thanks for the question, and this would definitely be a great addition! Unfortunately, this is not a trivial matter. This functionality would need to be added in [Nipype](https://github.com/nipy/nipype), as a feature of the [`MultiProc` execution plugin](https://github.com/nipy/nipype/blob/master/nipype/pipeline/plugins/multiproc.py). I don't have a lot of guidance for how to implement a progress bar, but if you are familiar with that, I can curate and answer questions about the plugin itself.

The main challenges I foresee is handling multiple progress bars to describe sub-workflow progress and keeping track of the total number of jobs. When workflows are run, they are flattened into one large workflow with only names to indicate the original nested structure. Further, when `MapNode`s are encountered, they dynamically generate new jobs, which need to be added to both the numerator and denominator of the correct sub-workflow.

**Comment by oesteban** [comment]
There was a telemetry retrieval project a couple of years ago that would have served to build something like this. Because the time a node takes can be so variable, a useful progress bar would also need to weight each node by their typical run time.

Agree with both, that this would be very useful and that this fits well within Nipype's development.

**Comment by mateuszpawlik** [comment]
I would be interested even in a very simplified version. Can we estimate where the workflow currently is using for example the job number (like `[Job 258]`) that can be found in the standard output?

**Comment by effigies** [comment]
This needs to be a feature request in nipype/pydra. We can't do it here, but we can take advantage of it if it becomes available.
