### ISSUE TITLE
ds001 sub-04 pre-skullstripped

### ISSUE THREAD

**Issue by effigies** [nipreps/fmriprep#2276]
### What version of fMRIPrep are you using?

20.2.0rc0

### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?

TACC run

### Did fMRIPrep generate the visual report for this particular subject? If yes, could you share it?

<img width="1792" alt="Screen Shot 2020-09-23 at 13 06 21" src="https://user-images.githubusercontent.com/83442/94045589-a5b4be00-fd9d-11ea-930b-a9f6965196ea.png">

### Details

Data is pre-skullstripped: https://openneuro.org/datasets/ds000001/versions/1.0.0/file-display/sub-04:anat:sub-04_T1w.nii.gz

INU causes an apparent lesion, but that's not evident in original data. Running with `--skull-strip-t1w skip` would improve things. This would be a good chance to try out `--skull-strip-t1w auto`.

@jbwexler Could you rerun with 20.2.0rc2 and `--skull-strip-t1w auto`?

**Comment by oesteban** [comment]
Thanks for marking this one. I had it in mind and failed to report.

**Comment by effigies** [comment]
This was resolved by running `--skull-strip-t1w auto`.
