### ISSUE TITLE
Functional data does not align with anatomical

### ISSUE THREAD

**Issue by evansorenson** [nipreps/fmriprep#2288]
Hello,

I previously asked for help on Neurostars, but am unable to upload the report files there.
https://neurostars.org/t/fmriprep-preprocessing-functional-data-does-not-align-with-anatomical/16875

@oesteban Here are the figures and report zipped.

[sub-04.zip](https://github.com/poldracklab/fmriprep/files/5284751/sub-04.zip)

**Comment by oesteban** [comment]
Hi @evansorenson, unfortunately, the figures/ folder is empty.

**Comment by evansorenson** [comment]
My bad the upload was too big apparently. Here is a dropbox link: https://www.dropbox.com/sh/mhuk7pb531qdpvz/AAAqAM05R3n5VsPr9IqefMENa?dl=0
