### ISSUE TITLE
acompcorr query

### ISSUE THREAD

**Issue by shilpitju** [nipreps/fmriprep#2297]
Hi,

I intend to include 6 acompcorr components as regressors. In the documentation of fmriprep it is mentioned that "fMRIPrep does high-pass filtering before running anatomical or temporal CompCor. Therefore, when using CompCor regressors, the corresponding cosine_XX regressors should also be included in the design matrix."

Now, sometimes there are only 3 cosine_XX regressors (and I am using 6 acompcorr components) in the output regressor tsv file. So, what should I do in such a case?

Thanks,

Regards,

Shilpi

**Comment by effigies** [comment]
No. These are independent. If you want to use 6 compcor components, there's no problem doing so.

**Comment by shilpitju** [comment]
okay. Thanks
