### ISSUE TITLE
does fmriprep include correction for baseline drifts?

### ISSUE THREAD

**Issue by vtsogli** [nipreps/fmriprep#2301]
Hello, 

Does fmriprep include correction for baseline drifts?
I need to use a LISA tool (LIPSIA) for single-subject analysis and it requires that: "The preprocessing pipeline must include a correction for baseline drifts."
According to the output of the fmriprep (Methods) it seems that there is no correction for baseline drifts.
Please correct me if I am wrong. 

Thank you :)

**Comment by effigies** [comment]
No, fMRIPrep only resamples, and does not attempt to denoise. You could check out https://github.com/nbraingroup/fmridenoise for this purpose. fMRIPrep does provide a set of cosine regressors that can be used to regress out low frequency components. We use a high-pass cutoff of 128s, so frequencies below ~0.008Hz should be effectively removed. This would likely satisfy "baseline drifts".

There are other methods for removing low-frequency components. The only cases where you really need to use the cosine regressors is if you also want to regress out CompCor components.

Hope this helps.

**Comment by vtsogli** [comment]
Thank you Chris for your response. 
I think I can apply the correction by LIPSIA: "vpreprocess -in tmp4.v -out prep_$1.v -fwhm 6 -low 10 -high 90"
using as input file the fmriprep derivative.

**Comment by effigies** [comment]
Sounds good. Thanks for the question!
