### ISSUE TITLE
Duplicate node error- singularity 20.2.0

### ISSUE THREAD

**Issue by CalebRHaynes** [nipreps/fmriprep#2306]
### What version of fMRIPrep are you using?
20.2.0
### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?
Singularity
### What is the exact command-line you used?
```
singularity run --cleanenv -B $maindir:/base -B /data/tools/licenses:/opts -B $scratchdir:/scratch \
/data/tools/fmriprep-20.2.0.simg \
/base/bids /base/derivatives \
participant --participant_label $sub \
--ignore fieldmaps --skip-bids-validation --use-aroma --fs-no-reconall --fs-license-file /opts/fs_license.txt -w /scratch
```

### Have you checked that your inputs are BIDS valid?
Yes
### Did fMRIPrep generate the visual report for this particular subject? If yes, could you share it?
No

### Can you find some traces of the error reported in the visual report (at the bottom) or in *crashfiles*?
```
File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py", line 766, in _check_nodes
    raise IOError('Duplicate node name "%s" found.' % node.name)
OSError: Duplicate node name "func_preproc_task_srDoors_run_01_wf" found.
```
I tried switching scratch folders and killing all user processes. also looked for hidden files 
### Are you reusing previously computed results (e.g., FreeSurfer, Anatomical derivatives, work directory of previous run)?
No

### fMRIPrep log
If you have access to the output logged by fMRIPrep, please make sure to attach it as a text file to this issue.

**Comment by effigies** [comment]
Can you list the directory contents for that subject.

**Comment by CalebRHaynes** [comment]
Thank you for the quick responses this week! I killed and restarted my processes and that looks to have fixed it.
