### ISSUE TITLE
[singularity] Isn't data mounting required first?

### ISSUE THREAD

**Issue by tashrifbillah** [nipreps/fmriprep#2308]
Don't you need to mount directories inside the singularity container to be able to process them?
https://fmriprep.org/en/stable/singularity.html#running-a-singularity-image
```vim
$ singularity run --cleanenv fmriprep.simg \
    path/to/data/dir path/to/output/dir \
    participant \
    --participant-label label
```

**Comment by eburkevt** [comment]
You can create bind points for directories in the external file system so they are visible to the fMRIPrep singularity container.

This usually involves making changes to the 'singularity.conf' file (our 'singularity.conf' file is located in /etc/singularity/, but might different for your system)

One way to do this to change the default of MOUNT HOSTFS to 'yes', but as suggested, there are better and more secure ways of doing this.

in singularity.conf file ... 

"MOUNT HOSTFS (boolean, default=’no’)
This feature will parse the host’s mounted file systems and attempt to replicate all mount points within the container. This maybe a desirable feature for the lazy, but it is generally better to statically define what bind points you wish to encapsulate within the container by hand (using the below “bind path” feature)."

More on this at this site: [https://singularity.lbl.gov/docs-config](url)

**Comment by tashrifbillah** [comment]
> This maybe a desirable feature for the lazy

Agreed and understood. Thanks.
