### ISSUE TITLE
Masking with multiecho sequences can be too aggressive

### ISSUE THREAD

**Issue by mvdoc** [nipreps/fmriprep#2309]
After running fmriprep-unstable on some multiecho sequences, I noticed that there is some aggressive masking going on. This is most likely a tedana issue (see https://github.com/ME-ICA/tedana/issues/600), but I'm posting it here as well because it makes fMRIPrep kind of unusable for these sequences (which were tested out to recover ATL/OFC).

Using tedana 0.8.0 (from pip) results in more reasonable masking

![image](https://user-images.githubusercontent.com/6150554/96516556-3dca8980-121c-11eb-83bf-cb29ee6aa5b3.png)

while using 0.9.0a1 (as in fmriprep-unstable), chunks of ATL and OFC are cut out

![image](https://user-images.githubusercontent.com/6150554/96516615-59ce2b00-121c-11eb-9add-6211d6e96b07.png)

**Comment by mvdoc** [comment]
Just to point out that this is being discussed in https://github.com/ME-ICA/tedana/issues/617

**Comment by effigies** [comment]
To be clear, is this the BOLD output or the BOLD reference? For single-echo data, we provide unmasked BOLD series + a BOLD mask.

From the perspective of consistency, I think I would prefer to have three outputs:

* `*_desc-preproc_bold.nii.gz` - unmasked
* `*_desc-brain_mask.nii.gz` - mask of voxels in brain
* `*_desc-tedana_mask.nii.gz` - (or some other desc) mask of "good" data

I will post this over on the other thread, and hopefully not make a fool of myself.

**Comment by mvdoc** [comment]
I need to double check whether the images I posted refer to the boldref or the bold data (I'll double check later today). I'm positive the problem affected the bold data files too, because the aggressive masking was evident both in the report and when I was computing tSNR.

**Comment by effigies** [comment]
Now that I think about it, we still want as unmasked a reference image as we can get, anyway. Degradation of the reference may harm coregistration.

**Comment by mvdoc** [comment]
To confirm, both the boldref and the bold are masked. This is what they look like for one of the ME3 sequences that I used.

![image](https://user-images.githubusercontent.com/6150554/96793974-350bbc00-13b2-11eb-813b-ce29f3c8b562.png)

**Comment by tsalo** [comment]
While the lion's share of the issue is definitely on `tedana`'s end (see ME-ICA/tedana#617), I've opened #2348, which proposes an idea of @emdupre's that may help.

**Comment by oesteban** [comment]
I'm curious about how the new masking utility I've put together in SDCFlows proper ([`sdcflows.utils.epimanip.epi_mask()`](https://github.com/nipreps/sdcflows/blob/39728a86816e014796b4df4171ac2b83748810e1/sdcflows/utils/epimanip.py#L205)) would work with these images.

could you give it a quick check @tsalo @mvdoc ?

**Comment by tsalo** [comment]
Thanks! I've only run a quick check with one of `nilearn`'s fetchable datasets, and it looks like `epi_mask` is more liberal than `nilearn`'s `compute_epi_mask`. Would the idea be to use `epi_mask` instead of the BET+Automask approach in `init_skullstrip_bold_wf`?

**Comment by oesteban** [comment]
> Thanks! I've only run a quick check with one of `nilearn`'s fetchable datasets, and it looks like `epi_mask` is more liberal than `nilearn`'s `compute_epi_mask`. Would the idea be to use `epi_mask` instead of the BET+Automask approach in `init_skullstrip_bold_wf`?

Yes, I'm testing it with EPI and b=0 DWIs (EPI) and pretty happy so far (esp. for the speed/accuracy balance). The mask can be made tighter reducing (or removing) a final binary dilation step.

**Comment by tsalo** [comment]
fMRIPrep switched to providing its own brain mask to tedana, and more recently (in June) to dilating that brain mask before feeding it to tedana, so I think this issue can be closed. New issues can be opened about the current methodology if necessary.
