### ISSUE TITLE
Partial FOV EPI: Issue with brain mask/registration. 

### ISSUE THREAD

**Issue by MasonTWells** [nipreps/fmriprep#2314]
Hi Experts, 

I have a series of partial FOV resting state data, which I want to pre-process with fMRIprep. I have a couple of questions/issues I hope you can help with. 

The command I am using is this:
fmriprep-docker /media/HDD/BIDS/Nifti/ /media/HDD/BIDS/derivatives/ participant --participant-label 0064 --output-spaces fsnative T1w func --use-aroma

Am I correct in thinking that I can use a whole-brain volume to aid registration in the case of partial FOV functional data, much like I would do if using Feat? 

I have tried this, naming the whole-brain sbref.nii. The data complies with BIDS format, but the derivatives from fMRIprep look unusual. For example, when I view the brain mask and desc-preproc files in FSLeyes, you can see the issue. 

![Screenshot from 2020-10-26 11-39-14](https://user-images.githubusercontent.com/67323940/97171337-3576cf00-1785-11eb-865d-21149b233a69.png)

If I run fmriprep without the sbref image, the mask seems to look OK.

![Screenshot from 2020-10-26 11-39-12](https://user-images.githubusercontent.com/67323940/97171347-39a2ec80-1785-11eb-87ed-66db5a7f5f38.png)

I also looked at the des-roi output. Here you can see a big difference between running frmiprep with a whole brain volume

![Screenshot from 2020-10-26 11-35-18](https://user-images.githubusercontent.com/67323940/97171983-3f4d0200-1786-11eb-8766-365e20115570.png)

And running it without the whole brain volume.

![Screenshot from 2020-10-26 11-34-27](https://user-images.githubusercontent.com/67323940/97171992-4247f280-1786-11eb-95b1-138ab230f0c1.png)

Perhaps I have misunderstood the use of the sbref image, so some advice as to why the outputs look so different would be really appreciated. 

Can I also confirm that using the --output-spaces T1w, fmriprep will resize the data (dim 1-3 changes in fslinfo compared to the input EPI), but it doesn't resample the data (pixdim 1-3 remains the same as the input/raw EPI)

Thanks in advance,
Mason

**Comment by effigies** [comment]
I think `sbref` is assumed to be the same field-of-view as the main BOLD series. I don't think we have any concept of "same sequence, bigger FoV".

If the two images have the same FoV and orientation, but sbref has more slices, that's a pretty easy case to detect. I imagine that you assume they're in register, use the sbref just for coregistration (and SyN-SDC, if used), but use the first BOLD volume for motion correction?

Would you be interested in adding this to fMRIPrep?

**Comment by pjkohler** [comment]
Hi @effigies,

I am trying to run this on Sherlock. I have been using this singularity image: 
`/home/groups/russpold/singularity_images/poldracklab_fmriprep_1.4.0-2019-05-15-2870a0e4efbf.simg`
but that does not have the --bold2t1w-init header option. 
So instead I am now trying to use
`/home/groups/russpold/singularity_images/fmriprep-20.2.3.simg`
but I am getting errors that I do not really understand (based on the error output in slurm_err).

Is there another singularity image on Sherlock I should use instead? Happy to continue this conversation over email if this is too far off-topic. 

Best,

Peter

**Comment by mgxd** [comment]
Hi Peter,

I recommend building your own image (see https://www.nipreps.org/apps/singularity/#preparing-a-singularity-image) off `21.0.0` and then giving that a go.

**Comment by pjkohler** [comment]
I tried doing so on Sherlock, using this command:
`singularity build singularity_images/fmriprep-21.0.0.simg docker://nipreps/fmriprep:21.0.0`
and get this error:
`While performing build: while creating squashfs: create command failed: signal: killed: 
Unrecognised xattr prefix lustre.lov`
Any idea what might be happening? 
/Peter

**Comment by mgxd** [comment]
You may be trying to build in a path you don't have access to - I created an image for you at `/home/groups/russpold/singularity_images/fmriprep-21.0.0.sif` - if you run into problems, feel free to open a new issue
