### ISSUE TITLE
skull stripped inputs not auto-detected for ds001110 [sherlockmerlin]

### ISSUE THREAD

**Issue by jsmentch** [nipreps/fmriprep#2318]
version 20.2.0, using singularity.

The sherlock merlin dataset (openneuro ds001110) has images that were already skull-stripped and fmriprep did not auto-detect that they were skull stripped (this seems to have happened for all of the subjects, not just one or a few). Passing the flag '--skull-strip-t1w skip' did indeed skip skull stripping as expected though.

report after running fmriprep naively with no option set for --skull-strip-t1w (default 'auto'):

![image](https://user-images.githubusercontent.com/20958589/98024020-b7927380-1dd5-11eb-92cd-6fba5b3b9ee4.png)

running with '--skull-strip-t1w skip':

![image](https://user-images.githubusercontent.com/20958589/98024042-bfeaae80-1dd5-11eb-8d1e-f6e8439ea81b.png)

**Comment by mgxd** [comment]
Hi @jsmentch - the default option is `force`.

https://github.com/nipreps/fmriprep/blob/67e085c00f1561188a18c79d3e328d2ccaaf063e/fmriprep/cli/parser.py#L394-L398

**Comment by jsmentch** [comment]
@mgxd ah, well that resolves this then... thank you!

**Comment by effigies** [comment]
Can you report back on the success of `auto`? Part of the reason for defaulting to force was lack of confidence in the heuristic.

**Comment by jsmentch** [comment]
Hi @effigies I've rerun this with `auto` and things look good for the most part, however, it appears that sub-27 was re-skull stripped, see image:

<img width="1039" alt="Screen Shot 2020-11-06 at 4 26 53 PM" src="https://user-images.githubusercontent.com/20958589/98416493-2af1ea80-204d-11eb-8f84-ec9402270c1f.png">

**Comment by effigies** [comment]
Ah, thanks! Good opportunity to improve our heuristic. I'm going to reopen this in smriprep where the heuristic is implemented.
