### ISSUE TITLE
check for skull-stripped data

### ISSUE THREAD

**Issue by satra** [nipreps/fmriprep#2319]
> What would you like changed/added and why?

we (@jsmentch) are running into issues where if a dataset already has skull-stripped images, the output of fmriprep has some issues. this can be resolved by turning off the skull stripping step.

it would be good if we could detect whether an image has been skull-stripped as a precursor to downstream processing. 

> What would be the benefit? Does the change make something easier to use?

we don't have to monitor each dataset, when we process lots of images. this was a specific dataset, so was easy to monitor.

also as a slight aside, we could add nobrainer based brain extraction, once the next version is ready and validated (sometime next year).

**Comment by effigies** [comment]
We have this functionality. Please use `--skull-strip-t1w auto`. I would have preferred to make it the default, but it was felt that the heuristic was not broadly tested enough to change from the default of assuming non-skull-stripped data.

**Comment by effigies** [comment]
Cool. Please report back if it works. It's worked on our test data, and an independent dataset or two would I think be justification enough to change the default.
