### ISSUE TITLE
head motion parameter

### ISSUE THREAD

**Issue by tib-sim** [nipreps/fmriprep#2323]
Hi,
My question is about head motion parameters. Once I considered the same run from the same subject, I noticed that the motion parameters from fMRIPrep are not the same than those from SPM. Why this difference ?
For SPM, I considered the data from the rp.txt file and for fMRIPrep it was the columns trans_x , trans_y , trans_z, rot_x , rot_y , rot_z from the dec-confounds_timeseries.tsv .
Best,
Simon

**Comment by effigies** [comment]
The motion parameters are going to be determined by the reference volume, the registration metric and any stochasticity in the registration algorithm. I don't know what reference volume SPM uses, but fMRIPrep uses the sbref if available, or a median image of the first few volumes (aligned to the first volume). The algorithms are also likely to be different, as SPM has its own motion correction algorithm and fMRIPrep uses FSL's MCFLIRT. And there is some amount of run-to-run variability indicating that MCFLIRT at least is not purely deterministic.

In any event, the collection of motion parameters should be highly correlated across algorithms. I would still use the parameters generated by whatever motion correction was applied to your data, for the sake of consistency.

Hope this helps.

**Comment by tib-sim** [comment]
Hi, 
Thanks for the help !
Indeed it seems to be correlated (negatively or positively) once considering the same run analysed with the two distinct pipelines.
I guess this difference of calculation could affect the final results, indeed I noticed that the second level results (ran with spm by using data preprocessed either with spm or with fmriprep) were different. Is this difference only because of the different calculation of motion parameters ? Or could it be for another reason ?
Best,
Simon

**Comment by tsalo** [comment]
There are almost certainly other differences in other steps between packages (e.g., the interpolation used for normalization in ANTS vs. SPM). I don't think it's feasible to determine every point at which SPM and fMRIPrep preprocessing might diverge.
