### ISSUE TITLE
Improve Carpet plot legend explanation

### ISSUE THREAD

**Issue by dkp** [nipreps/fmriprep#2335]
**What would you like changed/added and why?**  I'd like better documentation of the color coding for the carpet plots.
**Do you have any suggestions for the new documents?** Specifically,  it would be helpful to understand what the two different shades of blue correspond to.  I'm going to guess that dark blue is the left hemisphere and light blue is the right hmisphere.  Is that correct?

Thanks for an incredible tool and all your work on it,

Dianne Patterson, Ph.D.

**Comment by tsalo** [comment]
The current legend looks like this:

![image](https://github.com/nipreps/fmriprep/assets/8228902/1620ad31-7141-47b9-86cc-3372475f6797)

Now the hemisphere and tissue type are much clearer, I think.

**Comment by dkp** [comment]
Lovely, thank you!
