### ISSUE TITLE
Further process the results of fMRI prep

### ISSUE THREAD

**Issue by ly6ustc** [nipreps/fmriprep#2339]
Hi all,
I'm trying to preprocess resting-state fMRI data by fmriprep20.1.1 (docker). After fmriprep, I want to process my results furthermore including smoothing, regress out nuisance(mean white matter and CSF) and filtering. 

For data of volume and surface, I could use AFNI's command  "3dmerge" and Freesurfer's command "mri_surf2surf" to smooth them, respectively. However, when I tried to use Workbench's command "wb_command -cifti-smoothing" to smooth cifti data such as fsLR 91k, I was required to provide the left and right structural surface files. Where could I find these files? I have found some "xx_sphere.surf.gii" files on https://github.com/templateflow/tpl-fsLR, can I use them? Or should I find some "xx_white.surf.gii", "xx_pial.surf.gii" and "xx_midthickness.surf.gii" files? Do you have any websites?

After smoothing, I used AFNI's command "3dTproject" to complete regress out nuisance and filtering. I found mean white matter and CSF signals in fmriprep output results(xx_desc-confounds_regressors.tsv), I think they are extract from BOLD images based on segement ROI (xx_label-WM_probseg.nii.gz and xx_label-CSF_probseg.nii.gz) before warped to standard space. Is it right? Could I regress out them on results of standard space directly? Or Is it better for us to extract them in standard space based on standard template such as SPM's CsfMask_07_61x73x61.nii template? But I think it's diffcult to find the standard space templates of white matter and CSF if we process surface files.

Thanks!

**Comment by tsalo** [comment]
This question seems more appropriate for NeuroStars.
