### ISSUE TITLE
PhaseEncodingDirection set to "y-"

### ISSUE THREAD

**Issue by soichih** [nipreps/fmriprep#2341]
Hello. 

We came across some fmri data (CAM-CAN) with an odd looking `PhaseEncodingDirection`.

```
    "EffectiveEchoSpacing": 0.0005100042432,
    "PhaseEncodingDirection": "y-",
    "TaskName": "Rest",
    "subject": "CC110056"
```

It looks like fmriprep (v 20.2.0) doesn't like this format.

```
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/workflow.py", line 84, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 64, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 304, in init_single_subject_wf
    func_preproc_wf = init_func_preproc_wf(bold_file)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/bold/base.py", line 272, in init_func_preproc_wf
    tr=metadata.get("RepetitionTime")),
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 633, in __init__
    from_file=from_file, resource_monitor=resource_monitor, **inputs
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 183, in __init__
    self.inputs = self.input_spec(**inputs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/specs.py", line 66, in __init__
    super(BaseTraitedSpec, self).__init__(**kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'pe_direction' trait of a FunctionalSummaryInputSpec instance must be None or 'i' or 'i-' or 'j' or 'j-', but a value of 'y-' <class 'str'> was specified.
```

We are wondering how we should proceed. Do we need to somehow *correct* the PhaseEncodingDirection, or should we just drop it from our metadata, or should we run fmriprep with some option to work around it? Or should we contact CAM-CAN?

**Comment by mgxd** [comment]
It looks like the phase encoding isn't using voxel coordinate axes labels *ijk*. I think you should be fine relabelling it as `j-`.

**Comment by effigies** [comment]
It really depends what the orientation of the input image is. If it's LAS (or RAI or RAS or LAI), then j- is the same as y-. If not, then it's worth getting in touch with the dataset curator to clarify their intent.

**Comment by giulia-berto** [comment]
Hi, do you think the following relabeling works (whatever the axis direction code is)?
* x should be i
* x- should be i-
* y should be j
* y- should be j-
* z should be k
* z- should be k-

**Comment by effigies** [comment]
No, it depends on the orientation of the input image. You can check with fslhd or nibabel.aff2axcodes.

**Comment by soichih** [comment]
@effigies 

We were wondering maybe we don't need to check the aff2axcodes, because x/y/z already take the affine into consideration. So if the code is in *A*, then j will be positive, if it's *S* ,then it will be negative. Then, all we need to do is just replace the letter from j to y. 

If we need to flip the polarity based on aff2axcodes, then that implies that x/y/z takes affine into consideration but i/j/k does *not*. Is that your understanding?

**Comment by effigies** [comment]
> We were wondering maybe we don't need to check the aff2axcodes, because x/y/z already take the affine into consideration. So if the code is in A, then j will be positive, if it's S ,then it will be negative. Then, all we need to do is just replace the letter from j to y.

I assume you mean P? y is the AP axis, but we don't know which dimension of the data block it is without the affine.

> If we need to flip the polarity based on aff2axcodes, then that implies that x/y/z takes affine into consideration but i/j/k does not. Is that your understanding?

Yes.

**Comment by soichih** [comment]
Yes, sorry I meant P.

@giulia-berto Well then I think we need to do something like this after all
> https://github.com/brainlife/abcd-spec/pull/4#issuecomment-746985554

**Comment by giulia-berto** [comment]
I am still confused. Let's say we have the `pe='y-'`. Does it mean that if we have any *A* orientation it should be converted to ` j-`, and if we have any *P* orientation it should be converted to ` j`? Is that correct @effigies?

**Comment by effigies** [comment]
Supposing you have `y-`, then you need the anterior-to-posterior direction. You're always going to have A or P in some direction. If A, then you have a `-`, if P you don't. Then it's a question of where the A/P shows up in the axis codes. If it's in the first position, `A**` or `P**`, then you have `i-` or `i`, respectively. In the second position, `*A*` or `*P*`, then you have `j-` or `j`, respectively. In the third position `**A` or `**P`, then you have `k-` or `k`, respectively.

Similarly, if you have `x[-]`, then you look for where R or L show up in the axcodes, and `z[-]`, you look where S or I show up in the axcodes.

**Comment by soichih** [comment]
Oh I see. So the psudo code will be like

**Comment by effigies** [comment]
Yes, though your negative/positive could be reversed if your x/y/z PE direction has a `-` in it.

**Comment by effigies** [comment]
@mgxd Did a pretty thorough implementation in the other direction in #2302. Might be a useful model, and you can also use that to verify that `ijk_to_xyz(xyz_to_ijk(direction, orientation), orientation) == direction`.

**Comment by soichih** [comment]
Ah, yes, I've updated the pseudo code to reflect that.

One thing that I didn't know until you pointed out, is that axcode could be like like LAS, or ALS, or SAL, etc. But the test code for #2302 doesn't test this. Does it really happen?

**Comment by effigies** [comment]
Added some tests to demonstrate independence from the standard orientation: 4bb8a61cde27575865cdd2b7df5afcb5d6860523

**Comment by giulia-berto** [comment]
Thanks @effigies, now it is clear! I did not know about all the possible options!
