### ISSUE TITLE
Skull-strip first echo and apply mask to other echoes

### ISSUE THREAD

**Issue by tsalo** [nipreps/fmriprep#2348]
For multi-echo EPI data, fMRIPrep currently skull-strips all echoes independently and then feeds those skull-stripped time series into the t2smap workflow for optimal combination. However, I believe that it would be preferable to skull-strip just the first echo, retain the brain mask from that echo, and then apply the mask to all echoes instead.

This stems from @emdupre's idea in [this Mattermost post](https://mattermost.brainhack.org/brainhack/pl/1ifqy75c3pfcmd778c681ftgtc).

**Comment by oesteban** [comment]
Yes, definitely something we must do.

Please check this - https://github.com/nipreps/fmriprep/issues/2309#issuecomment-747334768

I believe the methodology proposed here should (in theory) work pretty well on the shortest echo.

**Comment by tsalo** [comment]
I can probably open a PR soonish. The change should be pretty straightforward- we just select the first BOLD time series, run that through the skull-strip workflow, collect the brain mask from that, and feed the brain mask into the T2* workflow. I'll need to check that the echo-wise skull-stripped files aren't used for anything else in the overall workflow, but I don't think they are.

**Comment by tsalo** [comment]
I realized that `bold_bold_trans_wf` has a BOLD mask based on the reference file, which for multi-echo data is the first echo, so I think it would be better to use that than skull-strip the first echo again.
