### ISSUE TITLE
determine fmriprep version used

### ISSUE THREAD

**Issue by marjolein15** [nipreps/fmriprep#2350]
Hi, 
A dataset that I recently started working on, was processed in fmriprep in August 2019. The fmriprep container was labeled fmriprep_1.4.1 (and the person who ran analyses thinks that version was used), but the output says processing was done in 1.5.0rc1. Version 1.5.0 wasn't released until September 2019 and I can't find documentation on 1.5.0rc1. How do I determine with certainty which version this data was processed with?

**Comment by effigies** [comment]
If 1.5.0rc1 is listed in the output, then that was the version used. It was a release candidate, which means that it will be most similar to 1.5.0, but there were some minor changes between that and the final release. The release notes are here: https://github.com/nipreps/fmriprep/releases/tag/1.5.0rc1

**Comment by effigies** [comment]
As to how the confusion arose, I would guess that the singularity image was generated from `fmriprep/poldracklab:latest` when that referred to the release candidate. The latest full release would still have been listed as 1.4.1.

We always recommend explicitly using version numbers when fetching fmriprep to avoid any ambiguity.

You can also check the version of the container by passing it the --version flag.
