### ISSUE TITLE
Dependency errors stemming from scikit-image+numpy

### ISSUE THREAD

**Issue by oesteban** [nipreps/fmriprep#2351]
@tsalo [has hit the dependency issues](https://github.com/nipreps/fmriprep/pull/2349#issuecomment-748187289) we have been seeing in *NiWorkflows* and *SDCFlows* lately. Solution in nipreps/sdcflows#158.

**Comment by tsalo** [comment]
I'm a little confused by the issue and the fix. It looks like sdcflows' fix was Python <3.7-specific (i.e., just install `numpy` with no specific version mentioned if Python 3.7+), while fMRIPrep requires 3.7+, and already requires `numpy` without a specific version mentioned.

**Comment by effigies** [comment]
`numpy <1.20; python_version < "3.7"` should only be relevant if you're using `python setup.py install`, rather than `pip install`, which you shouldn't be doing. Is your situation different?

**Comment by tsalo** [comment]
I haven't tried anything locally- I'm just focused on the test failures in #2349 and #2366.

**Comment by effigies** [comment]
Ah, so it's a super-old numpy in the Docker image conflicting with a new scikit-image. I'll try upgrading everything to the latest release that isn't a `x.y.0`.

**Comment by tsalo** [comment]
Oh... so it's just tied to the Docker. That makes sense. Thanks!

**Comment by oesteban** [comment]
This should be resolved now.
