### ISSUE TITLE
Fatal error with singularity build (permission denied)

### ISSUE THREAD

**Issue by giulia-berto** [nipreps/fmriprep#2354]
Hi, I am trying to create a singularity image with
`singularity build /my_images/fmriprep-20.2.1.simg docker://nipreps/fmriprep:20.2.1`
but I get
```
INFO:    Starting build...
FATAL:   While performing build: conveyor failed to get: error getting username and password: error reading JSON file "/home/giulia/.docker/config.json": open /home/giulia/.docker/config.json: permission denied
```
I am using singularity version 3.6.3. Any suggestions? Thank you for your help!

**Comment by heffjos** [comment]
This looks to be a permissions issue. The file `/home/giulia/.docker/config.json` has the wrong permissions and/or the wrong ownership set. I would check this file to make sure the permissions and ownership are correctly set. If they are not set correctly, then make them correct. A similar question was asked [here](https://askubuntu.com/questions/747778/docker-warning-config-json-permission-denied) and an answer was provided.

Also when you are building, make sure the output container path exists on your machine. If the path `/my_images` does not exist on your machine, the build will fail.

**Comment by giulia-berto** [comment]
Thank you very much, changing the permissions solved the problem.
