### ISSUE TITLE
recon-all aseg.mgz file not created

### ISSUE THREAD

**Issue by hrswearingen** [nipreps/fmriprep#2358]
Receiving error running fMRIprep: 

error: mghRead(/Volumes/external/data/derivates/freesurfer/sub-102614/mri/aseg.mgz, -1): could not open file
error: cannot compute vol stats without /Volumes/external/data/derivates/freesurfer/sub-102614/mri/aseg.mgz

Looking at the FreeSurfer files, it does not look like aseg.mgz is not created during the fMRIprep pipeline and then it errors out.

### What version of fMRIPrep are you using?

20.2.1

### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?

bare-metal

### What is the exact command-line you used?
```
</usr/local/bin/fmriprep /Volumes/external/data/subjects/ /Volumes/external/data/derivates/ participant --participant-label 102614 -w /Volumes/external/data/derivates/ --notrack --anat-only>
```

### Have you checked that your inputs are BIDS valid?

Yes

### Can you find some traces of the error reported in the visual report (at the bottom) or in *crashfiles*?
```
<Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 419, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 814, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 741, in raise_exception
    raise RuntimeError(
RuntimeError: Command:
recon-all -autorecon-hemi lh -nohyporelabel -openmp 8 -subjid sub-102614 -sd /Volumes/external/data/derivates/freesurfer -notessellate -nosmooth1 -noinflate1 -noqsphere -nofix -nowhite -nosmooth2 -noinflate2 -nocurvHK -nocurvstats -nosphere -nosurfreg -nojacobian_white -noavgcurv -nocortparc -nopial -nocortparc2 -nocortparc3 -nopctsurfcon>
```

### Are you reusing previously computed results (e.g., FreeSurfer, Anatomical derivatives, work directory of previous run)?

No

### fMRIPrep log
If you have access to the output logged by fMRIPrep, please make sure to attach it as a text file to this issue.

Recon-all logs and terminal output are attached. As well as PDF of HTML.

 
1) I ran fMRIprep with both functional and anatomical images and received the same error. 
2) I also ran the same data through recon-all separately to test if there was an issue with my Freesurfer installation/paths, and it processed successfully. 

![Freesurfer_Files](https://user-images.githubusercontent.com/37027603/104596057-71f9ee80-5641-11eb-80b0-f3b1d3a4fc22.png)
[sub-102614.pdf](https://github.com/nipreps/fmriprep/files/5814623/sub-102614.pdf)
[recon-all-lh.log](https://github.com/nipreps/fmriprep/files/5814630/recon-all-lh.log)
[recon-all-rh.log](https://github.com/nipreps/fmriprep/files/5814631/recon-all-rh.log)
[fmriprep_terminal.txt](https://github.com/nipreps/fmriprep/files/5814633/fmriprep_terminal.txt)

**Comment by effigies** [comment]
It looks like you're using FreeSurfer 7.1.1. Support for FreeSurfer 7 is an open issue: https://github.com/nipreps/smriprep/issues/184.

If you would like to use FreeSurfer 7, I would suggest finishing it separately. If it produces all of the expected outputs for FreeSurfer 6, then fMRIPrep should be able to use it without issue.

**Comment by hrswearingen** [comment]
Thank you! I was able to use my pre-run Freesurfer outputs in fMRIprep without issue.

**Comment by effigies** [comment]
I've run into this issue as well. It's related to https://github.com/freesurfer/freesurfer/pull/988. Fixing it in sMRIPrep by changing `-autorecon-hemi lh` to `-autorecon-hemi lh -lh-only` (and likewise for `rh`).
