### ISSUE TITLE
Specify version in output directory from fmriprep command

### ISSUE THREAD

**Issue by dlevitas** [nipreps/fmriprep#2361]
**What are you trying to accomplish?**
To better document my work, I'm making sure that each BIDS-app output directory contains the version of said BIDS-app (e.g. ```$bids_root_dir/derivatives/fmriprep-20.2.0```). 

**What have you tried?**
In a typical fmriprep command, I set the output directory to be in the derivatives folder, which creates a ```fmriprep``` output directory. If I specify the output directory as ```$bids_root_dir/derivatives/fmriprep-20.2.0``` then it creates ```fmriprep-20.2.0```, but also an ```fmriprep``` directory underneath, and the outputs are stored underneath there. I'm curious if I can simply have the output data stored directly underneath ```fmriprep-20.2.0```, rather than having to deal with the redundant sub-directory. I realize I could just do some file moving and/or output directory name changing afterwards, but I'm wondering if this can be achieved in the CLI itself? 

Thanks

**Comment by effigies** [comment]
This is now doable with [`--output-layout bids`](https://fmriprep.org/en/stable/usage.html#Other%20options). The default location for FreeSurfer will become `<output>/sourcedata/freesurfer`, so you may also want to modify that with `--fs-subjects-dir`.

**Comment by effigies** [comment]
Ah, this will require 20.2.1, however.

**Comment by dlevitas** [comment]
That's perfectly fine, thanks for the example
