### ISSUE TITLE
Config file usage for XNAT

### ISSUE THREAD

**Issue by hechlera** [nipreps/fmriprep#2373]
Dear fMRIPrep team,

am am using fmriprep 20.2.1, currently via docker.

My lab plans to integrate fmriprep with XNAT and make it accessible to colleagues without experience in using docker or even commandline. To make the usage simple and still flexible, we want to use the --config-file flag to pass the arguments. After some testing, the correct application is not clear to me. I took this format as blueprint (https://fmriprep.org/en/stable/api.html).

Essentially, I want our user only to have access to the [workflow] category + the output_spaces argument from [execution]. The rest will be preset by the admin via the appropriate arguments. For testing, I deleted everything else from the toml file. If I pass the file, I get the following error:

docker run --rm -v /home/tumnic/ahechler/fmriprep/:/input nipreps/fmriprep:latest /input/rawdata /input/test_derivatives participant --participant-label p005 -w /input/wdir_fmriprep --fs-license-file /input/FSLicence/license.txt --mem-mb 24000 --config-file /input/data/config.toml --write-graph

/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 17, in main
    parse_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/parser.py", line 598, in parse_args
    config.load(opts.config_file, skip=skip)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 634, in load
    section.load(configs, ignore=ignore)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 218, in load
    cls.init()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 453, in init
    re.compile(r"^\."),
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 136, in __init__
    root, description = validate_root(root, validate)
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/validation.py", line 68, in validate_root
    raise ValueError("BIDS root does not exist: %s" % root)
ValueError: BIDS root does not exist: /tmp/None`

If I leave out the [execution] and output_spaces, the file is accepted, fmriprep runs and completes but ignored the arguments I set in [workflow]. I'd be very glad for help in using pre-generated config files correctly. 

Thanks for your great work on fmriprep!

Best,

André

**Comment by oesteban** [comment]
Hi @hechlera, the intended utilization of the ``--config-file`` is not that you are trying. The config file is purely internal, and for very basic provenance tracking purposes. The idea for the argument is that, for a particular execution of fMRIPrep you have the opportunity to run again with (all) exactly the same parameters (but it requires you to use exactly the same command line). Therefore, it is not intended as an API.

I'd suggest you drop the ``--config-file`` option and include all the settings via command line.

**Comment by hechlera** [comment]
Hi @oesteban, thanks for the answer. Alright, I assumed the config file utilization might be similar to CPAC or maybe do double duty. Since our users won't have direct access to the command line when using containers via XNAT, a "setup" config file would have been a nice addition. But there are some alternative container launch options we can use.

**Comment by oesteban** [comment]
The point for *fMRIPrep* is to minimize the actionable knobs for the researcher. Back in time, when you could run fMRIPrep on OpenNeuro.org, the interface had just a selector for the subject label to process and an file upload box for the FS license.

What I'm trying to say is - if your GUI can map to a config file, it can easily map to just a text file with the final command line to be run.

**Comment by hechlera** [comment]
Sure, I can see that. We just noticed that our range of projects warrants a few more knobs then we assumed + we were searching for the most accessible way to provide these. But we now implemented a launcher window where the arguments are provided with a short explanation and default values that can then be changed by the user. So all is well!
