### ISSUE TITLE
macOS Big Sur + Docker: fMRIPREP raises BrokenProcessPool exception and stalls

### ISSUE THREAD

**Issue by fcmeyer** [nipreps/fmriprep#2374]
### What version of fMRIPrep are you using?
20.2.1

### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"

**Docker v.20.10.2** running on **macOS Big Sur, 11.2.1**

_Hardware:_ 
Mac Pro (2019), 3.5GHz 8-Core Intel Xeon W, 48 GB memory

_Docker Resources:_ 
- 12 CPUs* (logical, since the Xeon has HT)
- 32GB memory
- 2GB swap
- 80GB disk image space  

### What is the exact command-line you used?
```
#!/bin/bash

BIDS_ROOT_DIR="/Volumes/PNY/NeuroOCD/BIDS"
WORK_DIR="/Volumes/T5/Work/NeuroOCD_fmriprep"
FS_LICENSE=${WORK_DIR}/license.txt
sid="107"
# Match these to Docker! 
logicalcores=12
mem=32 #GB

# Optimal specs
# -------------
# Source: https://neurostars.org/t/choosing-number-of-threads-and-number-of-threads-per-process/18105

realcpus=`echo $((logicalcores/2))`

# Convert virtual memory from gb to mb
# ------------------------------------
# Source: https://andysbrainbook.readthedocs.io/en/latest/OpenScience/OS/fMRIPrep_Demo_2_RunningAnalysis.html

mem=`echo "${mem//[!0-9]/}"` #remove gb at end
mem_mb=`echo $(((mem*1000)-8000))` #reduce some memory for buffer space during pre-processing


gtime fmriprep-docker ${BIDS_ROOT_DIR} ${BIDS_ROOT_DIR}/derivatives \
participant \
--participant-label ${sid} \
--fs-license-file ${FS_LICENSE} \
--output-spaces MNI152NLin6Asym fsnative \
--nthreads ${logicalcores} \
--omp-nthreads ${realcpus} \
--stop-on-first-crash \
--mem-mb ${mem_mb} \
-w ${WORK_DIR}

exit
```

### Have you checked that your inputs are BIDS valid?
Yes, I have.

### Did fMRIPrep generate the visual report for this particular subject? If yes, could you share it?
All files generated by fMRIPREP are zipped and attached here.
[fmriprep_outputs.zip](https://github.com/nipreps/fmriprep/files/5973937/fmriprep_outputs.zip)

### Can you find some traces of the error reported in the visual report (at the bottom) or in *crashfiles*?

I ran the container with Activity Monitor on the side. When this message first popped up in the console output, Docker CPU and Real Memory usage started to go down to near zero. Then, the console kinda "hangs" there with nothing happening. I had to CTRL+C out.

```
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

### Are you reusing previously computed results (e.g., FreeSurfer, Anatomical derivatives, work directory of previous run)?
No, I am not.

### fMRIPrep log

See attached. Note, I CTRL+C'd to exit when it was clear it had "hung." [fpout.txt](https://github.com/nipreps/fmriprep/files/5973943/fpout.txt)

I tried adjusting the Docker memory settings, running with lower thresholds, etc. to no avail. I will note, I ran into a similar issue with MRIQC, so it may be a macOS Big Sur x Docker quirk.

Thank you in advance for your time and for the amazing software you have created. I immensely appreciate the awesome work you guys have done in developing this package :)

**Comment by fcmeyer** [comment]
**Update:** the issue is very likely macOS-specific. I tried running fMRIPREP in the same exact computer using the same scripts, but using Windows 10 w/ WSL 2 (Ubuntu) + Docker for Windows. It worked flawlessly. It would be awesome to fix our ability to run fMRIPREP in the macOS environment though :)

**Comment by effigies** [comment]
I can't find evidence that OSX has an equivalent of Linux's "overcommit policy", but  a BrokenProcessPool means that a job was killed by the OS for requesting too much memory. The main thing I can suggest is to tell fMRIPrep that you have less memory than you do.

**Comment by effigies** [comment]
Not much to go
