### ISSUE TITLE
--mem flag seems to be expecting mb rather than gb

### ISSUE THREAD

**Issue by jbwexler** [nipreps/fmriprep#2376]
The fmriprep v20.2.1 help command implies that --mem is expecting gb: "[--mem MEMORY_GB]". However, upon running fmriprep with `--mem 24`, it ouputs the following: "memory_gb = 0.024", implying that it's expecting mb.

**Comment by effigies** [comment]
`--mem` is a synonym for `--mem-mb`...

https://github.com/nipreps/fmriprep/blob/4bb8a61cde27575865cdd2b7df5afcb5d6860523/fmriprep/cli/parser.py#L183-L191

Not sure quite what the goal is in making it less explicit.

**Comment by jbwexler** [comment]
I think this line in the help output should be changed, no? "[--mem MEMORY_GB]"

**Comment by effigies** [comment]
Yeah, we should probably add `metavar="MEMORY_MB"`. Any interest in putting together a quick PR?

**Comment by jbwexler** [comment]
Sure, no problem
