### ISSUE TITLE
Will you release 20.2.1 as a docker container?

### ISSUE THREAD

**Issue by ulloaa** [nipreps/fmriprep#2377]
Hello,

I regularly install fmriprep for our users directly from the docker container at dockerhub. However, I noticed 20.2.1 has not been made available. Can I ask if you are planning on making 20.2.1 available as a docker container and if so what is the timeline?

Thank you,

**Comment by effigies** [comment]
[`nipreps/fmriprep:20.2.1`](https://hub.docker.com/layers/nipreps/fmriprep/20.2.1)

**Comment by ulloaa** [comment]
Thanks, I didn't realise you guys had swtiched from poldracklab to nipreps. Thanks again!
