### ISSUE TITLE
Upgrade Docker image base

### ISSUE THREAD

**Issue by mgxd** [nipreps/fmriprep#2382]
> Ubuntu 16.04 End of Life (EOL) is scheduled for April 30, 2021.

We should probably bump up to `20.04`

EDIT: They've added an extended security maintenance until 2024 - https://ubuntu.com/security/esm

**Comment by oesteban** [comment]
Yes, that will force us to change a fair amount of stuff. Probably, drop neurodebian (afni will not be available and we may have to take the leap and jump to FSL6 at last).
