### ISSUE TITLE
ignore irrelevant modalities when initializing layout

### ISSUE THREAD

**Issue by jdkent** [nipreps/fmriprep#2386]
In theory, BIDS datasets should be completely valid, in practice, sometimes not all files are valid in a dataset yet.
If a lab is working on converting their project to a BIDS valid dataset that contains many modalities, they may focus on getting `anat`, `func`, and `fmap` to get things right, but may not have finished:
- `dwi`
- `perf`
- `meg`
- `eeg`
- `ieeg`
- `beh`

Currently, one can skip validation (even if you do not, a multitude of irrelevant errors are ignored)
https://github.com/nipreps/fmriprep/blob/a42d9290d24298e7bce8bd8bef81ba8a147d04cc/fmriprep/utils/bids.py#L77-L124

but if one has malformed json files, the [pybids indexer will still fail](https://github.com/bids-standard/pybids/blob/62e59df57d4bd825a0cbdf9d57d49a97fd93c846/bids/layout/index.py#L281-L284) on potentially irrelevant (to fmriprep) files.

So my proposed solution is to ignore all the directories above when creating the bids layout so they will not be indexed (e.g., `re.compile("sub-.*/beh")`):
https://github.com/nipreps/fmriprep/blob/4bb8a61cde27575865cdd2b7df5afcb5d6860523/fmriprep/config.py#L448-L455

This may also have the added benefit of making indexing faster on larger datasets with many modalities.

**Comment by oesteban** [comment]
I think this is a pretty low-hanging fruit - don't you all agree?

**Comment by oesteban** [comment]
We can address this at the same time we remove the following warning:

```
/home/oesteban/.miniconda/lib/python3.8/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as e
arly as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and
 pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
```
