### ISSUE TITLE
'fMRIPrep failed' error in output logs. 

### ISSUE THREAD

**Issue by lbrucar** [nipreps/fmriprep#2389]
Hi everyone, 

I am running fMRIPrep in a singularity container and have noticed this error in the output logs for more than half of the subjects (around 500) after the pipeline is completed:

    210323-09:26:04,193 nipype.workflow CRITICAL:
	 fMRIPrep failed: Extra data: line 1 column 10838903 - line 1 column 10841390 (char 10838902 - 10841389)

The html files, confounds lists, and preprocessed data files all seem to be created appropriately for the subjects with this error. When opening the .nii files with Connectome Workbench, the registration and normalization also all seem to have been accurately executed for the subjects. 

I am wondering if this error is interfering with the proper processes in the pipeline and if there is a way to fix this!

Any help would be greatly appreciated!
Thank you! 

__

Version: 20.2.1
```
singularity run \
-B /code:/Freesurfer_dir  \
-B ${data_dir}/:/bids_dir \
-B /fmriprep_output/REST645:/output_dir \
-B /scratch.global/fmriprep_work/REST645:/work \
/code/fmriprep-v20.2.1-LTS.sif \
/bids_dir /output_dir participant \
--skip_bids_validation \
--participant_label ${subj_id} \
-t rest \
-w /work \
--fs-license-file /Freesurfer_dir/license.txt \
--nprocs ${cpu_usage} \
--omp-nthreads 1 \
--nthreads ${cpu_usage} \
--mem_mb ${mem_mb} \
--low-mem \
--bold2t1w-init header \
--bold2t1w-dof 9 \
-v \
--ignore {fieldmaps,slicetiming,sbref,t2w,flair} \
--force-bbr \
--dummy-scans 4 \
--fd-spike-threshold ${fd_thresh} \
--skull-strip-fixed-seed \
--skull-strip-t1w force \
--no-submm-recon \
--cifti-output 91k \
--output-layout bids \
--resource-monitor \
--write-graph \
--stop-on-first-crash
```

**Comment by effigies** [comment]
Hi, sorry I missed this when it hit. The "extra data" error seems to be a JSON decode error. Unfortunately, it's unclear what file is causing it.

I would try parsing all of the JSON files, and looking for errors. Something like:

```
find $BIDS_DIR -name "*.json" -exec jq . "{}" ";" > /dev/null
find $SCRATCH_DIR -name "*.json" -exec jq . "{}" ";" > /dev/null
find $OUTPUT_DIR -name "*.json" -exec jq . "{}" ";" > /dev/null
```
