### ISSUE TITLE
The output dimensions mismatch when AROMA is used

### ISSUE THREAD

**Issue by aghayoor** [nipreps/fmriprep#2390]
Hi Team,

I used fmriprep version 20.2.0.

I noticed that the dimensions of pre-processed functional data do not match with and without using AROMA.

Here is the output when AROMA is **not** used:

fslinfo ${subjID}_${sessID}_task-rest_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
data_type	INT16
**dim1		97
dim2	115
dim3	97
dim4	240**
datatype	4
pixdim1		2.000000
pixdim2		2.000000
pixdim3		2.000000
pixdim4		2.500000
cal_max		2537.676025
cal_min		-223.112579
file_type	NIFTI-1+

and here is the output when `--use_aroma` flag is used:

fslinfo ${subjID}_${sessID}_task-rest_space-MNI152NLin2009cAsym_desc-smoothAROMAnonaggr_bold.nii.gz
data_type	FLOAT32
**dim1		91
dim2	109
dim3	91
dim4	240**
datatype	16
pixdim1		2.000000
pixdim2		2.000000
pixdim3		2.000000
pixdim4		2.500000
cal_max		2553.395996
cal_min		-227.311096
file_type	NIFTI-1+

Both outputs are aligned in physical space, but I was wondering why the lattice dimensions are different among these two outputs? It can cause issues when we use a brain mask or a label map in down stream processing.

Thanks for your help here,
Ali

**Comment by effigies** [comment]
That does seem like a bug. I was under the impression that AROMA was always calculated on MNI152NLin6Asym. @jdkent do you happen to know about this? Otherwise I can look through the git blame to try to find how this happened.

**Comment by jdkent** [comment]
[Is this issue similar to the one on neurostars](https://neurostars.org/t/dimension-mismatch-among-preprocessed-bold-image-smootharoma-bold-and-the-corresponding-the-standard-template-while-mapping-to-mni152nlin2009casym-fmriprep-1-4-0/5043)?

**Comment by aghayoor** [comment]
Thank you both!
So based on neurostars link provided:

> The mismatch is intended:
> *_space-MNI152NLin2009cAsym_desc-preproc_bold (82, 97, 81 (voxel-size 2.4x2.4x2.4)) keeps the resolution of your original BOLD data (2.4mm isotropic)
> *_space-MNI152NLin2009cAsym_desc-smoothAROMAnonaggr_bold (91, 109, 91 (voxel-size 2x2x2)) uses the FSL MNI template matrix (91x109x91) because AROMA was trained with that one. At some point (after 1.4.0, it seems), you'll see that these outputs have changed to *_space-MNI152NLin6Asym_desc-smoothAROMAnonaggr_bold for consistency with AROMA (MNI152NLin6Asym corresponds to the MNI template shipped with FSL).

Also, I found this on the fmriprep page (here: https://fmriprep.org/en/latest/spaces.html)

> fMRIPrep will run nonlinear registration processes against the template T1w image corresponding to all the standard spaces supplied with the argument --output-spaces. By default, fMRIPrep will resample the preprocessed data on those spaces (...) but keeping the original resolution of the BOLD data to produce smaller files, more consistent with the original data gridding.

So it is not a bug! If we want to have the non-aroma output in MNI dimensions, we need to apply modifiers to the template identifier, separated by a `:` character; that means we need to use `--output-spaces MNI152NLin2009cAsym:res-2`  in fmriprep command line.
However, aroma output will always be in MNI dimensions because Aroma was trained on that one.
