### ISSUE TITLE
how is memory distributed across threads?

### ISSUE THREAD

**Issue by dmd** [nipreps/fmriprep#2391]
Suppose I call fmriprep with `--mem-mb 16384   --n_cpus 4`.

Will each thread use 16 GB for a total of 64, or will each thread use 4 GB for a total of 16, or is memory allocated some non-even way across threads?

**Comment by oesteban** [comment]
The ``--mem-mb 16384`` is *orientative* for NiPype.

Basically, when parallelizing, memory-fat tasks will tell NiPype an estimate of their memory fingerprint (and by *estimate* I'm being extremely generous) and NiPype will not allow a new task to be processed if its estimation doesn't fit withing the `--mem-mb` you've set.

So it's neither one or the other, but probably closer to saying *each thread use 4GB for a total of 16* (as you were indicating, memory is allocated non-evenly across processes).

Please note that each node in the compute graph will be executed as a new process, and they internally can spawn processes or threads again.

**Comment by dmd** [comment]
Thanks. That makes sense.
