### ISSUE TITLE
Issue noticed with https://fmriprep.org/en/stable/contributors.html#adding-dependencies while attempting to add new version of tedana (0.0.9) to docker image

### ISSUE THREAD

**Issue by QuintinFrerichsWUSTL** [nipreps/fmriprep#2395]
1. There’s a broken link in the documentation: https://github.com/nipreps/fmriprep/blob/master/requirements.txt (looks like the repo no longer has a requirements.txt) 
2. Rebuilding the docker image gives an error on step 8/42:
    E: Version ‘5.0.9-4~nd16.04+1’ for ‘fsl-core’ was not found

**Comment by emdupre** [comment]
Thanks for opening this, @QuintinFrerichsWUSTL !

For (1), I think we'll need to update the link to point to the `setup.cfg` file (likely defaulting to the [`install_requires` section](https://github.com/nipreps/fmriprep/blob/4bb8a61cde27575865cdd2b7df5afcb5d6860523/setup.cfg#L24-L41) ).

For (2) it looks like [neurodebian is now packaging](http://neuro.debian.net/pkgs/fsl-core.html) 5.0.9-5~nd16.04+1. So we'll likely need to update that in the Dockerfile.

For now, you might be able to patch (2) locally when you're building it s.t. you can have a built image to test with !

**Comment by mgxd** [comment]
Just to add on point 2) we have been pinning the FSL release to `5.0.9-5~nd16.04+1` for a least as far back as the `20.0.0` series
https://github.com/nipreps/fmriprep/blob/f9b2f5309f322a1464ffdd97044da26e4d5f97bf/Dockerfile#L74

so it's likely your Dockerfile is outdated.

**Comment by QuintinFrerichsWUSTL** [comment]
Thanks guys - I think I see what's going on. According to the documentation, I should modify the __about__.py file ("Python dependencies should generally be included in the REQUIRES list in fmriprep/__about__.py"). This files exists on the 510f28db branch, but not master, and the 510f28db branch's Dockerfile has the old version of fsl-core specified. I can workaround this by building with fsl-core=5.0.9-5~nd16.04+1 locally, but seems like another issue to me.

**Comment by QuintinFrerichsWUSTL** [comment]
Yes, so I was able to successfully build fmriprep with tedana 0.0.9 (the original issue from https://neurostars.org/t/zerodivisionerror-with-combine-py-for-multi-echo-fmri/17928/14), by copying the version of __about__.py from 510f28d into the repo on master and modifying it there.

**Comment by QuintinFrerichsWUSTL** [comment]
Ok sorry for the multiple replies, but after working through a couple more issues I ran into with the build, I've realized that IMO the best solution for the documentation is to link to setup.cfg (at install_requires) as you described, and remove the sentence on updating REQUIRES in __about__.py. This avoids having to transfer code between the branches and works for me.

**Comment by mgxd** [comment]
hi @QuintinFrerichsWUSTL -I'm a little confused, is your objective to build a docker image with an updated version of tedana?

If so, the easiest way may just be to download @tsalo's branch and build the Docker image from there.
```
wget https://github.com/tsalo/fmriprep/archive/refs/heads/update-tedana-req.zip  # or visit the page in browser
unzip update-tedana-req.zip
cd fmriprep-update-tedana-req
make docker-build tag="fmriprep:dev-aab2361"
```

**Comment by oesteban** [comment]
@QuintinFrerichsWUSTL next 21.x series coming up soon will build on tedana 0.0.10

Please reopen this issue if you the problems persist.
