### ISSUE TITLE
Wagner Lab Use Case - Poor Brain Mask

### ISSUE THREAD

**Issue by alitrelle** [nipreps/fmriprep#2399]
We are using fMRIPrep to preprocess fMRI data from a sample of older adults. For a number of subjects the EPI brain mask is inaccurate, and the accuracy of the mask often varies considerably from run to run. Any advice for how to improve the accuracy and reliability of this step would be very much appreciated!

### What version of fMRIPrep are you using?
We are using fmriprep v20.2.1, run via Singularity on Sherlock, and used the following command:

/usr/local/miniconda/bin/fmriprep /oak/stanford/groups/awagner/AM/FMRIPREP/trimmed_data /oak/stanford/groups/awagner/AM/FMRIPREP/trimmed_data/derivatives/fmriprep-20.2.1 participant --participant-label 125
 -w /work/ -vv --omp-nthreads 8 --nthreads 12 --mem_mb 30000 --skip_bids_validation --fs-license-file /home/users/atrelle/freesurfer.txt --skull-strip-t1w force --dummy-scans 5 --fd-spike-threshold 0.9 --dvars-spike-threshold 3.0 --output-spaces MNI152NLin2009cAsym:res-2 anat fsnative fsaverage5

The subjects are BIDS valid, run without error, and are using previously computed FreeSurfer outputs.

Reports can be found at /oak/stanford/groups/awagner/AM/FMRIPREP/trimmed_data/derivatives/fmriprep-20.2.1/fmriprep/${subject}/

See examples of outputs for some impacted subjects (sub-020, sub-030, sub-125) below:

<img width="1671" alt="Screen Shot 2021-04-16 at 1 04 33 PM" src="https://user-images.githubusercontent.com/43350768/115079242-bf426200-9eb5-11eb-9b23-970ce6901f5e.png">
<img width="1666" alt="Screen Shot 2021-04-19 at 3 02 01 PM" src="https://user-images.githubusercontent.com/43350768/115309393-10a25980-a121-11eb-8502-7e32f988e3e1.png">
<img width="1665" alt="Screen Shot 2021-04-16 at 11 59 56 AM" src="https://user-images.githubusercontent.com/43350768/115079052-6ffc3180-9eb5-11eb-9051-e082d8af9bb8.png">

**Comment by julfou81** [comment]
Hi,

Isn't the mask calculated from the T1w image and projected back to the bold space? Maybe there is an issue with the bold-to-T1w registration? Perhaps using the option ```--bold2t1w-init header```may help? or other like --bold2t1w-dof or check the distorsion correction step?

**Comment by oesteban** [comment]
> Isn't the mask calculated from the T1w image and projected back to the bold space?

No, that one is calculated on the EPI.

That said, it indeed looks like the first subject has a bad alignment with the T1w.

@alitrelle we've been working on the masking of EPIs - but that work has not yet been released. Can you share these three examples? Please drop me an email with more details about the dataset - maybe we can use Sherlock to share them.

**Comment by oesteban** [comment]
I'm thinking, one thing you could test (at the expense of undesired behavior) is removing the `--dummy-scans` flag. That will let fMRIPrep handle which timepoints are to be used in masking and perhaps get a better result.

**Comment by effigies** [comment]
@oesteban We've been in contact with Ali. They're sharing data with us on Sherlock, and @mgxd, @rciric and I have been talking with them.

**Comment by oesteban** [comment]
That's great, thanks!

**Comment by mgxd** [comment]
Just to bring some closure to the issue:

The problematic subjects tended to have large negative values - clipping the images to remove these negative values seemed to fix the co-registration and masking errors. This clipping (for both extremely negative/positive values) is something planned for the next upcoming release.
