### ISSUE TITLE
Performance of `_get_series_len`

### ISSUE THREAD

**Issue by HippocampusGirl** [nipreps/fmriprep#2405]
I am having some performance issues with creating fMRIPrep workflows for large datasets. As such, I did some profiling, and found that a lot of time is spent during creation of the workflow in `init_func_preproc_wf` on doing outlier detection. 

<img width="1458" alt="2021-04-28_12-05" src="https://user-images.githubusercontent.com/789054/116386492-20552880-a81a-11eb-8a6a-b5bb6bfd6356.png">

As far is I understand, this is to make sure that slice timing correction is only included if a sufficient number of volumes remains after removing non-steady state volumes in `init_bold_reference_wf`/`EstimateReferenceImage`. However, if `dummy_scans` is specified in the configuration, then this check may not be necessary, and workflows could be created twice as fast. 

Is my reasoning correct? Would you be interested in me contributing code to make this faster?

<https://github.com/nipreps/fmriprep/blob/674124ee80b3e2a8affddf005e910e4ca1c97cc0/fmriprep/workflows/bold/base.py#L221-L225>

https://github.com/nipreps/fmriprep/blob/674124ee80b3e2a8affddf005e910e4ca1c97cc0/fmriprep/workflows/bold/base.py#L879-L887

https://github.com/nipreps/niworkflows/blob/11ac7a18a403af717c0c2a29a33b7cadb75eabd7/niworkflows/interfaces/registration.py#L552-L557

**Comment by effigies** [comment]
Wow, yes. Thanks for this profiling. I didn't think that function would ever be a bottleneck, but let's optimize...

**Comment by HippocampusGirl** [comment]
My pull request only fixes this for the maintenance branch. Please let me know if I should also make one for the main branch :-)

**Comment by effigies** [comment]
We'll merge it. If it would be useful to have it merged sooner than later, we can do it right away.

**Comment by HippocampusGirl** [comment]
Ah perfect, I wasn't sure how you normally handle this
