### ISSUE TITLE
FreeSurfer license.txt file path provided, yet does not exist

### ISSUE THREAD

**Issue by Aamir-Sohail** [nipreps/fmriprep#2408]
Hello experts, I am new to using fMRIPrep and so wanted to test run it on a example dataset, however, I get the following message when running the fmriprep-docker command: 

fmriprep-docker /Users/aamirsohail/Reading/LT_haemodynamics/sub-01 /Users/aamirsohail/Reading/LT_haemodynamics/sub-01/output participant -- participant-label 01 --fs-license-file /Users/aamirsohail/Reading/LT_haemodynamics/license.txt --shell
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=20.10.5 -it -v /Users/aamirsohail/Reading/LT_haemodynamics/sub-01:/data:ro -v /Users/aamirsohail/Reading/LT_haemodynamics/sub-01/output:/out nipreps/fmriprep:20.2.1 /data /out participant participant-label 01 --fs-license-file /Users/aamirsohail/Reading/LT_haemodynamics/license.txt --shell
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
usage: fmriprep [-h] [--version] [--skip_bids_validation]
                [--participant-label PARTICIPANT_LABEL [PARTICIPANT_LABEL ...]]
                [-t TASK_ID] [--echo-idx ECHO_IDX] [--bids-filter-file FILE]
                [--anat-derivatives PATH] [--bids-database-dir PATH]
                [--nprocs NPROCS] [--omp-nthreads OMP_NTHREADS]
                [--mem MEMORY_GB] [--low-mem] [--use-plugin FILE]
                [--anat-only] [--boilerplate_only] [--md-only-boilerplate]
                [--error-on-aroma-warnings] [-v]
                [--ignore {fieldmaps,slicetiming,sbref,t2w,flair} [{fieldmaps,slicetiming,sbref,t2w,flair} ...]]
                [--longitudinal]
                [--output-spaces [OUTPUT_SPACES [OUTPUT_SPACES ...]]]
                [--bold2t1w-init {register,header}] [--bold2t1w-dof {6,9,12}]
                [--force-bbr] [--force-no-bbr] [--medial-surface-nan]
                [--dummy-scans DUMMY_SCANS] [--random-seed _RANDOM_SEED]
                [--use-aroma]
                [--aroma-melodic-dimensionality AROMA_MELODIC_DIM]
                [--return-all-components]
                [--fd-spike-threshold REGRESSORS_FD_TH]
                [--dvars-spike-threshold REGRESSORS_DVARS_TH]
                [--skull-strip-template SKULL_STRIP_TEMPLATE]
                [--skull-strip-fixed-seed]
                [--skull-strip-t1w {auto,skip,force}] [--fmap-bspline]
                [--fmap-no-demean] [--use-syn-sdc] [--force-syn]
                [--fs-license-file FILE] [--fs-subjects-dir PATH]
                [--no-submm-recon] [--cifti-output [{91k,170k}] |
                --fs-no-reconall] [--output-layout {bids,legacy}]
                [-w WORK_DIR] [--clean-workdir] [--resource-monitor]
                [--reports-only] [--config-file FILE] [--write-graph]
                [--stop-on-first-crash] [--notrack]
                [--debug {compcor,all} [{compcor,all} ...]] [--sloppy]
                bids_dir output_dir {participant}
fmriprep: error: Path does not exist: </Users/aamirsohail/Reading/LT_haemodynamics/license.txt>.
fMRIPrep: Please report errors to https://github.com/nipreps/fmriprep/issues

I have provided the correct path to where the FreeSurfer license.txt file is in my directory, but am unsure why it does not exist. 

Thanks!

Aamir

**Comment by mgxd** [comment]
it looks like you have a space in `-- participant-label 01` that might be causing some trouble. Also, you probably don't need the `--shell` command unless you want to run it interactively.

**Comment by effigies** [comment]
Your first argument should be the dataset, not the subject in the dataset.

**Comment by Aamir-Sohail** [comment]
Cheers, it works fine now!
