### ISSUE TITLE
fMRIPrep failed

### ISSUE THREAD

**Issue by Kang1448** [nipreps/fmriprep#2412]
fMRIPrep failed: Each element of the 'in_files' trait of a _IntraModalMergeInputSpec instance must be a pathlike object or string representing an existing file, but a value of '/data/sub-01/fmap/sub-01_magnitude1.nii.gz' <class 'str'> was specified.
fMRIPrep: Please report errors to https://github.com/nipreps/fmriprep/issues

**Comment by effigies** [comment]
Hi, can you fill out a [bug report]? Any details you're able to give us will make it easier to figure out what went wrong.

In general, this indicates that your file `/data/sub-01/fmap/sub-01_magnitude1.nii.gz` cannot be read for some reason. You may want to verify that you can open it outside of fMRIPrep.

**Comment by effigies** [comment]
Please open a new issue with a full bug report if you're still experiencing problems.
