### ISSUE TITLE
fmriprep taking too long to run a single dataset

### ISSUE THREAD

**Issue by Meishai96** [nipreps/fmriprep#2414]
I have a dataset with the following contents:
![image](https://user-images.githubusercontent.com/62561104/118560516-9a9d0c80-b737-11eb-8b86-ffb7e9f8919e.png)

Here is my settings for slurm job:
#SBATCH --job-name=jobMA_fmriprep
#SBATCH --partition=short
#SBATCH --time=23:59:00
#SBATCH --ntasks=8
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=16GB

The time limit for a slurm job is 24hrs, and the job will be cancelled if it runs over than the time limit. I have set number of tasks as 8, in order to have parallel computing and reduce the time length of running it. But the job still can't be finished within 24 hours.

I was wondering if it will take that long to run a single subject with such memory/cores settings? Or is there anything I need to set up in the fmriprep command in order to have the correct parallel mode? Thank you!

**Comment by mgxd** [comment]
There are many factors that can affect fMRIPrep's runtime, including:
- BOLD resolution
- BOLD series with many timepoints
- multiple runs per BOLD task
- FreeSurfer reconstruction (~8 hours)

If you wanted to exclude certain tasks / runs, this guide might be helpful: https://fmriprep.org/en/stable/faq.html#how-do-i-select-only-certain-files-to-be-input-to-fmriprep

Also, if you preserve the working directory across invocations, fMRIPrep should be able to pick up where it left off. This can be helpful if jobs are cancelled prematurely.

**Comment by Meishai96** [comment]
> There are many factors that can affect fMRIPrep's runtime, including:
> 
> * BOLD resolution
> * BOLD series with many timepoints
> * multiple runs per BOLD task
> * FreeSurfer reconstruction (~8 hours)
> 
> If you wanted to exclude certain tasks / runs, this guide might be helpful: https://fmriprep.org/en/stable/faq.html#how-do-i-select-only-certain-files-to-be-input-to-fmriprep
> 
> Also, if you preserve the working directory across invocations, fMRIPrep should be able to pick up where it left off. This can be helpful if jobs are cancelled prematurely.

Thank you so much! Yes I only picked up my interested functional imagings and it worked out with a shorter time! Also I found if I don't do any denoising, it will take far shorter.

**Comment by effigies** [comment]
Please reopen if there is anything left to resolve.
