### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/out/fmriprep/logs'

### ISSUE THREAD

**Issue by ramtilak** [nipreps/fmriprep#2416]
C:\Users\Ram Tilak>fmriprep-docker C:\Users\Ram\sp\dataset C:\Users\Ram\sp\op  --fs-license-file C:\Users\Ram\sp\license.txt
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=20.10.6 -it -v C:\Users\Ram\sp\license.txt:/opt/freesurfer/license.txt:ro -v C:\Users\Ram\sp\dataset:/data:ro -v C:\Users\Ram\sp\op:/out nipreps/fmriprep:20.2.1 /data /out participant
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
bids-validator@1.4.0

        1: [WARN] The Authors field of dataset_description.json should contain an array of fields - with one author per field. This was triggered based on the presence of only one author field. Please ignore if all contributors are already properly listed. (code: 102 - TOO_FEW_AUTHORS)

        Please visit https://neurostars.org/search?q=TOO_FEW_AUTHORS for existing conversations about this issue.

        Summary:                 Available Tasks:        Available Modalities:
        145 Files, 1.38GB        rest                    T1w
        28 - Subjects                                    bold
        1 - Session                                      physio

        If you have any questions, please post on https://neurostars.org/tags/bids.

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/pathlib.py", line 1241, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/out/fmriprep/logs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 17, in main
    parse_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/parser.py", line 709, in parse_args
    config.execution.log_dir.mkdir(exist_ok=True, parents=True)
  File "/usr/local/miniconda/lib/python3.7/pathlib.py", line 1245, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/local/miniconda/lib/python3.7/pathlib.py", line 1241, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 1] Operation not permitted: '/out/fmriprep'
fMRIPrep: Please report errors to https://github.com/nipreps/fmriprep/issues
```

**Comment by effigies** [comment]
It seems you don't have permissions to write to the output directory. This may be an interaction with Windows, where you need to adjust the Uid of the container. Do you know your UID?

**Comment by effigies** [comment]
Please reopen if this is not resolved.
