### ISSUE TITLE
failed preprocessing only in two particular subjects

### ISSUE THREAD

**Issue by jcbeucke** [nipreps/fmriprep#2428]
Hello everyone, 

I tried to run fMRIPrep to preprocess six subjects with one command (given below). At the end, the HTLM-file shows the following error for the first two subjects (sub-14 and sub-15, please find the detailed error report further below).

Standard error:
 file NULL does not exist .
 file NULL does not exist .
 file NULL does not exist .
Killed
Return code: 137

Now the error shows some similarity with a previous post  (#2126; https://github.com/nipreps/fmriprep/issues/2126) however what is striking and different is that the remaining 4 subjects  included in the command after the two ones with errors finished without any errors.

Previously, thus before running those six subjects, we had preprocessed 13 subjects in a row without any errors, so it seems to has that there is a particular problem with those subjects instead of a general one. 

Do you have an idea what is going on here? We would love to learn how to fix this issue so those two subjects can be included. 

(My PC/system characteristics:
Processor: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz 3.41GHz
RAM: 8.00 GB
System type: 64-bit, x64-based processor
Operating system: Windows 10 Education)

Please find below the HTLM-file (converted to pdf) which shows the complete error-code and report for one of the two failed subjects. Thanks so much for having a look at this, any hint will be appreciated!

**Answers to the standard questions:**

### Yes, fMRIPrep generated a visual report for all subjects, both for those where it worked and for those where it did not work. The two subjects with failed preprocessing had the following output

[sub-14_html2pdf.pdf](https://github.com/nipreps/fmriprep/files/6695427/sub-14_html2pdf.pdf)

### 
Stage 2
  iterations = 50x10x0
  convergence threshold = 1.0000e-09
  convergence window size = 15
  number of levels = 3
  using the CC metric (radius = 4, weight = 5.0000e-01)
  preprocessing:  winsorizing the image intensities
  preprocessing:  histogram matching the images
  using the CC metric (radius = 4, weight = 5.0000e-01)
  preprocessing:  winsorizing the image intensities
  preprocessing:  histogram matching the images
  Shrink factors (level 1 out of 3): [4, 4, 4]
  Shrink factors (level 2 out of 3): [2, 2, 2]
  Shrink factors (level 3 out of 3): [1, 1, 1]
  smoothing sigmas per level: [2, 1, 0]
  Using default NONE metricSamplingStrategy 

*** Running SyN registration (varianceForUpdateField = 3.0000e+00, varianceForTotalField = 0.0000e+00) ***

Standard error:
file NULL does not exist . 
 file NULL does not exist . 
 file NULL does not exist . 
Killed
Return code: 137

### No, I don´t reuse previously computed results.

[crash-20210616-122947-root-norm-c1645837-5aa4-4bdc-9c51-49ec5cfe3300.txt](https://github.com/nipreps/fmriprep/files/6695279/crash-20210616-122947-root-norm-c1645837-5aa4-4bdc-9c51-49ec5cfe3300.txt)

**Comment by oesteban** [comment]
> Do you have an idea what is going on here? We would love to learn how to fix this issue so those two subjects can be included.

As in the thread you linked, this looks like you are running out of space on the temporal folder. One potential solution is to set the argument `-w` (work directory) to some mount point that you already know has enough space, or alternatively, configure Docker to have a much larger temporal space allocation.

**Comment by effigies** [comment]
Please reopen if this is not resolved.
