### ISSUE TITLE
fmriprep 20.2.1 image on Docker Hub?

### ISSUE THREAD

**Issue by justbennet** [nipreps/fmriprep#2432]
I was just looking to update our Singularity image to fmriprep 20.2.1, which I see at GitHub is at

20.2.1 (Long-Term Support)

from Nov 6, 2020.  On Docker Hub, though, the version is reported as fmriprep 20.2.0, though, but the date says Sep, 28, 2020.

Will there be an updated Docker Hub image for 20.2.1?

**Comment by effigies** [comment]
[nipreps/fmriprep:20.2.1](https://hub.docker.com/layers/nipreps/fmriprep/20.2.1/images/sha256-e99e02baff67944aad941f88a7a9b1ed99dac32ec099a7b3ed002176d3851a75)

**Comment by justbennet** [comment]
Ah.  Sorry I missed the switch to the new group name at Docker Hub.
