### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Kang1448** [nipreps/fmriprep#2438]
### What version of fMRIPrep are you using?
 20.2.1
### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?
Docker 
### What is the exact command-line you used?
```
bash fmriprep.sh
```

### Have you checked that your inputs are BIDS valid?
Yes
### Did fMRIPrep generate the visual report for this particular subject? If yes, could you share it?
https://www.dropbox.com/s/j5co4hcqo0sjs66/sub-01.html?dl=0

### Can you find some traces of the error reported in the visual report (at the bottom) or in *crashfiles*?
```
Node Name: fmriprep_wf.single_subject_01_wf.func_preproc_task_IBL_run_01_wf.bold_hmc_wf.mcflirt
```

### Are you reusing previously computed results (e.g., FreeSurfer, Anatomical derivatives, work directory of previous run)?

Nope
### fMRIPrep log
If you have access to the output logged by fMRIPrep, please make sure to attach it as a text file to this issue.

**Comment by oesteban** [comment]
Hi @Kang1448, we will need to know the contents of your `fmriprep.sh` script. Also, more information about the error, as the line you provided only indicates a node run by the pipeline. But it says nothing about the error, unfortunately.

Finally, you just shared the HTML file of the report, but we would need to see the whole report (meaning, please package in a zip file this HTML file and the `sub-01/figures/` folder of the subject.

I have at least extracted the error from your HTML file:

<details>
    <summary>Node Name: fmriprep_wf.single_subject_01_wf.func_preproc_task_IBL_run_01_wf.bold_hmc_wf.mcflirt</summary><br>
    <div>
        File: <code>/out/fmriprep/sub-01/log/20210705-001607_293aeeee-a502-4a04-bf82-41f1c54a6e8f/crash-20210705-001955-root-mcflirt-8bf33080-7eb5-458c-a8dd-856b3e4a3c5d.txt</code><br>
        Working Directory: <code>/scratch/fmriprep_wf/single_subject_01_wf/func_preproc_task_IBL_run_01_wf/bold_hmc_wf/mcflirt</code><br>
        Inputs: <br>
        <ul>
            <li>args: <code><undefined></code></li>
            <li>bins: <code><undefined></code></li>
            <li>cost: <code><undefined></code></li>
            <li>dof: <code><undefined></code></li>
            <li>environ: <code>{'FSLOUTPUTTYPE': 'NIFTI_GZ'}</code></li>
            <li>in_file: <code><undefined></code></li>
            <li>init: <code><undefined></code></li>
            <li>interpolation: <code><undefined></code></li>
            <li>mean_vol: <code><undefined></code></li>
            <li>out_file: <code><undefined></code></li>
            <li>output_type: <code>NIFTI_GZ</code></li>
            <li>ref_file: <code><undefined></code></li>
            <li>ref_vol: <code><undefined></code></li>
            <li>rotation: <code><undefined></code></li>
            <li>save_mats: <code>True</code></li>
            <li>save_plots: <code>True</code></li>
            <li>save_rms: <code>True</code></li>
            <li>scaling: <code><undefined></code></li>
            <li>smooth: <code><undefined></code></li>
            <li>stages: <code><undefined></code></li>
            <li>stats_imgs: <code><undefined></code></li>
            <li>use_contour: <code><undefined></code></li>
            <li>use_gradient: <code><undefined></code></li>
        </ul>
        <pre>Traceback (most recent call last):
File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
result["result"] = node.run(updatehash=updatehash)
File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
result = self._run_interface(execute=True)
File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
return self._run_command(execute)
File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
result = self._interface.run(cwd=outdir)
File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 421, in run
outputs = self.aggregate_outputs(runtime)
File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 498, in aggregate_outputs
predicted_outputs = self._list_outputs()  # Predictions from _list_outputs
File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/fsl/preprocess.py", line 936, in _list_outputs
_, _, _, timepoints = load(self.inputs.in_file).shape
ValueError: not enough values to unpack (expected 4, got 3)</pre>
    </div>
</details>

Based on this error, my question is: how many timepoints your BOLD series have? It seems to me you are trying to pass in a 3D file.

**Comment by Kang1448** [comment]
Dear all,
Thanks for helping. Please see the attachments.

**Comment by Kang1448** [comment]
Hello, may I know any update?

**Comment by effigies** [comment]
Hi @Kang1448 , if you sent an attachment by email, it was scrubbed. Please post directly to GitHub.

**Comment by Kang1448** [comment]
#!/bin/bash

#User inputs:
bids_root_dir=$HOME/learning/
subj=01
nthreads=16
mem=64 #gb
container=docker #docker or singularity

#Begin:

#Convert virtual memory from gb to mb
mem=`echo "${mem//[!0-9]/}"` #remove gb at end
mem_mb=`echo $(((mem*1000)-5000))` #reduce some memory for buffer space during pre-processing

export TEMPLATEFLOW_HOME=$HOME/templateflow
export FS_LICENSE=$HOME/learning/derivatives/
cd $FS_LICENSE
ls

#Run fmriprep
if [ $container == singularity ]; then
  unset PYTHONPATH; singularity run -B $HOME/templateflow:/opt/templateflow /rds/general/user/wk20/home/fmriprep.simg \
    $bids_root_dir $bids_root_dir/derivatives \
    participant \
    --participant-label $subj \
    --md-only-boilerplate \
    --fs-license-file $HOME/learning/derivatives/license.txt \
    --fs-no-reconall \
    --output-spaces MNI152NLin2009cAsym:res-2 \
    --nthreads $nthreads \
    --stop-on-first-crash \
    --mem_mb $mem_mb \
    -w $HOME/learning/
else
  fmriprep-docker $bids_root_dir $bids_root_dir/derivatives \
    participant \
    --participant-label $subj \
    --skip-bids-validation \
    --md-only-boilerplate \
    --fs-license-file $HOME/learning/derivatives/license.txt \
    --fs-no-reconall \
    --output-spaces MNI152NLin2009cAsym:res-2 \
    --nthreads $nthreads \
    --stop-on-first-crash \
    --mem_mb $mem_mb \
    -w $HOME
fi
[sub-01.zip](https://github.com/nipreps/fmriprep/files/6774036/sub-01.zip)

**Comment by oesteban** [comment]
> Based on this error, my question is: how many timepoints your BOLD series have? It seems to me you are trying to pass in a 3D file.

Hi @Kang1448, I was waiting on your feedback regarding the above question.

**Comment by Kang1448** [comment]
![fmr](https://user-images.githubusercontent.com/67905967/124858623-ffab0b00-dfe0-11eb-9fe7-a9c002683f99.png)
My colleague is suspecting that there is something wrong with the bids format, you can see from picture, he believes that there should be only one nii.gz and one .json. Do you know why? In order to find out how many timepoints I have, I need to open the nii.gz right?

**Comment by Kang1448** [comment]
please see the files here: https://drive.google.com/file/d/1Y-3FSaDlfUawwH0caazjAY-MhAt9i0Dr/view?usp=sharing

**Comment by oesteban** [comment]
Hi @Kang1448 your IBL task does have a 3D (not 4D) bold file:

```
$ nib-ls *_bold.nii.gz
sub-01_task-IBL_run-01_bold.nii.gz  int16 [ 70,  70,  55]      3.00x3.00x3.00        sform
sub-01_task-SST_run-01_bold.nii.gz  int16 [ 88,  88,  64, 810] 2.39x2.39x2.40x2.00   sform
sub-01_task-rest_run-01_bold.nii.gz int16 [ 88,  88,  64, 705] 2.39x2.39x2.40x2.00   sform
```

I'm not sure what can be the use of a 3D bold file other than reference, but fMRIPrep will definitely not process it correctly as you are experiencing.

Can I ask why do you have such a 3D bold file?
