### ISSUE TITLE
REQUEST: --fs-subjects-dir in fmriprep 1.3.x

### ISSUE THREAD

**Issue by StephDocTUM** [nipreps/fmriprep#2442]
Dear all,

I am using  fmriprep version 2.1.0. in a python script and want to give in already processed freesurfer data:
`   subprocess.run(['fmriprep', str(subject_path), str(path_output_fmriprep)+'/participant/', 'participant', '--fs-subjects-dir', str(path_freesurfer), '--fs-license-file', str(path_fs_license)])
`

It does not find the command `--fs-subjects-dir`. Is it not included in 2.1.0? but in 2.2.1 it does work.
I use a docker container with `FROM tigrlab/fmriprep_ciftify:latest`, which uses I think not the 2.2.1 version of fmriprep.

**Comment by effigies** [comment]
It looks like `--fs-subjects-dir` was added in version 1.5.3. We don't have versions 2.1.x or 2.2.x, so I'm not sure what those correspond to.

**Comment by StephDocTUM** [comment]
Sorry, I meant 20.2.1

**Comment by effigies** [comment]
So it looks like ciftify's BIDS App uses fMRIPrep 1.3.2: https://github.com/edickie/ciftify/blob/421f87d59bd08775e846847fceb8e8430ea81bc8/ciftify/bidsapp/Dockerfile

This would be a good issue to raise in ciftify. My guess is that that version was chosen to avoid changing derivatives, so upgrading to 20.2+ might be involved. If they need to continue using 1.3.x, it would not be terribly difficult to backport https://github.com/nipreps/fmriprep/pull/1901.

**Comment by oesteban** [comment]
@edickie, can we safely assume ciftify will upgrade to 20.2.x at some point? (we recommend that as it is tagged LTS and situations like this issue will have it harder to regress)

**Comment by mgxd** [comment]
Closing this as it is a ciftify issue
