### ISSUE TITLE
TraitError

### ISSUE THREAD

**Issue by SoveshMohapa** [nipreps/fmriprep#2447]
### What is the exact command-line you used?
```
<place your command line here>
```

### Can you find some traces of the error reported in the visual report (at the bottom) or in *crashfiles*?
```
<please copy&paste all the information you can gather about errors>
```

```
TraitError: The 'reference_image' trait of an ApplyTransformsInputSpec instance must be a pathlike object or string representing an existing file, but a value of '[]' <class 'str'> was specified.
```

### fMRIPrep log
If you have access to the output logged by fMRIPrep, please make sure to attach it as a text file to this issue.

**Comment by effigies** [comment]
Hi @SoveshMohapa, please fill in the form so that we can help you.

**Comment by effigies** [comment]
Please open a new issue with the requested information if you still need help.
