### ISSUE TITLE
20.2.2 docker image says it's an older version (20.1.4)?

### ISSUE THREAD

**Issue by fcmeyer** [nipreps/fmriprep#2453]
Hi folks,

I'm trying out the new 20.2.2 release via the Docker image, and upon running this latest image I got a warning that I was using an older version (20.1.4) and a newer one was available. Upon inspection, it seems that the image layer details for this release do mention this older version code (e.g. lines 38+ [in the docker image layer details](https://hub.docker.com/layers/nipreps/fmriprep/20.2.2/images/sha256-0f4618f0790576c25e85e3bcf1869c8f6abed13c69e0b4f596a9aad683432de2?context=explore)). Is this still the newer image that has been mislabeled? Or is it a resubmit of the older image with a newer version?

Thank you!

**Comment by effigies** [comment]
It's possible we may need to re-run the export for 20.2.2. There were a number of mis-fires with the 20.1.4 release, and the version may be messed up. Looking into it.

**Comment by fcmeyer** [comment]
Thank you!! I will note, funny enough this version is working really well on Docker for Mac - isn't giving me issues like 20.2.1!

**Comment by effigies** [comment]
Nope, looks like it's actually 20.1.4, going by the changelog:

```
fmriprep-docker --shell  
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=20.10.7 -it -v /home/chris:/data:ro -v /home/chris:/out --entrypoint=bash nipreps/fmriprep:20.2.2
root@ab8cc7d7e3ca:/tmp# cd /
root@ab8cc7d7e3ca:/# ls
bin   data  etc   lib    media  opt  proc  run   src  sys  usr
boot  dev   home  lib64  mnt    out  root  sbin  srv  tmp  var
root@ab8cc7d7e3ca:/# cd src
root@ab8cc7d7e3ca:/src# ls
fmriprep
root@ab8cc7d7e3ca:/src# cd fmriprep/
root@ab8cc7d7e3ca:/src/fmriprep# ls
CHANGES.rst         LICENSE      REFERENCES.md  long_description.rst  setup.cfg
CODE_OF_CONDUCT.md  MANIFEST.in  docker         notebooks             setup.py
Dockerfile          Makefile     docs           pyproject.toml        versioneer.py
Dockerfile_devel    README.rst   fmriprep       scripts               wrapper
root@ab8cc7d7e3ca:/src/fmriprep# head -n 30 CHANGES.rst 
20.1.4 (July 16, 2021)
======================
Hotfix release addressing a bug on *fMRIPrep*'s resampling to standard spaces.
This release also includes some maintenance changes handling old versions of software.

* FIX: Feed *NiTransforms* with LTAs of type RAS2RAS (#2444)
* MAINT: Pin ``svgutils==0.3.1`` for the 20.1.x series (#2450)
* MAINT: Keep pip and setuptools with support for Python 3.5 (#2449)
* MAINT: Some dependencies cannot be left unpinned (#2446)

20.1.3 (September 15, 2020)
```

@oesteban I think you're the only one with permission to remove things from Docker Hub.

**Comment by oesteban** [comment]
O_O I'll check asap

**Comment by julfou81** [comment]
It is solved now: I typed:
- ```singularity build fmriprep-20.2.2.simg docker://nipreps/fmriprep:20.2.2```
-```singularity run fmriprep-20.2.2.simg --version```
and got: ```fMRIPrep v20.2.2```

**Comment by effigies** [comment]
Thanks for reporting back.
