### ISSUE TITLE
Are these images the same? 

### ISSUE THREAD

**Issue by ly6ustc** [nipreps/fmriprep#2473]
Hi,
I found there are several source of fmriprep in Docker hub (see figure below), including "nipreps/fmriprep" and "poldracklab/fmriprep" . 
![image](https://user-images.githubusercontent.com/69618541/126607776-65cf392c-e3af-48df-9329-7b388cfba25b.png)

The latter has more downloads but not the newest version. So what's the difference between these two sources?  I think they are quite the same but updated by different people or institutes, is it right?

**Comment by effigies** [comment]
fMRIPrep began as a project in the Poldrack lab, but to transition it to a community-driven project, we've moved it under the nipreps organization in GitHub, and begun uploading it to nipreps on DockerHub.

Both are official, but the nipreps one will receive all new versions (possibly some exceptions if we have to release a fix for an old series) while the poldracklab one is now a historical archive.

**Comment by ly6ustc** [comment]
> fMRIPrep began as a project in the Poldrack lab, but to transition it to a community-driven project, we've moved it under the nipreps organization in GitHub, and begun uploading it to nipreps on DockerHub.
> 
> Both are official, but the nipreps one will receive all new versions (possibly some exceptions if we have to release a fix for an old series) while the poldracklab one is now a historical archive.

Got it, thanks for your explanations.
