### ISSUE TITLE
 error waiting for container: invalid character 'u' looking for beginning of value  + afni can not work

### ISSUE THREAD

**Issue by shauyin520** [nipreps/fmriprep#2475]
Hi, i am using  fMRIPrep:  20.2.1
i tried to run : $ fmriprep-docker --fs-license-file license.txt/ fMRIanalysissession/Nifti fMRIanalysissession/derivatives participant
it works , 
but after one night"s running, 
the error at the end comes out like this:
ERRO[40676] error waiting for container: invalid character 'u' looking for beginning of value

and another problem is: i tried to fun $ afni
messages comes out like this: 
Precompiled binary linux_ubuntu_16_64: Jun 28 2021 (Version AFNI_21.1.20 'Domitian')
** Version check disabled: AFNI_VERSION_CHECK forbids
Thanks go to JA Butman for useful feedback
Initializing: X11Error: Can't open display: localhost:0.0
++ AFNI is detached from terminal.
i can not run afni, 

can anyone help me to figure out what the problems are?
thank you for your help, 
greeting, 
chen

**Comment by effigies** [comment]
Hi.

> i tried to run : $ fmriprep-docker --fs-license-file license.txt/ fMRIanalysissession/Nifti fMRIanalysissession/derivatives participant
> it works ,
> but after one night"s running,
> the error at the end comes out like this:
> ERRO[40676] error waiting for container: invalid character 'u' looking for beginning of value

This seems to be a Docker issue: https://github.com/docker/for-mac/issues/5139
There doesn't seem to be a clear cause or solution.



> $ afni
> messages comes out like this:
> Precompiled binary linux_ubuntu_16_64: Jun 28 2021 (Version AFNI_21.1.20 'Domitian')
> ** Version check disabled: AFNI_VERSION_CHECK forbids
> Thanks go to JA Butman for useful feedback
> Initializing: X11Error: Can't open display: localhost:0.0
> ++ AFNI is detached from terminal.
> i can not run afni,

AFNI support is generally provided on https://afni.nimh.nih.gov/afni/community/board/list.php?1.
