### ISSUE TITLE
Slice-timing-correction induced time shift holds potential for error in subsequent fMRI analysis

### ISSUE THREAD

**Issue by theoschaefer** [nipreps/fmriprep#2477]
Hi everyone,

with this post, we would like to point to a potentially serious issue introduced by fMRIPrep’s slice-timing correction (STC) which affects further processing of fMRI data and might therefore be relevant for a large number of users.

STC in fMRIPrep is referenced to the middle slice which leads to a time-shift in the onsets by 0.5 TR. Importantly, users might not be explicitly aware of this time shift and might therefore not consider it for subsequent analyses, especially since defaults of other software packages are sometimes misaligned (e.g. nilearn’s function “nilearn.glm.first_level.FirstLevelModel'' has a default microtime onset of 0). This may inadvertently lead to model misspecification for a potentially large number of users. Currently, it is not clear how many users are affected by this issue but an informal survey of fMRIPrep users at our institute makes us think this may be quite prevalent. The impact is currently also not very clear but correcting for the effect (i.e. considering the time shift in subsequent analyses) strongly improved the results of all users involved at our institute, so we think the impact may be high. The upside of this effect is that accurately taking the time shift into account should only improve model specification and therefore lead to stronger results.

While the reference to the middle slice is currently documented at two locations in fMRIPrep ([here](https://fmriprep.org/en/stable/workflows.html#slice-time-correction) and [here](https://raw.githubusercontent.com/oesteban/fmriprep/38a63e9504ab67812b63813c5fe9af882109408e/docs/_static/fmriprep-workflow-all.png)), it does not appear in the usage notes or in the output documentation.

For this reason, it might first be necessary to explicitly inform users in the documentation about the time shift at many different locations and - importantly - explain the consequence for statistical analyses after fMRIPrep is completed. This could include an explicit warning box along the lines of “Caution! Slice timing correction shifts the data by half a TR. This means that you need to adjust your onset files, the microtime onset or the parameters in your first-level model function”.  The information could be included in “Processing Pipeline Details”, “Outputs of fMRIprep”, “Citing fMRIPrep” and in the methods template.

Here are some additional ideas on how to deal with the time-shift issue:

1. More information in the outputs, e.g. by emphasizing the new reference time in the output or by providing new time frames in the output (e.g. [1., 3., 5., ...] instead of [0., 2., 4., …] for TR = 2)

2. Adjust the STC reference to the first slice to make fMRIPrep more modular. This has to be accompanied by additional documentation to avoid similar errors in the other direction. 

3. Write out new time-shifted onset files to keep everything downwards compatible and still use the optimal processing pipeline. This also has to be accompanied by additional documentation of the output files. This may, however, currently not be possible with the current version of BIDS.

4. Include an argument in the fmriprep function which specifies the preferred reference slice. 

Looking forward to hearing from you!

@martinhebart
@nitschalex
@oliver-contier
@theoschaefer

**Comment by effigies** [comment]
Hi Theo, thanks for this.

> 1. More information in the outputs, e.g. by emphasizing the new reference time in the output or by providing new time frames in the output (e.g. [1., 3., 5., ...] instead of [0., 2., 4., …] for TR = 2)

This seems doable. There's a [`toffset` field in NIfTI](https://github.com/NIFTI-Imaging/nifti_clib/blob/7934f742f435c3d6628a1099cd2dba14d6cd2216/niftilib/nifti1.h#L1306-L1308). I'm not sure if this is respected by most tools. My initial thought had been to use `slice_code` to indicate how slice timing was performed, but `toffset` seems like the better fix.

CIFTI images do have explicit time series axes, so we should update the `SeriesStart` field.

GIFTI time series do not have any representation of an offset. We will need a BIDS metadata field for this.

In all cases, we need to ensure that downstream tools handle the internal and BIDS metadata correctly.

> 2. Adjust the STC reference to the first slice to make fMRIPrep more modular. This has to be accompanied by additional documentation to avoid similar errors in the other direction.

> 4. Include an argument in the fmriprep function which specifies the preferred reference slice.

4 seems to cover 2. I think that's reasonable.

> 3. Write out new time-shifted onset files to keep everything downwards compatible and still use the optimal processing pipeline. This also has to be accompanied by additional documentation of the output files. This may, however, currently not be possible with the current version of BIDS.

Given that fMRIPrep doesn't use or modify `events.tsv`, this would be a significant change in where downstream tools are expecting to find events files. I could also imagine situations where somebody preprocesses their fMRI data and then separately updates their events files; it would be burdensome to re-compute.

That said, a small tool that takes the original dataset and the fMRIPrep outputs and produces corrected events files would be sensible.

**Comment by neurolabusc** [comment]
>  2. Adjust the STC reference to the first slice to make fMRIPrep more modular. This has to be accompanied by additional documentation to avoid similar errors in the other direction.

**Comment by effigies** [comment]
Opened discussion for BIDS metadata on https://github.com/bids-standard/bids-specification/issues/836.

**Comment by theoschaefer** [comment]
Thanks for your answers and for cross-posting the issue!

We could start to write documentation snippets as we think that explicitly informing users in the documentation about the time-shift consequences might be one of the first steps. We would then push our suggestions to the repository. 

Adding the information to the Nifti `toffset` field would certainly make the metadata more informative. How many software packages consider the `toffset` field automatically? Or would this still require users to actively retrieve this information out of the metadata?

We agree that changing the original `events.tsv` might lead to additional difficulties for downstream tools or custom scripts. Perhaps the tool you propose, Chris, could either save corrected `events.tsv` separately in the fMRIPrep derivatives folder or output new frame times for the acquired volumes (e.g. 1,3,5 instead of 0,2,4 s). Also for the frame times, the question would then be if this is used by software packages (e.g. the nilearn function make_first_level_design_matrix requires frame times as an explicit input) - or at least generating these outputs might make the user aware of the time shift and perhaps help them to double check their timings.

**Comment by effigies** [comment]
> We could start to write documentation snippets as we think that explicitly informing users in the documentation about the time-shift consequences might be one of the first steps. We would then push our suggestions to the repository.

Sounds good to me. Please feel free to ask questions if you need help getting going on that.

> Adding the information to the Nifti `toffset` field would certainly make the metadata more informative. How many software packages consider the `toffset` field automatically? Or would this still require users to actively retrieve this information out of the metadata?

We would need to look into this. We should definitely encourage tools to use `toffset` by default *and* to allow users to provide an offset. I know nilearn does not use `toffset`.

> We agree that changing the original `events.tsv` might lead to additional difficulties for downstream tools or custom scripts. Perhaps the tool you propose, Chris, could either save corrected `events.tsv` separately in the fMRIPrep derivatives folder or output new frame times for the acquired volumes (e.g. 1,3,5 instead of 0,2,4 s).

I would personally keep them in a new derivatives dataset, to keep the provenance of the fMRIPrep derivatives clean. But clean organization is in the eye of the beholder, and this will almost certainly be a decision that will be made by the user.

> Also for the frame times, the question would then be if this is used by software packages (e.g. the nilearn function make_first_level_design_matrix requires frame times as an explicit input) - or at least generating these outputs might make the user aware of the time shift and perhaps help them to double check their timings.

Yeah, user awareness seems essential. While a BIDS-aware tool should respect the BIDS metadata, it's going to take time to percolate through, and not all tools are going to be BIDS-aware.

**Comment by HippocampusGirl** [comment]
Would it be possible to also add the number of non-steady state volumes that are skipped to the `toffset`? Or is it meant only as the offset within a volume?

**Comment by effigies** [comment]
From [the spec](https://github.com/NIFTI-Imaging/nifti_clib/blob/7934f742f435c3d6628a1099cd2dba14d6cd2216/niftilib/nifti1.h#L1306-L1308): `The toffset field can be used to indicate a nonzero start point for the time axis.  That is, time point #m is at t=toffset+m*pixdim[4] for m=0..dim[4]-1.`

This seems clear to me that toffset should give the timing of the first volume, regardless of whether it's steady state or not.

If the goal is to indicate that the first steady state volume is t0, and events.tsv are defined relative to that, then it would make sense for the raw `toffset` to be set to `-n_steadystate * pixdim[4]`. And we should make sure that we do respect incoming `toffset` and `StartTime` when making these adjustments.

**Comment by kellyhennigan** [comment]
Thanks for taking this issue seriously as it does impact timing and subsequent modeling choices. Would it be possible to add which slice (or timepoint) the slice timing correction aligns as a user option? So that users can choose for example to align their data to the first or last slice, rather than the middle slice?

**Comment by effigies** [comment]
AFNI's 3dTshift allows a lot of flexibility with `-tzero` or `-slice`:

```
  -tzero zzz    = align each slice to time offset 'zzz';
                  the value of 'zzz' must be between the
                  minimum and maximum slice temporal offsets.
            N.B.: The default alignment time is the average
                  of the 'tpattern' values (either from the
                  dataset header or from the -tpattern option)

  -slice nnn    = align each slice to the time offset of slice
                  number 'nnn' - only one of the -tzero and
                  -slice options can be used.
```

I suspect we don't want to provide this much flexibility, but what options should we allow? I'm a little inclined to only allow the first slice or the middle of acquisition. Are there other use cases we should seriously consider?

To make a concrete proposal, I'd say let's create a new `--stc-target` flag with possible values `first` and `mid`. (Not really attached to any of these, so happy for others to propose alternatives.)

**Comment by effigies** [comment]
I believe this has been substantially addressed, and I will close it now. We're always open to additional PRs for improved documentation, metadata, or corrected behavior.

Thanks again for bringing driving this discussion!
