### ISSUE TITLE
singularity and template flow

### ISSUE THREAD

**Issue by ejcorn** [nipreps/fmriprep#2480]
Hello,

I'm having issues similar to #1778 and those listed in #1801. However, I have tried multiple solutions and still, when I run fmriprep v20.2.3 on my HPC (no internet access) with singularity, it keeps trying to download template flow even though the templateflow folder with all templates exists in multiple locations. As best I can tell, I've bound the necessary directories. Here are a couple examples of what I've tried:

`export SINGULARITYENV_https_proxy=http://micc:8899`
`singularity run --cleanenv --home /home/fmriprep/ -B /project:/project \`
`    -B $HOME:/home/fmriprep/ \`
`    $fmriprep \`
`    $SUBJDIR \`
 `   ${OUTDIR}derivatives/ \`
 `   participant \`
 `   --skip_bids_validation \`
 `   --notrack \`
`    --participant-label $SUBJ \`
`    --output-spaces MNI152NLin2009cAsym:res-2 T1w \`
  `  --fs-license-file $FSLIC`

`export SINGULARITYENV_TEMPLATEFLOW_HOME=/home/fmriprep/.cache/templateflow/`
`singularity run --cleanenv -B /project:/project \`
`    -B ~/.cache/templateflow:/home/fmriprep/.cache/templateflow \`
`    -B ~/.cache/fmriprep:/home/fmriprep/.cache/fmriprep \`
`    $fmriprep \`
`    $SUBJDIR \`
`    ${OUTDIR}derivatives/ \`
`    participant \`
 `   --skip_bids_validation \`
`    --notrack \`
`    --participant-label $SUBJ \`
`    --output-spaces MNI152NLin2009cAsym:res-2 T1w \`
`    --fs-license-file $FSLIC`

Do you have any suggestions? Thanks in advance for your time!

**Comment by effigies** [comment]
Have you tried running `singularity shell` and ensuring that the locations you think are visible are indeed visible?

**Comment by ejcorn** [comment]
Hi, sorry for the delay. When I run:

$ export SINGULARITYENV_TEMPLATEFLOW_HOME=/home/fmriprep/.cache/templateflow/
$ singularity shell --cleanenv \
>     $fmriprep \
>     $SUBJDIR \
>     ${OUTDIR}derivatives/
Singularity> ls /home/fmriprep/.cache/templateflow/

that directory has all of the templates in it.

However, SINGULARITYENV_TEMPLATEFLOW_HOME is not defined in the singularity shell.

If I bind directories as in the second command above, I get the same thing.

**Comment by effigies** [comment]
Can you try running https://github.com/nipreps/fmriprep/blob/master/scripts/fetch_templates.py inside your container and reporting the output?

**Comment by ejcorn** [comment]
It doesn't work, because I don't have internet access on my compute nodes. per the fMRIprep documentation I did run 

` python -c "from templateflow.api import get; get(['MNI152NLin2009cAsym', 'MNI152NLin6Asym', 'OASIS30ANTs', 'MNIPediatricAsym', 'MNIInfant'])"`

and placed the output in `${BASE}.templateflow`, which I tried binding to `/templateflow` which matched with `SINGULARITYENV_TEMPLATEFLOW_HOME`. But that still didn't work.

**Comment by mgxd** [comment]
@ejcorn do you know what file(s) it is downloading?

**Comment by ejcorn** [comment]
Yes, sorry should have included that! It's `tpl-OASIS30ANTs_res-01_T1w.nii.gz`:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/local/miniconda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/miniconda/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='templateflow.s3.amazonaws.com', port=443): Max retries exceeded with url: /.cache/templateflow/tpl-OASIS30ANTs/tpl-OASIS30ANTs_res-01_T1w.nii.gz (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x2abd8caf2c88>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

**Comment by mgxd** [comment]
Okay, `/.cache/templateflow/tpl-OASIS30ANTs/tpl-OASIS30ANTs_res-01_T1w.nii.gz` makes me think something is not going right with your bindings - I'd recommend using absolute paths to ensure everything is pointing to the correct location.

If you want to verify, try the following minimal example in a shell - lines starting with # are comments and lines starting with $ are commands
```
# if you don't have the wget, you can replace `wget` below with `curl -O`
$ wget https://raw.githubusercontent.com/mgxd/fmriprep/enh/fetch-tf-templates/scripts/fetch_templates.py

$ python -m pip install --upgrade templateflow  # to ensure access to the latest templates 

$ mkdir <path-to-save-templateflow-templates>

$ python fetch_templates.py --tf-dir <path-to-save-templateflow-templates>

$ export SINGULARITYENV_TEMPLATEFLOW_HOME="/templates"

$ singularity shell --cleanenv -B <full-path-to-saved-templates>:/templates:ro <fmriprep-image>

# This is inside the container
# Should be "/templates"
$ > echo $TEMPLATEFLOW_HOME

# The file should not be empty (0B)
$ > du -h ${TEMPLATEFLOW_HOME}/tpl-OASIS30ANTs/tpl-OASIS30ANTs_res-01_T1w.nii.gz

# Nothing should be downloaded since the file was already retrieved
$ > python -c "from templateflow.api import get; get('OASIS30ANTs', resolution=1, desc=None, label=None, suffix='T1w')"
```

**Comment by ejcorn** [comment]
Tried the above and everything checks out. The `tpl-OASIS30ANTs_res-01_T1w.nii.gz` file is 31MB, and templateflow doesn't try to download anything. however, the equivalent command was still giving me an error.

Previously I was pre-downloading the templateflow files to a folder called `.templateflow`, but now that I've changed it to a non-hidden `templateflow` it seems to be working. however, I can't seem to reproduce the original behavior where it was trying to download templates.

Now I'm having a problem getting the freesurfer license to be recognized. I'm not sure if this is upstream or downstream of the templateflow issue.

With this command:

```
export SINGULARITYENV_TEMPLATEFLOW_HOME=/templates
export FS_LICENSE=${BASE}license.txt
export SINGULARITYENV_FS_LICENSE=/license.txt
singularity run --cleanenv -B /project:/project \
    -B /path/to/templateflow:/templates:ro \
    -B /path/to/license.txt:/license.txt:ro \
    $fmriprep \
    $SUBJDIR \
    ${OUTDIR}derivatives/ \
    participant \
    --skip_bids_validation \
    --participant-label $SUBJ \
    --output-spaces T1w MNI152NLin2009cAsym:res-2 \
    --fs-license-file /license.txt
``

**Comment by mgxd** [comment]
Please post the error traceback. It sounds like something is not right in your command - what I found helps is making the `singularity run ...` command a string, printing it, and then executing it, to help catch any obvious errors.

in bash, it'd look something like:
```bash
cmd="singularity run..."
echo $cmd
$cmd
```

**Comment by ejcorn** [comment]
```
	 210730-14:23:34,326 nipype.workflow IMPORTANT:
	 
    Running fMRIPREP version 20.2.3:
      * BIDS dataset path: /project/davis_group/elicorn/BIDS_tmp.
      * Participant list: ['RID0440'].
      * Run identifier: 20210730-142319_70fb8059-c538-4c39-85dd-e0ac50896fb7.
      * Output spaces: T1w MNI152NLin2009cAsym:res-2.
      * Pre-run FreeSurfer's SUBJECTS_DIR: /project/davis_group/elicorn/projects/fMRIpreproc/derivatives/freesurfer.
210730-14:23:35,215 nipype.workflow INFO:
	 No single-band-reference found for sub-RID0440_ses-research3Tv02_task-rest_bold.nii.gz.
210730-14:23:36,323 nipype.workflow IMPORTANT:
	 Slice-timing correction will be included.
210730-14:23:36,392 nipype.interface INFO:
	 We advise you to upgrade DIPY version. This upgrade will open access to more function
210730-14:23:36,394 nipype.interface INFO:
	 We advise you to upgrade DIPY version. This upgrade will open access to more function
210730-14:23:36,396 nipype.interface INFO:
	 We advise you to upgrade DIPY version. This upgrade will open access to more models
210730-14:23:38,214 nipype.workflow CRITICAL:
	 ERROR: a valid license file is required for FreeSurfer to run. fMRIPrep looked for an existing license file at several paths, in this order: 1) command line argument ``--fs-license-file``; 2) ``$FS_LICENSE`` environment variable; and 3) the ``$FREESURFER_HOME/license.txt`` path. Get it (for free) by registering at https://surfer.nmr.mgh.harvard.edu/registration.html

```

I've now tried several variations of this that produce this error, where I've used different license files in different locations, all of which singularity should be able to see based on what paths I'm binding.

**Comment by mgxd** [comment]
Something is wrong with your license, either it is not being found or is not formatted properly. Singularity shell is very useful when debugging, you can check the file exists inside the container and contains the expected text (`cat /license.txt`). I would also avoid setting `export SINGULARITYENV_FS_LICENSE=/license.txt` since you are using `--fs-license-file` directly.

**Comment by ejcorn** [comment]
Okay, so now I'm running this command, using a different license that I've used to successfully start running recon-all through fmriprep on a different machine:

```
export SINGULARITYENV_TEMPLATEFLOW_HOME=/templates
export FS_LICENSE=${BASE}license.txt

cat $FS_LICENSE

singularity run --cleanenv -B /project:/project \
    -B ${BASE}templateflow:/templates:ro \
    -B ${FS_LICENSE}:/license.txt:ro \
    $fmriprep \
    $SUBJDIR \
    ${OUTDIR}derivatives/ \
    participant \
    --skip_bids_validation \
    --participant-label $SUBJ \
    --output-spaces T1w MNI152NLin2009cAsym:res-2 \
    --fs-license-file /license.txt
```

and getting the same error. I did singularity shell and cat /license.txt gives the expected text in the license (don't want to post the license here)

**Comment by mgxd** [comment]
When you use include variables (like $BASE) that are not defined in the snippet, I can't really help debug. Please look at my suggestion in https://github.com/nipreps/fmriprep/issues/2480#issuecomment-890075863 to convert your singularity run command into a string (expanding variables along the way) and share that

**Comment by ejcorn** [comment]
Sorry about that! here you go:

```
$ export SINGULARITYENV_TEMPLATEFLOW_HOME=/templates
$ export FS_LICENSE=${BASE}license.txt

$ echo $FS_LICENSE
/project/davis_group/elicorn/license.txt

$ echo $cmd
singularity run --cleanenv -B /project:/project -B /project/davis_group/elicorn/templateflow:/templates:ro -B /project/davis_group/elicorn/license.txt:/license.txt:ro /project/davis_group/elicorn/images_pmacs/fmriprep-20.2.3.simg /project/davis_group/elicorn/BIDS_tmp/ /project/davis_group/elicorn/projects/fMRIpreproc/derivatives/ participant --skip_bids_validation --participant-label RID0440 --output-spaces T1w MNI152NLin2009cAsym:res-2 --fs-license-file /license.txt
```

produces

```
210730-16:43:13,791 nipype.workflow IMPORTANT:
	 
    Running fMRIPREP version 20.2.3:
      * BIDS dataset path: /project/davis_group/elicorn/BIDS_tmp.
      * Participant list: ['RID0440'].
      * Run identifier: 20210730-164259_bc744c99-e64e-4cdb-bf12-6c2efa17fa29.
      * Output spaces: T1w MNI152NLin2009cAsym:res-2.
      * Pre-run FreeSurfer's SUBJECTS_DIR: /project/davis_group/elicorn/projects/fMRIpreproc/derivatives/freesurfer.
210730-16:43:14,402 nipype.workflow INFO:
	 No single-band-reference found for sub-RID0440_ses-research3Tv02_task-rest_bold.nii.gz.
210730-16:43:15,366 nipype.workflow IMPORTANT:
	 Slice-timing correction will be included.
210730-16:43:15,414 nipype.interface INFO:
	 We advise you to upgrade DIPY version. This upgrade will open access to more function
210730-16:43:15,417 nipype.interface INFO:
	 We advise you to upgrade DIPY version. This upgrade will open access to more function
210730-16:43:15,418 nipype.interface INFO:
	 We advise you to upgrade DIPY version. This upgrade will open access to more models
210730-16:43:17,214 nipype.workflow CRITICAL:
	 ERROR: a valid license file is required for FreeSurfer to run. fMRIPrep looked for an existing license file at several paths, in this order: 1) command line argument ``--fs-license-file``; 2) ``$FS_LICENSE`` environment variable; and 3) the ``$FREESURFER_HOME/license.txt`` path. Get it (for free) by registering at https://surfer.nmr.mgh.harvard.edu/registration.html
```

**Comment by mgxd** [comment]
Hm, nothing jumps out. This might be a long shot, but theres a readonly binding within a binding, which might introduce some complexity. Try removing this binding `-B /project/davis_group/elicorn/license.txt:/license.txt:ro` and just setting `--fs-license-file /project/davis_group/elicorn/license.txt`, since `/project` is already available within the container.

**Comment by ejcorn** [comment]
```
singularity run --cleanenv -B /project:/project -B /project/davis_group/elicorn/templateflow:/templates:ro /project/davis_group/elicorn/images_pmacs/fmriprep-20.2.3.simg /project/davis_group/elicorn/BIDS_tmp/ /project/davis_group/elicorn/projects/fMRIpreproc/derivatives/ participant --skip_bids_validation --participant-label RID0440 --output-spaces T1w MNI152NLin2009cAsym:res-2 --fs-license-file /project/davis_group/elicorn/license.txt
```

same error unfortunately. I know you can only do so much without sitting at my machine, but would appreciate any other suggestions you have! it's odd because singularity shell can find the license, and I've tried it with many different licenses.

**Comment by oesteban** [comment]
Alternatively, you can use environment variables: https://www.nipreps.org/apps/singularity/#handling-environment-variables

```
$ export SINGULARITYENV_FS_LICENSE=/project/davis_group/elicorn/license.txt
$ singularity exec --cleanenv /project/davis_group/elicorn/images_pmacs/fmriprep-20.2.3.simg env | grep FS_LICENSE
FS_LICENSE=/project/davis_group/elicorn/license.txt
```

Overall, a deep read of the singularity documentation there (https://www.nipreps.org/apps/singularity/) may be of particular help in this case.

**Comment by ejcorn** [comment]
That command works and shows that `FS_LICENSE` has the correct path in it, and if I run:

```
singularity exec --cleanenv /project/davis_group/elicorn/images_pmacs/fmriprep-20.2.3.simg cat /project/davis_group/elicorn/images_pmacs/license.txt
```

I can see the license file (this is a new license I just downloaded from freesurfer's website). When I run this:

```
$ export SINGULARITYENV_FS_LICENSE=/project/davis_group/elicorn/images_pmacs/license.txt
$ export SINGULARITYENV_TEMPLATEFLOW_HOME=/templates

singularity run --cleanenv -B /project:/project -B /project/davis_group/elicorn/templateflow:/templates /project/davis_group/elicorn/images_pmacs/fmriprep-20.2.3.simg --skip_bids_validation --participant-label RID0440 --output-spaces T1w MNI152NLin2009cAsym:res-2 --verbose /project/davis_group/elicorn/BIDS_tmp/ /project/davis_group/elicorn/projects/fMRIpreproc/derivatives/ participant
```

In the log file, `fs_license_file` is `/project/davis_group/elicorn/images_pmacs/license.txt`, as expected. I get the same error!! What is going on?? Is there a better way to debug? lol.

**Comment by mgxd** [comment]
I wonder if you are getting an unrelated FreeSurfer error that is being picked up by our test function:
https://github.com/nipreps/niworkflows/blob/962c2344571ab080a415504daec0821a4877c6f4/niworkflows/utils/misc.py#L310-L333

Can you try running the following after defining `SINGULARITYENV_FS_LICENSE` and shelling into the container:

```
> mri_convert /usr/local/miniconda/lib/python3.7/site-packages/niworkflows/data/sentinel.nii.gz sentinel.mgz
> echo $?
```

and paste the output you get?

**Comment by ejcorn** [comment]
```
singularity shell --cleanenv -B /project:/project -B /project/davis_group/elicorn/templateflow:/templates /project/davis_group/elicorn/images_pmacs/fmriprep-20.2.3.simg --skip_bids_validation --participant-label RID0440 --output-spaces T1w MNI152NLin2009cAsym:res-2 --verbose /project/davis_group/elicorn/BIDS_tmp/ /project/davis_group/elicorn/projects/fMRIpreproc/derivatives/ participant
[elicorn@bsc06 elicorn]$ $cmd
Singularity> echo $FS_LICENSE
/project/davis_group/elicorn/images_pmacs/license.txt
Singularity> mri_convert.bin /usr/local/miniconda/lib/python3.7/site-packages/niworkflows/data/sentinel.nii.gz sentinel.mgz
mri_convert.bin /usr/local/miniconda/lib/python3.7/site-packages/niworkflows/data/sentinel.nii.gz sentinel.mgz 
$Id: mri_convert.c,v 1.226 2016/02/26 16:15:24 mreuter Exp $
reading from /usr/local/miniconda/lib/python3.7/site-packages/niworkflows/data/sentinel.nii.gz...
ERROR: crypt() returned null with 4-line file
Singularity> echo $?
1

```

**Comment by mgxd** [comment]
Aha, looks like we found the problem - the issue is actually not related to the license file. Taken from [this post](https://www.mail-archive.com/freesurfer@nmr.mgh.harvard.edu/msg69625.html) in the FreeSurfer mailing list:

> We work on different servers within the same institution and have been in 
contact with our administrators, we are sure at this point that the error is 
caused by FIPS 140 compliance on some of our systems. It is unrelated to 
Singularity. The crypt() function, as called in freesurfer/utils/chklc.cpp, 
returns NULL with errno == EPERM on machines booted in FIPS mode. I believe 
these users have encountered the same problem

**Comment by effigies** [comment]
Looks like we can check `/proc/sys/crypto/fips_enabled` to at least give an informative error: https://www.man7.org/linux/man-pages/man3/crypt.3.html#ERRORS

**Comment by ejcorn** [comment]
Ah, thank you very much!! Yes, when I run `cat /proc/sys/crypto/fips_enabled` on the compute node it returns `1`. I will work on getting FIPS disabled. For other users, it might save a lot of headache to separate out these two errors in the output if possible, or add to the documentation that this is another cause of the FS license error. Thank you all for your help!

**Comment by snapfinger** [comment]
> Okay, `/.cache/templateflow/tpl-OASIS30ANTs/tpl-OASIS30ANTs_res-01_T1w.nii.gz` makes me think something is not going right with your bindings - I'd recommend using absolute paths to ensure everything is pointing to the correct location.
> 
> If you want to verify, try the following minimal example in a shell - lines starting with # are comments and lines starting with $ are commands
> 
> ```
> # if you don't have the wget, you can replace `wget` below with `curl -O`
> $ wget https://raw.githubusercontent.com/mgxd/fmriprep/enh/fetch-tf-templates/scripts/fetch_templates.py
> 
> $ python -m pip install --upgrade templateflow  # to ensure access to the latest templates 
> 
> $ mkdir <path-to-save-templateflow-templates>
> 
> $ python fetch_templates.py --tf-dir <path-to-save-templateflow-templates>
> 
> $ export SINGULARITYENV_TEMPLATEFLOW_HOME="/templates"
> 
> $ singularity shell --cleanenv -B <full-path-to-saved-templates>:/templates:ro <fmriprep-image>
> 
> # This is inside the container
> # Should be "/templates"
> $ > echo $TEMPLATEFLOW_HOME
> 
> # The file should not be empty (0B)
> $ > du -h ${TEMPLATEFLOW_HOME}/tpl-OASIS30ANTs/tpl-OASIS30ANTs_res-01_T1w.nii.gz
> 
> # Nothing should be downloaded since the file was already retrieved
> $ > python -c "from templateflow.api import get; get('OASIS30ANTs', resolution=1, desc=None, label=None, suffix='T1w')"
> ```

Hi, I'm having exactly the same issue of binding templateflow. Everything worked correctly based on this test. I found that templateflow can be accessed without problem if with python even inside singularity shell, but will be problematic with command line only (either singularity shell / singularity run / singularity exec). I'm not that lucky as @ejcorn, changing directory name of templateflow did not help me. Just wonder if there's anything else I can do to debug this?
