### ISSUE TITLE
Adding carbon trackers to estimate compute costs of various workflows

### ISSUE THREAD

**Issue by nikhil153** [nipreps/fmriprep#2481]
Hi @effigies,

I have been testing a couple of recently developed tools for tracking power consumption and subsequent carbon emissions of various compute pipelines. 
1. [Experiment-impact-tracker](https://github.com/Breakend/experiment-impact-tracker)
2. [CodeCarbon](https://github.com/mlco2/codecarbon)

These tools launch a separate python process to monitor RAPL/nvidia metrics. So far, I have tested FreeSurfer using Nipype singularity container. 

Ideally, we would like to have two features. 1) Allow users to set a flag to have these tools track their workflow. 2) Allow them to set a flag to upload the tracker logs to a remote server - potentially hosted by [OHBM SEA-SIG](https://neuropipelines.github.io/index). 

This will allow us to get a better estimate of carbon emissions on different hardware as well as geographical locations.

Let me know what you think. I am happy to help and contribute in any manner possible. 

Thanks!
Nikhil

**Comment by tsalo** [comment]
It seems like this has been implemented. Can it be closed?
