### ISSUE TITLE
Docker container OS version does not match Dockerfile specification: Ubuntu 16 vs Ubuntu 20

### ISSUE THREAD

**Issue by ypicard** [nipreps/fmriprep#2483]
I am trying to extend the base fmriprep docker image for some personal usage with the following Dockerfile:
```
FROM nipreps/fmriprep:20.2.3
```

When I run a container and get a shell in it, I tried checking the current OS version and it returned the following:
```
root@649bad6e91a3:/# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```

Isn't this supposed to be Ubuntu 20.04 LTS as stated in your Dockerfile line 25?
```
# Use Ubuntu 20.04 LTS
FROM ubuntu:focal-20210416
```

**Comment by mgxd** [comment]
The `20.2.x` series is fixed to Ubuntu 16.04

https://github.com/nipreps/fmriprep/blob/a45ea486a8aa58541add3370a60ae87a70af8efb/Dockerfile#L1-L2

The Dockerfile you are referring to is for the next major release (`21.0.0`)

**Comment by ypicard** [comment]
Oh I see! Sorry for the confusion.
Is there an estimated release date for the next major release?

**Comment by mgxd** [comment]
Yes, we have Sept 1 as the target
