### ISSUE TITLE
Does fMRIPrep detrend functional data?

### ISSUE THREAD

**Issue by MasonTWells** [nipreps/fmriprep#2484]
Hi Experts, 

I am using fMRIPrep to pre-process a set of resting state data (via docker) using the following command:

fmriprep-docker /media/HDD/PMA_dataset_movie/rawdata/ /media/HDD/PMA_dataset_movie/derivatives/ participant --participant-label 0010 --output-spaces fsnative T1w --fs-subjects-dir /media/HDD/PMA_dataset_movie/derivatives/freesurfer/sub-0010/

I then intend on registering these data to the MNI template before performing temporally concatenated group ICA with Melodic. However, I can't seem to find whether fMRIPrep detrends the EPI data during the process? Can anyone advise on this, as I would have to detrend the data post-fMRIprep if not.

Cheers,
Mason

**Comment by oesteban** [comment]
> I then intend on registering these data to the MNI template before performing temporally concatenated group ICA with Melodic. However, I can't seem to find whether fMRIPrep detrends the EPI data during the process? Can anyone advise on this, as I would have to detrend the data post-fMRIprep if not.

- Except for the AROMA-denoised outputs (which you did not seem to enable), all outputs of fMRIPrep will NOT be detrended.
- fMRIPrep generates outputs aligned into MNI as specified via the `--output-spaces` argument (i.e., you probably should not run the registration process on your own).
- Before group ICA, effectively, you'll need to detrend the preprocessed data that fMRIPrep generates.

**Comment by MasonTWells** [comment]
Thanks for the reply. When I first ran fMRIPrep I had no intention of using data in MNI space, hence not adding this to the --output-spaces flag. I have been using FSL's flirt/fnirt/epi_reg/applywarp commands to achieve this. Having said that, is there a way to re-run fMRIPrep docker to only perform this additional step? I have already run it on 20+ brains, so if there is a way to go back a re-run the process without having to wait for it to do everything else, that would be great. 

Thanks again,
Mason

**Comment by oesteban** [comment]
Yes, if you preserved the working directory (which, by default, will be created in a temporal folder - so you probably want to override that with the `-w <workdir>` argument.

There's also a "fast-track" for the anatomical workflow that could speed up things if you don't have access to fMRIPrep's work directory anymore.

All those details should be documented here - https://fmriprep.org/en/stable/usage.html#reusing-precomputed-derivatives

Please let us know if you find gaps that need further explanation.

**Comment by MasonTWells** [comment]
Thanks again for this. I am a little unsure as to the best command to use with respect to the working directory. I have kept all the outputs of both fMRIPrep and FreeSurfer in the "derivatives" folder, is this what you mean by the working directory? If so, will running the following command only run the BOLD to MNI step?

fmriprep-docker /media/HDD/PMA_dataset_movie/rawdata/ /media/HDD/PMA_dataset_movie/derivatives/ participant --participant-label 0010 --output-spaces fsnative T1w MNI152NLin6Asym:res-2 --fs-subjects-dir /media/HDD/PMA_dataset_movie/derivatives/freesurfer/

or do I need to use the --anat-derivatives flag and point this to the derivatives > freesurfer folder?

Best,
Mason

**Comment by oesteban** [comment]
You will need the `--anat-derivatives <path>` to skip over the anatomical workflow altogether.
