### ISSUE TITLE
new release 20.2.3 on dockerhub? 

### ISSUE THREAD

**Issue by jungheejung** [nipreps/fmriprep#2485]
Will the new release "20.2.3" be available on dockerhub anytime soon?
Thank you in advance!

**Comment by mgxd** [comment]
It is available on DockerHub 
https://hub.docker.com/r/nipreps/fmriprep/tags?page=1&ordering=last_updated&name=20.2.3

**Comment by jungheejung** [comment]
Ah, sorry for the inconvenience. I was looking in the poldracklab. Thank you! @mgxd
