### ISSUE TITLE
Warning should be ERROR - *Incorrect phase-encoding direction, assuming PA (posterior-to-anterior)*

### ISSUE THREAD

**Issue by oesteban** [nipreps/fmriprep#2497]
When running "fieldmapless" we get this message *Incorrect phase-encoding direction, assuming PA (posterior-to-anterior)* when the phase encoding direction is not specified.

Although fieldmapless runs without knowledge of the polarity, applying estimation on the wrong axis (when assuming AP/PA) could be extremely problematic.

This warning, IMHO, should be an error.

This affects the 20.2.x series and will likely become irrelevant with the integration of SDCFlows 2.0 (the new API makes the phase encoding direction a required parameter).

**Comment by effigies** [comment]
This has been done 21.0. I would vote for keeping the behavior as-is for 20.2.

**Comment by oesteban** [comment]
Sounds reasonable.
