### ISSUE TITLE
ERROR: traits.trait_errors.TraitError: The 'tr' trait of a FunctionalSummaryInputSpec instance must be a float, but a value of None <class 'NoneType'> was specified.

### ISSUE THREAD

**Issue by BlackHoleExelion** [nipreps/fmriprep#2512]
Ran with Fmriprep_20.2.3 in singularity. Also tested with Fmriprep_20.2.0 and got the same error.

Here is the command and error message: 

>(base) [xxx@singularity01 ~]$ singularity run --writable-tmpfs --cleanenv \
> -B /project/oathes_group:/mnt \
> /project/oathes_group/singularity_images/fmriprep_20.2.3.simg \
> -w /mnt/fmriprep/temp_fmriprep \
> --fs-license-file /mnt/fs_licenses/freesurfer_license.txt \
> --skip_bids_validation \
> --skull-strip-template OASIS30ANTs \
> --output-spaces MNI152NLin2009cAsym fsaverage5 T1w fsnative \
> --cifti-output 91k \
> --bold2t1w-dof 6 \
> --aroma-melodic-dimensionality -200 \
> --dvars-spike-threshold 1.5 \
> --fd-spike-threshold 0.5 \
> /mnt/BIDS/ZAPR01 /mnt/fmriprep/output participant --participant-label C262

> 210823-16:40:58,101 nipype.workflow IMPORTANT:
> 
>     Running fMRIPREP version 20.2.3:
>       * BIDS dataset path: /mnt/BIDS/ZAPR01.
>       * Participant list: ['C262'].
>       * Run identifier: 20210823-163855_b93f51a8-c988-493b-9fb8-2b09026ddc87.
>       * Output spaces: MNI152NLin2009cAsym:res-native fsaverage:den-10k T1w fsnative.
>       * Pre-run FreeSurfer's SUBJECTS_DIR: /mnt/fmriprep/output/freesurfer.
> 210823-16:41:02,9 nipype.workflow INFO:
>          No single-band-reference found for sub-C262_ses-Baseline_task-nback02_run-01_bold.nii.gz.
> Process Process-2:
> Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
>     self.run()
>   File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/workflow.py", line 82, in build_workflow
>     retval["workflow"] = init_fmriprep_wf()
>   File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 64, in init_fmriprep_wf
>     single_subject_wf = init_single_subject_wf(subject_id)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 304, in init_single_subject_wf
>     func_preproc_wf = init_func_preproc_wf(bold_file)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/bold/base.py", line 281, in init_func_preproc_wf
>     tr=metadata.get("RepetitionTime")),
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 641, in __init__
>     from_file=from_file, resource_monitor=resource_monitor, **inputs
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 191, in __init__
>     self.inputs.trait_set(**inputs)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/traits/has_traits.py", line 1543, in trait_set
>     setattr( self, name, value )
>   File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 172, in error
>     value )
> traits.trait_errors.TraitError: The 'tr' trait of a FunctionalSummaryInputSpec instance must be a float, but a value of None <class > 'NoneType'> was specified.

**Comment by mgxd** [comment]
Can you try rerunning without the `--skip_bids_validation` flag?

Your functional data is likely missing the required [`RepetitionTime` metadata](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#required-fields).

**Comment by effigies** [comment]
Could you share the contents of the relevant `bold.json` files in your BIDS dataset? My guess is that you have something like the following in there:

```YAML
{
  ...
  "RepetitionTime": null,
  ...
}
```

**Comment by effigies** [comment]
Edit: Actually, I think @mgxd is right, and it's probably missing. We use `metadata.get("RepetitionTime")`. We should probably just use `metadata["RepetitionTime"]`, which should now give a better error like

```
Metadata term "RepetitionTime" unavailable for file ...
```

**Comment by BlackHoleExelion** [comment]
You guys are right, I just forgot to generate .json and stuff while converting dicoms to BIDS with heudiconv.
It is working now. Thank you so much for the responsive help!
