### ISSUE TITLE
Use of fmriprep for multiband scans

### ISSUE THREAD

**Issue by HarshitSamani** [nipreps/fmriprep#2522]

**Comment by effigies** [comment]
Hi, do you have a question?

**Comment by HarshitSamani** [comment]
Hi Sir,

Can you tell me what are the important flags we need to take care of while
using fmriprep for Multiband scans?
The Multiband acceleration factor is 8 and TR=607ms.

Thanks and regards,
Harshit Samani.

**Comment by effigies** [comment]
In general, we recommend using the default behaviors. If you're seeing poor preprocessing of some initial data, then you might need to adjust processing or we might need to fix a bug, but single and multi-band data are both supported by default.
