### ISSUE TITLE
Mising scl_slope and scl_inter in NIfTI header

### ISSUE THREAD

**Issue by bearsun** [nipreps/fmriprep#2531]
Bug report:
I preprocessed my data into 3 spaces: T1w, MNI152NLin6Asym, MNI152NLin6Asym_res-2. No errors were reported.
For the brain_mask files of T1w and MNI152NLin6Asym_res-2, the scl_slope and scl_inter in their NIfTI header were set to NaN. As a result, when I ran something like: 
fslmaths sub-01_task-rest_space-T1w_desc-preproc_bold.nii.gz -mas sub-01_task-rest_space-T1w_desc-brain_mask.nii.gz tt.nii.gz
It returned an empty image file. Such problem did not happen to the MNI152NLin6Asym image since the scl_slope and scl_inter were set to 1 and 0.

Best regards,
Liwei

### What version of fMRIPrep are you using?
20.2.3

### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?
Singularity

### What is the exact command-line you used?
```
singularity run --cleanenv -B /mnt ~/Documents/simgs/fmriprep-20.2.3.simg /mnt/data1/data/bids/ /mnt/data1/data/fmriprep/ participant --fs-license-file ~/Documents/license.txt --output-spaces T1w MNI152NLin6Asym:res-2
```

### Have you checked that your inputs are BIDS valid?
Yes

### Did fMRIPrep generate the visual report for this particular subject? If yes, could you share it?

The report looks normal.

### Can you find some traces of the error reported in the visual report (at the bottom) or in *crashfiles*?
```
No. The preprocessing was done without error.
```

**Comment by effigies** [comment]
This has been fixed in 21.0.0rc0 and will be fixed in 20.2.4.
