### ISSUE TITLE
numpy in fMRIPrep 21.0.0rc0

### ISSUE THREAD

**Issue by juansanchezpena** [nipreps/fmriprep#2532]
### What version of fMRIPrep are you using?
fMRIPrep 21.0.0rc0

### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?
Docker

### What is the exact command-line you used?

```
<place your command line here>
sudo /usr/local/pipelines/subfmri-arg-rc -i /MRI_DATA/nyspi/patensasc/rawdata -o /MRI_DATA/nyspi/patensasc/derivatives -l /MRI_DATA/nyspi/patensasc/derivatives/fmripreplogs/rc.log -a "--participant-label  sub-patensasc0089 --output-spaces T1w MNI152NLin2009cAsym:res-2 --cifti-output"
```

### Have you checked that your inputs are BIDS valid?
YES

### Can you find some traces of the error reported in the visual report (at the bottom) or in *crashfiles*?
```
< Running fMRIPrep version 21.0.0rc0
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    | 
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |          License NOTICE ##################################################
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |          fMRIPrep 21.0.0rc0
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |          Copyright 2021 The NiPreps Developers.
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |          
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |          This product includes software developed by
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |          the NiPreps Community (https://nipreps.org/).
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |          
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |          Portions of this software were developed at the Department of
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |          Psychology at Stanford University, Stanford, CA, US.
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |          
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |          This software contains code ultimately derived from the epidewarp.fsl
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |          script (https://www.nmr.mgh.harvard.edu/~greve/fbirn/b0/epidewarp.fsl)
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |          by Doug Greve, Dave Tuch, Tom Liu, and Bryon Mueller with generous
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |          help from the FSL crew (www.fmrib.ox.ac.uk/fsl) and the Biomedical
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |          Informatics Research Network (www.nbirn.net).
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |          
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |          This software redistributes the versioneer Python package, which is
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |          Public domain source code.
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |          
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |          This software is also distributed as a Docker container image.
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |          The bootstraping file for the image ("Dockerfile") is licensed
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |          under the MIT License.
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |          
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |          This software may be distributed through an add-on package called
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |          "Docker Wrapper" that is under the BSD 3-clause License.
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |          #################################################################
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    | 210913-12:50:17,650 nipype.workflow IMPORTANT:
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    | 	 Building fMRIPrep's workflow:
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |            * BIDS dataset path: /input.
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |            * Participant list: ['patensasc0089'].
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |            * Run identifier: 20210913-125008_6cdd3539-2f3d-4af1-9be8-0786ebf1ddc9.
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |            * Output spaces: MNI152NLin2009cAsym:res-2 MNI152NLin2009cAsym:res-native T1w.
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |            * Pre-run FreeSurfer's SUBJECTS_DIR: /output/freesurfer.
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    | 210913-12:50:19,632 nipype.workflow INFO:
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    | 	 No single-band-reference found for sub-patensasc0089_ses-1385_task-gbu_run-01_bold.nii.gz.
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    | 210913-12:50:19,633 nipype.workflow INFO:
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    | 	 Found usable B0 fieldmap <('auto_00000',)>
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    | Process Process-2:
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    | Traceback (most recent call last):
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |   File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |     self.run()
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |   File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |     self._target(*self._args, **self._kwargs)
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |   File "/usr/local/miniconda/lib/python3.8/site-packages/fmriprep/cli/workflow.py", line 118, in build_workflow
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |     retval["workflow"] = init_fmriprep_wf()
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |   File "/usr/local/miniconda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 85, in init_fmriprep_wf
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |     single_subject_wf = init_single_subject_wf(subject_id)
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |   File "/usr/local/miniconda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 349, in init_single_subject_wf
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |     func_preproc_wf = init_func_preproc_wf(bold_file, has_fieldmap=has_fieldmap)
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |   File "/usr/local/miniconda/lib/python3.8/site-packages/fmriprep/workflows/bold/base.py", line 446, in init_func_preproc_wf
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |     bold_stc_wf = init_bold_stc_wf(name='bold_stc_wf', metadata=metadata)
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |   File "/usr/local/miniconda/lib/python3.8/site-packages/fmriprep/workflows/bold/stc.py", line 99, in init_bold_stc_wf
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    |     tzero = np.round(first + frac * (last - first), 3)
fa-rootpi_patensasc_rawdata.1.6x7cq98u6eek@mrinode5.nyspi.local    | NameError: name 'np' is not defined>
```

### fMRIPrep log
If you have access to the output logged by fMRIPrep, please make sure to attach it as a text file to this issue.

**Comment by effigies** [comment]
Ah, good catch. Curious why we didn't see it before. Will submit a fix momentarily.

**Comment by juansanchezpena** [comment]
Thanks I will re download the container

**Comment by effigies** [comment]
You'll need to use `:unstable` until we release a 21.0.0rc1.

**Comment by juansanchezpena** [comment]
Thanks so much  I will follow up

From: Chris Markiewicz ***@***.***>
Date: Monday, September 13, 2021 at 3:24 PM
To: nipreps/fmriprep ***@***.***>
Cc: Sanchez, Juan (NYSPI) ***@***.***>, Author ***@***.***>
Subject: Re: [nipreps/fmriprep] numpy in fMRIPrep 21.0.0rc0 (#2532)

ATTENTION: This email came from an external source. Do not open attachments or click on links from unknown senders or unexpected emails.


You'll need to use :unstable until we release a 21.0.0rc1.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://protect2.fireeye.com/v1/url?k=12e929a8-4d72108c-12ebd09d-000babd9f8b3-974e849d02293764&q=1&e=32fe9eeb-d3e7-4f8a-aeb6-acdf4f7b66a8&u=https%3A%2F%2Fgithub.com%2Fnipreps%2Ffmriprep%2Fissues%2F2532%23issuecomment-918505101>, or unsubscribe<https://protect2.fireeye.com/v1/url?k=e431bc14-bbaa8530-e4334521-000babd9f8b3-ca25242ad0c37a49&q=1&e=32fe9eeb-d3e7-4f8a-aeb6-acdf4f7b66a8&u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARKALFBF5L4SKNCDKM45OT3UBZFUZANCNFSM5D6CCICA>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://protect2.fireeye.com/v1/url?k=28ec5e31-77776715-28eea704-000babd9f8b3-2eb9d63f0c8d3713&q=1&e=32fe9eeb-d3e7-4f8a-aeb6-acdf4f7b66a8&u=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub>.

**Comment by juansanchezpena** [comment]
I re ran 21.0,0rc0 with the same inputs
The data were processed through and the html file was created.
I looked through the logs and saw this:

 cat  crash-20210919-130513-root-_resample1-18334bb1-9f5b-4c47-a68d-2781a55f2f87.txt

Node: _resample1

Working directory: /tmp/work/fmriprep_wf/single_subject_patensasc0089_wf/func_preproc_ses_1385_task_gbu_run_02_wf/bold_grayords_wf/resample/mapflow/_resample1



Node inputs:



area_metrics = True

area_surfs = <undefined>

args = <undefined>

current_area = /home/fmriprep/.cache/templateflow/tpl-fsaverage/tpl-fsaverage_hemi-R_den-164k_desc-vaavg_midthickness.shape.gii

current_sphere = /home/fmriprep/.cache/templateflow/tpl-fsaverage/tpl-fsaverage_hemi-R_den-164k_desc-std_sphere.surf.gii

environ = {}

in_file = /tmp/work/fmriprep_wf/single_subject_patensasc0089_wf/func_preproc_ses_1385_task_gbu_run_02_wf/bold_surf_wf/_target_fsaverage/update_metadata/mapflow/_update_metadata1/rh.fsaverage.gii

largest = <undefined>

method = ADAP_BARY_AREA

new_area = /home/fmriprep/.cache/templateflow/tpl-fsLR/tpl-fsLR_hemi-R_den-32k_desc-vaavg_midthickness.shape.gii

new_sphere = /home/fmriprep/.cache/templateflow/tpl-fsLR/tpl-fsLR_space-fsaverage_hemi-R_den-32k_sphere.surf.gii

out_file = space-fsLR_hemi-R_den-91k_bold.gii

roi_metric = <undefined>

valid_roi_out = <undefined>



Traceback (most recent call last):

  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node

    result["result"] = node.run(updatehash=updatehash)

  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run

    result = self._run_interface(execute=True)

  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface

    return self._run_command(execute)

  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command

    result = self._interface.run(cwd=outdir)

  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 406, in run

    version=self.version,

  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/workbench/base.py", line 39, in version

    return Info.version()

  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 1127, in version

    clout = CommandLine(

  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run

    runtime = self._run_interface(runtime)

  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 822, in _run_interface

    self.raise_exception(runtime)

  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 749, in raise_exception

    raise RuntimeError(

RuntimeError: Command:

wb_command -version

Standard output:



Standard error:

wb_command: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory

Return code: 127

***@***.*** 20210917-162529_f3075109-8311-4e04-b16f-1c43168379c7]$

________________________________

**Comment by effigies** [comment]
Just merged a fix to that. In an hour or so, you should be able to update `:unstable`.

**Comment by juansanchezpena** [comment]
Thank you

From: Chris Markiewicz ***@***.***>
Date: Monday, September 20, 2021 at 11:52 AM
To: nipreps/fmriprep ***@***.***>
Cc: Sanchez, Juan (NYSPI) ***@***.***>, Author ***@***.***>
Subject: Re: [nipreps/fmriprep] numpy in fMRIPrep 21.0.0rc0 (#2532)

ATTENTION: This email came from an external source. Do not open attachments or click on links from unknown senders or unexpected emails.


Just merged a fix to that. In an hour or so, you should be able to update :unstable.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://protect2.fireeye.com/v1/url?k=4ed0a9fb-114b9126-4ed250ce-0cc47aa8c6e0-0f726e3a6a08aa60&q=1&e=3024db46-ff52-4c8f-9d7e-7add05ff6a1b&u=https%3A%2F%2Fgithub.com%2Fnipreps%2Ffmriprep%2Fissues%2F2532%23issuecomment-923054055>, or unsubscribe<https://protect2.fireeye.com/v1/url?k=a2f6ae7e-fd6d96a3-a2f4574b-0cc47aa8c6e0-e45dc35dc9c4bab3&q=1&e=3024db46-ff52-4c8f-9d7e-7add05ff6a1b&u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARKALFGHRCH6XV4JRFSH3L3UC5KDPANCNFSM5D6CCICA>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://protect2.fireeye.com/v1/url?k=dbc28c25-8459b4f8-dbc07510-0cc47aa8c6e0-42d731524d735b85&q=1&e=3024db46-ff52-4c8f-9d7e-7add05ff6a1b&u=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub>.

**Comment by juansanchezpena** [comment]
Hey Chris just wanted to make sure htis image was updated!

Thanks so much
J
________________________________

**Comment by effigies** [comment]
Yes. You'll need to `docker pull nipreps/fmriprep:unstable` again.

**Comment by juansanchezpena** [comment]
Great thanks!


________________________________
