### ISSUE TITLE
Should functional bold phase acquisitions be included in IntendedFor?

### ISSUE THREAD

**Issue by dlevitas** [nipreps/fmriprep#2548]
My current understanding is that `fmap` acquisition metadata requires the IntendedFor field to determine which acquisitions to perform SDC. Acquisitions accepted in IntendedFor are functional bold and [probably functional sbref](https://neurostars.org/t/using-an-sbref-with-susceptibility-distortion-correction-should-intendedfor-field-include-sbref/4276). However, I have a functional bold phase (`part-phase`) acquisition, and am unsure whether fmriprep performs SDC on such acquisitions?

**Comment by effigies** [comment]
We don't process phase maps at this point. If we do, I expect we would apply the same transforms as the corresponding magnitude images, so there would be no need to add additional metadata.

**Comment by dlevitas** [comment]
> I expect we would apply the same transforms as the corresponding magnitude images
I see. Just to clarify, the phase acquisitions doesn't come with any corresponding magnitude(s). The phase only corresponds to the functional bold.

**Comment by effigies** [comment]
> Just to clarify, the phase acquisitions doesn't come with any corresponding magnitude(s). The phase only corresponds to the functional bold.

Unless I'm misunderstanding something, the functional bold should be the corresponding magnitudes.

FWIW I don't think it'll harm anything to include the phase maps in IntendedFor. I just don't think fMRIPrep is likely to insist on it.

**Comment by dlevitas** [comment]
@effigies, sorry for the late reply. I misunderstood your response, but you're correct, I have a functional bold magnitude and corresponding phase. 

Typically with functional bold I label it in a parsimonious manner like `sub-01_task-bart_bold.nii.gz`. In the context of this magnitude & phase pairing, I've been doing

```
sub-01_task-bart-_bold.nii.gz

**Comment by effigies** [comment]
Either is fine. IIRC BIDS says that `part-mag` is the default interpretation.
