### ISSUE TITLE
ME-EPI + fieldmaps (will be) broken

### ISSUE THREAD

**Issue by oesteban** [nipreps/fmriprep#2558]
When I merge #2547, I'll be breaking the multiecho path when fieldmaps are present. This issue is just a note to remind myself to look at this after the single-echo pathways are finalized.

**Comment by Lestropie** [comment]
Was going to report an issue with `21.0.0rc0`; suspect it might be the issue you're reminding yourself of here, but want to confirm, will list separate issue if it's not a duplicate. Problem arises [here](https://github.com/nipreps/fmriprep/blob/21.0.0rc0/fmriprep/workflows/bold/base.py#L248-L251) as for multi-echo data "`bold_file`" is a tuple.

**Comment by oesteban** [comment]
Well, I think the way I broke the pipeline is more profound (in the sense that, for the sake of making smaller steps on the overall integration, I thought that was the best way to proceed), but I would say yes, you are pointing at the earliest symptom of this feature failing.

I don't think the particular bug you have reported was created by #2547, so thanks for catching it - I'll address it together with this bug report.

Indeed, the difficulties to run ME-EPI + fieldmaps at this point are deeper: since the ME-EPI pipeline is probably going to undergo an overhaul, I think the fieldmap graph should be designed after the pipeline has been revised.

All things considered, thanks much for the bug report - I think you are right we can have it unified under this issue.

**Comment by Lestropie** [comment]
Unsurprising that it's a deeper issue to resolve; "earliest symptom" is apt. :+1:

**Comment by effigies** [comment]
Should be resolved.
