### ISSUE TITLE
iostream error during fsl2itk?

### ISSUE THREAD

**Issue by nataliavelez** [nipreps/fmriprep#2566]
Hello! I tried running fmriprep, but it raised this error about 4 hours in while running fsl2itk. I'm totally stumped with this one - any advice on how to fix this issue? 

### What version of fMRIPrep are you using?
20.2.0

### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?
Singularity container

### What is the exact command-line you used?
```
singularity run $FMRIPREP_IMG -B $GROUP_SCRATCH/swist/work:/home/fmriprep \
        $BIDS_DIR $OUT_DIR participant \
        --participant-label $SUBJECT -w $WORKING_DIR \
        --nthreads 2 --omp-nthreads 4 --mem-mb 64000 \
        --fs-no-reconall -vvv \
        --fs-license-file $FS_LICENSE
```
(Note: I added the -B flag as suggested by [a previous fmriprep issue](https://github.com/nipreps/fmriprep/issues/1777), but I'm not sure this is actually necessary)

### Have you checked that your inputs are BIDS valid?
Yes

### Did fMRIPrep generate the visual report for this particular subject? If yes, could you share it?
[Download link
](https://drive.google.com/file/d/1kE-I9LJFWVr8Pn8dxiVpP-aC-tuum3ZA/view?usp=sharing)

### Can you find some traces of the error reported in the visual report (at the bottom) or in *crashfiles*?
```
File: /scratch/groups/hyo/swist/BIDS_data/derivatives/fmriprep/sub-04/log/20210929-101149_d4270998-24d1-4bed-b3f0-f480aa31a4bd/crash-20210929-121930-nvelez-fsl2itk-bb9f3c49-9f37-4d54-8c7d-b7cb4f9fba20.txt
Working Directory: /scratch/groups/hyo/swist/cache/fmriprep/fmriprep_wf/single_subject_04_wf/func_preproc_task_tomloc_run_02_wf/bold_hmc_wf/fsl2itk
Inputs:
in_files:
in_reference:
in_source:
num_threads: 4
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 419, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/itk.py", line 69, in _run_interface
    for i, in_mat in enumerate(self.inputs.in_files)
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/itk.py", line 204, in _mat2itk
    resource_monitor=False,
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 419, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 814, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 745, in raise_exception
    ).format(**runtime.dictcopy())
RuntimeError: Command:
c3d_affine_tool -ref /scratch/groups/hyo/swist/cache/fmriprep/fmriprep_wf/single_subject_04_wf/func_preproc_task_tomloc_run_02_wf/initial_boldref_wf/gen_ref/ref_bold.nii.gz -src /scratch/groups/hyo/swist/cache/fmriprep/fmriprep_wf/single_subject_04_wf/func_preproc_task_tomloc_run_02_wf/initial_boldref_wf/gen_ref/ref_bold.nii.gz /scratch/groups/hyo/swist/cache/fmriprep/fmriprep_wf/single_subject_04_wf/func_preproc_task_tomloc_run_02_wf/bold_hmc_wf/mcflirt/sub-04_task-tomloc_run-02_bold_mcf.nii.gz.mat/MAT_0076 -fsl2ras -oitk /scratch/groups/hyo/swist/cache/fmriprep/fmriprep_wf/single_subject_04_wf/func_preproc_task_tomloc_run_02_wf/bold_hmc_wf/fsl2itk/tmp-v6zj3p6o/MAT_0076_itk-00076.txt
Standard output:

Standard error:
Exception raised during processing:
basic_filebuf::underflow error reading the file: iostream error
Return code: 255
```

### Are you reusing previously computed results (e.g., FreeSurfer, Anatomical derivatives, work directory of previous run)?
No

### fMRIPrep log
See link to report above

**Comment by effigies** [comment]
My best guess is that you ran out of room in your working directory. Can you check that you can read the following files:

* `/scratch/groups/hyo/swist/cache/fmriprep/fmriprep_wf/single_subject_04_wf/func_preproc_task_tomloc_run_02_wf/initial_boldref_wf/gen_ref/ref_bold.nii.gz`
* `/scratch/groups/hyo/swist/cache/fmriprep/fmriprep_wf/single_subject_04_wf/func_preproc_task_tomloc_run_02_wf/bold_hmc_wf/mcflirt/sub-04_task-tomloc_run-02_bold_mcf.nii.gz.mat/MAT_0076`

If you can run `fslhd` on the NIfTI file, that should be enough for this tool. I think `MAT_0076` should be a text file with 12 numbers in it.

Assuming you do have enough room, you could try removing `/scratch/groups/hyo/swist/cache/fmriprep/fmriprep_wf/single_subject_04_wf/func_preproc_task_tomloc_run_02_wf/bold_hmc_wf/mcflirt/` and re-running fMRIPrep. Occasionally you can get some one-off errors that go away on re-run.

**Comment by nataliavelez** [comment]
Thanks for the quick response! I can read both of those files and have 100 TB available in the working directory, so it doesn't seem that those are causing the issue. 

> Assuming you do have enough room, you could try removing /scratch/groups/hyo/swist/cache/fmriprep/fmriprep_wf/single_subject_04_wf/func_preproc_task_tomloc_run_02_wf/bold_hmc_wf/mcflirt/ and re-running fMRIPrep. Occasionally you can get some one-off errors that go away on re-run.

I just tried this and it seems to be chugging along - fingers crossed!

**Comment by nataliavelez** [comment]
Update: That fixed it - fmriprep finished running without issues. Thank you! :)

**Comment by effigies** [comment]
Glad to hear!
