### ISSUE TITLE
freesurfer recon-all

### ISSUE THREAD

**Issue by mindmap2** [nipreps/fmriprep#2569]
Hi,
I installed freesurfer and trying to do recon-all before segmentation.Where should I keep my mp2rage images which have been converted to nii.gz? Should my own data directory be within freesurfer/subjects directory or could be outside freesurfer directory? I tried to recon and the error is for 001.mgz file that does not exist in my directory.

I appreciate your help

**Comment by effigies** [comment]
Hi, the fMRIPrep issues are for bugs and problems related to fMRIPrep.

FreeSurfer support is handled on their mailing list: http://mail.nmr.mgh.harvard.edu/mailman/listinfo/freesurfer

You can also try NeuroStars: https://neurostars.org/
