### ISSUE TITLE
Validation error despite –skip_bids_validation

### ISSUE THREAD

**Issue by hechlera** [nipreps/fmriprep#2582]
### What version of fMRIPrep are you using?
20.2.3
### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?
Docker
### What is the exact command-line you used?
```
--skip_bids_validation --fs-license-file /input/config/freesurfer_license.txt --fs-no-reconall --output-spaces T1w --mem 24 /input /output participant
```

### Have you checked that your inputs are BIDS valid?
The same dataset finished successfully with the same command using fmriprep 20.1.1

### Can you find some traces of the error reported in the visual report (at the bottom) or in *crashfiles*?
```


    Traceback (most recent call last):

    File “/usr/local/miniconda/bin/fmriprep”, line 10, in

    sys.exit(main())

    File “/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py”, line 17, in main

    parse_args()

    File “/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/parser.py”, line 635, in parse_args

    config.from_dict(vars(opts))

    File “/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py”, line 648, in from_dict

    execution.load(settings)

    File “/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py”, line 218, in load

    cls.init()

    File “/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py”, line 469, in init

    indexer=_indexer,

    File “/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py”, line 137, in init

    root, description = validate_root(root, validate)

    File “/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/validation.py”, line 77, in validate_root

    json.dumps(EXAMPLE_BIDS_DESCRIPTION)

    bids.exceptions.BIDSValidationError: ‘dataset_description.json’ is missing from project root. Every valid BIDS dataset must have this file.

    Example contents of ‘dataset_description.json’:

    {“Name”: “Example dataset”, “BIDSVersion”: “1.0.2”}

```

### Are you reusing previously computed results (e.g., FreeSurfer, Anatomical derivatives, work directory of previous run)?
No, ran on raw data

We just updated from fmriprep 20.1.1 to 20.2.3 and (using the same command as before with the same data) I suddenly get bids validation errors even though I called fmriprep with the --skip_bids_validation flag. Note that the root folder really does not have dataset_description.json, but it also did not have it before and 20.1.1 ran smoothly.

Including the dataset_description.json is generally possible, but I am limited in the control over the data I get (we use XNATs container service which can be a bit finnicky). I am mainly posting this because this worked in the previous version. I also tested in directly via the docker container and the same error persists.

Thanks for any suggestions!

**Comment by effigies** [comment]
`--skip-bids-validation` tells fMRIPrep not to try to run the external BIDS validator tool before running, itself. When we index datasets with PyBIDS, "validation" plays a different role, where it helps exclude files that are invalid.

Pre-indexing the dataset with `--validate=False` (if you're sure there are no files that might confuse fMRIPrep) can be done according to [this FAQ](https://fmriprep.org/en/latest/faq.html?highlight=layout#how-to-decrease-fmriprep-runtime-when-working-with-large-datasets).

**Comment by jflournoy** [comment]
I'm also having this issue even after running pybids to create the `layout_index.sqlite` folder. I'll respond to the queries above as well in case it's helpful:

## Version

20.2.5

## Installation

Singularity

## Command line

```
singularity run \
        --cleanenv \
        -B /ncf/mclaughlin/fmriprep_SEA_temp_jcf/${SUBJECT}:/work  \
        -B ${BIDS_DIR}/derivatives/fmriprep-${VERSION}/bids_database:/bids_database \
        -B ${BIDS_DIR} \
        /mnt/stressdevlab/scripts/Containers/fmriprep-${VERSION}.simg/ \
        --participant-label ${SUBJECT} \
        -w /work \
        -vvv --mem_mb 4000 --nthreads 4 \
        --return-all-components \
        --fd-spike-threshold 0.5 \
        --fs-license-file ${BIDS_DIR}/derivatives/license.txt \
        --fs-subjects-dir ${BIDS_DIR}/derivatives/fmriprep-${VERSION}/freesurfer \
        --cifti-output 91k \
        --output-spaces MNI152NLin6Asym:res-2 MNI152NLin2009cAsym fsnative T1w fsLR:den-32k  \
        --skip-bids-validation \
        --bids-database-dir /bids_database \
        ${BIDS_DIR} ${BIDS_DIR}/derivatives/fmriprep-${VERSION} participant
```

## Have you checked that your inputs are BIDS valid?

This has been processed with previous versions of fmriprep (20.2.0, I believe)

## More error info

```
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 17, in main
    parse_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/parser.py", line 640, in parse_args
    config.from_dict(vars(opts))
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 648, in from_dict
    execution.load(settings)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 218, in load
    cls.init()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 469, in init
    indexer=_indexer,
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 137, in __init__
    root, description = validate_root(root, validate)
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/validation.py", line 77, in validate_root
    json.dumps(EXAMPLE_BIDS_DESCRIPTION)
bids.exceptions.BIDSValidationError: 'dataset_description.json' is missing from project root. Every valid BIDS dataset must have this file.
Example contents of 'dataset_description.json': 
{"Name": "Example dataset", "BIDSVersion": "1.0.2"}
```

## Are you reusing previously computed results (e.g., FreeSurfer, Anatomical derivatives, work directory of previous run)?

Yes, freesurfer.

## pybids

I ran a shell in the container using the same mountpoints as above and ran:
```pybids layout --no-validate --index-metadata /mnt/stressdevlab/SEA/ /bids_database/
```

**Comment by effigies** [comment]
The easy fix here (and what I would strongly suggest) is to add a `dataset_description.json` and ensure that you have a BIDS-compliant dataset. fMRIPrep assumes that it is given a valid BIDS dataset, and the validator is bundled specifically to allow users to catch issues with their datasets before they cause difficult-to-interpret behavior in fMRIPrep. (The `--skip-bids-validation` option is there for edge cases, not to change the actual requirements of fMRIPrep.)

`validate=False` is there to allow certain files (lesion masks) to be indexed prior to their standardization. Now that there is a derivatives standard, the fix for this will be to instruct users to organize their lesion masks according to BIDS Derivatives, not to relax our requirements further.

**Comment by jflournoy** [comment]
That's what I ended up doing. Thank you for the explanation. That all makes sense!
