### ISSUE TITLE
Setting up server to run fmriprep effficiently

### ISSUE THREAD

**Issue by KarisColyerPatel** [nipreps/fmriprep#2584]
Hey there,

I will try to keep this short :) 

Our team has been running fmriprep on a linux server (16 processor cores and 64gb internal system memory) and when inc freesurfer segmentation per participant it is currently taking more than 2 days to complete. We have quite a large dataset so would like to improve on this! 

We are currently running the following command:

fmriprep-docker $home/c110667/bids_old $home/c11096667/bids_old/derivatives participant --fs-license-file $home/c1106667/bids_old/derivatives/license.txt -w $home/c11096667/intermediate --ignore slicetiming --bold2t1w-dof 6 --output-spaces T1w fsaverage5 MNI152NLin6Asym MNI152NLin2009cAsym --use-aroma --nthreads 16 --omp-nthreads 16

We are actually in the process of setting up surfsara and we were hoping you guys could offer some recommendations on performance related specifications!

Thanks in advance,

Karis

**Comment by KarisColyerPatel** [comment]
Hey,

Thanks for the quick response. We will be sure to try this out! 

As we will be setting up our new HPC cluster shortly, would you say 16 processor cores and 64gb internal system memory  should be sufficient?

**Comment by effigies** [comment]
Failed to respond in a timely fashion, but yes.
