### ISSUE TITLE
Running fmriprep using singularity

### ISSUE THREAD

**Issue by shilpitju** [nipreps/fmriprep#2587]
Hi,

I am trying to run fmriprep using singularity image on a HPC server with the following command (my current directory was directory storing fmriprep.simg files) in a puTTy shell:

 singularity run --cleanenv -B /path/to/userhome/scratch/Nifti:/fmriprep-20.2.4.simg  $HOME/scratch/Nifti $HOME/scratch/Derivatives participant --participant-label sub-R0130 --nthreads 16 -w $HOME/scratch/work --omp-nthreads 16 --fs-license-file $HOME/scratch/license.txt

I am getting the following error:
WARNING: skipping mount of sysfs: stat sysfs: no such file or directory
WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
WARNING: Skipping mount sysfs [kernel]: /sys doesn't exist in container
ERROR:   No runscript and no /bin/sh executable found in container, aborting

I would like to just mention that the my current directory has three fmriprep.simg versions saved. Should the versions of fmriprep not to be used be deleted?

Thanks,

Shilpi Modi

**Comment by effigies** [comment]
With FreeSurfer, 5.5 hours is about as good as you can expect.
