### ISSUE TITLE
Should we jump into Python 3.10 ?

### ISSUE THREAD

**Issue by oesteban** [nipreps/fmriprep#2589]
For much I would like to start using the walrus operator, I don't think any of the new features of Python 3.8-3.10 would justify that we pushed the current boundary beyond 3.7. However, the new error information features of 3.10 seem to me like an excellent reason to upgrade. I'm especially looking forward to not seeing the "tuple is not callable" errors from typos in nipype workflows anymore, along with other similar issues giving really bad feedback to the user.

WDYT?

**Comment by tsalo** [comment]
This was done in #3108.
