### ISSUE TITLE
Failed registrations between BOLD and T1w

### ISSUE THREAD

**Issue by HippocampusGirl** [nipreps/fmriprep#2591]
I am experiencing a significant number of failed registrations between BOLD and T1w for multiple datasets. We noticed that the images appear to be rotated basically in the wrong direction after registration. 

We also re-ran some of the registrations with FSL BBR and ANTs, which worked without any problem.

Sadly we are not able to share any of the underlying data, but I am happy to help diagnose the issue.

<img width="738" alt="screenshot" src="https://user-images.githubusercontent.com/789054/136358195-446a0393-2de0-4b36-ba33-b4db7c1673b5.png">

### What version of fMRIPrep are you using?

20.2.3

### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?

Singularity, via [HALFpipe](https://github.com/HALFpipe/HALFpipe/)

### What is the exact command-line you used?

singularity run --containall --bind /:/ext halfpipe-halfpipe-1.2.0.sif

### Are you reusing previously computed results (e.g., FreeSurfer, Anatomical derivatives, work directory of previous run)?

No, we were running from scratch

### Have you checked that your inputs are BIDS valid?

They seem to be missing some metadata, but are valid.

![remmina_mindandbrain server_localhost_20211012-6165](https://user-images.githubusercontent.com/789054/136901918-6e6b9a48-034f-43d6-932f-12ecdb060691.png)

### Do you know if this used to work in the past? 

We were also having these issues with version 20.2.1, but were hoping that #2307 would fix it.

### Are you running it with the --fs-no-reconall flag? 

Yes

### And are you running with susceptibility distortion correction?

No

### Did fMRIPrep generate the visual report for this particular subject? If yes, could you share it?

See screenshot above. I was asked not to share the full image, please let me know if the provided information is sufficient for diagnosing the issue.

### Can you find some traces of the error reported in the visual report (at the bottom) or in *crashfiles*?

There are no crashfiles.

### fMRIPrep log
If you have access to the output logged by fMRIPrep, please make sure to attach it as a text file to this issue.

The log file is quite large for the entire dataset. I will re-run a single subject to generate a smaller one and post that.

**Comment by oesteban** [comment]
> Sadly we are not able to share any of the underlying data, but I am happy to help diagnose the issue.

But, you should be able to share the visual report, right? :D

If not, the first thing I'm going to try to look up is whether FSL FLIRT+BBR was used or there's a reason the BBR registration was rejected. That should be stated on the caption above the reportlet showing T1w-BOLD registration.

**Comment by HippocampusGirl** [comment]
I investigated the issue some more, and it appears to be specific to datasets where the T1w image has a very high resolution (at least one voxel dimension smaller than 0.75 mm).

In this case, FLIRT will scale all input images by one over the minimum voxel dimension via the `basescale` parameter. 

I think there may be some issue with how this scaling is applied when calculating the starting value for registration. I have sent my report to the FSL developers here <https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?A2=FSL;78d20013.2110>. It will be interesting to get their expert opinion on this issue.

In general, I think this scaling may be important for animal/rodent data, but should be safe to disable for human images. This can be easily accomplished with the command line argument `-basescale 1`.

**Comment by HippocampusGirl** [comment]
Using a different tool like `mri_coreg` for the initial registration is a great idea. I think may be an much easier change than waiting for an updated version of `flirt`. I will have a look and check how `mri_coreg` it performs with my data. 

Would such a change be made only in 21.x and later, or would you also consider incorporating it into the LTS?

**Comment by effigies** [comment]
Will be fixed in 20.2.7. Is fixed in 21.0.0.
