### ISSUE TITLE
CI skips docker build/push if tag is on commit with "DOC: " message

### ISSUE THREAD

**Issue by effigies** [nipreps/fmriprep#2592]
Forgot to update the release date for 20.2.5, did it with a `DOC: ` message, and the workflow powered through: https://app.circleci.com/pipelines/github/nipreps/fmriprep/506/workflows/e70958be-c88e-46c0-b48f-91eb77753401

We should probably skip those checks for tags.

The code is already on PyPI, so we should build locally and push. @oesteban who all has credentials to do the push? Happy to let you build if that's easiest. Or I can push to `markiewicz/fmriprep:20.2.5` and you can re-tag?

**Comment by oesteban** [comment]
Pushing ATM. Should be up within minutes.
