### ISSUE TITLE
Is there a way in fMRIPrep to automatically convert native T1w coordinate to SCS / CTF ?

### ISSUE THREAD

**Issue by zhengchencai** [nipreps/fmriprep#2596]
Hi there,

Thanks for this amazing work. I am quite new to fMRIPrep and couldn't find a relevant topic on Neurostars by a quick search. I wonder if fMRIPrep has a solution to automatically convert native T1w to coordinate like SCS/CTF in which the original point and x- y- z-axis are defined by fiducials (nasion, left/right pre-auricular points). Usually, this requires a manual definition of the fiducials, or there are some automatic ways such as the Brainstorm software could also do it by registering T1w to MNI and use the coordinate in MNI to convert native T1w to CTF (details can be found at the bottom of this tutorial https://neuroimage.usc.edu/brainstorm/Tutorials/ImportAnatomy). I guess this is useful if we don't do group-level analysis and some native T1w are tilted which is not preferable for visualization.  

Thanks,
Zhengchen

**Comment by effigies** [comment]
Among the [Anatomical derivatives](https://fmriprep.org/en/stable/outputs.html#anatomical-derivatives) you'll find:

```
sub-<subject_label>/
  anat/
    sub-<subject_label>_from-fsnative_to-T1w_mode-image_xfm.txt
    sub-<subject_label>_from-T1w_to-fsnative_mode-image_xfm.txt
```

The latter affine may be applied to anything in T1w space to move it into the fsnative space.
