### ISSUE TITLE
fmriprep didn't perform SyN sdc

### ISSUE THREAD

**Issue by m-petersen** [nipreps/fmriprep#2615]
Dear Developers,

I am aiming for preprocessing of rsfMRI data on our local HPC using fmriprep. Since we do not acquire fieldmaps or other data allowing for sdc I want to use SyN sdc providing "--use-syn-sdc" to my fmriprep call. However, fmriprep seemingly didn't perform SyN sdc. The output looks uncorrected to me (admittedly, I have only experience with SyN sdc in DWI until now) and fmriprep reports do not mention any SDC steps or state that "SyN processing is not implemented yet". Am I missing something?

Grateful for any input.

Cheers,
Marvin

sub-000480a3_ses-1_task-rest_space-MNI152NLin6Asym_desc-preproc_bold.nii.gz
![Screenshot from 2021-10-25 15-59-04](https://user-images.githubusercontent.com/39294105/138714553-8c5fe98a-1d15-45b7-901a-3cc4dca144bf.png)

Raw bidsified bold image
![Screenshot from 2021-10-25 15-59-23](https://user-images.githubusercontent.com/39294105/138714716-77809cb6-2475-4d43-a5f5-0ff3c3e3bb5c.png)

### What version of fMRIPrep are you using?
21.0.0rc1

### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?
Singularity container

### What is the exact command-line you used?
```
   singularity run --cleanenv --userns -B /work/fatx405/projects/CSI_HCHS -B /scratch/fatx405.1499508/sub-ff86147c/tmp/:/tmp -B /scratch/fatx405.1499508/sub-ff86147c/tmp//input:/tmp_in -B /scratch/fatx405.1499508/sub-ff86147c/tmp//output:/tmp_out    /work/fatx405/projects/CSI_HCHS/envs/fmriprep-21.0.0rc1    /tmp_in /tmp_out participant    -w /tmp    --participant-label sub-ff86147c    --output-spaces fsnative fsaverage MNI152NLin6Asym    --nthreads 8    --omp-nthreads 7    --mem-mb 16000    --stop-on-first-crash    --ignore t2w    --fs-subjects-dir /tmp_out/freesurfer    --use-aroma    --cifti-output 91k    --random-seed 12345    --use-syn-sdc    --notrack    --skip_bids_validation    --fs-license-file envs/freesurfer_license.txt'
```

### Have you checked that your inputs are BIDS valid?
Yes

### Did fMRIPrep generate the visual report for this particular subject? If yes, could you share it?

Yes, but there is no visual report regarding the problem (syn sdc)

### Can you find some traces of the error reported in the visual report (at the bottom) or in *crashfiles*?
```
<please copy&paste all the information you can gather about errors>
```
Visual report says "No errors to report!"
No crashfiles produced.
Log file says "SyN processing is not yet implemented." and there is no mentioning of any SyN processing.
'figures/sub-ff86147c_ses-1_task-rest_desc-summary_bold.html' states "Susceptibility distortion correction: None"

### Are you reusing previously computed results (e.g., FreeSurfer, Anatomical derivatives, work directory of previous run)?
Yes, freesurfer outputs

### fMRIPrep log
If you have access to the output logged by fMRIPrep, please make sure to attach it as a text file to this issue.

Log files (fmriprep call parallelized with gnu parallel)
[1499508-fmriprep-2648-01102021.err.txt](https://github.com/nipreps/fmriprep/files/7411196/1499508-fmriprep-2648-01102021.err.txt)
[1499508-fmriprep-2648-01102021.out.txt](https://github.com/nipreps/fmriprep/files/7411197/1499508-fmriprep-2648-01102021.out.txt)

**Comment by oesteban** [comment]
@m-petersen the `unstable` tag of the docker image should have SDC-SyN back. Could you try it out and let us know how did it go?

**Comment by effigies** [comment]
This is restored. We can open a new issue if there are problems with the quality of SDC.

**Comment by m-petersen** [comment]
Sorry for missing out on reporting back. Everything works fine now. Thanks a lot!
