### ISSUE TITLE
--output-spaces MNI152NLin6Asym for Schaefer's atlas?

### ISSUE THREAD

**Issue by GerardYu** [nipreps/fmriprep#2618]
i intend to use the schaefers atlas from nilearn (datasets.fetch_atlas_schaefer_2018(200)) to construct my FC matrices. I see that the downloaded atlas template has the filename of "Schaefer2018_200Parcels_7Networks_order_FSLMNI152_1mm.nii.gz" — suggesting that this template is in the FSL MNI space. 

does this mean i should run my fmriprep with the --output-spaces MNI152NLin6Asym option?

**Comment by oesteban** [comment]
AFAICT, nilearn's atlas is defined on MNI152NLin6Asym. However, best practice would be downloading it from TemplateFlow, as the orientation of the NIfTI files is matched with that of the template fMRIPrep is using. If I'm not wrong, I think we also resampled the Schaefer atlas into MNI152NLin2009cAsym, so either way you will be able to use the atlas.
