### ISSUE TITLE
fmriprep asking for dataset_description.json even when bids dir has the json file

### ISSUE THREAD

**Issue by bdeck8317** [nipreps/fmriprep#2619]
### What happened?

I was attempting to run fmriprep on gcloud via a SLURM cluster. The data is mounted via gscfuse from a cloud bucket.

### What command did you use?

```shell
'''
singularity run --cleanenv $HOME/fmriprep.sif \
  $HOME/work/bids_dir/ $HOME/work/fmriprep_out/ \
  participant \
  --skip-bids-validation \
  --participant-label sub-10159 \
  --verbose \
  --omp-nthreads 1 \
  --mem 32000 \
  --output-spaces T1w fsaverage fsaverage6 fsaverage5 MNI152NLin2009cAsym \
  --fs-license-file $HOME/work/license.txt \
  --work-dir $HOME/work/tmpdir/ 
'''
```

### What version of fMRIPrep are you running?

fMRIPrep-20.2.4

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
'''

mkdir: cannot create directory '/home/bdeck8317_gmail_com/work/tmpdir': File exists
You are using fMRIPrep-20.2.4, and a newer version of fMRIPrep is available: 20.2.5.
Please check out our documentation about how and when to upgrade:
https://fmriprep.readthedocs.io/en/latest/faq.html#upgrading
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 17, in main
    parse_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/parser.py", line 635, in parse_args
    config.from_dict(vars(opts))
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 648, in from_dict
    execution.load(settings)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 218, in load
    cls.init()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 469, in init
    indexer=_indexer,
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 137, in __init__
    root, description = validate_root(root, validate)
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/validation.py", line 77, in validate_root
    json.dumps(EXAMPLE_BIDS_DESCRIPTION)
bids.exceptions.BIDSValidationError: 'dataset_description.json' is missing from project root. Every valid BIDS $
Example contents of 'dataset_description.json':
{"Name": "Example dataset", "BIDSVersion": "1.0.2"}

'''
```

### Additional information / screenshots

![image](https://user-images.githubusercontent.com/49119525/139514242-f452a487-215d-4bd5-906d-7faccc3415b0.png)

'''  

GNU nano 2.3.1                                        File: dataset_description.json                                                                                       

{
    "Name": "UCLA Consortium for Neuropsychiatric Phenomics LA5c Study",
    "License": "CC0",
    "Authors": [
        "Bilder, R",
        "Poldrack, R",
        "Cannon, T",
        "London, E",
        "Freimer, N",
        "Congdon, E",
        "Karlsgodt, K",
        "Sabb, F"
    ],
    "Acknowledgements": "This work was supported by the Consortium for Neuropsychiatric Phenomics (NIH Roadmap for Medical Research grants UL1-DE019580, RL1MH083268, RL1MH0$
    "HowToAcknowledge": "This data was obtained from the OpenfMRI database (https://openfmri.org/dataset/ds000030/). Its accession number is ds000030. Please cite https://w$
    "ReferencesAndLinks": [
        "https://www.nature.com/articles/sdata2016110",
        "https://f1000research.com/articles/6-1262/v2"
    ],
    "Description": "The Consortium for Neuropsychiatric Phenomics (CNP) is a large study funded by the NIH Roadmap Initiative that aims to facilitate discovery of the genet$
    "Funding": [
        "Consortium for Neuropsychiatric Phenomics"
    ],
    "OpenFMRIAccessionNumber": "ds000030",
    "BIDSVersion": "1.0.2",
    "DatasetDOI": "10.18112/openneuro.ds000030.v1.0.0"
}

'''

**Comment by smeisler** [comment]
1) Make sure that `dataset_description.json`is not in the `.bidsignore `file (if one exists) in the bids directory
2) Try binding `$HOME` to the singularity container with `-B $HOME` between `run` and `--cleanenv`

**Comment by bdeck8317** [comment]
@smeisler  was hoping that would work.

1. `.bidsignore` doesn't exist
2.  Warning about `-B` as $HOME is already a mount point for the container.

**Comment by effigies** [comment]
Does upgrading to 20.2.5 resolve the issue?

And is the following part of the contents of your dataset_description?

```
GNU nano 2.3.1 File: dataset_description.json
```

**Comment by bdeck8317** [comment]
@effigies hey sorry, no `GNU ....` is not part of my dataset-description.json. That was a copy paste error :/

I think my problem is actually occurring using `gcsfuse` and binding the bucket to my compute instances. I will close this issue as it really isn't an fmriprep issue.
