### ISSUE TITLE
The `hemi` keyword should come before `space` in output files

### ISSUE THREAD

**Issue by tsalo** [nipreps/fmriprep#2620]
In the BIDS specification, the `hemi` entity appears before the `space` entity. However, in fMRIPrep's documentation (and at least the outputs from the ds005 test), files with the `hemi` keyword have `space` come first.

```
sub-<subject_label>/
  func/
    sub-<subject_label>_[specifiers]_space-T1w_desc-aparcaseg_dseg.nii.gz
    sub-<subject_label>_[specifiers]_space-T1w_desc-aseg_dseg.nii.gz
    sub-<subject_label>_[specifiers]_space-<space_label>_hemi-[LR]_bold.func.gii
```

It doesn't look like any files with `hemi` in them contain any derivatives-only entities other than `space`, so I think the fix should be fairly straightforward. 

This stems from https://github.com/bids-standard/bids-specification/pull/917#pullrequestreview-793177804.

**Comment by effigies** [comment]
This will be a fix in niworkflows. Guess the question is whether this is fixed in the LTS or the next fMRIPrep release.

**Comment by effigies** [comment]
Just a note that I think I *like* hemi coming after `space`. In general the entities go from broad to narrow, and I think of the space as broader than the hemisphere.

How set-in-stone is the ordering at this point? Does it make sense to update the order in BIDS instead?
