### ISSUE TITLE
fmriprep hangs on 3dqwarp for all functional runs

### ISSUE THREAD

**Issue by smweis** [nipreps/fmriprep#2623]
### What happened?

After discovering dropout in the frontal/anterior temporal lobe regions, I tried SDC with fmriprep. I'm using a Philips scanner, but am providing `EffectiveEchoSpacing` and `TotalReadoutTime` in the sidecars of all relevant files. 

What happens is fmriprep runs until it gets to 3dqwarp, where it hangs with no output indefinitely. I've tried running fmriprep fresh after deleting the working directory (but retaining recon-all outputs) and allowing it to pick up where it left off. Each functional run hangs in the same spot. 

Curiously, running the 3dqwarp command manually (pasted below) runs in 5 minutes outside the singularity with AFNI version 18.1.04: 

`3dQwarp -prefix DEMOQwarp.nii.gz -plusminus -noXdis -noZdis -base /blue/stevenweisberg/share/tmp/fmriprep_wf/single_subject_dspfmri12005_wf/func_preproc_task_funcLocalizer_run_02_wf/sdc_estimate_wf/pepolar_unwarp_wf/qwarp/transform_Warped.nii.gz -blur -1.0 -1.0 -source /blue/stevenweisberg/share/tmp/fmriprep_wf/single_subject_dspfmri12005_wf/func_preproc_task_funcLocalizer_run_02_wf/sdc_estimate_wf/pepolar_unwarp_wf/qwarp/transform_Warped_c0000.nii.gz -minpatch 9 -nopadWARP -noweight -pblur 0.05 0.05`

### What command did you use?

```shell
#!/bin/bash
#SBATCH --account=stevenweisberg
#SBATCH --qos=stevenweisberg
#SBATCH --job-name=fmriprep_dspfmri
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=stevenweisberg@ufl.edu
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=8gb
#SBATCH --time=24:00:00
#SBATCH --output=fmriprep_dspfmri12005_%j.out
#pwd; hostname; date

#BP 1/19/21
# SW 7/2/21

module load singularity
echo "dspfmri12005"

#directories
BIDS_dir=/blue/stevenweisberg/share/DSP_fMRI
fmriprep_derivatives_dir=/blue/stevenweisberg/share/DSP_fMRI/derivatives
freesurfer_license_dir=/blue/stevenweisberg/elianyperez/code/fmriprep
singularity_dir=/blue/stevenweisberg/share/DSP_fMRI/code/singularities
work_dir=/blue/stevenweisberg/share/tmp
fmriprep_version=fmriprep-20.2.3.simg


#running fmriprep with ICA-AROMA
# for info on inputs, see here: https://fmriprep.org/en/stable/usage.html
singularity run --cleanenv $singularity_dir/$fmriprep_version $BIDS_dir $fmriprep_derivatives_dir participant --participant-label dspfmri12005 --no--debug all -vvv --output-space T1w MNI152NLin2009cAsym --work-dir $work_dir --fs-license-file $freesurfer_license_dir/freesurfer_license.txt --use-aroma
```

### What version of fMRIPrep are you running?

20.2.3

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

FreeSurfer, Work directory, No

### Please copy and paste any relevant log output.

```shell
Log attached.
```

### Additional information / screenshots

[fmriprep_dspfmri12005_11666440.txt](https://github.com/nipreps/fmriprep/files/7521597/fmriprep_dspfmri12005_11666440.txt)

**Comment by effigies** [comment]
I would retry with the nipreps/fmriprep:unstable image. We've switched from qwarp to topup, which we've found performs better, apart from whatever problem is being exhibited here.

**Comment by smweis** [comment]
Thanks, will do.

**Comment by smweis** [comment]
This did not appear to solve the issue as the job now hangs as it is trying to resample. I'm thinking it's an HPC issue so I'll check with them and update here.

**Comment by smweis** [comment]
This appears to be a memory issue, but one thing I noticed when I was running this job is that despite allocating only 64gb (8gb/cpu) fmriprep would think it has access to ~420gb (my entire ram allotment). You can see for example on these lines: 

`211111-09:30:07,826 nipype.workflow INFO:
	 [MultiProc] Running 21 tasks, and 17 jobs ready. Free memory (GB): 438.88/452.27, Free processors: 1/64.
                     Currently running:
                       * fmriprep_wf.single_subject_dspfmri12005_wf.anat_preproc_wf.fs_isrunning`

Calling fmriprep with the --mem tag does restrict memory (which I'm doing now). 

Happy to close this but maybe worth opening another issue? Or maybe someone can explain what/why this is happening.

**Comment by effigies** [comment]
In general, batch quotas are not available to fMRIPrep, unless they modify the system calls Python uses to determine how many cores or how much RAM is present on the system. (I don't know of any that do that..)

By default we use all CPUs and 90% of RAM that can be detected on the system, so using `--mem-mb` and `--n-cpus` is the correct way to constrain it.

**Comment by smweis** [comment]
Thank you - that's super helpful to know! I'll close this then.
