### ISSUE TITLE
Templateflow: No space left on device

### ISSUE THREAD

**Issue by butellyn** [nipreps/fmriprep#2627]
### What happened?

I am trying to run fmriprep using Singularity, but it is failing at the templateflow step. I followed @utooley's [solution from 2019](https://neurostars.org/t/antsbrainextraction-failure-freesurfer-does-fine/3949/32), but my guess is this is out of date now because it did not fix my problem. 

I also tried binding my templateflow directory to `/templateflow` because I managed to get that to work with fmriprep version 20.0.5 [here](https://github.com/PennBBL/ExtraLong/blob/master/scripts/process/datafreeze-2019/FreesurferCross/submitFMRIPrep.py). This solution did not work for me now.

Additionally, I shelled into the Singularity container and noticed that `$HOME` was set to `/home/erb9722`, but `/home/fmriprep` also existed (noticed that this was a major issue that came up on Ursula's post). 

I would really appreciate any tips on the best way to handle templateflow using fmriprep version 20.2.3 with singularity. Thanks!

### What command did you use?

```shell
#!/bin/bash
#SBATCH --account=b1081 
#SBATCH --partition=buyin 
#SBATCH --array=1       
#SBATCH --nodes=1  
#SBATCH --ntasks-per-node=1              
#SBATCH --time=30:00:00          
#SBATCH --mem-per-cpu=64G 
#SBATCH --job-name="sample_job_\${SLURM_ARRAY_TASK_ID}" 
#SBATCH --output=sample_job.%A_%a.out  
#SBATCH --mail-type=FAIL   
#SBATCH --mail-user=ellynbutler2027@u.northwestern.edu  

pwd; hostname; date

singularity run --cleanenv --containall \
    -B /projects/b1108:/projects/b1108 \
    -B /projects/b1108/software/freesurfer_license/license.txt:/opt/freesurfer/license.txt \
    -B /projects/b1108/templateflow:/home/erb9722/templateflow \
    /home/erb9722/fmriprep_20.2.3.sif \
    /projects/b1108/data/MWMH/bids_directory /projects/b1108/data/MWMH \
    participant \
    --participant-label MWMH117 \
    --fs-license-file /opt/freesurfer/license.txt \
    -w /projects/b1108/data/MWMH/work \
    --output-spaces MNI152NLin2009cAsym \
    --skull-strip-template OASIS30ANTs \
    --bids-filter-file /projects/b1108/data/MWMH/config/ses-1_config.json
```

### What version of fMRIPrep are you running?

20.2.3

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/workflow.py", line 82, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 64, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 252, in init_single_subject_wf
    t1w=subject_data['t1w'],
  File "/usr/local/miniconda/lib/python3.7/site-packages/smriprep/workflows/anatomical.py", line 321, in init_anat_preproc_wf
    normalization_quality='precise' if not debug else 'testing')
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/anat/ants.py", line 180, in init_brain_extraction_wf
    in_template, template_spec=template_spec
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/utils/misc.py", line 58, in get_template_specs
    tpl_target_path = get_template(in_template, **template_spec)
  File "/usr/local/miniconda/lib/python3.7/site-packages/templateflow/api.py", line 78, in get
    _s3_get(filepath)
  File "/usr/local/miniconda/lib/python3.7/site-packages/templateflow/api.py", line 234, in _s3_get
    t.update(len(data))
OSError: [Errno 28] No space left on device
```

### Additional information / screenshots

`/projects/b1108` is only 90% full.

**Comment by effigies** [comment]
This is likely to be a quota issue and the operating system is rejecting an attempt to write to a file. I assume `/projects/b1108` is meant to be fairly long-term, so one thing you might do is put the working directory in scratch space, which should be much larger.

**Comment by butellyn** [comment]
I actually just found your [thread on neurostars](https://neurostars.org/t/fmriprep-pre-download-templateflow/15491/3), which fixed the problem (at least made it past the templateflow step). It looks like templateflow is still downloading, though, which is odd, considering I am binding the templateflow directory. Here is my call now:

`SINGULARITYENV_TEMPLATEFLOW_HOME=/home/fmriprep/.cache/templateflow \
    singularity run --cleanenv --containall \
    -B /projects/b1108:/projects/b1108 \
    -B /projects/b1108/software/freesurfer_license/license.txt:/opt/freesurfer/license.txt \
    -B /projects/b1108/templateflow:/home/fmriprep/.cache/templateflow \
    /home/erb9722/fmriprep_20.2.3.sif \
    /projects/b1108/data/MWMH/bids_directory /projects/b1108/data/MWMH \
    participant \
    --participant-label MWMH117 \
    --fs-license-file /opt/freesurfer/license.txt \
    -w /projects/b1108/data/MWMH/work \
    --output-spaces MNI152NLin2009cAsym \
    --skull-strip-template OASIS30ANTs \
    --bids-filter-file /projects/b1108/data/MWMH/config/ses-1_config.json`

This is what is in `/projects/b1108/templateflow`:
<img width="985" alt="Screen Shot 2021-11-15 at 3 46 59 PM" src="https://user-images.githubusercontent.com/41019524/141858472-e780712f-4a1a-4a1a-81ba-cdbb09234ed9.png">

And here are the lines that indicate templateflow is downloading:
<img width="1382" alt="Screen Shot 2021-11-15 at 3 48 21 PM" src="https://user-images.githubusercontent.com/41019524/141858592-7b74f4a2-87c1-4214-8bbf-a3119e790748.png">

**Comment by mgxd** [comment]
By default, TemplateFlow will only create the skeleton, and populate the files as they are needed. Once they have been downloaded in `/projects/b1108/templateflow`, they won't need to be redownloaded in subsequent runs.

Please reopen if you are still running into issues.
