### ISSUE TITLE
fmriprep on different machines

### ISSUE THREAD

**Issue by shilpitju** [nipreps/fmriprep#2631]
Hi,

This might seem to be a silly question, but I wanted to know if I have a large dataset to be processed, can I split it into two and process in two separate machines with the same fmriprep version.

Thanks,

**Comment by effigies** [comment]
Yes. To be clear, is it large in that you have a lot of data per subject or many subjects?

If it's many subjects, that's very common, and the way to do this is to use the `--participant-label` option to select the subjects to run.

If it's a lot of data per subject, then you'll probably want to run `--anat-only`, and then use the `--bids-filter-file` to split across sessions.

I can give more details if you need, but it would be good to understand the problem more first.

**Comment by shilpitju** [comment]
Its many subjects. I want to run half on them on one computer and remaining subjects on the other computer.

**Comment by effigies** [comment]
Yes, each subject can be run entirely independently, so you can split them up how you want.

**Comment by shilpitju** [comment]
Thanks so much.
