### ISSUE TITLE
Incorrect multi-echo detection with multiple runs

### ISSUE THREAD

**Issue by Lestropie** [nipreps/fmriprep#2634]
### What happened?

Following a seemingly inconsequential change to file names, multi-echo processing is no longer activated.

-----

We have previously executed on multiple multi-echo fMRI runs without issue. Our BIDS structure would appear as follows:

```Text
sub-###/
    func/
         sub-###_task-rest_run-1_echo-1_bold.nii.gz
         sub-###_task-rest_run-1_echo-1_bold.json
         sub-###_task-rest_run-1_echo-2_bold.nii.gz
         sub-###_task-rest_run-1_echo-2_bold.json
         sub-###_task-rest_run-1_echo-3_bold.nii.gz
         sub-###_task-rest_run-1_echo-3_bold.json
         sub-###_task-rest_run-2_echo-1_bold.nii.gz
         sub-###_task-rest_run-2_echo-1_bold.json
         sub-###_task-rest_run-2_echo-2_bold.nii.gz
         sub-###_task-rest_run-2_echo-2_bold.json
         sub-###_task-rest_run-2_echo-3_bold.nii.gz
         sub-###_task-rest_run-2_echo-3_bold.json
```

Notably here, the identification of those multiple runs during DICOM to BIDS conversion was *explicit*.

We have recently changed our acquisition protocol. Our two fMRI runs are now named identically to one another on the scanner console, such that their disambiguation is necessitated by the DICOM to BIDS conversion software (`dcm2bids`). The resulting BIDS structure is now:

```Text
sub-###/
    func/
         sub-###_task-rest_echo-1_run-1_bold.nii.gz
         sub-###_task-rest_echo-1_run-1_bold.json
         sub-###_task-rest_echo-1_run-2_bold.nii.gz
         sub-###_task-rest_echo-1_run-2_bold.json
         sub-###_task-rest_echo-2_run-1_bold.nii.gz
         sub-###_task-rest_echo-2_run-1_bold.json
         sub-###_task-rest_echo-2_run-2_bold.nii.gz
         sub-###_task-rest_echo-2_run-2_bold.json
         sub-###_task-rest_echo-3_run-1_bold.nii.gz
         sub-###_task-rest_echo-3_run-1_bold.json
         sub-###_task-rest_echo-3_run-2_bold.nii.gz
         sub-###_task-rest_echo-3_run-2_bold.json
```

Note that the BIDS conversion software automatically appends the "`_run-#`" key-value; this is outside of user control.

With these data, `fmriprep` no longer engages a multi-echo pipeline, instead processing each echo of each run independently. It should however IMO be possible for the underlying logic to be built in such a way that it seeks files for which the only difference is in the "`_echo-#`" key-value, without necessitating that that be the last key-value before the `bold` suffix.

### What command did you use?

```shell
singularity run --cleanenv \
    --bind /projects/####:/projects/####,/scratch/####:/scratch/#### \
    $FMRIPREP_IMAGE \
    $BIDSDIR $OUTDIR participant \
    --participant_label sub-$SUBJECT \
    --nthreads $SLURM_CPUS_PER_TASK --omp-nthreads $SLURM_CPUS_PER_TASK \
    --mem_mb $SLURM_MEM_PER_NODE \
    --output-spaces T1w MNI152NLin6Asym:res-2 fsaverage5 \
    --fs-license-file $FREESURFER_LICENSE \
    --fs-subjects-dir $FREESURFER_SUBJECTS \
    -w $WORKDIR "
```

### What version of fMRIPrep are you running?

20.2.1

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by effigies** [comment]
In general, I agree that we should be forgiving here. I would note that BIDS is itself strict about the order of entities, so it's likely that somewhere we relied on the entity order matching BIDS.

**Comment by Lestropie** [comment]
> I would note that BIDS is itself strict about the order of entities

I hadn't actually realised that, I'd always assumed that everything between subject/session and suffix was permutable. In that case it's fundamentally a `dcm2bids` issue (though as you say you could theoretically be more permissible); I'll post there also, though the project appears to be EOL. I'll also double-check the BIDS validation, as misordering should have been reported.

**Comment by Lestropie** [comment]
Can confirm that BIDS validator `1.8.5` does *not* issue any message relating to the fact that the order of entities is inconsistent with the specification.

**Comment by tsalo** [comment]
Given that the linked Dcm2Bids and bids-validator issues have been addressed, can this issue be closed as well?
