### ISSUE TITLE
fmriprep-docker command not found, Mac Monterey zsh

### ISSUE THREAD

**Issue by keithcdodd** [nipreps/fmriprep#2635]
### What happened?

I have docker installed and running. The fmriprep website suggests using docker for use and installation, so I installed docker successfully. I then followed [this link](https://www.nipreps.org/apps/docker/#running-a-niprep-with-a-lightweight-wrapper) as suggested by the fmriprep website to install fmriprep with "docker pull nipreps/fmriprep:20.2.6". That same website suggests that if the fmriprep wrapper is installed, then you should now be able to call it with fmriprep-docker. Their link to the "fmriprep wrapper" is just directly back to the fmriprep website. So I assume that means I have the wrapper installed since I have installed fmriprep with the docker command.

However, when I type "fmriprep-docker" in my terminal, the result errors with "zsh: command not found: fmriprep-docker." Does this mean I am still missing the wrapper? Or, does it mean I have the wrapper, but the command is not being recognized?

I read some more, and I see suggestions in the [step by step tutorial](https://reproducibility.stanford.edu/fmriprep-tutorial-running-the-docker-image/) saying to use "pip install --user --upgrade fmriprep-docker" to install the wrapper. However, I am wary of doing this for the following reason:

While the fmriprep website says the docker container method is preferable, the website appears to be written with more guidance on the bare metal installation which utilizes pip install. Was this maybe the main method in the past? If so, then I wonder if trying to install the fmriprep wrapper with pip install is what is desired for the bare metal installation? And not the currently suggested docker container? 

Is there another method I should be using with docker that should install the wrapper correctly? Or is the wrapper installed already by what I did, but somehow my computer is not recognizing the command shortcut (Mac Monterey -- uses zsh)? 

I am more wary simply because I had a similar issue when installing neurodocker with docker where their shortcut "neurodocker" was supposed to work right after installation, but something with this mac version stopped that somehow and I had to create an alias myself in the ~/.zprofile. Do I need to do something similar here?

Otherwise, I am happy to do the pip install of the fmriprep-wrapper, I just wanted to make sure that was necessary or best before I mess something up.

Thanks!

### What command did you use?

```shell
docker pull nipreps/fmriprep:20.2.6

fmriprep-docker --help
```

### What version of fMRIPrep are you running?

20.2.6

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

No

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
zsh: command not found: fmriprep-docker
```

**Comment by mgxd** [comment]
hi @keithcdodd 

I can see your confusion - there are two things here:
1) The `docker pull` command. This is getting the docker image (which serves as a self contained environment) for running fmriprep.
2) `fmriprep-docker`. This is a standalone python script that facilitates using the docker container. This script is generally installed locally (like in the tutorial: `pip install --user --upgrade fmriprep-docker`), and then used to create the command line.

Since you already have the docker image from running `docker pull nipreps/fmriprep:20.2.6`, all you need to do is install the wrapper.

**Comment by keithcdodd** [comment]
Perfect. Thanks a lot for the clarification. That makes sense.
