### ISSUE TITLE
no space left on device with 21.0.0rc2

### ISSUE THREAD

**Issue by DVSneuro** [nipreps/fmriprep#2644]
### What happened?

I was testing the latest release candidate (21.0.0rc2) in the hopes that it would fix an issue was experience with masking and negative data on multi-echo images (https://neurostars.org/t/negative-data-following-multi-echo-optimal-combination-in-fmriprep/20698), but the analysis fails with a no space left on device error. I've deleted all intermediate output (including scratch), so there shouldn't be any conflict with what I've ran previously. 

(Apologies for cross posting mostly-unrelated issues here and on NeuroStars, but hopefully this can help tune the 21.* series.)

### What command did you use?

```shell
TEMPLATEFLOW_DIR=/data/tools/templateflow
export SINGULARITYENV_TEMPLATEFLOW_HOME=/opt/templateflow
singularity run --cleanenv \
-B ${TEMPLATEFLOW_DIR}:/opt/templateflow \
-B $maindir:/base \
-B /data/tools/licenses:/opts \
-B $scratchdir:/scratch \
/data/tools/fmriprep-21.0.0rc2.simg \
/base/bids /base/derivatives \
participant --participant_label $sub \
--stop-on-first-crash \
--fs-no-reconall --fs-license-file /opts/fs_license.txt -w /scratch
```

### What version of fMRIPrep are you running?

21.0.0rc2 

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
OSError: [Errno 28] No space left on device: '/opt/conda/lib/python3.8/site-packages/skimage/data/../data/astronaut.png' -> '/home/fmriprep/.cache/scikit-image/0.18.3/data/../data/astronaut.png'
```

**Comment by DVSneuro** [comment]
Sorry that got omitted! Here it is below. I'm also attaching the crash log.

Crash log: [crash-20211130-020623-tug87422-acc_masks-fe41e079-3d96-4539-8793-43f5c6224ad8.txt](https://github.com/nipreps/fmriprep/files/7628285/crash-20211130-020623-tug87422-acc_masks-fe41e079-3d96-4539-8793-43f5c6224ad8.txt)

```
File: /base/derivatives2/sub-2001/log/20211130-010121_a5aaf801-457e-42da-9fb0-577ddac9cc94/crash-20211130-020623-tug87422-acc_masks-fe41e079-3d96-4539-8793-43f5c6224ad8.txt
Working Directory: /scratch/fmriprep_wf/single_subject_2001_wf/func_preproc_task_sharedreward_acq_mb1me1_wf/bold_confounds_wf/acc_masks
Inputs:
bold_zooms:in_vfs:is_aseg: FalseTraceback (most recent call last): File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node result["result"] = node.run(updatehash=updatehash) File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run result = self._run_interface(execute=True) File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface return self._run_command(execute) File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command result = self._interface.run(cwd=outdir) File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run runtime = self._run_interface(runtime) File "/opt/conda/lib/python3.8/site-packages/fmriprep/interfaces/confounds.py", line 68, in _run_interface self._results["out_masks"] = acompcor_masks( File "/opt/conda/lib/python3.8/site-packages/fmriprep/utils/confounds.py", line 113, in acompcor_masks from skimage.morphology import ball File "/opt/conda/lib/python3.8/site-packages/skimage/__init__.py", line 135, in from .data import data_dir File "/opt/conda/lib/python3.8/site-packages/skimage/data/__init__.py", line 270, in _init_pooch() File "/opt/conda/lib/python3.8/site-packages/skimage/data/__init__.py", line 262, in _init_pooch _fetch(filename) File "/opt/conda/lib/python3.8/site-packages/skimage/data/__init__.py", line 222, in _fetch shutil.copy2(gh_repository_path, resolved_path) File "/opt/conda/lib/python3.8/shutil.py", line 432, in copy2 copyfile(src, dst, follow_symlinks=follow_symlinks) File "/opt/conda/lib/python3.8/shutil.py", line 272, in copyfile _fastcopy_sendfile(fsrc, fdst) File "/opt/conda/lib/python3.8/shutil.py", line 163, in _fastcopy_sendfile raise err from None File "/opt/conda/lib/python3.8/shutil.py", line 149, in _fastcopy_sendfile sent = os.sendfile(outfd, infd, offset, blocksize)OSError: [Errno 28] No space left on device: '/opt/conda/lib/python3.8/site-packages/skimage/data/../data/astronaut.png' -> '/home/fmriprep/.cache/scikit-image/0.18.3/data/../data/astronaut.png'
```

**Comment by effigies** [comment]
```
from skimage.morphology import ball
```

Yeah, `skimage` should not be downloading things for this. I'll check whether this has already been fixed upstream, and report if not.

**Comment by hmaarrfk** [comment]
I think gcc supports float16.
https://gcc.gnu.org/onlinedocs/gcc/Half-Precision.html

Relevant quotes:
> On x86 targets with SSE2 enabled, GCC supports half-precision (16-bit) floating point via the _Float16 type. For C++, x86 provides a builtin type named _Float16 which contains same data format as C. 

> On x86 targets with SSE2 enabled, without -mavx512fp16, all operations will be emulated by software emulation and the float instructions. The default behavior for FLT_EVAL_METHOD is to keep the intermediate result of the operation as 32-bit precision. This may lead to inconsistent behavior between software emulation and AVX512-FP16 instructions. Using -fexcess-precision=16 will force round back after each operation.

> Using -mavx512fp16 will generate AVX512-FP16 instructions instead of software emulation. The default behavior of FLT_EVAL_METHOD is to round after each operation. The same is true with -fexcess-precision=standard and -mfpmath=sse. If there is no -mfpmath=sse, -fexcess-precision=standard alone does the same thing as before, It is useful for code that does not have _Float16 and runs on the x87 FPU. 

Though, the comments on that page for ARM or rather concerning for dynamically loaded libraries which may be compiled with incompatible versions of float16.

**Comment by hmaarrfk** [comment]
You can try to set the `SKIMAGE_DATADIR` environment variable to somewhere writable.

We are trying to release, but the slew of the new computers and versions of python is slowing things down a bit.
