### ISSUE TITLE
Run number name pattern using run-01 instead of run-1

### ISSUE THREAD

**Issue by zhengchencai** [nipreps/fmriprep#2655]
### What would you like to see added in fMRIPrep?

Hi there,

I had this small "issue" with the way fmriprep numbers the runs. The current naming pattern is run-1 instead of run-01. However, run-01 is the way BIDS number the runs, this 1) requires a little bit extra but annoying work when querying files from both BIDS root folder and fmriprep folder. 2) the order of HTML report will be run-1, then run-10, 11, 12 ... and then run-2. It would be nice to fix this to be consistent with BIDS. Thanks a lot.

Thanks,
Zhengchen

### Do you have any interest in helping implement the feature?

No

**Comment by effigies** [comment]
At this point, we're unlikely to go back to zero-padding unless somebody proposes a patch that is not too complicated.

That said, I agree that we should be sorting run reports numerically, not lexically.
