### ISSUE TITLE
Cannot register to MNI152 3mm isotropic template

### ISSUE THREAD

**Issue by wizofe** [nipreps/fmriprep#2660]
### What happened?

I tried adding a 3mm isotropic MNI152Lin template file from CPAC (T1W, brain, mask) to `~/.cache/templateflow/tpl-MNI152Lin3mm` and ask fmriprep to register my files (ABIDE 1) to this template.

The result was a bit weird though, as the final pre-processed BOLD file was 3x3x4 (mm) even though the template file was correct 3x3x3 (mm) [the original is 3.5x3.5x4.25 or somthing similar] Is there anything I am missing?

### What command did you use?

```shell
fmriprep BIDS_data/ BIDS_data/derivatives participant --participant-label 0050570 --nthreads 16 --fs-license-file BIDS_data/derivatives/license.txt --fs-no-reconall MNI152Lin3mm fsnative --output-spaces  --use-aroma --skip-bids-validation --stop-on-first-crash
```

### What version of fMRIPrep are you running?

20.2.5

### How are you running fMRIPrep?

Local installation ("bare-metal")

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
N/A
```

### Additional information / screenshots

N/A

**Comment by effigies** [comment]
Could you provide the listing of `tpl-MNI152Lin3mm`? Assuming it's something like:

```
tpl-MNI152Lin3mm_res-03_desc-brain_mask.nii.gz
tpl-MNI152Lin3mm_res-03_desc-head_mask.nii.gz
tpl-MNI152Lin3mm_res-03_PD.nii.gz
tpl-MNI152Lin3mm_res-03_T1w.nii.gz
tpl-MNI152Lin3mm_res-03_T2w.nii.gz
```

then `--output-spaces MNI152Lin3mm:res-03` should work.

**Comment by wizofe** [comment]
```
.
├── template_description.json
├── tpl-MNI152Lin3mm_res-01_desc_brain-mask_dil.nii.gz
├── tpl-MNI152Lin3mm_res-01_desc-brain_mask.nii.gz
├── tpl-MNI152Lin3mm_res-01_desc-brain_T1w.nii.gz
└── tpl-MNI152Lin3mm_res-01_T1w.nii.gz
```

That's how it looks.

**Comment by effigies** [comment]
Okay, then I think you want to use `--output-spaces MNI152Lin3mm:res-01`.

I suspect with the holidays rapidly approaching, trying to update the template on TemplateFlow isn't going to see much of a response before January.

**Comment by wizofe** [comment]
This solved my issue. I'll close that here and try to update the Templateflow with this new template. Thank you @effigies :)
