### ISSUE TITLE
Pre-release 21.0.0rc2 alters derivatives directory structure

### ISSUE THREAD

**Issue by smweis** [nipreps/fmriprep#2661]
### What happened?

Running the pre-release 21.0.0rc2 appears to alter the typical directory structure. 

Expected results of fmriprep to appear as: 

`derivatives/fmriprep/sub-`
`derivatives/freesurfer/sub-`

Actual results of fmriprep appear as:

`derivatives/sub-`
`derivatives/sourcedata/freesurfer/sub-`

There's also a .bidsignore file that appears within /derivatives.  

### What command did you use?

```shell
BIDS_dir=/blue/stevenweisberg/share/DSP_fMRI
fmriprep_derivatives_dir=/blue/stevenweisberg/share/DSP_fMRI/derivatives
freesurfer_license_dir=/blue/stevenweisberg/elianyperez/code/fmriprep
singularity_dir=/blue/stevenweisberg/share/DSP_fMRI/code/singularities
work_dir=/blue/stevenweisberg/share/tmp
fmriprep_version=fmriprep-21.0.0rc2.simg

singularity run --cleanenv $singularity_dir/$fmriprep_version $BIDS_dir $fmriprep_derivatives_dir participant --participant-label dspfmri11002 --mem 120000 --output-space T1w MNI152NLin2009cAsym --work-dir $work_dir --fs-license-file $freesurfer_license_dir/freesurfer_license.txt --use-aroma
```

### What version of fMRIPrep are you running?

21.0.0rc2

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by effigies** [comment]
Use `--output-layout legacy` if you want to retrieve the old behavior.

**Comment by smweis** [comment]
Is this the new layout?

**Comment by smweis** [comment]
Sorry. Caught this a few versions back: https://fmriprep.org/en/stable/changes.html
