### ISSUE TITLE
The reversal of the sign of laterality index score as obtained by LI toolbox of SPM

### ISSUE THREAD

**Issue by shilpitju** [nipreps/fmriprep#2662]
The LI scores from laterality index toolbox, for the data preprocessed using SPM, are positive for left side dominance and are negative for right side dominance. 

For fmriprep preprocessed data there is no reference available as such.

We preprocessed a fMRI language dataset with both SPM and fmriprep. The activation map was  clearly left dominant for language (visually) for both the SPM and fMRIPrep preprocessed files. The LI score as obtained from SPM preprocessed data was positive (which is correct). For data preproceseed using fmriprep the LI score was however negative.

Can you please explain the reason behind this sign reversal?

Thanks'
Shilpi

**Comment by effigies** [comment]
I suspect if you provide the inputs to the LI toolbox developers, they will be able to give you an explanation. I don't know of any fMRIPrep contributors that have expertise with that toolbox.

**Comment by shilpitju** [comment]
Sure. Thanks.
