### ISSUE TITLE
Several errors with fmriprep-21.0.0

### ISSUE THREAD

**Issue by pjkohler** [nipreps/fmriprep#2676]
I am getting several errors with fmriprep-21.0.0 on Sherlock, from the generously supplied image by @mgxd:
- functional and anatomical alignment is off, despite images being well-aligned prior to running fMRIprep and using "--bold2t1w-init header". 
- Node Name fmriprep_wf.single_subject_0011_wf.anat_preproc_wf.brain_extraction_wf.mrg_tmpl gives the error "ModuleNotFoundError: No module named 'niworkflows.interfaces.ants'"
- slice-timing correction gives the following error: "[7m** FATAL ERROR:[0m tpattern file slice_timing.1D has 32 values but have 256 slices"
- Slurm appears to terminate execution because time limit is reached: "slurmstepd: error: *** JOB 40542383 ON sh02-10n48 CANCELLED AT 2021-12-18T19:09:42 DUE TO TIME LIMIT ***"

**Comment by effigies** [comment]
Can you fill in the details at: https://github.com/nipreps/fmriprep/issues/new?assignees=&labels=bug&template=bug_report.yml

**Comment by effigies** [comment]
Thanks. Closing in favor of #2677.
