### ISSUE TITLE
Embed SVG images into fMRIprep HTML reports directly

### ISSUE THREAD

**Issue by keithcallenberg** [nipreps/fmriprep#2686]
### What would you like to see added in fMRIPrep?

It would be nice to have an option to embed SVG images into fMRIprep HTML reports as base64 data. It would increase their filesize but make them more portable.

`clpipe` has a script that creates a zip archive of the html report with all of the images. This improves the portability but still requires an unzipping step to view the report. https://clpipe.readthedocs.io/en/latest/fmriprep.html#getting-quality-control-reports

I have modified a script to directly embed the SVG images into the HTML report. I think this script would just need to be made into a function and a command-line option added, assuming we don't want this to be default behavior. The standalone script is available here: https://gist.github.com/keithcallenberg/6a52f526db2a9d3530b2151ec251ffc7

### Do you have any interest in helping implement the feature?

Yes

**Comment by effigies** [comment]
Hi, thanks for this issue. We did previously embed all images, and that led to browser-crashingly large files for many datasets, forcing us to make the default linked images.

I think a generic embedding tool is probably the most future-proof, but I do also see the value in having the option to build self-contained HTML reports without a further step.

As you imagine it, would this replace the current `figures/` directory in the derivatives, or simply be a change in the HTML construction? I would guess that replacing would be a much deeper revision and probably require more maintenance in the long run.

**Comment by keithcallenberg** [comment]
I take this back. I thought this would be low effort, but I realized from @effigies comment and some further investigation that more would be needed. The approach and script I suggested above is fine for displaying static SVGs, but more would need to be done to get them to alternate on hover as they do currently.
