### ISSUE TITLE
3dvolreg fails: base image has 0 nonzero voxels - in 21.0.1 but NOT 20.2

### ISSUE THREAD

**Issue by dmd** [nipreps/fmriprep#2703]
### What happened?

I have a user who was using 20.2.1. They updated to 21.0.1, and are getting 

```
3dvolreg fails: base image has 0 nonzero voxels
```

We've created a minimal case, containing a single anatomical and single functional:

```
$ tree sub-test2101
sub-test2101
├── anat
│   ├── sub-test2101_T1w.json
│   └── sub-test2101_T1w.nii.gz
└── func
    ├── sub-test2101_task-VOCMIXEDPRE_run-01_bold.json
    └── sub-test2101_task-VOCMIXEDPRE_run-01_bold.nii.gz
```

When we run under 21.0.1 it fails. The **same exact data** (we test with a clean workdir, and with the data extracted using the name sub-test2021 instead) succeeds under 20.2.1.

### What command did you use?

```shell
/usr/bin/singularity run \
    --contain \
    --cleanenv \
    -B /tmp -B /data -B /data1 -B /data2 -B /data3 -B /n -B /cm/shared \
    /cm/shared/singularity/images/fmriprep-21.0.1.simg \
    /data/belleau_lab/vers21.0.1/2101 \
    /data/belleau_lab/vers21.0.1/2101/derivatives \
    participant \
    --fs-license-file /cm/shared/freesurfer-6.0.1/license.txt \
    --participant_label 2101 \
    --output-spaces MNI152NLin6Asym:res-2 anat fsaverage \
    --n_cpus 4 \
    --mem-mb 16384 \
    --notrack \
    --use-aroma \
    --use-syn-sdc \
    --return-all-components \
    -vv \
    -w  /data/fmriprep-workdir/ebelleau
```

### What version of fMRIPrep are you running?

21.0.1

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Additional information / screenshots

I have sent a Dropbox link to nipreps@gmail.com containing all of our log output for both versions and our full BIDS directory.

**Comment by dmd** [comment]
Any ideas? Is there any other information we could provide?

**Comment by effigies** [comment]
Sorry, I haven't seen your email. Could you send it to this username @ gmail?

**Comment by dmd** [comment]
Done.

**Comment by effigies** [comment]
@dmd I was unable to reproduce with the following command:

```
fmriprep-docker Downloads/issues/fmriprep-2703/20vs21/vers21.0.1/2101 /data/out/fmriprep-2703 participant \
    -vv -w <workdir> \
    --fs-subjects-dir Downloads/issues/fmriprep-2703/20vs21/vers21.0.1/2101/derivatives/sourcedata/freesurfer/ \
    --output-spaces anat --use-syn-sdc
```

I'm re-running with `--output-spaces MNI152NLin6Asym:res-2 anat fsaverage --use-aroma --return-all-components` added back in to see if that affects things.

Could you post the contents of `fmriprep_wf/single_subject_2101_wf/func_preproc_task_VOCMIXEDPRE_run_01_wf/final_boldref_wf/gen_avg/_report/report.rst` and add the file referenced by `in_file` to Dropbox?

**Comment by effigies** [comment]
Update: I was not able to reproduce this issue with the following command:

```
fmriprep-docker Downloads/issues/fmriprep-2703/20vs21/vers21.0.1/2101 /data/out/fmriprep-2703 participant \
    -w $WORKDIR -vv \
    --fs-subjects-dir Downloads/issues/fmriprep-2703/20vs21/vers21.0.1/2101/derivatives/sourcedata/freesurfer/\
    --mem-mb 10240 --n-cpus 4 \
    --output-spaces MNI152NLin6Asym:res-2 anat fsaverage --use-aroma --return-all-components --use-syn-sdc
```

I don't think I changed any significant parameters, but let me know if you see something.

One thing I noted is that you're using the same working directory in both of your scripts. Is it possible that you're reusing the working a 20.2.x working directory with 21.0.x? In any case, I would try deleting that and restarting.

The final thing that occurs to me is that somehow there could be an issue with your singularity image. Re-building that may produce some change.

**Comment by dmd** [comment]
> One thing I noted is that you're using the same working directory in both of your scripts. Is it possible that you're reusing the working a 20.2.x working directory with 21.0.x? In any case, I would try deleting that and restarting.

I don't think so, because I'm using a different participant name for the 20 run than the 21 run. AFAIK, fmriprep doesn't do any mixing across participants, does it?

I'm rerunning right now to see if it happens again; one of the times I ran it, it **didn't** fail!

**Comment by effigies** [comment]
> AFAIK, fmriprep doesn't do any mixing across participants, does it?

Nope, it shouldn't.

**Comment by dmd** [comment]
Well, %%&*@@, this time it didn't reproduce. I'm going to close this for now and I'll reopen it if we can reproduce it again, and will make sure not to remove the working folder so we have more data to show you.

**Comment by precity** [comment]
I met the same error when using 'singularity' in 21.0.1, while successful when using 'fmriprep-docker' in 20.2. 
Did you successfull finish it in 'singularity'？



> Well, glad it worked. Apologies for the apparent non-determinism.
> 
> One thing you can try to reproduce is `--random-seed 26272`, based on your reported seed:
> 
> ```
> 		[seeds]
> 		master = 26272
> 		ants = 18454
> 		numpy = 24865
> ```
> 
> I can also try when I get a chance.
