### ISSUE TITLE
concat_blips

### ISSUE THREAD

**Issue by juansanchezpena** [nipreps/fmriprep#2706]
### What happened?

I am unable to  produce func results for a data that looks standard.

### What command did you use?

```shell
/usr/local/pipelines/subfmri-arg_latest -i /MRI_DATA/nyspi/test/rawdata -o /MRI_DATA/nyspi/test/derivatives -l  /MRI_DATA/nyspi/test/derivatives/fmriprep/logs/gold.log -a "--participant-label test03gold --output-spaces T1w MNI152NLin2009cAsym:res-2 --cifti-output --output-layout legacy”
```

### What version of fMRIPrep are you running?

21.0

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
Node Name: fmriprep_wf.single_subject_test03gold_wf.fmap_preproc_wf.wf_auto_00000.concat_blips
File: /output/fmriprep/sub-test03gold/log/20220204-140358_cfdc6d40-fc00-456a-9b71-4a44a81323ce/crash-20220204-140521-root-concat_blips-138212d8-935a-4164-a554-5ca62213c680.txt
Working Directory: /tmp/work/fmriprep_wf/single_subject_test03gold_wf/fmap_preproc_wf/wf_auto_00000/concat_blips
Inputs:
allow_4D: True
in_files:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
    runtime = self._run_interface(runtime)
  File "/opt/conda/lib/python3.8/site-packages/niworkflows/interfaces/nibabel.py", line 191, in _run_interface
    img_4d = nb.concat_images(nii_list)
  File "/opt/conda/lib/python3.8/site-packages/nibabel/funcs.py", line 141, in concat_images
    raise ValueError(f'Affine for image {i} does not match affine for first image')
ValueError: Affine for image 2 does not match affine for first image
```

### Additional information / screenshots

RAWDATA:
anat:
sub-test03gold_ses-21117_acq-cubepromo_T2w.json    sub-test03gold_ses-21117_acq-nopromo_T1w.json
sub-test03gold_ses-21117_acq-cubepromo_T2w.nii.gz  sub-test03gold_ses-21117_acq-nopromo_T1w.nii.gz

fmap:
sub-test03gold_ses-21117_dir-fpe_epi.json    sub-test03gold_ses-21117_dir-rpe_epi.json
sub-test03gold_ses-21117_dir-fpe_epi.nii.gz  sub-test03gold_ses-21117_dir-rpe_epi.nii.gz

func:
sub-test03gold_ses-21117_task-rest_run-01_bold.json  sub-test03gold_ses-21117_task-rest_run-01_bold.nii.gz

This same raw data went through abcd

**Comment by reisnerv** [comment]
I obtain an almost identical error about 40% of time when using v21.0.0 or v21.0.1 via Singularity.

**Comment by effigies** [comment]
Could you share the affine matrices of your fieldmap and BOLD files?

**Comment by effigies** [comment]
No affine matrices are present in this data. You can use `fslhd` or `mri_info` or if you have `nibabel` installed in your Python environment: `python -c "import sys; import nibabel as nb; print(nb.load(sys.argv[1]).header)" $FILENAME`.

**Comment by juansanchezpena** [comment]
FMAP:

filename       sub-test03gold_ses-21117_acq-func_dir-fpe_epi.nii.gz



sizeof_hdr     348

data_type      INT16

dim0           4

dim1           90

dim2           90

dim3           60

dim4           2

dim5           1

dim6           1

dim7           1

vox_units      mm

time_units     s

datatype       4

nbyper         2

bitpix         16

pixdim0        0.000000

pixdim1        2.400000

pixdim2        2.400000

pixdim3        2.400000

pixdim4        7.400000

pixdim5        0.000000

pixdim6        0.000000

pixdim7        0.000000

vox_offset     352

cal_max        0.0000

cal_min        0.0000

scl_slope      1.000000

scl_inter      0.000000

phase_dim      2

freq_dim       1

slice_dim      3

slice_name     Unknown

slice_code     0

slice_start    0

slice_end      0

slice_duration 0.000000

time_offset    0.000000

intent         Unknown

intent_code    0

intent_name

intent_p1      0.000000

intent_p2      0.000000

intent_p3      0.000000

qform_name     Scanner Anat

qform_code     1

qto_xyz:1      -2.376758  0.176580  0.282559  88.406891

qto_xyz:2      0.119177  2.351140  -0.466841  -108.382652

qto_xyz:3      0.311154  0.448289  2.337139  -97.876495

qto_xyz:4      0.000000  0.000000  0.000000  1.000000

qform_xorient  Right-to-Left

qform_yorient  Posterior-to-Anterior

qform_zorient  Inferior-to-Superior

sform_name     Scanner Anat

sform_code     1

sto_xyz:1      -2.376759  0.176580  0.282557  88.406891

sto_xyz:2      0.119177  2.351139  -0.466841  -108.382652

sto_xyz:3      0.311152  0.448289  2.337139  -97.876495

sto_xyz:4      0.000000  0.000000  0.000000  1.000000

sform_xorient  Right-to-Left

sform_yorient  Posterior-to-Anterior

sform_zorient  Inferior-to-Superior

file_type      NIFTI-1+

file_code      1

descrip        TE=80;Time=153835.000

aux_file

FUNC

filename       sub-test03gold_ses-21117_task-rest_run-01_bold.nii.gz



sizeof_hdr     348

data_type      INT16

dim0           4

dim1           90

dim2           90

dim3           60

dim4           525

dim5           1

dim6           1

dim7           1

vox_units      mm

time_units     s

datatype       4

nbyper         2

bitpix         16

pixdim0        0.000000

pixdim1        2.400000

pixdim2        2.400000

pixdim3        2.400000

pixdim4        0.800000

pixdim5        0.000000

pixdim6        0.000000

pixdim7        0.000000

vox_offset     352

cal_max        0.0000

cal_min        0.0000

scl_slope      1.000000

scl_inter      0.000000

phase_dim      2

freq_dim       1

slice_dim      3

slice_name     Unknown

slice_code     0

slice_start    0

slice_end      0

slice_duration 0.000000

time_offset    0.000000

intent         Unknown

intent_code    0

intent_name

intent_p1      0.000000

intent_p2      0.000000

intent_p3      0.000000

qform_name     Scanner Anat

qform_code     1

qto_xyz:1      -2.376759  0.176580  0.282555  88.406898

qto_xyz:2      0.119177  2.351140  -0.466841  -108.382652

qto_xyz:3      0.311150  0.448289  2.337140  -97.876450

qto_xyz:4      0.000000  0.000000  0.000000  1.000000

qform_xorient  Right-to-Left

qform_yorient  Posterior-to-Anterior

qform_zorient  Inferior-to-Superior

sform_name     Scanner Anat

sform_code     1

sto_xyz:1      -2.376759  0.176580  0.282557  88.406898

sto_xyz:2      0.119177  2.351139  -0.466841  -108.382652

sto_xyz:3      0.311152  0.448289  2.337139  -97.876450

sto_xyz:4      0.000000  0.000000  0.000000  1.000000

sform_xorient  Right-to-Left

sform_yorient  Posterior-to-Anterior

sform_zorient  Inferior-to-Superior

file_type      NIFTI-1+

file_code      1

descrip        TE=30;Time=154026.000;mb=6

aux_file

From: Chris Markiewicz ***@***.***>
Date: Tuesday, February 8, 2022 at 11:11 AM
To: nipreps/fmriprep ***@***.***>
Cc: Sanchez, Juan (NYSPI) ***@***.***>, Author ***@***.***>
Subject: Re: [nipreps/fmriprep] concat_blips (Issue #2706)

ATTENTION: This email came from an external source. Do not open attachments or click on links from unknown senders or unexpected emails.


No affine matrices are present in this data. You can use fslhd or mri_info or if you have nibabel installed in your Python environment: python -c "import sys; import nibabel as nb; print(nb.load(sys.argv[1]).header)" $FILENAME.

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnipreps%2Ffmriprep%2Fissues%2F2706%23issuecomment-1032793445&data=04%7C01%7CJuan.Sanchez%40nyspi.columbia.edu%7Ccb145a34f0ce4a8b6df108d9eb1d9c29%7Cf46cb8ea79004d108ceb80e8c1c81ee7%7C0%7C0%7C637799334671396023%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2Fj9qSOhe3e90ex9Q1xXJOLD6POR%2FxTzk6q9ftAFIt4M%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARKALFECDG5CDF3JGO46WATU2E6BTANCNFSM5NX5HWWQ&data=04%7C01%7CJuan.Sanchez%40nyspi.columbia.edu%7Ccb145a34f0ce4a8b6df108d9eb1d9c29%7Cf46cb8ea79004d108ceb80e8c1c81ee7%7C0%7C0%7C637799334671396023%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pfPjyVlkCsBUfbaV33scgDDlNZCWZsQTd1D0W19TJhs%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CJuan.Sanchez%40nyspi.columbia.edu%7Ccb145a34f0ce4a8b6df108d9eb1d9c29%7Cf46cb8ea79004d108ceb80e8c1c81ee7%7C0%7C0%7C637799334671396023%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0eqj48Q9a2bkEEQZKF3PYl0CueixEAww%2FmUB5F%2BP14s%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CJuan.Sanchez%40nyspi.columbia.edu%7Ccb145a34f0ce4a8b6df108d9eb1d9c29%7Cf46cb8ea79004d108ceb80e8c1c81ee7%7C0%7C0%7C637799334671396023%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=69CxWd%2F4nEALIEDIQN2QfLnhS6dljyR8Dx8AfjT0IeU%3D&reserved=0>.

**Comment by effigies** [comment]
It looks like there are some differences in your sforms, but they are close enough that we should probably relax our constraint.

**Comment by julfou81** [comment]
Hi I notice a similar error on a dataset where there was a tiny difference (in the fifth decimal in one component of the affine matrix!) between the two affines for the two `_epi` files  used to perform `topup`.

For now, the workaround I used was to use `fslcpgeom` to copy the affine of one file to the other and fmriprep v21.0.1 was able to run correctly after this modification.

**Comment by MarcoB-MD** [comment]
So what is the current work-around to run fMRIprep 21.0.1 with very slight differences in the affine matrix of images ?

**Comment by mgxd** [comment]
@MarcoB-MD we just released `21.0.2` which allows for slight differences between the affine matrix of your fmaps. Give that version a try and let us know if it fixes the problem!

**Comment by MarcoB-MD** [comment]
@mgxd Thanks Mathias - 21.0.2 seems to be working fine now.

**Comment by cmpetty** [comment]
i just ran into this same issue in v22.0.0 .. the same data ran in 21.0.2 without the concat_blips error.

```
In [10]: run1.affine
Out[10]: 
array([[ -2.        ,   0.        ,   0.        , 126.12599945],
       [  0.        ,  -1.99296677,   0.16758209, 163.897995  ],
       [  0.        ,   0.16758142,   1.9929657 , -53.04059982],
       [  0.        ,   0.        ,   0.        ,   1.        ]])

In [11]: pe1.affine
Out[11]: 
array([[ -2.        ,   0.        ,   0.        , 126.12599945],
       [  0.        ,  -1.99296665,   0.16758209, 163.897995  ],
       [  0.        ,   0.16758208,   1.9929657 , -53.04059982],
       [  0.        ,   0.        ,   0.        ,   1.        ]])

In [12]: pe1.affine == run1.affine
Out[12]: 
array([[ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [14]: pe1.affine == pe2.affine
Out[14]: 
array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])


```



```
Inputs:
affine_tolerance:
allow_4D: True
in_files:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node concat_blips.

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 398, in run
    runtime = self._run_interface(runtime)
  File "/opt/conda/lib/python3.9/site-packages/niworkflows/interfaces/nibabel.py", line 227, in _run_interface
    img_4d = nb.concat_images(
  File "/opt/conda/lib/python3.9/site-packages/nibabel/funcs.py", line 141, in concat_images
    raise ValueError(f'Affine for image {i} does not match affine for first image')
ValueError: Affine for image 1 does not match affine for first image
```

**Comment by smazurchuk** [comment]
Just adding a +1 to above comment

I upgraded from 20.1.0 to 22.0.0 and there are several participants who ran without error in the earlier version who are now giving the same error as above in the most recent version

**Comment by effigies** [comment]
Hi, please open a new issue. In general, comments on closed issues will not be as visible to us.

**Comment by cmpetty** [comment]
> Just adding a +1 to above comment
> 
> I upgraded from 20.1.0 to 22.0.0 and there are several participants who ran without error in the earlier version who are now giving the same error as above in the most recent version.
> 
> @cmpetty did you figure out any approach to deal with this, or plan to re-open the issue?

@smazurchuk 

I edited site-packages/niworkflows/interfaces/nibabel.py to include the fix from here, which seemed to be missing in v22.0.0: [https://github.com/nipreps/niworkflows/pull/706](url)

```

227         #img_4d = nb.concat_images(
228         #    nii_list,
229         #    check_affines=not bool(self.inputs.affine_tolerance)
230         #)
231         img_4d = nb.concat_images(nii_list, check_affines=False)
```
