### ISSUE TITLE
fmriprep 21.0.1 hangs at surface recon step when lesion mask is included in anat folder

### ISSUE THREAD

**Issue by akelkar26** [nipreps/fmriprep#2707]
### What happened?

I have stroke data I am working with. Adding the lesion mask to the anat folder for better normalization and adding it to .bidsignore, fmriprep starts successfully but hangs at the surface recon step. I have to kill the docker after 40 hours. 
If I don't use the lesion mask, fmriprep runs successfully in 8 hours. However, I am not too confident of the normalization even though it looks kind of okay in the html file. I would like the better registration with the lesion mask in the anat folder.
[fmriprep_addlesionTMSA02errorlog.txt](https://github.com/nipreps/fmriprep/files/8024919/fmriprep_addlesionTMSA02errorlog.txt)
 

### What command did you use?

```shell
screen docker run -ti \                     
    -v /Users/neurouser1/Documents/TMS_Aphasia/bids_directory/:/data \
    -v /Users/neurouser1/Documents/TMS_Aphasia/xcp/fmriprepout_again/:/out \
    -v /Users/neurouser1/Documents/fs_files/:/license \
    -v /Users/neurouser1/Documents/TMS_Aphasia/scratch:/scratch \
    nipreps/fmriprep:21.0.1 \
    /data/ \
    /out/ \
    participant \
    --output-spaces fsaverage T1w MNI152NLin6Asym MNI152NLin2009cAsym \
    --cifti-output 91k \
    --participant_label sub-TMSA02 \
    --fs-license-file /license/license.txt \
    --n_cpus 12 \
    --omp-nthreads 8 \
    --mem 150GB \
    --work-dir /scratch \
    --resource-monitor
```

### What version of fMRIPrep are you running?

21.0.1

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
[Node] Setting-up "_fix_surfs7" in "/scratch/fmriprep_wf/single_subject_TMSA02_wf/anat_preproc_wf/surface_recon_wf/gifti_surface_wf/fix_surfs/mapflow/_fix_surfs7".
220131-07:19:01,307 nipype.workflow INFO:
	 [Node] Cached "_fix_surfs7" - collecting precomputed outputs
220131-07:19:01,307 nipype.workflow INFO:
	 [Node] "_fix_surfs7" found cached.
220131-07:19:01,317 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_TMSA02_wf.anat_preproc_wf.surface_recon_wf.gifti_surface_wf.fix_surfs".
```

**Comment by akelkar26** [comment]
Thank you so much for the input. I will let you know if I find anything and add it to the enhancement tag.

**Comment by 276562578** [comment]
Same question, What should I do while using `fmriprep`? Sorry, I'm a newbie in MRI processing and can't understand the how to fix it.
