### ISSUE TITLE
raise RuntimeError("Custom template %s requires a `tpl-` prefix" % tpl)

### ISSUE THREAD

**Issue by lollopasquini** [nipreps/fmriprep#2709]
### What happened?

Hello,
I am using fmriprep-docker to preprocess one subject into a 3mm template we built.

I am getting the following error:
raise RuntimeError("Custom template %s requires a `tpl-` prefix" % tpl)

I am unclear what is  happening. I have templateflow directory, within this directory a template folder starting with tpl, the files within also start with tpl and have a json file.

### What command did you use?

```shell
fmriprep-docker /path1/test /path1/der_test --participant-label 2 --fs-license-file /pathfreesurfer/license.txt --output-spaces MNI152NLin2009cAsym3mm:res-01
```

### What version of fMRIPrep are you running?

 21.0.1

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

FreeSurfer

### Please copy and paste any relevant log output.

```shell
Traceback (most recent call last):
  File "/Users/xxx/.local/bin/fmriprep-docker", line 8, in <module>
    sys.exit(main())
  File "/Users/xxx/.local/lib/python3.8/site-packages/fmriprep_docker.py", line 522, in main
    raise RuntimeError("Custom template %s requires a `tpl-` prefix" % tpl)
RuntimeError: Custom template MNI152NLin2009cAsym3mm:res-01 requires a `tpl-` prefix
```

**Comment by effigies** [comment]
Did you try `--output-spaces tpl-MNI152NLin2009cAsym3mm:res-01`?

**Comment by lollopasquini** [comment]
thanks. yes, then I get the error docker: Error response from daemon: invalid volume specification: '/Users/xxx/.templateflow/tpl-MNI152NLin2009cAsym3mm:res-01:/home/fmriprep/.cache/templateflow/tpl-MNI152NLin2009cAsym3mm:res-01:ro'.

**Comment by effigies** [comment]
Okay, so that's going to be a bug in how we're mapping these in. Do you get a `RUNNING:` line? We can edit that to give you something that will work until the bug is fixed.

**Comment by lollopasquini** [comment]
The weird thing is that if I use  --output-spaces tpl-MNI152NLin2009cAsym:res-02 the code works. It is specifically related to the template I added. I can run the code from the 3mm tpl-folder by adding tpl-MNI152NLin2009cAsym3mm, but the data does not get resliced to 3mm at the end. It keeps the native space dimensions

**Comment by lollopasquini** [comment]
Just saw this, I do not get a running line

**Comment by effigies** [comment]
What is the full output when you run your `fmriprep-docker` command?

**Comment by lollopasquini** [comment]
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=20.10.12 -it -v /Users/lorenzopasquini/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v /Users/lorenzopasquini/Desktop/Ayahuasca_acute_Natal/test:/data:ro -v /Users/lorenzopasquini/Desktop/Ayahuasca_acute_Natal/der_test:/out -v /Users/lorenzopasquini/.templateflow/tpl-MNI152NLin2009cAsym3mm/tpl-MNI152NLin2009cAsym3mm:res-01:/home/fmriprep/.cache/templateflow/tpl-MNI152NLin2009cAsym3mm:res-01:ro nipreps/fmriprep:21.0.1 /data /out participant --participant-label 2 --output-spaces MNI152NLin2009cAsym3mm:res-01
docker: Error response from daemon: invalid volume specification: '/Users/lorenzopasquini/.templateflow/tpl-MNI152NLin2009cAsym3mm/tpl-MNI152NLin2009cAsym3mm:res-01:/home/fmriprep/.cache/templateflow/tpl-MNI152NLin2009cAsym3mm:res-01:ro'.
See 'docker run --help'.
fMRIPrep: Please report errors to https://github.com/nipreps/fmriprep/issues

**Comment by effigies** [comment]
Okay, so here's your "RUNNING" line:

```
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=20.10.12 -it -v /Users/lorenzopasquini/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v /Users/lorenzopasquini/Desktop/Ayahuasca_acute_Natal/test:/data:ro -v /Users/lorenzopasquini/Desktop/Ayahuasca_acute_Natal/der_test:/out -v /Users/lorenzopasquini/.templateflow/tpl-MNI152NLin2009cAsym3mm/tpl-MNI152NLin2009cAsym3mm:res-01:/home/fmriprep/.cache/templateflow/tpl-MNI152NLin2009cAsym3mm:res-01:ro nipreps/fmriprep:21.0.1 /data /out participant --participant-label 2 --output-spaces MNI152NLin2009cAsym3mm:res-01
```

So we just edit this:

```
docker run --rm -e DOCKER_VERSION_8395080871=20.10.12 -it \
    -v /Users/lorenzopasquini/freesurfer/license.txt:/opt/freesurfer/license.txt:ro \
    -v /Users/lorenzopasquini/Desktop/Ayahuasca_acute_Natal/test:/data:ro \
    -v /Users/lorenzopasquini/Desktop/Ayahuasca_acute_Natal/der_test:/out \
    -v /Users/lorenzopasquini/.templateflow/tpl-MNI152NLin2009cAsym3mm/tpl-MNI152NLin2009cAsym3mm:/home/fmriprep/.cache/templateflow/tpl-MNI152NLin2009cAsym3mm:ro \
    nipreps/fmriprep:21.0.1 /data /out participant --participant-label 2 \
    --output-spaces MNI152NLin2009cAsym3mm:res-01
```

**Comment by lollopasquini** [comment]
I just do copy and paste? then I get the error : ValueError: space identifier "MNI152NLin2009cAsym3mm" is invalid.

**Comment by effigies** [comment]
Updated the line. Try again?

**Comment by lollopasquini** [comment]
fmriprep started! thank you so much! Do you have two sec to explain me the error?

**Comment by lollopasquini** [comment]
Thanks again for your help!

**Comment by effigies** [comment]
The error is just that when we have a bad mapping from the custom template into the docker image, we don't strip off the parameters like resolution. So I changed:

```diff
- -v /Users/lorenzopasquini/.templateflow/tpl-MNI152NLin2009cAsym3mm/tpl-MNI152NLin2009cAsym3mm:res-01:/home/fmriprep/.cache/templateflow/tpl-MNI152NLin2009cAsym3mm:res-01:ro
+ -v /Users/lorenzopasquini/.templateflow/tpl-MNI152NLin2009cAsym3mm:/home/fmriprep/.cache/templateflow/tpl-MNI152NLin2009cAsym3mm:ro \
```
