### ISSUE TITLE
fmriprep: error: argument --mem/--mem_mb/--mem-mb: invalid _to_gb value: 'echo'

### ISSUE THREAD

**Issue by JanaHermans** [nipreps/fmriprep#2713]
### What happened?

Hi, when trying to go through the fMRIPrep tutorial from https://andysbrainbook.readthedocs.io/en/latest/OpenScience/OS/fMRIPrep.html, I ran into an issue when running the actual script. The error message I got was `fmriprep: error: argument --mem/--mem_mb/--mem-mb: invalid _to_gb value: 'echo'`.

### What command did you use?

```shell
source $HOME/rds/hpc-work/BIDS_tutorial/code/fmriprep.sh
```

### What version of fMRIPrep are you running?

Version 20.2.0

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
fmriprep: error: argument --mem/--mem_mb/--mem-mb: invalid _to_gb value: 'echo'
```

**Comment by JanaHermans** [comment]
Script from fMRIPrep tutorial (https://andysbrainbook.readthedocs.io/en/latest/OpenScience/OS/fMRIPrep.html):

`#!/bin/bash

#User inputs:
bids_root_dir=$HOME/BIDS_tutorial
subj=01
nthreads=4
mem=20 #gb
container=docker #docker or singularity

#Begin:

#Convert virtual memory from gb to mb
mem=`echo "${mem//[!0-9]/}"` #remove gb at end
mem_mb=`echo $(((mem*1000)-5000))` #reduce some memory for buffer space during pre-processing

export TEMPLATEFLOW_HOME=$HOME/.cache/templateflow
export FS_LICENSE=$HOME/BIDS_tutorial/derivatives/license.txt

#Run fmriprep
if [ $container == singularity ]; then
  unset PYTHONPATH; singularity run -B $HOME/.cache/templateflow:/opt/templateflow $HOME/fmriprep.simg \
    $bids_root_dir $bids_root_dir/derivatives \
    participant \
    --participant-label $subj \
    --skip-bids-validation \
    --md-only-boilerplate \
    --fs-license-file $FREESURFER_HOME/license.txt \
    --fs-no-reconall \
    --output-spaces MNI152NLin2009cAsym:res-2 \
    --nthreads $nthreads \
    --stop-on-first-crash \
    --mem_mb $mem_mb \
    -w $HOME
else
  fmriprep-docker $bids_root_dir $bids_root_dir/derivatives \
    participant \
    --participant-label $subj \
    --skip-bids-validation \
    --md-only-boilerplate \
    --fs-license-file $HOME/BIDS_tutorial/derivatives/license.txt \
    --fs-no-reconall \
    --output-spaces MNI152NLin2009cAsym:res-2 \
    --nthreads $nthreads \
    --stop-on-first-crash \
    --mem_mb $mem_mb \
    -w $HOME
fi`

**Comment by effigies** [comment]
So what's happening is that `--mem_mb $mem_mb` is being rendered as `--mem_mb echo [...]`, which seems like it might derive from this line not executing correctly:

```Bash
mem_mb=`echo $(((mem*1000)-5000))` #reduce some memory for buffer space during pre-processing
```

It may be that you're using a shell other than bash, or your bash configuration has backticks disabled. You can always replace backticks with `$()`, so:

```Bash
mem=$(echo "${mem//[!0-9]/}") #remove gb at end
mem_mb=$(echo $(((mem*1000)-5000))) #reduce some memory for buffer space during pre-processing
```

**Comment by JanaHermans** [comment]
This solved it, thank you very much!
