### ISSUE TITLE
21.0.1 stuck changing data types

### ISSUE THREAD

**Issue by sitek** [nipreps/fmriprep#2725]
### What happened?

Similar to #2652,  processing stuck for multiple days:

```
220228-11:18:01,591 nipype.workflow INFO:
	 [Node] Running "save_midthickness" ("nipype.interfaces.io.DataSink")
220228-11:18:02,10 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_FLT01_wf.anat_preproc_wf.surface_recon_wf.gifti_surface_wf.save_midthickness".
220228-11:18:49,404 nipype.interface WARNING:
	 Changing /{filepath}/derivatives/fmriprep/sub-FLT01/anat/sub-FLT01_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz dtype from float64 to uint8
220228-11:18:52,346 nipype.interface WARNING:
	 Changing /{filepath}/derivatives/fmriprep/sub-FLT01/anat/sub-FLT01_space-MNI152NLin2009cAsym_dseg.nii.gz dtype from float64 to int16
```

### What command did you use?

```shell
singularity run --cleanenv -B /bgfs:/bgfs $sing_img \
  $data_dir $out_dir participant \
  --participant-label $sub \
  --fs-license-file $fs_license \
  --skip_bids_validation \
  --debug all \
  --nprocs $nprocs \
  --output-spaces T1w func fsnative MNI152NLin2009cAsym
```

### What version of fMRIPrep are you running?

21.0.1

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

Work directory

**Comment by effigies** [comment]
Are you able to look at the running processes (e.g., with htop) to see what is hanging? Also can you run with -vv to get more nipype debug info? Also, --debug is not intended for end user use. It is almost certainly not doing something you want.

**Comment by sitek** [comment]
Thanks @effigies and @mgxd – delayed response as I've slowly been rerunning things (kept hitting SLURM time limits; also, I thought it could be a SLURM memory issue [similar to #2623] so I used `--mem` to restrict the amount of memory `fmriprep` is aware of, but it's in MB, not GB, so it hung on `topup` for a while -_- ).
Re: FreeSurfer: This is a new dataset so I'm rerunning everything fresh, so I expect it to take a little bit. I'm starting it again with correct memory allocation and clean work/out directories, so I'll update you on how things go.

**Comment by sitek** [comment]
Update: stuck on `topup` for the last four days (running for 93 hours per htop). 

FreeSurfer appears to be finished – here's the latest fmriprep update (as of 03-18 at 10:40am):
> 220316-04:14:22,798 nipype.workflow INFO:
         [MultiProc] Running 1 tasks, and 0 jobs ready. Free memory (GB): 99.80/100.00, Free processors: 7/8.
                     Currently running:
                       * fmriprep_wf.single_subject_FLT01_wf.fmap_preproc_wf.wf_auto_00000.topup

currently running command:
> topup --config=/opt/conda/lib/python3.8/site-packages/sdcflows/data/flirtsch/b02b0.cnf --datain=/{workdir}/fmriprep_2022.03.14/fmriprep_wf/single_subject_FLT01_wf/fmap_preproc_wf/wf_auto_00000/topup/sub-FLT01_dir-AP_magnitude_run-1_epi_idx-000_merged_encfile.txt --imain=/{workdir}/fmriprep_2022.03.14/fmriprep_wf/single_subject_FLT01_wf/fmap_preproc_wf/wf_auto_00000/concat_blips/sub-FLT01_dir-AP_magnitude_run-1_epi_idx-000_merged.nii.gz --out=sub-FLT01_dir-AP_magnitude_run-1_epi_idx-000_merged_base --iout=sub-FLT01_dir-AP_magnitude_run-1_epi_idx-000_merged_corrected.nii.gz --fout=sub-FLT01_dir-AP_magnitude_run-1_epi_idx-000_merged_field.nii.gz --jacout=jac --logout=sub-FLT01_dir-AP_magnitude_run-1_epi_idx-000_merged_topup.log --rbmout=xfm --dfout=warpfield

I have 6 BOLD runs, each with an EPI field map pair (assigned to the `*_bold.nii.gz` and `*_sbref.nii.gz` for each run in the `IntendedFor` json field).`topup` appears to still be working on the first pair.

**Comment by effigies** [comment]
Very likely to be too many volumes in `fmriprep_wf/single_subject_FLT01_wf/fmap_preproc_wf/wf_auto_00000/concat_blips/sub-FLT01_dir-AP_magnitude_run-1_epi_idx-000_merged.nii.gz`. What's your full file listing and `IntendedFor`/`B0Field*` metadata?

**Comment by sitek** [comment]
> Very likely to be too many volumes in `fmriprep_wf/single_subject_FLT01_wf/fmap_preproc_wf/wf_auto_00000/concat_blips/sub-FLT01_dir-AP_magnitude_run-1_epi_idx-000_merged.nii.gz`.

Yep, you were right – I had unused field map files stored in a subdirectory that I had included in my `.bidsignore` file, assuming `fmriprep` would ignore them (which it doesn't). After removing those files from the bids directory tree, `fmrirpep` (sans freesurfer) with 6 pairs of PE EPI images took 8 hours to run.
