### ISSUE TITLE
RFC: Assessing ME-EPI with carpetplot - what would you like to see?

### ISSUE THREAD

**Issue by oesteban** [nipreps/fmriprep#2734]
The carpetplot has been refactored to make assessment easier and the plot itself clearer, more useful, and more self-explanatory (i.e., legend added, sorting of rows *a la* Aquino et al., added the "crown" or brain-edge mask).

However, it is unclear to me what researcher who uses to work with ME-EPI would find helpful to see. Let's say we have BOLD series with 4 echos. What do you think it would be best to have?

- One carpetplot per echo (i.e., four carpetplots for each run and task in your fMRIPrep report)
- One carpetplot only, showing the optimally combined T2* series
- One carpetplot only, showing the echo closest to the standard TE of SE-EPI
- One carpetplot only, showing one echo selected in some other way than the immediately above.
- Something not listed above.

I'm trying to strike a good balance between rendering something useful without extending the report with many plots. There is an antecedent in #1135, although I think we (or I) assumed at the time that only one carpetplot with the T2* combination would work out.

WDYT? @tsalo @emdupre @handwerkerd @dowdlelt @eilidhmacnicol

**Comment by tsalo** [comment]
I think the optimally combined series is the most useful, although if having two wouldn't be too many, then maybe the closest echo to the standard TE would be good to have as well, for QC of the optimal combination.

**Comment by marcelzwiers** [comment]
I always wondered at what stage of pre-processing the carpetplots are made? I suppose right after realignment or?

**Comment by oesteban** [comment]
That depends on what you'd like to see. I think the original Power paper
showed before and after realignment.

fMRIPrep builds them after realignment. However, there have been plans to
create a visualization tool with a scroll that allows seeing before and
after together.

For MRIQC and such you probably always want before realignment.

**Comment by eilidhmacnicol** [comment]
I agree with @tsalo - it would be useful to be able to assess the optimal combination and it seems to me that the echo closest to a field-dependent TE would be most useful for that. However, if only choosing one, I would prefer the optimal combination.

**Comment by handwerkerd** [comment]
I'm not particularly fond of carpet plots, but I also agree. The weighted combination of the echoes is the most likely to be useful.

**Comment by dowdlelt** [comment]
Another agreement here - opt com makes the most sense to look at - reduced thermal noise contribution from the multiple echoes means that any structure in the carpet plot should show up even more vs any single echo. And if more than one is available, then comparing to typical TE should show that benefit as well (in theory, if they have the same sorting based on the opt com).

**Comment by tsalo** [comment]
I think the current report (T2* histogram and optcom carpet plot) is pretty solid. Can this issue be closed?
