### ISSUE TITLE
Don't we want to test the ``--cifti-output`` integration?

### ISSUE THREAD

**Issue by oesteban** [nipreps/fmriprep#2735]
Since this 8421f89701d2f474d788e3f24d695f5393c4a9bb, ds005 is run without ``--cifti-output``. We probably want to take it back, right? /cc @effigies

**Comment by effigies** [comment]
I thought we only removed it in the rerun test.

**Comment by oesteban** [comment]
I haven't looked in depth but I don't think it's in the config file at all.

I spotted it because the report doesn't have anything about CIFTI
