### ISSUE TITLE
WORK_DIR -w output empty

### ISSUE THREAD

**Issue by juansanchezpena** [nipreps/fmriprep#2749]
### What happened?

I am trying to get the native space cifti data from fmriprep so that I can determine if the sulcal artifact in the 91k dtseries is present in the native surface. Per our lane1 conversation I have been trying to use the -w flag to obtain these data as output, however the wordir remains empty even though it is written to in the logs.
Thanks

### What command did you use?

```shell
/usr/local/pipelines/subfmri-arg_latest -i /MRI_DATA/nyspi/patensasc/rawdata -o /MRI_DATA/nyspi/patensasc/derivatives -l /MRI_DATA/nyspi/patensasc/derivatives/fmripreplogs/working.log -a "--participant-label patensasc0085 --output-spaces T1w MNI152NLin2009cAsym:res-2 --cifti-output -w  /MRI_DATA/nyspi/patensasc/derivatives/fmriprep/WORK_DIR "
```

### What version of fMRIPrep are you running?

nipreps/fmriprep:21.0.0

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
fMRIPrep finished successfully!
```

**Comment by mgxd** [comment]
This looks like you are using a third-party wrapper (`/usr/local/pipelines/subfmri-arg_latest`) to run fmriprep - I would guess there is flag to pass in a working directory but you should reach out to whoever manages that

**Comment by juansanchezpena** [comment]
We had to mount locally! Thanks so much Mathias
