### ISSUE TITLE
fMRIprep 21.0.1 fatal error : kernel too old

### ISSUE THREAD

**Issue by oliver-xie** [nipreps/fmriprep#2763]
### What would you like to see added in fMRIPrep?

Hello! I compiled the latest fmriprep singularity (v21.0.1) on our HPC cluster and it succeeded without error. However, when I tried to run it, I encountered an error message of "FATAL: kernel too old". Our cluster uses Red Hat Enterprise Linux Server release 6.10 (Santiago) with the kernel version of 2.6.32-754.35.1.el6.x86_64. Moreover, a slightly older version v20.2.5 works just fine. I wonder if it is possible for fMRIprep to continue supporting lower versions of Linux system/kernel.
Thank you! 

### Do you have any interest in helping implement the feature?

No

**Comment by mgxd** [comment]
After the LTS series (20.2.x), we decided to upgrade the base of Docker image to Ubuntu 20.04 LTS, which facilitates staying up to date with our dependencies. Unfortunately, it would require significant effort to continue supporting older kernel versions - my recommendation would be to either:
- Continue using the LTS, which is still being supported (for more info, see: https://www.nipreps.org/devs/releases/#long-term-support-series)
- Upgrade your OS / kernel

**Comment by oliver-xie** [comment]
> After the LTS series (20.2.x), we decided to upgrade the base of Docker image to Ubuntu 20.04 LTS, which facilitates staying up to date with our dependencies. Unfortunately, it would require significant effort to continue supporting older kernel versions - my recommendation would be to either:
> 
> * Continue using the LTS, which is still being supported (for more info, see: https://www.nipreps.org/devs/releases/#long-term-support-series)
> * Upgrade your OS / kernel

Thank you for your clarification!
