### ISSUE TITLE
 ModuleNotFoundError: No module named 'niworkflows.interfaces.ants'

### ISSUE THREAD

**Issue by dhyangcheng** [nipreps/fmriprep#2775]
### What happened?

220507-07:57:10,513 nipype.workflow IMPORTANT:
         fMRIPrep started!
Downloading https://templateflow.s3.amazonaws.com/tpl-MNI152NLin6Asym/tpl-MNI152NLin6Asym_res-01_T1w.nii.gz
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11.0M/11.0M [00:22<00:00, 486kB/s]
Downloading https://templateflow.s3.amazonaws.com/tpl-MNI152NLin6Asym/tpl-MNI152NLin6Asym_res-01_desc-brain_mask.nii.gz
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150k/150k [00:00<00:00, 189kB/s]
Downloading https://templateflow.s3.amazonaws.com/tpl-MNI152NLin6Asym/tpl-MNI152NLin6Asym_res-02_T1w.nii.gz
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.41M/1.41M [00:04<00:00, 345kB/s]
220507-07:58:37,362 nipype.utils WARNING:
         No metadata was found in the pkl file. Make sure you are currently using the same Nipype version from the generated pkl.
220507-07:58:37,635 nipype.workflow WARNING:
         Error while checking node hash, forcing re-run. Although this error may not prevent the workflow from running, it could indicate a major problem. Please report a new issue at https://github.com/nipy/nipype/issues adding the following information:

        Node: fmriprep_wf.single_subject_01_wf.anat_preproc_wf.brain_extraction_wf.mrg_tmpl
        Interface: nipype.interfaces.utility.base.Merge
        Traceback:
Traceback (most recent call last):

  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 347, in _local_hash_check
    cached, updated = self.procs[jobid].is_cached()

  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 332, in is_cached
    hashed_inputs, hashvalue = self._get_hashval()

  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 538, in _get_hashval
    self._get_inputs()

  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 580, in _get_inputs
    outputs = _load_resultfile(results_fname).outputs

  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/utils.py", line 293, in load_resultfile
    result = loadpkl(results_file)

  File "/opt/conda/lib/python3.8/site-packages/nipype/utils/filemanip.py", line 666, in loadpkl
    raise e

  File "/opt/conda/lib/python3.8/site-packages/nipype/utils/filemanip.py", line 643, in loadpkl
    unpkl = pickle.loads(pkl_contents)

ModuleNotFoundError: No module named 'niworkflows.interfaces.ants'

### What command did you use?

```shell
singularity  run --cleanenv fmriprep.21.0.1.simg /public/home/zzufah01/pdtest/test2 /public/home/zzufah01/pdtest/test participant --participant-label 01 --fs-license-file /public/home/zzufah01/pdtest/license.txt --skip_bids_validation  --use-aroma --ignore fieldmaps --write-graph
```

### What version of fMRIPrep are you running?

fmriprep.21.0.1

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by dhyangcheng** [comment]
> This looks like a case of a stale working directory - can you try rerunning with a fresh one?

Yes, I have tried, but the same error still occurs.

**Comment by effigies** [comment]
Please reopen if this is still an issue in 23.2.0a1.
