### ISSUE TITLE
Incorrect/dark functional images after SDC with SyN

### ISSUE THREAD

**Issue by alexsayal** [nipreps/fmriprep#2777]
### What happened?

I am testing version 21.0.2 on an fMRI dataset for which fieldmaps were not acquired. As such, I am using the SyN method to attempt susceptibility distortion correction. However, I am getting strange results, inconsistent across subjects. I provide two examples.

1. [sub-01] The SDC estimation includes a considerable translation to match the functional and the anatomical images, which results in this estimated fieldmap

![sub-01_fmapid-auto00000_desc-anat_fieldmap](https://user-images.githubusercontent.com/9429033/167824918-6c1d6d43-147b-48ea-9b0f-8b7db1a16674.png)

and corrected image:

![sub-01_task-control_run-1_desc-sdc_bold](https://user-images.githubusercontent.com/9429033/167824960-d81fc002-1a16-47af-bd6e-0bb695c3571b.png)

I see no problems in the func to T1w or T1w to MNI registrations.

2. [sub-04] The estimated fieldmap seems more reasonable

![sub-04_fmapid-auto00000_desc-anat_fieldmap](https://user-images.githubusercontent.com/9429033/167825001-9b69b2f1-8529-486f-b250-3b19f7e6c5ae.png)

but the corrected image is mostly dark 

![sub-04_task-control_run-1_desc-sdc_bold](https://user-images.githubusercontent.com/9429033/167825031-45a34a78-f44c-428f-ac01-fd7d3f40305a.png)

I have tested fmriPrep on the same dataset without the SyN correction and all seems fine.

### What command did you use?

```shell
docker run -ti --rm \
    -v /SCRATCH/users/alexandresayal/BIDS-VP-HYSTERESIS:/data:ro \
    -v /SCRATCH/users/alexandresayal/BIDS-VP-HYSTERESIS/derivatives:/out \
    -v /SCRATCH/users/alexandresayal/fmriprep-workdir-hyst:/work \
    -v /SCRATCH/software/freesurfer/license.txt:/license \
    nipreps/fmriprep:21.0.2 \
    /data /out/fmriprep \
    participant \
    -w /work \
    --fs-license-file /license \
    --use-syn-sdc \
    --nprocs 10 \
    --mem-mb 35000 \
    --stop-on-first-crash \
    --fs-no-reconall \
    --output-spaces MNI152NLin2009cAsym \
    --participant-label 04
```

### What version of fMRIPrep are you running?

21.0.2

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
No errors to report in either case.
```

### Additional information / screenshots

I share the .svg images also in this Gdrive folder https://drive.google.com/drive/folders/1RcC4568D6_04gqNGFGp-j4Ec6o8_vdPp?usp=sharing

**Comment by ypicard** [comment]
Hi, I just opened this issue (https://github.com/nipreps/fmriprep/issues/2823) and I think our problems may be related. Did you solve this? Do you have any logs that could be interesting?

**Comment by mgxd** [comment]
Are there any subjects in the dataset where the SyN correction worked as expected?

**Comment by ypicard** [comment]
On our side, processing multi-echo scans works without any problems when non multi-echo scans that were being processed successfully in version 20.0.2 breaks.

**Comment by alexsayal** [comment]
> Are there any subjects in the dataset where the SyN correction worked as expected?

Hi, yes, for some subjects it works fine.

**Comment by mgxd** [comment]
Good to hear - the `--use-syn-sdc` flag is still fairly experimental, so I can't say I'm surprised about these discrepancies. Do you know if there is something different (scanning parameters, missing metadata, etc) about the failing participants?

If you have any data that you can share with us (T1w + BOLD) of one of the failing runs, it will help us tremendously to improve the robustness of the SyN implementation.

**Comment by julfou81** [comment]
Hi, I tried the "Syn" procedure for the first time with fmriprep v21.0.2 and couldn't make it work for the 3 subjects I tested.
- For these subjects we have the fmap images available for the pepolar SDC method to be used. When we use the pepolar method, fmriprep worked as expected.
- To compare with the "Syn" method, I relaunched the same execution (renaming the output and working directories) by adding ```--ignore filedmaps --use-syn-sdc``` but even if in the log output I could read: 
```
	 Option "--ignore fieldmaps" was set, but either "--use-syn-sdc" or "--force-syn" were given, so fieldmap-less estimation will be executed.
```
in the end no SDC method was used for this execution.

- I moved away the fmap folder, as if we didn't have any fieldmap acquisition for these subjects and launched again (renaming again the working and output directories) the fmriprep execution with "--use-syn-sdc" . This time the "Syn" SDC procedure was indeed launched for fmriprep crashed for the 3 participants.

Here is output logs for the failed execution using "Syn" .
[output.txt](https://github.com/nipreps/fmriprep/files/9547084/output.txt)

**Comment by julfou81** [comment]
A test on another dataset with the same command (with other acquisition parameters and less distorsion than the one I presented above) with "Syn" option didn't fail with fmriprep v21.0.2:

<img width="1421" alt="Capture d’écran 2022-09-12 à 23 32 04" src="https://user-images.githubusercontent.com/32452352/189762503-96f01999-d129-448e-a5e0-1f6105735c51.png">

**Comment by effigies** [comment]
I'm seeing a very similar result to https://github.com/nipreps/fmriprep/issues/2777#issuecomment-1243532076 on another dataset. I am trying to track this down. Linking to https://github.com/nipreps/fmriprep/issues/2878, as both of these are happening.

**Comment by effigies** [comment]
@julfou81 Would you mind sharing the voxel sizes and shape of your datasets?

**Comment by julfou81** [comment]
The data set that failed with SyN had the following parameters but strong distortions due to improper shimming values during the acquisition:
```
dim1		126
dim2		126
dim3		81
dim4		180
datatype	512
pixdim1		1.603175
pixdim2		1.603175
pixdim3		1.600000
pixdim4		2.800000
```

The data that went through with SyN with correctly estimated deformations had the following parameters: 

```
dim1		100
dim2		100
dim3		70
dim4		359
datatype	512
pixdim1		2.000000
pixdim2		2.000000
pixdim3		2.000000
```

**Comment by liuzhenqi77** [comment]
Met the same issue as above when processing ds004215 using fmriprep 22.0.0. Only some subjects have fieldmap ('IntendedFor' not present). I was expecting `--ignore filedmaps --use-syn-sdc` to ignore the fieldmaps for those with it and run fieldmap-less correction for all subjects.

<table>
<tr>
	<td>
	<td> Without `--ignore filedmaps --use-syn-sdc`
	<td> With `--ignore filedmaps --use-syn-sdc`
<tr>
	<td> Has fieldmap (sub-ON01016)
	<td> fieldmap-based SDC ✓
	<td> <b>no SDC</b> (!)
<tr>
	<td> No fieldmap (sub-ON01802)
	<td> no SDC ✓
	<td> fieldmap-less SDC ✓
</table>

All of these did not crash. I did not use `--force-syn`.

**Comment by julfou81** [comment]
Hi,

I am using FMRIPREP v22.0.2 with the command below:
```
singularity run -B /scratch/jsein/BIDS:/work,$HOME/.templateflow:/opt/templateflow --cleanenv \
 		 /scratch/jsein/my_images/fmriprep-22.0.2.simg \
		 --fs-license-file /work/freesurfer/license.txt /work/$study /work/$study/derivatives/fmriprep22syn  \
		 participant --participant-label $sub \
		 -w /work/temp_data22syn_${study}\
		 --mem-mb 50000 --omp-nthreads 10 --nthreads 12  \
		 --fd-spike-threshold 0.5 --dvars-spike-threshold 2.0 --bold2t1w-dof 9   \
		 --output-spaces MNI152NLin2009cAsym T1w  --ignore fieldmaps --use-syn-sdc --ignore slicetiming --debug compcor \
		 --fs-subjects-dir /work/$study/derivatives/fmriprep22syn/sourcedata/freesurfer  \
		 --bids-filter-file /work/$study/code/fmriprep/bids_filter01.json
```
And FMRIPREP is still not ignoring the Fieldmaps.

Here is the beginning of the output log:
```
01
bids-validator@1.8.0

[32mThis dataset appears to be BIDS compatible.[39m

        [34m[4mSummary:[24m[39m                  [34m[4mAvailable Tasks:[24m[39m        [34m[4mAvailable Modalities:[24m[39m 
        426 Files, 17.81GB        TOLD                    MRI                   
        5 - Subjects              VibStim                                       
        3 - Sessions                                                            


[36m	If you have any questions, please post on https://neurostars.org/tags/bids.[39m

221122-20:52:30,80 nipype.workflow IMPORTANT:
	 Running fMRIPrep version 22.0.2

         License NOTICE ##################################################
         fMRIPrep 22.0.2
         Copyright 2022 The NiPreps Developers.
         
         This product includes software developed by
         the NiPreps Community (https://nipreps.org/).
         
         Portions of this software were developed at the Department of
         Psychology at Stanford University, Stanford, CA, US.
         
         This software redistributes the versioneer Python package, which is
         Public domain source code.
         
         This software is also distributed as a Docker container image.
         The bootstraping file for the image ("Dockerfile") is licensed
         under the MIT License.
         
         This software may be distributed through an add-on package called
         "Docker Wrapper" that is under the BSD 3-clause License.
         #################################################################
221122-20:52:30,115 nipype.workflow WARNING:
	 Previous output generated by version 0+unknown found.
221122-20:52:30,650 nipype.workflow IMPORTANT:
	 Building fMRIPrep's workflow:
           * BIDS dataset path: /work/TOLD.
           * Participant list: ['01'].
           * Run identifier: 20221122-205202_20c3e7f9-ae1e-4e65-bce8-46d14a3bb07f.
           * Output spaces: MNI152NLin2009cAsym:res-native T1w.
           * Pre-run FreeSurfer's SUBJECTS_DIR: /work/TOLD/derivatives/fmriprep22syn/sourcedata/freesurfer.
221122-20:52:32,540 nipype.workflow INFO:
	 B0 field inhomogeneity map will be estimated with  the following 2 estimators: [<EstimatorType.PEPOLAR: 2>, <EstimatorType.PEPOLAR: 2>].
221122-20:52:32,806 nipype.workflow INFO:
	 Using single-band reference file(s) sub-01_ses-post_task-TOLD_run-01_sbref.nii.gz.
221122-20:52:32,806 nipype.workflow INFO:
	 Found usable B0-map (fieldmap) estimator(s) <B0mappost> to correct </work/TOLD/sub-01/ses-post/func/sub-01_ses-post_task-TOLD_run-01_bold.nii.gz> for susceptibility-derived distortions.
221122-20:52:33,339 nipype.workflow INFO:
	 Using single-band reference file(s) sub-01_ses-post_task-TOLD_run-02_sbref.nii.gz.
221122-20:52:33,339 nipype.workflow INFO:
	 Found usable B0-map (fieldmap) estimator(s) <B0mappost> to correct </work/TOLD/sub-01/ses-post/func/sub-01_ses-post_task-TOLD_run-02_bold.nii.gz> for susceptibility-derived distortions.
221122-20:52:33,715 nipype.workflow INFO:
	 Using single-band reference file(s) sub-01_ses-post_task-TOLD_run-03_sbref.nii.gz.
221122-20:52:33,715 nipype.workflow INFO:
	 Found usable B0-map (fieldmap) estimator(s) <B0mappost> to correct </work/TOLD/sub-01/ses-post/func/sub-01_ses-post_task-TOLD_run-03_bold.nii.gz> for susceptibility-derived distortions.
221122-20:52:34,192 nipype.workflow INFO:
	 Using single-band reference file(s) sub-01_ses-post_task-TOLD_run-04_sbref.nii.gz.
221122-20:52:34,192 nipype.workflow INFO:
	 Found usable B0-map (fieldmap) estimator(s) <B0mappost> to correct </work/TOLD/sub-01/ses-post/func/sub-01_ses-post_task-TOLD_run-04_bold.nii.gz> for susceptibility-derived distortions.
221122-20:52:34,556 nipype.workflow INFO:
	 Using single-band reference file(s) sub-01_ses-post_task-TOLD_run-05_sbref.nii.gz.
221122-20:52:34,556 nipype.workflow INFO:
	 Found usable B0-map (fieldmap) estimator(s) <B0mappost> to correct </work/TOLD/sub-01/ses-post/func/sub-01_ses-post_task-TOLD_run-05_bold.nii.gz> for susceptibility-derived distortions.
221122-20:52:34,926 nipype.workflow INFO:
	 Using single-band reference file(s) sub-01_ses-pre_task-TOLD_run-01_sbref.nii.gz.
221122-20:52:34,926 nipype.workflow INFO:
	 Found usable B0-map (fieldmap) estimator(s) <B0mappre> to correct </work/TOLD/sub-01/ses-pre/func/sub-01_ses-pre_task-TOLD_run-01_bold.nii.gz> for susceptibility-derived distortions.
221122-20:52:35,294 nipype.workflow INFO:
	 Using single-band reference file(s) sub-01_ses-pre_task-TOLD_run-02_sbref.nii.gz.
221122-20:52:35,295 nipype.workflow INFO:
	 Found usable B0-map (fieldmap) estimator(s) <B0mappre> to correct </work/TOLD/sub-01/ses-pre/func/sub-01_ses-pre_task-TOLD_run-02_bold.nii.gz> for susceptibility-derived distortions.
221122-20:52:35,663 nipype.workflow INFO:
	 Using single-band reference file(s) sub-01_ses-pre_task-TOLD_run-03_sbref.nii.gz.
221122-20:52:35,664 nipype.workflow INFO:
	 Found usable B0-map (fieldmap) estimator(s) <B0mappre> to correct </work/TOLD/sub-01/ses-pre/func/sub-01_ses-pre_task-TOLD_run-03_bold.nii.gz> for susceptibility-derived distortions.
221122-20:52:36,143 nipype.workflow INFO:
	 Using single-band reference file(s) sub-01_ses-pre_task-TOLD_run-04_sbref.nii.gz.
221122-20:52:36,143 nipype.workflow INFO:
	 Found usable B0-map (fieldmap) estimator(s) <B0mappre> to correct </work/TOLD/sub-01/ses-pre/func/sub-01_ses-pre_task-TOLD_run-04_bold.nii.gz> for susceptibility-derived distortions.
221122-20:52:36,511 nipype.workflow INFO:
	 Using single-band reference file(s) sub-01_ses-pre_task-TOLD_run-05_sbref.nii.gz.
221122-20:52:36,511 nipype.workflow INFO:
	 Found usable B0-map (fieldmap) estimator(s) <B0mappre> to correct </work/TOLD/sub-01/ses-pre/func/sub-01_ses-pre_task-TOLD_run-05_bold.nii.gz> for susceptibility-derived distortions.
221122-20:52:36,931 nipype.workflow INFO:
	 Setting-up fieldmap "B0mappost" (EstimatorType.PEPOLAR) with <sub-01_ses-post_dir-AP_epi.nii.gz, sub-01_ses-post_dir-PA_epi.nii.gz>
221122-20:52:36,947 nipype.workflow INFO:
	 Setting-up fieldmap "B0mappre" (EstimatorType.PEPOLAR) with <sub-01_ses-pre_dir-AP_epi.nii.gz, sub-01_ses-pre_dir-PA_epi.nii.gz>
221122-20:52:42,980 nipype.workflow INFO:
	 fMRIPrep workflow graph with 2506 nodes built successfully.
221122-20:52:58,373 nipype.workflow IMPORTANT:
	 fMRIPrep started!
```

Here is the data tree for sub-01, that passes the BIDS validator:

sub-01
├── ses-01
│   ├── anat
│   │   ├── sub-01_ses-01_T1w.json
│   │   ├── sub-01_ses-01_T1w.nii.gz
│   │   ├── sub-01_ses-01_T2w.json
│   │   └── sub-01_ses-01_T2w.nii.gz
│   └── dwi
│       ├── sub-01_ses-01_dir-AP_dwi.bval
│       ├── sub-01_ses-01_dir-AP_dwi.bvec
│       ├── sub-01_ses-01_dir-AP_dwi.json
│       ├── sub-01_ses-01_dir-AP_dwi.nii.gz
│       ├── sub-01_ses-01_dir-AP_part-phase_dwi.bval
│       ├── sub-01_ses-01_dir-AP_part-phase_dwi.bvec
│       ├── sub-01_ses-01_dir-AP_part-phase_dwi.json
│       ├── sub-01_ses-01_dir-AP_part-phase_dwi.nii.gz
│       ├── sub-01_ses-01_dir-PA_dwi.bval
│       ├── sub-01_ses-01_dir-PA_dwi.bvec
│       ├── sub-01_ses-01_dir-PA_dwi.json
│       ├── sub-01_ses-01_dir-PA_dwi.nii.gz
│       ├── sub-01_ses-01_dir-PA_part-phase_dwi.bval
│       ├── sub-01_ses-01_dir-PA_part-phase_dwi.bvec
│       ├── sub-01_ses-01_dir-PA_part-phase_dwi.json
│       └── sub-01_ses-01_dir-PA_part-phase_dwi.nii.gz
├── ses-post
│   ├── anat
│   │   ├── sub-01_ses-post_T1w.json
│   │   ├── sub-01_ses-post_T1w.nii.gz
│   │   ├── sub-01_ses-post_T2w.json
│   │   └── sub-01_ses-post_T2w.nii.gz
│   ├── dwi
│   │   ├── sub-01_ses-post_dir-AP_dwi.bval
│   │   ├── sub-01_ses-post_dir-AP_dwi.bvec
│   │   ├── sub-01_ses-post_dir-AP_dwi.json
│   │   ├── sub-01_ses-post_dir-AP_dwi.nii.gz
│   │   ├── sub-01_ses-post_dir-AP_part-phase_dwi.json
│   │   ├── sub-01_ses-post_dir-AP_part-phase_dwi.nii.gz
│   │   ├── sub-01_ses-post_dir-PA_dwi.bval
│   │   ├── sub-01_ses-post_dir-PA_dwi.bvec
│   │   ├── sub-01_ses-post_dir-PA_dwi.json
│   │   ├── sub-01_ses-post_dir-PA_dwi.nii.gz
│   │   ├── sub-01_ses-post_dir-PA_part-phase_dwi.json
│   │   └── sub-01_ses-post_dir-PA_part-phase_dwi.nii.gz
│   ├── fmap
│   │   ├── sub-01_ses-post_dir-AP_epi.json
│   │   ├── sub-01_ses-post_dir-AP_epi.nii.gz
│   │   ├── sub-01_ses-post_dir-PA_epi.json
│   │   └── sub-01_ses-post_dir-PA_epi.nii.gz
│   └── func
│       ├── sub-01_ses-post_task-TOLD_run-01_bold.json
│       ├── sub-01_ses-post_task-TOLD_run-01_bold.nii.gz
│       ├── sub-01_ses-post_task-TOLD_run-01_recording-cardiac_physio.json
│       ├── sub-01_ses-post_task-TOLD_run-01_recording-cardiac_physio.tsv.gz
│       ├── sub-01_ses-post_task-TOLD_run-01_recording-respiratory_physio.json
│       ├── sub-01_ses-post_task-TOLD_run-01_recording-respiratory_physio.tsv.gz
│       ├── sub-01_ses-post_task-TOLD_run-01_sbref.json
│       ├── sub-01_ses-post_task-TOLD_run-01_sbref.nii.gz
│       ├── sub-01_ses-post_task-TOLD_run-02_bold.json
│       ├── sub-01_ses-post_task-TOLD_run-02_bold.nii.gz
│       ├── sub-01_ses-post_task-TOLD_run-02_recording-cardiac_physio.json
│       ├── sub-01_ses-post_task-TOLD_run-02_recording-cardiac_physio.tsv.gz
│       ├── sub-01_ses-post_task-TOLD_run-02_recording-respiratory_physio.json
│       ├── sub-01_ses-post_task-TOLD_run-02_recording-respiratory_physio.tsv.gz
│       ├── sub-01_ses-post_task-TOLD_run-02_sbref.json
│       ├── sub-01_ses-post_task-TOLD_run-02_sbref.nii.gz
│       ├── sub-01_ses-post_task-TOLD_run-03_bold.json
│       ├── sub-01_ses-post_task-TOLD_run-03_bold.nii.gz
│       ├── sub-01_ses-post_task-TOLD_run-03_recording-cardiac_physio.json
│       ├── sub-01_ses-post_task-TOLD_run-03_recording-cardiac_physio.tsv.gz
│       ├── sub-01_ses-post_task-TOLD_run-03_recording-respiratory_physio.json
│       ├── sub-01_ses-post_task-TOLD_run-03_recording-respiratory_physio.tsv.gz
│       ├── sub-01_ses-post_task-TOLD_run-03_sbref.json
│       ├── sub-01_ses-post_task-TOLD_run-03_sbref.nii.gz
│       ├── sub-01_ses-post_task-TOLD_run-04_bold.json
│       ├── sub-01_ses-post_task-TOLD_run-04_bold.nii.gz
│       ├── sub-01_ses-post_task-TOLD_run-04_recording-cardiac_physio.json
│       ├── sub-01_ses-post_task-TOLD_run-04_recording-cardiac_physio.tsv.gz
│       ├── sub-01_ses-post_task-TOLD_run-04_recording-respiratory_physio.json
│       ├── sub-01_ses-post_task-TOLD_run-04_recording-respiratory_physio.tsv.gz
│       ├── sub-01_ses-post_task-TOLD_run-04_sbref.json
│       ├── sub-01_ses-post_task-TOLD_run-04_sbref.nii.gz
│       ├── sub-01_ses-post_task-TOLD_run-05_bold.json
│       ├── sub-01_ses-post_task-TOLD_run-05_bold.nii.gz
│       ├── sub-01_ses-post_task-TOLD_run-05_recording-cardiac_physio.json
│       ├── sub-01_ses-post_task-TOLD_run-05_recording-cardiac_physio.tsv.gz
│       ├── sub-01_ses-post_task-TOLD_run-05_recording-respiratory_physio.json
│       ├── sub-01_ses-post_task-TOLD_run-05_recording-respiratory_physio.tsv.gz
│       ├── sub-01_ses-post_task-TOLD_run-05_sbref.json
│       └── sub-01_ses-post_task-TOLD_run-05_sbref.nii.gz
└── ses-pre
    ├── anat
    │   ├── sub-01_ses-pre_T1w.json
    │   ├── sub-01_ses-pre_T1w.nii.gz
    │   ├── sub-01_ses-pre_T2w.json
    │   └── sub-01_ses-pre_T2w.nii.gz
    ├── fmap
    │   ├── sub-01_ses-pre_dir-AP_epi.json
    │   ├── sub-01_ses-pre_dir-AP_epi.nii.gz
    │   ├── sub-01_ses-pre_dir-PA_epi.json
    │   └── sub-01_ses-pre_dir-PA_epi.nii.gz
    └── func
        ├── sub-01_ses-pre_task-TOLD_run-01_bold.json
        ├── sub-01_ses-pre_task-TOLD_run-01_bold.nii.gz
        ├── sub-01_ses-pre_task-TOLD_run-01_recording-respiratory_physio.json
        ├── sub-01_ses-pre_task-TOLD_run-01_recording-respiratory_physio.tsv.gz
        ├── sub-01_ses-pre_task-TOLD_run-01_sbref.json
        ├── sub-01_ses-pre_task-TOLD_run-01_sbref.nii.gz
        ├── sub-01_ses-pre_task-TOLD_run-02_bold.json
        ├── sub-01_ses-pre_task-TOLD_run-02_bold.nii.gz
        ├── sub-01_ses-pre_task-TOLD_run-02_recording-respiratory_physio.json
        ├── sub-01_ses-pre_task-TOLD_run-02_recording-respiratory_physio.tsv.gz
        ├── sub-01_ses-pre_task-TOLD_run-02_sbref.json
        ├── sub-01_ses-pre_task-TOLD_run-02_sbref.nii.gz
        ├── sub-01_ses-pre_task-TOLD_run-03_bold.json
        ├── sub-01_ses-pre_task-TOLD_run-03_bold.nii.gz
        ├── sub-01_ses-pre_task-TOLD_run-03_recording-cardiac_physio.json
        ├── sub-01_ses-pre_task-TOLD_run-03_recording-cardiac_physio.tsv.gz
        ├── sub-01_ses-pre_task-TOLD_run-03_recording-respiratory_physio.json
        ├── sub-01_ses-pre_task-TOLD_run-03_recording-respiratory_physio.tsv.gz
        ├── sub-01_ses-pre_task-TOLD_run-03_sbref.json
        ├── sub-01_ses-pre_task-TOLD_run-03_sbref.nii.gz
        ├── sub-01_ses-pre_task-TOLD_run-04_bold.json
        ├── sub-01_ses-pre_task-TOLD_run-04_bold.nii.gz
        ├── sub-01_ses-pre_task-TOLD_run-04_recording-cardiac_physio.json
        ├── sub-01_ses-pre_task-TOLD_run-04_recording-cardiac_physio.tsv.gz
        ├── sub-01_ses-pre_task-TOLD_run-04_recording-respiratory_physio.json
        ├── sub-01_ses-pre_task-TOLD_run-04_recording-respiratory_physio.tsv.gz
        ├── sub-01_ses-pre_task-TOLD_run-04_sbref.json
        ├── sub-01_ses-pre_task-TOLD_run-04_sbref.nii.gz
        ├── sub-01_ses-pre_task-TOLD_run-05_bold.json
        ├── sub-01_ses-pre_task-TOLD_run-05_bold.nii.gz
        ├── sub-01_ses-pre_task-TOLD_run-05_recording-cardiac_physio.json
        ├── sub-01_ses-pre_task-TOLD_run-05_recording-cardiac_physio.tsv.gz
        ├── sub-01_ses-pre_task-TOLD_run-05_recording-respiratory_physio.json
        ├── sub-01_ses-pre_task-TOLD_run-05_recording-respiratory_physio.tsv.gz
        ├── sub-01_ses-pre_task-TOLD_run-05_sbref.json
        └── sub-01_ses-pre_task-TOLD_run-05_sbref.nii.gz

**Comment by julfou81** [comment]
I noticed that I was able to trigger this output log: (still with FMRIPEP v22.0.2)

```
221122-21:55:03,191 nipype.workflow INFO:
	 Option "--ignore fieldmaps" was set, but either "--use-syn-sdc" or "--force-syn" were given, so fieldmap-less estimation will be executed.
221122-21:55:03,191 nipype.workflow INFO:
	 B0 field inhomogeneity map will be estimated with  the following 2 estimators: [<EstimatorType.ANAT: 5>, <EstimatorType.ANAT: 5>].
221122-21:55:03,452 nipype.workflow INFO:
	 Using single-band reference file(s) sub-01_ses-post_task-TOLD_run-01_sbref.nii.gz.
221122-21:55:03,452 nipype.workflow INFO:
	 Found usable B0-map (fieldmap) estimator(s) <B0mappost> to correct </work/TOLD/sub-01/ses-post/func/sub-01_ses-post_task-TOLD_run-01_bold.nii.gz> for susceptibility-derived distortions.
221122-21:55:03,988 nipype.workflow INFO:
	 Using single-band reference file(s) sub-01_ses-post_task-TOLD_run-02_sbref.nii.gz.
221122-21:55:03,989 nipype.workflow INFO:
	 Found usable B0-map (fieldmap) estimator(s) <B0mappost> to correct </work/TOLD/sub-01/ses-post/func/sub-01_ses-post_task-TOLD_run-02_bold.nii.gz> for susceptibility-derived distortions.
221122-21:55:04,363 nipype.workflow INFO:
	 Using single-band reference file(s) sub-01_ses-post_task-TOLD_run-03_sbref.nii.gz.
221122-21:55:04,363 nipype.workflow INFO:
	 Found usable B0-map (fieldmap) estimator(s) <B0mappost> to correct </work/TOLD/sub-01/ses-post/func/sub-01_ses-post_task-TOLD_run-03_bold.nii.gz> for susceptibility-derived distortions.
221122-21:55:04,849 nipype.workflow INFO:
	 Using single-band reference file(s) sub-01_ses-post_task-TOLD_run-04_sbref.nii.gz.
221122-21:55:04,849 nipype.workflow INFO:
	 Found usable B0-map (fieldmap) estimator(s) <B0mappost> to correct </work/TOLD/sub-01/ses-post/func/sub-01_ses-post_task-TOLD_run-04_bold.nii.gz> for susceptibility-derived distortions.
221122-21:55:05,219 nipype.workflow INFO:
	 Using single-band reference file(s) sub-01_ses-post_task-TOLD_run-05_sbref.nii.gz.
221122-21:55:05,219 nipype.workflow INFO:
	 Found usable B0-map (fieldmap) estimator(s) <B0mappost> to correct </work/TOLD/sub-01/ses-post/func/sub-01_ses-post_task-TOLD_run-05_bold.nii.gz> for susceptibility-derived distortions.
221122-21:55:05,591 nipype.workflow INFO:
	 Using single-band reference file(s) sub-01_ses-pre_task-TOLD_run-01_sbref.nii.gz.
221122-21:55:05,592 nipype.workflow INFO:
	 Found usable B0-map (fieldmap) estimator(s) <B0mappre> to correct </work/TOLD/sub-01/ses-pre/func/sub-01_ses-pre_task-TOLD_run-01_bold.nii.gz> for susceptibility-derived distortions.
221122-21:55:05,961 nipype.workflow INFO:
	 Using single-band reference file(s) sub-01_ses-pre_task-TOLD_run-02_sbref.nii.gz.
221122-21:55:05,961 nipype.workflow INFO:
	 Found usable B0-map (fieldmap) estimator(s) <B0mappre> to correct </work/TOLD/sub-01/ses-pre/func/sub-01_ses-pre_task-TOLD_run-02_bold.nii.gz> for susceptibility-derived distortions.
221122-21:55:06,337 nipype.workflow INFO:
	 Using single-band reference file(s) sub-01_ses-pre_task-TOLD_run-03_sbref.nii.gz.
221122-21:55:06,337 nipype.workflow INFO:
	 Found usable B0-map (fieldmap) estimator(s) <B0mappre> to correct </work/TOLD/sub-01/ses-pre/func/sub-01_ses-pre_task-TOLD_run-03_bold.nii.gz> for susceptibility-derived distortions.
221122-21:55:06,816 nipype.workflow INFO:
	 Using single-band reference file(s) sub-01_ses-pre_task-TOLD_run-04_sbref.nii.gz.
221122-21:55:06,816 nipype.workflow INFO:
	 Found usable B0-map (fieldmap) estimator(s) <B0mappre> to correct </work/TOLD/sub-01/ses-pre/func/sub-01_ses-pre_task-TOLD_run-04_bold.nii.gz> for susceptibility-derived distortions.
221122-21:55:07,187 nipype.workflow INFO:
	 Using single-band reference file(s) sub-01_ses-pre_task-TOLD_run-05_sbref.nii.gz.
221122-21:55:07,187 nipype.workflow INFO:
	 Found usable B0-map (fieldmap) estimator(s) <B0mappre> to correct </work/TOLD/sub-01/ses-pre/func/sub-01_ses-pre_task-TOLD_run-05_bold.nii.gz> for susceptibility-derived distortions.
221122-21:55:07,618 nipype.workflow INFO:
	 Setting-up fieldmap "auto_00000" (EstimatorType.ANAT) with <sub-01_ses-01_T1w.nii.gz, sub-01_ses-post_task-TOLD_run-01_bold.nii.gz, sub-01_ses-post_task-TOLD_run-02_bold.nii.gz, sub-01_ses-post_task-TOLD_run-03_bold.nii.gz, sub-01_ses-post_task-TOLD_run-04_bold.nii.gz, sub-01_ses-post_task-TOLD_run-05_bold.nii.gz>
221122-21:55:07,649 nipype.workflow INFO:
	 Setting-up fieldmap "auto_00001" (EstimatorType.ANAT) with <sub-01_ses-01_T1w.nii.gz, sub-01_ses-pre_task-TOLD_run-01_bold.nii.gz, sub-01_ses-pre_task-TOLD_run-02_bold.nii.gz, sub-01_ses-pre_task-TOLD_run-03_bold.nii.gz, sub-01_ses-pre_task-TOLD_run-04_bold.nii.gz, sub-01_ses-pre_task-TOLD_run-05_bold.nii.gz>
221122-21:55:13,367 nipype.workflow INFO:
	 fMRIPrep workflow graph with 2577 nodes built successfully.
221122-21:55:28,392 nipype.workflow IMPORTANT:
	 fMRIPrep started!
```

when I passed all these arguments together: `--ignore fieldmaps --use-syn-sdc --force-syn`

`--ignore fieldmaps --use-syn-sdc`or  `--ignore fieldmaps --force-syn` do not seem to trigger the sentence: 
'Option "--ignore fieldmaps" was set, but either "--use-syn-sdc" or "--force-syn" were given, so fieldmap-less estimation will be executed.`

However the output log is still saying that the pepolar method will be used to correct the functional runs, which is inconsistent with the `--ignore fieldmaps` argument.

**Comment by effigies** [comment]
This has gotten out of date and hard to tell what's still an issue. Please open a new issue if this is still a problem in 23.2.0a1.
