### ISSUE TITLE
22.0.0rc0 Image will not Open on Singularity

### ISSUE THREAD

**Issue by smeisler** [nipreps/fmriprep#2787]
### What happened?

I cannot run or enter the new 22.0.0rc0 container.

### What command did you use?

```shell
singularity build fmriprep_22.0.0rc0.sif docker://nipreps/fmriprep:22.0.0rc0
singularity shell fmriprep_22.0.0rc0.sif
```

### What version of fMRIPrep are you running?

22.0.0rc0

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
FATAL:   could not open image /om2/user/smeisler/fmriprep_22.0.0rc0.sif: failed to retrieve path for /om2/user/smeisler/fmriprep_22.0.0rc0.sif: lstat /net/vast-storage.ib.cluster/scratch/vast/gablab/smeisler/fmriprep_22.0.0rc0.sif: no such file or directory
```

### Additional information / screenshots

Same error for `singularity run` and `singularity shell`. 

Compiled with Singularity 3.9.5 on CentOs 7.6

**Comment by effigies** [comment]
Can you try rebuilding an older version to ensure that it's not related to a problem with singularity build?

**Comment by smeisler** [comment]
It turned out to be an error about our HPC, not the image.
