### ISSUE TITLE
Q: Output dimensions

### ISSUE THREAD

**Issue by effigies** [nipreps/fmriprep#2791]
Hey fmriprep team, 
I just encountered the same problem with fmriprep as in this thread or as discussed [here](https://neurostars.org/t/dimensions-mismatch-in-preprocessed-fmri-data-fmriprep-0-3-2/362/10).

I have multiple runs of data for multiple participants. 

The output shape is consistent across runs/conditions for each subject, however, are different across all subjects. The shape of the Nifti files that go in to the analysis is the same for all subjects and sessions. 

Do you have any suggestions on what I may try in order to get all output nifti files to have the same dimensions? 

Jonas

_Originally posted by @jonasmago in https://github.com/nipreps/fmriprep/issues/1317#issuecomment-1148737120_

**Comment by effigies** [comment]
Hi @jonasmago. Could you share your command and what you're seeing? The [bug report template](https://github.com/nipreps/fmriprep/issues/new?assignees=&labels=bug&template=bug_report.yml) has prompts for commonly needed information.

**Comment by jonasmago** [comment]
I just re-submitted the issue using the foarm, it's now here: 
https://github.com/nipreps/fmriprep/issues/2792
Maybe you can just close this issue as there is the new one?
