### ISSUE TITLE
unsmoothed first volume in smoothAROMAnonaggr*.nii.gz

### ISSUE THREAD

**Issue by ka251** [nipreps/fmriprep#2793]
![smoothAROMAnonaggr](https://user-images.githubusercontent.com/107125760/172635620-c5429e14-3713-448f-91fb-5a06d2e3aae2.PNG)

Dear fMRI experts,

After running fMRIPREP with non-aggressive smoothing, we're noticing a few instances in which the first volume of the image following ICA-AROMA preprocessing looks much sharper than the rest.  I have attached a screenshot of the image displaying the first volume at the top and second volume in the bottom (the remaining volumes are also smoothed).  What could be causing this issue which has potential downstream effects in post-processing?  Please let me know if you need further information.  Thank you for your help.

Best regards,

Kareem Al-Khalil

**Comment by effigies** [comment]
I would guess that you have a non-steady-state volume. ICA-AROMA needs to be run on the steady-state time series, so non-steady-state volumes are removed and then re-added to the beginning to ensure that the volumes still represent the same time points. It's not ideal, but we figured it'd be better than having a first volume that was actually 1-3 TRs after the start of the series.

**Comment by ka251** [comment]
Thank you for your help.  We have some follow-up questions.
1 - Is there any way to fix this, or could this feature be turned off ?  The reason for asking is we're running post-processing steps including detrending, high and low pass filtering, and removal of WM/CSF confounds (https://nilearn.github.io/modules/generated/nilearn.image.clean_img.html).  The data with the unsmoothed first volume turned out very odd following post-processing (shown on the right of these snapshots - the left is a normal post-processed output with all volumes smoothed). 
![PostProc_vol2](https://user-images.githubusercontent.com/107125760/172706428-ca680947-a0df-4c52-bb8f-ee7cbecfc4c8.png)
![PostProc_vol1](https://user-images.githubusercontent.com/107125760/172706430-d577f69b-045c-46ed-88ab-b41fea6208ea.png)
2 - What are the implications of leaving this as is?  Do you suppose the post-processed data is reliable? Maybe there's way of running the aforementioned post-processing cleanup to better account for unsmoothed first volume?

**Comment by ka251** [comment]
Could I remove the first unsmoothed volume and first line of the confounds.tsv file, and then run the post-processing (https://nilearn.github.io/modules/generated/nilearn.image.clean_img.html)? The dataset would end up with a few runs with 1 less volume than others. This is resting-state data - so no issues with matching timing to external stimuli.

**Comment by ka251** [comment]
It seems the best way to clean up the post processing is to add the non-steady-state0* as confounds for removal.
