### ISSUE TITLE
22.0.0rc0 fMRIPrep takes hours to start

### ISSUE THREAD

**Issue by Ashrmis** [nipreps/fmriprep#2797]
### What happened?

fMRIPrep is taking forever to start. I'm even skipping bids validation. For example I ran it at 4pm and it started (see the console output)  3.5 hours later. And then it takes another 1 hour before it prints out that it's building the workflow. 
Not sure if this is a singularity issue or with this new version (I am using singularity version 3.7.4). In the end the whole workflow does execute perfectly, It's just that 4.5 hours in the beginning.

### What command did you use?

```shell
nohup singularity run -B /etc/ssl/certs/:/etc/ssl/certs \
 -B ${directory}:/data \
 -B ${directory}/derivatives/freesurfer:/fs \
 -B ${directory}/derivatives/fmriprep:/out \
 -B ${directory}/derivatives/fmriprep/work:/work \
 -B ${directory}/code:/AC --cleanenv \
 /usr/local/fmriprep/fmriprep-22.0.0rc0.simg \
 /data /out participant --participant-label \
 $subj -w /work \
 --fs-subjects-dir /fs/ \
 --skip_bids_validation --fs-license-file /AC/license.txt > nohup/${subj}.out &
```

### What version of fMRIPrep are you running?

22.0.0rc0

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
Here are the first couple chunks of the console where you can see the timestamp

220610-19:33:11,68 nipype.workflow IMPORTANT:
         Running fMRIPrep version 22.0.0rc0

         License NOTICE ##################################################
         fMRIPrep 22.0.0rc0
         Copyright 2022 The NiPreps Developers.

         This product includes software developed by
         the NiPreps Community (https://nipreps.org/).

         Portions of this software were developed at the Department of
         Psychology at Stanford University, Stanford, CA, US.

         This software redistributes the versioneer Python package, which is
         Public domain source code.

         This software is also distributed as a Docker container image.
         The bootstraping file for the image ("Dockerfile") is licensed
         under the MIT License.

         This software may be distributed through an add-on package called
         "Docker Wrapper" that is under the BSD 3-clause License.
         #################################################################
220610-20:33:11,624 nipype.workflow IMPORTANT:
         Building fMRIPrep's workflow:
           * BIDS dataset path: /data.
           * Participant list: ['ms002'].
           * Run identifier: 20220610-153749_0e944dfd-4384-43cf-a50b-0cd901e18627.
           * Output spaces: MNI152NLin2009cAsym:res-native.
           * Pre-run FreeSurfer's SUBJECTS_DIR: /out/sourcedata/freesurfer.
220610-20:36:59,612 nipype.workflow INFO:
         B0 field inhomogeneity map will be estimated with  the following 1 estimators: [<EstimatorType.PHASEDIFF: 3>].
220610-20:37:08,771 nipype.workflow INFO:
```

**Comment by effigies** [comment]
I would try running in `singularity shell`. Something like:

```
singularity shell -B /etc/ssl/certs/:/etc/ssl/certs \
 -B ${directory}:/data \
 -B ${directory}/derivatives/freesurfer:/fs \
 -B ${directory}/derivatives/fmriprep:/out \
 -B ${directory}/derivatives/fmriprep/work:/work \
 -B ${directory}/code:/AC --cleanenv \
 /usr/local/fmriprep/fmriprep-22.0.0rc0.simg
```

From here you can start to probe to narrow down where the slowdown might arise:

1) Test starting Python:

```
> time python -c "import sys; print(sys.version_info)"
sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
python -c "import sys; print(sys.version_info)"  0.03s user 0.00s system 99% cpu 0.027 total
```

2) Test importing numpy, nipype and fMRIPrep:

```
> time python -c "import numpy; print(numpy.__version__)"
> time python -c "import nipype; print(nipype.__version__)"
> time python -c "import fmriprep; print(fmriprep.__version__)"
```

4) Finally, try running and seeing if you still see the problem:

```
> fmriprep /data /out participant --participant-label \
 $subj -w /work \
 --fs-subjects-dir /fs/ \
 --skip_bids_validation --fs-license-file /AC/license.txt
```

----

We have found that there's a bug in nipype that's causing repeated requests to a webserver that's been having downtime recently. Setting the environment variable `NO_ET` will help, if that's the issue. Inside the container, `NO_ET` would be needed; outside, you would need to use `SINGULARITYENV_NO_ET`  to ensure it gets passed through despite `--cleanenv`.

**Comment by Ashrmis** [comment]
Starting Python and importing numpy, nipype and fMRIPrep are no problem. What would I set `NO_ET` and `SINGULARITYENV_NO_ET`, `FALSE`?

**Comment by effigies** [comment]
Any value at all is fine. I usually do `SINGULARITYENV_NO_ET=1`.

**Comment by Ashrmis** [comment]
Hmm it's been about 30 min but no console output yet, did I add them correctly? The fmriprep process is still running.
```
export SINGULARITYENV_NO_ET=1 

nohup singularity run --env NO_ET=1 \
 -B /etc/ssl/certs/:/etc/ssl/certs \
 -B ${directory}:/data \
 -B ${directory}/derivatives/freesurfer:/fs \
 -B ${directory}/derivatives/fmriprep:/out \
 -B ${directory}/derivatives/fmriprep/work:/work \
 -B ${directory}/code:/AC --cleanenv \
 /usr/local/fmriprep/fmriprep-22.0.0rc0.simg \
 /data /out participant --participant-label \
 $subj -w /work \
 --fs-subjects-dir /fs/ \
 --skip_bids_validation --fs-license-file /AC/license.txt > nohup/${subj}.out &
```

**Comment by effigies** [comment]
If you run `top` (or better, `htop`) can you see what process is running and how much CPU it's using? If your dataset is large, it could be spending a lot of time building the BIDS layout. See https://fmriprep.org/en/stable/faq.html?highlight=pybids#how-to-decrease-fmriprep-runtime-when-working-with-large-datasets.

**Comment by Ashrmis** [comment]
It's using about 20-25% of a CPU. For that single subject it's about total 300M for the anat and func (8 task files) sub-directories.

Thanks for the link, I'll try to set up the layout prior to fmriprep
