### ISSUE TITLE
Freesurfer 7.2?

### ISSUE THREAD

**Issue by hoptman** [nipreps/fmriprep#2798]
### What would you like to see added in fMRIPrep?

Hi all,
Is there any way to force fMRIPrep to use freesurfer 7.2? I'm using fmriprep-docker, so I'm thinking that 7.2 is not yet in the container. Is there a plan to incorporate 7.2 in a forthcoming version? I find that it performs better than 6.0, and it includes parcellations for hippocampal and amygdala subfields. 
Thanks,
Matt

### Do you have any interest in helping implement the feature?

No

**Comment by effigies** [comment]
FreeSurfer 7.2 is bundled with fMRIPrep 22.0.0, which is in release-candidate phase. If you're using `fmriprep-docker` upgrade with `pip install --upgrade --pre fmriprep-docker`.

**Comment by hoptman** [comment]
Thanks!!
