### ISSUE TITLE
mcflirt crashing in fmriprep: 22.0.0.RC1

### ISSUE THREAD

**Issue by hoptman** [nipreps/fmriprep#2802]
### What happened?

I get a crash during the mcflirt step as indicated below.

### What command did you use?

```shell
fmriprep-docker `pwd`/bids_data `pwd`/derivatives participant --fs-license-file=/mnt/software/freesurfer/license.txt -w 'pwd'/tmp --ignore=slicetiming  --stop-on-first-crash --n_cpus=8 --nthreads=8 --notrack --low-mem --dummy-scans=8 -vvv
```

### What version of fMRIPrep are you running?

fmriprep:22.0.0rc1

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

Work directory

### Please copy and paste any relevant log output.

```shell
Node: fmriprep_22_0_wf.single_subject_A00040383_wf.func_preproc_ses_BAS1_task_rest_acq_1400_wf.bo
ld_hmc_wf.mcflirt
Working directory: /scratch/fmriprep_22_0_wf/single_subject_A00040383_wf/func_preproc_ses_BAS1_ta
sk_rest_acq_1400_wf/bold_hmc_wf/mcflirt

Node inputs:

args = <undefined>
bins = <undefined>
cost = <undefined>
dof = <undefined>
environ = {'FSLOUTPUTTYPE': 'NIFTI_GZ'}
in_file = /data/sub-A00040383/ses-BAS1/func/sub-A00040383_ses-BAS1_task-rest_acq-1400_bold.nii
init = <undefined>
interpolation = <undefined>
mean_vol = <undefined>
out_file = <undefined>
output_type = NIFTI_GZ
ref_file = /scratch/fmriprep_22_0_wf/single_subject_A00040383_wf/func_preproc_ses_BAS1_task_rest_
acq_1400_wf/initial_boldref_wf/gen_avg/sub-A00040383_ses-BAS1_task-rest_acq-1400_bold_average.nii
ref_vol = <undefined>
rotation = <undefined>
save_mats = True
save_plots = True
save_rms = True
scaling = <undefined>
smooth = <undefined>
stages = <undefined>
stats_imgs = <undefined>
use_contour = <undefined>
use_gradient = <undefined>

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node mcflirt.

RuntimeError: subprocess exited with code 137.
```

### Additional information / screenshots

The text I see is like this (for each subject);
220623-14:38:09,442 nipype.workflow ERROR:
         Saving crash info to /out/sub-A00040383/log/20220623-142659_61f984df-9c2c-4b04-8682-677d8ad1dd54/crash-20220623-143809-root-mcflirt-fc8d8014-b95b-41cf-91f9-83253af35faf.txt
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node mcflirt.

RuntimeError: subprocess exited with code 137.

**Comment by mgxd** [comment]
This looks like an out of memory issue - if you are running on mac/windows, you may need to [increase the memory allocated to Docker](https://stackoverflow.com/questions/44533319/how-to-assign-more-memory-to-docker-container)

**Comment by hoptman** [comment]
Thanks. I'll try that, though I'm using Linux. I did set the --low-mem flag as you see.

**Comment by effigies** [comment]
Setting `--low-mem` helps with some very specific high-memory nodes, but cannot change some basic memory requirements. Please reopen if increasing available memory does not resolve this.
