### ISSUE TITLE
Output motion transforms in BIDS Derivatives

### ISSUE THREAD

**Issue by effigies** [nipreps/fmriprep#2803]
Affine transforms from each original BOLD volume to the BOLD reference volume should be stored in the derivatives.

For now let's use a simple format that roughly corresponds to an array such that:

```Python
# affine : list of 4x4 matrices
# all_params : n x 12 matrix
affine[i][:3] = all_params[i, :].reshape(3, 4)
```

Part of #2207.

**Comment by Lestropie** [comment]
This will require two small applications for inclusion in the workflow:

1. Generation of a single file of some format that includes the affine transformation (likely in the 1x12 ITK format) for *every volume*.

2. Load this file, select a specific volume, and export a text file that conforms to the ITK format.
