### ISSUE TITLE
Unusual fieldmap data

### ISSUE THREAD

**Issue by MasonTWells** [nipreps/fmriprep#2808]
Hi,

I have downloaded a set of publicly available data (Healthy Brain Network Serial Scanning Initiative) which contains a fieldmap folder for each subject. However, each of these folders contain a phase difference image with 2 volumes (not one) and a single magnitude image that does not resemble a "typical" magnitude image (see below). 
![sub-21_magnitude](https://user-images.githubusercontent.com/67323940/175912823-02dd8f3e-6f10-46b8-acf7-2a848107a04f.jpg)
![sub-21_phasediff1](https://user-images.githubusercontent.com/67323940/175912831-0260d808-839c-4d41-b0b2-c1e18d960b74.jpg)
![sub-21_phasediff2](https://user-images.githubusercontent.com/67323940/175912837-6e2f6331-d559-437c-89d6-a0d2d8dd5629.jpg)

My understanding is that fMRIPrep will perform SDC using either an opposite phase encoding direction image (will use topup) or two magnitude images and a phase difference image (will use fsl_prepare_fieldmap). However, the data set I have does not fall into either of those categories. My questions are 1) has anyone used the HBN-SSI data set with fMRIPrep and used the fmap data? 2) Does fMRIPrep have anything in the SDC workflow that will handle the fmap data shown above?

Thanks in advance,
Mason

**Comment by effigies** [comment]
I think you have this backwards. The first image is a phase difference, and the second contains the magnitude at each echo.

**Comment by MasonTWells** [comment]
Hi @effigies, these data have come straight from the publicly available datasets. Perhaps they named the images incorrectly prior to upload? I have split the image with two volumes (originally called _phasediff) and renamed them as _magnitude1 and _magnitude2. I have also renamed the original _magnitude1 as _phasediff. The dataset is bids compliant and I have set fMRIPrep to run. I have created a .json file (named sub-0031121_ses-SSV2_phasediff.json) which contains the information below:

"EchoTime1": 0.00328,
 "EchoTime2": 0.008039999999999999,
 "IntendedFor": ["ses-SSV2/func/sub-0031121_ses-SSV2_task-INSCAPES_acq-TR1450_bold.nii.gz","ses-SSV2/func/sub-0031121_ses-SSV2_task-MOVIE_acq-TR1450_bold.nii.gz", "ses-SSV2/func/sub-0031121_ses-SSV2_task-RESTINGSTATE_acq-TR1450_bold.nii.gz"]
  
Please can you advise whether the above seems appropriate to you?

Thanks for your help.
Mason

**Comment by MasonTWells** [comment]
No problem. I have written to the curators and they have said they will get back to me ASAP. I'll update this thread when I hear back from them. 

fMRIPrep is currently running for this subject. I can see fieldmap is displayed in the "Available Modalities" part of the report when fMRIPrep begins. Looking at the report, it appears that the sdc workflow is being called. All the fieldmaps are like this, it isn't just one bad subject.

**Comment by mgxd** [comment]
Please re-open if further discussion is needed
