### ISSUE TITLE
Misaligned anatomical CompCor ROI

### ISSUE THREAD

**Issue by MasonTWells** [nipreps/fmriprep#2815]
### What happened?

The anatomical CompCor ROI in the html report appears to be misaligned relative to the ventricles. There were no reported errors and the rest of the QC reports look fine. Is this misalignment likely to causes any issues? For reference, I am pre-processing the data in fMRIPrep and then performing ICA on these data with MELODIC. 

### What command did you use?

```shell
singularity run --cleanenv --bind /cubric/collab/object-motion/MTW_RA/HBN-SSI/RawData/sourcedata --bind /cubric/collab/object-motion/MTW_RA/HBN-SSI/RawData/derivatives --bind /cubric/collab/object-motion/MTW_RA/HBN-SSI/RawData/work /cubric/scratch/c1749990/singularity.images/fmriprep_20.2.7.simg /cubric/collab/object-motion/MTW_RA/HBN-SSI/RawData/sourcedata /cubric/collab/object-motion/MTW_RA/HBN-SSI/RawData/derivatives participant --participant_label $SUBJ --output-spaces fsnative fsaverage T1w func MNI152NLin6Asym:res-2 MNI152NLin2009cAsym:res-2 --stop-on-first-crash --fs-license-file $HOME/freesurfer_license.txt -w /cubric/collab/object-motion/MTW_RA/HBN-SSI/RawData/work --n_cpus $SLURM_CPUS_PER_TASK --omp-nthreads 4
```

### What version of fMRIPrep are you running?

20.2.7

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
No errors reported in html log.
```

### Additional information / screenshots

![Compcor](https://user-images.githubusercontent.com/67323940/178482816-bd51fc90-0f9f-4d63-9b57-0424352f0d6f.jpg)

**Comment by effigies** [comment]
> The anatomical CompCor ROI in the html report appears to be misaligned relative to the ventricles. There were no reported errors and the rest of the QC reports look fine. Is this misalignment likely to causes any issues?

This looks reasonable to me. I'm curious what you were expecting to see. The anatomical compcor mask is the union of white matter and CSF masks at least 3 voxels distant from gray matter.

> For reference, I am pre-processing the data in fMRIPrep and then performing ICA on these data with MELODIC.

The CompCor masks only affect the CompCor components; there is no impact on the BOLD outputs.

**Comment by effigies** [comment]
Please reopen if an issue remains.
