### ISSUE TITLE
Docker run on Mac got NodeExecutionError and FileNotFoundError

### ISSUE THREAD

**Issue by wjy73** [nipreps/fmriprep#2819]
Dear fmriprep team:
**Here is the command I used:**
docker run -v $HOME/Data/tmp:/tmp -v $HOME/Data/fmriprep_test:/data:ro -v $HOME/fmriprep_testout:/out -v $HOME/Data/Freesurfer/:/Freesurfer:ro nipreps/fmriprep /data /out participant --fs-license-file /Freesurfer/license.txt --skull-strip-template OASIS30ANTs --nthreads 1 --low-mem -w /tmp 

**The two errors I got were:**
220713-22:11:02,131 nipype.workflow ERROR:
	 could not run node: fmriprep_22_0_wf.single_subject_222103015_wf.anat_preproc_wf.brain_extraction_wf.norm
220713-22:11:02,198 nipype.workflow CRITICAL:
	 fMRIPrep failed: Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node norm.

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nibabel/loadsave.py", line 42, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/fmriprep_22_0_wf/single_subject_222103015_wf/anat_preproc_wf/brain_extraction_wf/norm/anat_to_template_Warped.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 398, in run
    runtime = self._run_interface(runtime)
  File "/opt/conda/lib/python3.9/site-packages/niworkflows/interfaces/fixes.py", line 110, in _run_interface
    _copyxform(
  File "/opt/conda/lib/python3.9/site-packages/niworkflows/utils/images.py", line 79, in _copyxform
    resampled = nb.load(out_image, mmap=False)
  File "/opt/conda/lib/python3.9/site-packages/nibabel/loadsave.py", line 44, in load
    raise FileNotFoundError(f"No such file or no access: '{filename}'")
FileNotFoundError: No such file or no access: '/tmp/fmriprep_22_0_wf/single_subject_222103015_wf/anat_preproc_wf/brain_extraction_wf/norm/anat_to_template_Warped.nii.gz'

**Here is my system info:**
Model Name:	iMac
  Model Identifier:	iMac19,1
  Processor Name:	8-Core Intel Core i9
  Processor Speed:	3.6 GHz
  Number of Processors:	1
  Total Number of Cores:	8
  L2 Cache (per Core):	256 KB
  L3 Cache:	16 MB
  Hyper-Threading Technology:	Enabled
  Memory:	32 GB
  Boot ROM Version:	1731.120.8.0.0
  SMC Version (system):	2.46f13

Thank you.

**Comment by effigies** [comment]
Is there any chance that you ran out of disk space on `$HOME/Data/tmp`, or could it be a network filesystem? And did you verify that `$HOME/Data/tmp/fmriprep_22_0_wf/single_subject_222103015_wf/anat_preproc_wf/brain_extraction_wf/norm/anat_to_template_Warped.nii.gz` exists?

**Comment by wjy73** [comment]
Thanks. Here is the tree of the anat_preproc_wf dir. The anat_to_template_Warped.nii.gz is missing under norm. I'm not sure if there's anything else missing. How can I get the nat_to_template_Warped.nii.gz file?
.
├── anat_derivatives_wf
│   ├── _in_tuple_MNI152NLin2009cAsym.resnative
│   │   ├── gen_tplid
│   │   │   ├── _0x1cf0d728c9c697a56f2e5e5b29fd7e53.json
│   │   │   ├── _inputs.pklz
│   │   │   ├── _node.pklz
│   │   │   ├── _report
│   │   │   │   └── report.rst
│   │   │   └── result_gen_tplid.pklz
│   │   ├── select_tpl
│   │   │   ├── _0x6fd8ff2a21c9701984a05d8ceef8bfce.json
│   │   │   ├── _inputs.pklz
│   │   │   ├── _node.pklz
│   │   │   ├── _report
│   │   │   │   └── report.rst
│   │   │   └── result_select_tpl.pklz
│   │   └── spacesource
│   │       ├── _0xdd036324d026174e1d54150bf3f300c4.json
│   │       ├── _inputs.pklz
│   │       ├── _node.pklz
│   │       ├── _report
│   │       │   └── report.rst
│   │       └── result_spacesource.pklz
│   ├── ds_fsnative_t1w
│   │   ├── _0xa87ef0a747cdb05ddc06a07cbeaa691c.json
│   │   ├── _inputs.pklz
│   │   ├── _node.pklz
│   │   ├── _report
│   │   │   └── report.rst
│   │   └── result_ds_fsnative_t1w.pklz
│   ├── ds_t1w_fsnative
│   │   ├── _0xb96e0d856a5c57df741703ba3b89d2c9.json
│   │   ├── _inputs.pklz
│   │   ├── _node.pklz
│   │   ├── _report
│   │   │   └── report.rst
│   │   └── result_ds_t1w_fsnative.pklz
│   ├── lta2itk_fwd
│   │   ├── _0x77b3b3f16438609baad746600ab3b524.json
│   │   ├── _inputs.pklz
│   │   ├── _node.pklz
│   │   ├── _report
│   │   │   └── report.rst
│   │   ├── out_fwd.tfm
│   │   └── result_lta2itk_fwd.pklz
│   ├── lta2itk_inv
│   │   ├── _0x9bc53c6da7bcd169cc61e88a478c1901.json
│   │   ├── _inputs.pklz
│   │   ├── _node.pklz
│   │   ├── _report
│   │   │   └── report.rst
│   │   ├── out_fwd.tfm
│   │   └── result_lta2itk_inv.pklz
│   └── raw_sources
│       ├── _0x22105c1d0b6fd658e1e01a3c3a54f5fe.json
│       ├── _inputs.pklz
│       ├── _node.pklz
│       ├── _report
│       │   └── report.rst
│       └── result_raw_sources.pklz
├── anat_norm_wf
│   └── _template_MNI152NLin2009cAsym
│       ├── split_desc
│       │   ├── _0xa542f06598146bcc9f5d688cc1f5e505.json
│       │   ├── _inputs.pklz
│       │   ├── _node.pklz
│       │   ├── _report
│       │   │   └── report.rst
│       │   └── result_split_desc.pklz
│       └── tf_select
│           ├── _0x89a1dbfeba9805fcf469a03a6090e18f.json
│           ├── _inputs.pklz
│           ├── _node.pklz
│           ├── _report
│           │   └── report.rst
│           └── result_tf_select.pklz
├── anat_reports_wf
│   ├── _template_MNI152NLin2009cAsym
│   │   └── tf_select
│   │       ├── _0x6fd8ff2a21c9701984a05d8ceef8bfce.json
│   │       ├── _inputs.pklz
│   │       ├── _node.pklz
│   │       ├── _report
│   │       │   └── report.rst
│   │       └── result_tf_select.pklz
│   ├── ds_t1w_conform_report
│   │   ├── _0xbb31af5d08681fa06cf35b33a97d3c0b.json
│   │   ├── _inputs.pklz
│   │   ├── _node.pklz
│   │   ├── _report
│   │   │   └── report.rst
│   │   └── result_ds_t1w_conform_report.pklz
│   └── t1w_conform_check
│       ├── _0x25030019fbd164ca459cb20c7ebd7ba3.json
│       ├── _inputs.pklz
│       ├── _node.pklz
│       ├── _report
│       │   └── report.rst
│       └── result_t1w_conform_check.pklz
├── anat_template_wf
│   ├── get1st
│   │   ├── _0x9ff970fd329dd0ffbba9d05bf0b8c6be.json
│   │   ├── _inputs.pklz
│   │   ├── _node.pklz
│   │   ├── _report
│   │   │   └── report.rst
│   │   └── result_get1st.pklz
│   ├── t1w_conform
│   │   ├── _0x4f4a09cd5dc6af6c01e84d272353751b.json
│   │   ├── _inputs.pklz
│   │   ├── _node.pklz
│   │   ├── _report
│   │   │   └── report.rst
│   │   ├── mapflow
│   │   │   └── _t1w_conform0
│   │   │       ├── _0xc5a456c84f37dc48149c7c46b5188f7a.json
│   │   │       ├── _inputs.pklz
│   │   │       ├── _node.pklz
│   │   │       ├── _report
│   │   │       │   └── report.rst
│   │   │       └── result__t1w_conform0.pklz
│   │   └── result_t1w_conform.pklz
│   └── t1w_ref_dimensions
│       ├── _0xe26e0aa7c14f1718a689fb2fb1f82d14.json
│       ├── _inputs.pklz
│       ├── _node.pklz
│       ├── _report
│       │   └── report.rst
│       ├── report.html
│       └── result_t1w_ref_dimensions.pklz
├── anat_validate
│   ├── _0x92d1b6e13d351ea1a6f653741d1716cf.json
│   ├── _inputs.pklz
│   ├── _node.pklz
│   ├── _report
│   │   └── report.rst
│   └── result_anat_validate.pklz
├── brain_extraction_wf
│   ├── full_wm
│   │   ├── _0x34a64345d724ab5e941733b659d6ec46.json
│   │   ├── _inputs.pklz
│   │   ├── _node.pklz
│   │   ├── _report
│   │   │   └── report.rst
│   │   ├── result_full_wm.pklz
│   │   └── summap.nii.gz
│   ├── init_aff
│   │   ├── _0xfacb2e8e3f92fcf198dc0f7154ec0198.json
│   │   ├── _inputs.pklz
│   │   ├── _node.pklz
│   │   ├── _report
│   │   │   └── report.rst
│   │   ├── command.txt
│   │   ├── initialization.mat
│   │   └── result_init_aff.pklz
│   ├── inu_n4
│   │   ├── _0x79f0055029d752267bca3e1101380f22.json
│   │   ├── _inputs.pklz
│   │   ├── _node.pklz
│   │   ├── _report
│   │   │   └── report.rst
│   │   ├── mapflow
│   │   │   └── _inu_n40
│   │   │       ├── _0x51b3e707c52e4c01422d2b42ed007b56.json
│   │   │       ├── _inputs.pklz
│   │   │       ├── _node.pklz
│   │   │       ├── _report
│   │   │       │   └── report.rst
│   │   │       ├── command.txt
│   │   │       ├── result__inu_n40.pklz
│   │   │       └── sub-222103015_T1w_maths_corrected.nii.gz
│   │   └── result_inu_n4.pklz
│   ├── lap_target
│   │   ├── _0x0fd5fbe1877dda993e800d24d662acf5.json
│   │   ├── _inputs.pklz
│   │   ├── _node.pklz
│   │   ├── _report
│   │   │   └── report.rst
│   │   ├── command.txt
│   │   ├── result_lap_target.pklz
│   │   └── sub-222103015_T1w_maths_corrected_maths.nii.gz
│   ├── lap_tmpl
│   │   ├── _0x58bffd631e1970e2633c0aab5f0aefbf.json
│   │   ├── _inputs.pklz
│   │   ├── _node.pklz
│   │   ├── _report
│   │   │   └── report.rst
│   │   ├── command.txt
│   │   ├── result_lap_tmpl.pklz
│   │   └── tpl-OASIS30ANTs_res-01_T1w_maths.nii.gz
│   ├── mrg_target
│   │   ├── _0xd4ffc190b696fc921d91733b12ae7a07.json
│   │   ├── _inputs.pklz
│   │   ├── _node.pklz
│   │   ├── _report
│   │   │   └── report.rst
│   │   └── result_mrg_target.pklz
│   ├── mrg_tmpl
│   │   ├── _0x7fb355919b919627346c933792ad380e.json
│   │   ├── _inputs.pklz
│   │   ├── _node.pklz
│   │   ├── _report
│   │   │   └── report.rst
│   │   └── result_mrg_tmpl.pklz
│   ├── norm
│   │   ├── _inputs.pklz
│   │   ├── _node.pklz
│   │   ├── _report
│   │   │   └── report.rst
│   │   ├── command.txt
│   │   └── result_norm.pklz
│   ├── res_target
│   │   ├── _0xa91f4bbb0e68e07a313d3eab45426c53.json
│   │   ├── _inputs.pklz
│   │   ├── _node.pklz
│   │   ├── _report
│   │   │   └── report.rst
│   │   ├── result_res_target.pklz
│   │   └── sub-222103015_T1w_maths_corrected_regrid.nii.gz
│   ├── res_tmpl
│   │   ├── _0x56474d0fb211a6a62352b9e4ae8a75af.json
│   │   ├── _inputs.pklz
│   │   ├── _node.pklz
│   │   ├── _report
│   │   │   └── report.rst
│   │   ├── result_res_tmpl.pklz
│   │   └── tpl-OASIS30ANTs_res-01_T1w_regrid.nii.gz
│   └── truncate_images
│       ├── _0xfce13682a1f91256ec2ac4d903878734.json
│       ├── _inputs.pklz
│       ├── _node.pklz
│       ├── _report
│       │   └── report.rst
│       ├── mapflow
│       │   └── _truncate_images0
│       │       ├── _0x6a5393664eb18111c3f64c0e80367413.json
│       │       ├── _inputs.pklz
│       │       ├── _node.pklz
│       │       ├── _report
│       │       │   └── report.rst
│       │       ├── command.txt
│       │       ├── result__truncate_images0.pklz
│       │       └── sub-222103015_T1w_maths.nii.gz
│       └── result_truncate_images.pklz
├── fs_isrunning
│   ├── _0x21bed417dc6d7984465fd62a72fd4865.json
│   ├── _inputs.pklz
│   ├── _node.pklz
│   ├── _report
│   │   └── report.rst
│   └── result_fs_isrunning.pklz
└── surface_recon_wf
    ├── autorecon1
    │   ├── _0xc0004c9c5c27ef1221f6aca539d2ee94.json
    │   ├── _inputs.pklz
    │   ├── _node.pklz
    │   ├── _report
    │   │   └── report.rst
    │   ├── command.txt
    │   └── result_autorecon1.pklz
    ├── fov_check
    │   ├── _0xa434528079b12108e1606cef34c1e73e.json
    │   ├── _inputs.pklz
    │   ├── _node.pklz
    │   ├── _report
    │   │   └── report.rst
    │   └── result_fov_check.pklz
    ├── fsnative2t1w_xfm
    │   ├── T1_robustreg.lta
    │   ├── _0xba12024dc8bf2c08d91bfef4c77e42d5.json
    │   ├── _inputs.pklz
    │   ├── _node.pklz
    │   ├── _report
    │   │   └── report.rst
    │   ├── command.txt
    │   └── result_fsnative2t1w_xfm.pklz
    ├── recon_config
    │   ├── _0x2636768993232b93080529bf08a4e54f.json
    │   ├── _inputs.pklz
    │   ├── _node.pklz
    │   ├── _report
    │   │   └── report.rst
    │   └── result_recon_config.pklz
    └── t1w2fsnative_xfm
        ├── _0xcf459354c0e7b4a3206b5b70dcb62cfd.json
        ├── _inputs.pklz
        ├── _node.pklz
        ├── _report
        │   └── report.rst
        ├── command.txt
        ├── out.lta
        └── result_t1w2fsnative_xfm.pklz

**Comment by wjy73** [comment]
Thanks! I'll try this.

**Comment by effigies** [comment]
Hi @kartikeysaran. Can you please open a [new issue](https://github.com/nipreps/fmriprep/issues/new?assignees=&labels=bug&template=bug_report.yml) with the requested inputs. I'm going to have a hard time re-reading this issue and trying to figure what things transfer from their situation to yours.

**Comment by kartikeysaran** [comment]
Sure
