### ISSUE TITLE
A new brain mask is still estimated while feeding skull-stripped T1w and specifying --skull-strip-t1w skip 

### ISSUE THREAD

**Issue by zhengchencai** [nipreps/fmriprep#2828]
### What happened?

Hello, 

I had [issues](https://github.com/nipreps/niworkflows/issues/734#issuecomment-1193164306) of accurate brain mask extractions for a few participants. Standalone ANTs using MNI152NLin2009cAsym template provided good enough brain masks but specifying ```--skull-strip-template MNI152NLin2009cAsym``` in fmriprep did not. So I tried to feed fmriprep with skull-stripped T1w, but it seems a brain mask is still estimated for skull-stripped T1w. I was expecting it will just take the contour of the skull-stripped T1w as the brain mask, is my understanding wrong or there is a potential bug? Maybe I missed something and there is a way to also feed the brain mask file? 

Btw, is there a way that I can conduct a 2 passes procedure in fmriprep? 1st pass just to complete all anat pipelines. After visual inspections, the 2nd pass will just continue to finish the rest func pipelines. This will save a lot of computation resources since brain extraction is at the beginning of the whole process and if it's bad the rest computations will be wasted, also one can only know it after all computations are finished. 

Thanks a lot.

### What command did you use?

```shell
fMRIPrep command: /opt/conda/bin/fmriprep -w /DATA/fmriprep_work --participant-label 055 --bids-filter-file /OUTPUT/bids_filters.json --skull-strip-t1w skip --output-spaces MNI152NLin2009cAsym MNI152NLin6Asym T1w fsnative fsaverage --output-layout bids --notrack --skip_bids_validation --write-graph --omp-nthreads 8 --nprocs 16 --mem_mb 65536 --resource-monitor /DATA/EEGfMRI /DATA/EEGfMRI/derivatives/fmriprep participant
```

### What version of fMRIPrep are you running?

20.2.5, 21.0.2, 22.0.0

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Additional information / screenshots

fmriprep with default ```--skull-strip-template``` and no skull-stripped T1w
![image](https://user-images.githubusercontent.com/29985544/182162769-a78406ef-4f4a-4d5c-979b-35f7b27b7edd.png)

fmriprep with ```--skull-strip-template MNI152NLin2009cAsym``` and no skull-stripped T1w
![image](https://user-images.githubusercontent.com/29985544/182161932-e4bef0ba-d922-4746-b3c8-09612acca94c.png)

Standalone ANTs
```
antsBrainExtraction.sh -d 3 -a sub-xx_T1w.nii.gz -e tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz -m tpl-MNI152NLin2009cAsym_res-01_desc-brain_probseg.nii.gz -o sub-xx_T1w_brain
```
![image](https://user-images.githubusercontent.com/29985544/182161872-0e15d660-00a3-4dd4-9f9f-5692fb3babfa.png)

20.2.5 with skull-stripped T1w resulted from standalone ANTs and ```--skull-strip-t1w skip ```
![image](https://user-images.githubusercontent.com/29985544/182161646-51aa318c-ed22-4fc1-b3b1-efc189e8cb39.png)

21.0.2 with skull-stripped T1w resulted from standalone ANTs and ```--skull-strip-t1w skip ```
![image](https://user-images.githubusercontent.com/29985544/182161684-cc10b2f1-1889-4c64-b768-e3233949b027.png)

22.0.0 with skull-stripped T1w resulted from standalone ANTs and ```--skull-strip-t1w skip ```
![image](https://user-images.githubusercontent.com/29985544/182161727-2171dd1c-3f9e-4acb-88f0-32da61bfcb52.png)

**Comment by mgxd** [comment]
If skipping skullstripping, a [modified brain extraction workflow](https://github.com/nipreps/niworkflows/blob/1f44298559cd3e8161c3fe9278e1037c39423d59/niworkflows/anat/ants.py#L881-L1049) is used and a brain mask is calculated from [binarizing the input image](https://github.com/nipreps/niworkflows/blob/1f44298559cd3e8161c3fe9278e1037c39423d59/niworkflows/anat/ants.py#L980) where values > 2.

> Btw, is there a way that I can conduct a 2 passes procedure in fmriprep? 

Yes, you can call fmriprep with the `--anat-only` flag to limit processing to just anatomicals. Then, if results look okay, you can add in the `--anat-derivatives` flag (followed by the path to the existing derivatives) to skip anatomical processing and just reuse the generated files

**Comment by zhengchencai** [comment]
Thanks a lot @mgxd 
> If skipping skullstripping, a [modified brain extraction workflow](https://github.com/nipreps/niworkflows/blob/1f44298559cd3e8161c3fe9278e1037c39423d59/niworkflows/anat/ants.py#L881-L1049) is used and a brain mask is calculated from [binarizing the input image](https://github.com/nipreps/niworkflows/blob/1f44298559cd3e8161c3fe9278e1037c39423d59/niworkflows/anat/ants.py#L980) where values > 2.

Please correct me if I misunderstand your point and the code. If I feed skull-stripped T1w, the brain mask is just binarized by intensity > 2? If so, I may not see it from what I got. In the following snapshot, brain mask ```_desc-brain_mask.nii.gz``` is superimposed on the brain image ```_desc-preproc_T1w.nii.gz``` from fmriprep's anat folder. I set the lowest intensity for the brain image to be 5, it is still larger than the mask. 
![image](https://user-images.githubusercontent.com/29985544/182266134-2d6652b1-5f56-4ee8-96f9-06070263b727.png)

And this red area is where intensity lower than 2 which indeed looks good but is different from ```_desc-brain_mask.nii.gz``` (blue, sorry for the inconsistent color coding)
![image](https://user-images.githubusercontent.com/29985544/182268883-a3e8317e-de23-41bf-b631-32cf38e02e0a.png)


> Yes, you can call fmriprep with the --anat-only flag to limit processing to just anatomicals. Then, if results look okay, you can add in the --anat-derivatives flag (followed by the path to the existing derivatives) to skip anatomical processing and just reuse the generated files

Thanks for this tip, this is great. If I may ask a bit more, does --anat-derivatives only accept a fully finished anat derivatives folder (containing brain mask, registration, freesurfer etc) or do we have the freedom to give a part of them? For instance, in my case, I could do brian extraction externally and arrange everything in fmriprep anat folder's way. Then one fmriprep launch with ```--anat-derivatives``` would just start after brain exaction. In this way, I can keep all original T1w in the BIDS data set, instead of some participants with original T1w, some with brain extracted T1w (failed in brain extractions by fmriprep).

**Comment by mgxd** [comment]
Ah, my mistake - since you are running FreeSurfer, we actually calculate and propagate a [different mask](https://github.com/nipreps/smriprep/blob/b29578ec45e51da63e5df6b47a8c88b02ae43acd/smriprep/workflows/surfaces.py#L239) generated from both the aseg + ants tissue segmentation. How does the `...desc-brain_mask.nii.gz` mask look like in relation to these files? In any case, this is something that we'll need to investigate.

> Thanks for this tip, this is great. If I may ask a bit more, does --anat-derivatives only accept a fully finished anat derivatives folder

ATM yes, it needs a fully completed smriprep run - but processing with just some of the anatomical derivatives (brainmask, aseg) is something we are hoping to add as it can be very useful, especially for challenging data.

**Comment by zhengchencai** [comment]
Thanks @mgxd. This is ```_desc-aseg_dseg.nii.gz``` (green + white) on top of ```_desc-brain_mask.nii.gz``` (red) and ```_desc-preproc_T1w.nii.gz```. As you mentioned, there is a tiny bit of difference between ```_desc-aseg_dseg.nii.gz``` and ```_desc-brain_mask.nii.gz```. Does this mean the problem is freesurfer estimated a bad brain mask although the one from ANTs is good? I thought the brain mask is fully determined by ANTs from the pipeline, maybe I am wrong again. 

![image](https://user-images.githubusercontent.com/29985544/182386628-b2b145c3-cb9e-4589-9b66-ca5565c2687d.png)

> ATM yes, it needs a fully completed smriprep run - but processing with just some of the anatomical derivatives (brainmask, aseg) is something we are hoping to add as it can be very useful, especially for challenging data.

Thanks for the confirmation. I guess then I stuck with these "challenging" cases. I've tried the following: 1) rerun multiple times fmriprep and hope some random initialization will grant me luck, which works for some cases but not all https://github.com/nipreps/niworkflows/issues/734 and https://neurostars.org/t/inaccurate-brain-mask-when-enabling-use-syn-sdc/22930 2) change skull stripping template, which worked with standalone ANTs but not in fmriprep 3) feed only brian T1w from ANTs, which is the case we are discussing now. Probably another way to try is to compute brain extraction with ANTs and Freesurfer, but I am not sure if there are other tricks to be able to arrange the results exactly following the structure of a fully completed smriprep run. Do you have any suggestions? Thanks again.

**Comment by mgxd** [comment]
How do the FS `mri/brainmask.mgz` and `mri/brainmask.auto.mgz` look?

If they look decent, this subject may just require some manual intervention to help recon-all correctly identify the white matter, the contrast near some edges is not very defined - see https://andysbrainbook.readthedocs.io/en/latest/FreeSurfer/FS_ShortCourse/FS_14_ControlPoints.html for more information.

I would try:
- running these edits on the `sourcedata/freesurfer` directory directly
- if/once you are satisfied with the FS outputs, rerun fmriprep with the `--fs-subjects-dir <fs-directory>` argument. you may need to clear the working directory to avoid reusing previous files

**Comment by zhengchencai** [comment]
Thanks @mgxd. The brain masks (red) in the FS folder look fine, I assume it is just the binarization with intensity > 2.
mri/brainmask.mgz
![image](https://user-images.githubusercontent.com/29985544/182404192-6e3cf3d1-8133-4c2b-9985-f9c835d0de36.png)
mri/brainmask.auto.mgz
![image](https://user-images.githubusercontent.com/29985544/182404625-0695f1db-0b1a-4975-850b-2833dfdc5a2d.png)

> running these edits on the sourcedata/freesurfer directory directly

This is great and sounds promising, I will give it a try and update it here. 

> if/once you are satisfied with the FS outputs, rerun fmriprep with the --fs-subjects-dir <fs-directory> argument. you may need to clear the working directory to avoid reusing previous files

Just to get your confirmation, for challenging cases I should 
run brain extraction with ANTs and FS prior to fmriprep >>> edit Control Points and rerun recon-all >>> fmriprep with ```--fs-subjects-dir <fs-directory>```

Thanks a lot for the help.
