### ISSUE TITLE
Full freesurfer longitudinal output

### ISSUE THREAD

**Issue by butellyn** [nipreps/fmriprep#2829]
### What would you like to see added in fMRIPrep?

I've noticed that when I run fmriprep with the `--longitudinal` flag, it does not include the individual session structural output from freesurfer. My understanding is that the freesurfer longitudinal pipeline runs the full cross-sectional pipeline on all sessions, and creates an unbiased single subject template. I also don't see much freesurfer output at all. Does fmriprep clean out most of the freesurfer output when you run it with the `--longitudinal` flag? It would be nice to have all of it. Below is my call, and my general output:

```
SINGULARITYENV_TEMPLATEFLOW_HOME=/home/fmriprep/.cache/templateflow \
     singularity run --writable-tmpfs --cleanenv --containall \
     -B /tmp:/tmp -B /projects/b1108:/projects/b1108 \
     -B /projects/b1108/software/freesurfer_license/license.txt:/opt/freesurfer/license.txt \
     -B /projects/b1108/templateflow:/home/fmriprep/.cache/templateflow \ 
     /projects/b1108/software/singularity_images/fmriprep_21.0.2.sif \ 
     /projects/b1108/studies/mwmh/data/raw/neuroimaging/bids/ \
     /projects/b1108/studies/mwmh/data/processed/neuroimaging/fmriprep/ participant --participant-label MWMH352 \
     --longitudinal --nprocs=1 --omp-nthreads=1 \
     -w /projects/b1108/studies/mwmh/data/processed/neuroimaging/work2 \
     --fs-license-file /opt/freesurfer/license.txt --output-spaces MNI152NLin6Asym \
     --skull-strip-template OASIS30ANTs
```

Output:
<img width="1229" alt="Screen Shot 2022-08-01 at 4 45 35 PM" src="https://user-images.githubusercontent.com/41019524/182251787-3792616f-1242-43c4-b4e6-d0fbcab0482f.png">
<img width="540" alt="Screen Shot 2022-08-01 at 4 46 05 PM" src="https://user-images.githubusercontent.com/41019524/182251802-d0b14560-6715-4618-8586-3e3a437e546c.png">

### Do you have any interest in helping implement the feature?

Yes, but I would need guidance

**Comment by effigies** [comment]
Missed this when coming back from summer vacation, apologies. I think this is going to be possible in the near future with https://github.com/nipy/nipype/pull/3529. We will need assistance from somebody familiar with FreeSurfer longitudinal to implement it, however.

**Comment by effigies** [comment]
Further discussion should take place in https://github.com/nipreps/smriprep/issues/21.
