### ISSUE TITLE
Edge-comp regressors not included in confounds files

### ISSUE THREAD

**Issue by sjw42** [nipreps/fmriprep#2831]
### What happened?

I just started preprocessing a data set with fMRIPrep version 22.0.0 and am interested in exploring the newly added edge regressors. However, the edge-comp regressors are not included in the confounds tsv files. I have pasted the headers from one of the confounds files at the bottom of this post. Information about the 24 edge components is included in the corresponding confounds json files and they are listed as retained; e.g.
  "edge_comp_00": {
    "CumulativeVarianceExplained": 0.0865755779,
    "Mask": "Edge",
    "Method": "EdgeRegressor",
    "Retained": true,
    "SingularValue": 404.9880253639,
    "VarianceExplained": 0.0865755779

------headers from sample confounds file------
global_signal
global_signal_derivative1
global_signal_derivative1_power2
global_signal_power2
csf
csf_derivative1
csf_derivative1_power2
csf_power2
white_matter
white_matter_derivative1
white_matter_derivative1_power2
white_matter_power2
csf_wm
tcompcor
std_dvars
dvars
framewise_displacement
rmsd
t_comp_cor_00
t_comp_cor_01
c_comp_cor_00
c_comp_cor_01
c_comp_cor_02
c_comp_cor_03
c_comp_cor_04
c_comp_cor_05
c_comp_cor_06
w_comp_cor_00
w_comp_cor_01
w_comp_cor_02
w_comp_cor_03
w_comp_cor_04
w_comp_cor_05
w_comp_cor_06
w_comp_cor_07
w_comp_cor_08
w_comp_cor_09
w_comp_cor_10
w_comp_cor_11
w_comp_cor_12
w_comp_cor_13
w_comp_cor_14
w_comp_cor_15
w_comp_cor_16
w_comp_cor_17
w_comp_cor_18
w_comp_cor_19
w_comp_cor_20
w_comp_cor_21
w_comp_cor_22
w_comp_cor_23
w_comp_cor_24
w_comp_cor_25
w_comp_cor_26
w_comp_cor_27
w_comp_cor_28
w_comp_cor_29
w_comp_cor_30
w_comp_cor_31
w_comp_cor_32
w_comp_cor_33
w_comp_cor_34
w_comp_cor_35
w_comp_cor_36
w_comp_cor_37
w_comp_cor_38
w_comp_cor_39
w_comp_cor_40
w_comp_cor_41
w_comp_cor_42
w_comp_cor_43
w_comp_cor_44
w_comp_cor_45
w_comp_cor_46
w_comp_cor_47
w_comp_cor_48
a_comp_cor_00
a_comp_cor_01
a_comp_cor_02
a_comp_cor_03
a_comp_cor_04
a_comp_cor_05
a_comp_cor_06
a_comp_cor_07
a_comp_cor_08
a_comp_cor_09
a_comp_cor_10
a_comp_cor_11
a_comp_cor_12
a_comp_cor_13
a_comp_cor_14
a_comp_cor_15
a_comp_cor_16
a_comp_cor_17
a_comp_cor_18
a_comp_cor_19
a_comp_cor_20
a_comp_cor_21
a_comp_cor_22
a_comp_cor_23
a_comp_cor_24
a_comp_cor_25
a_comp_cor_26
a_comp_cor_27
a_comp_cor_28
a_comp_cor_29
a_comp_cor_30
a_comp_cor_31
a_comp_cor_32
a_comp_cor_33
a_comp_cor_34
a_comp_cor_35
a_comp_cor_36
a_comp_cor_37
a_comp_cor_38
a_comp_cor_39
a_comp_cor_40
a_comp_cor_41
a_comp_cor_42
a_comp_cor_43
a_comp_cor_44
a_comp_cor_45
a_comp_cor_46
a_comp_cor_47
cosine00
cosine01
cosine02
cosine03
non_steady_state_outlier00
non_steady_state_outlier01
non_steady_state_outlier02
non_steady_state_outlier03
trans_x
trans_x_derivative1
trans_x_derivative1_power2
trans_x_power2
trans_y
trans_y_derivative1
trans_y_derivative1_power2
trans_y_power2
trans_z
trans_z_derivative1
trans_z_derivative1_power2
trans_z_power2
rot_x
rot_x_derivative1
rot_x_derivative1_power2
rot_x_power2
rot_y
rot_y_derivative1
rot_y_derivative1_power2
rot_y_power2
rot_z
rot_z_derivative1
rot_z_power2
rot_z_derivative1_power2
motion_outlier00
motion_outlier01
motion_outlier02
motion_outlier03
motion_outlier04
motion_outlier05
motion_outlier06
motion_outlier07
motion_outlier08
motion_outlier09
motion_outlier10
motion_outlier11
motion_outlier12
motion_outlier13
motion_outlier14
motion_outlier15
motion_outlier16
motion_outlier17
motion_outlier18
motion_outlier19
motion_outlier20
motion_outlier21
motion_outlier22
motion_outlier23
motion_outlier24
motion_outlier25
motion_outlier26
motion_outlier27
motion_outlier28
motion_outlier29
motion_outlier30
motion_outlier31
motion_outlier32
motion_outlier33
motion_outlier34
motion_outlier35
motion_outlier36
motion_outlier37
motion_outlier38
motion_outlier39
motion_outlier40
motion_outlier41
motion_outlier42
motion_outlier43
motion_outlier44
motion_outlier45
motion_outlier46
motion_outlier47
motion_outlier48
motion_outlier49
motion_outlier50
motion_outlier51
motion_outlier52
motion_outlier53
motion_outlier54
motion_outlier55
motion_outlier56
motion_outlier57
motion_outlier58
motion_outlier59
motion_outlier60
aroma_motion_01
aroma_motion_02
aroma_motion_03
aroma_motion_04
aroma_motion_05
aroma_motion_06
aroma_motion_08
aroma_motion_09
aroma_motion_10
aroma_motion_11
aroma_motion_12
aroma_motion_16
aroma_motion_21
aroma_motion_25
aroma_motion_27
aroma_motion_28
aroma_motion_29
aroma_motion_30
aroma_motion_31
aroma_motion_33

### What command did you use?

```shell
singularity run --cleanenv /gpfs/group/sjw42/default/sjw42_collab/sw/singularity/fmriprep/fmriprep_v22.0.0.sif
–participant_label 102
–nthreads 4
–omp-nthreads 3
–low-mem
–skip_bids_validation
–verbose
–longitudinal
–dummy-scans 4
–use-aroma
–output-layout legacy
–output-spaces MNI152NLin6Asym:res-2 MNI152NLin6Asym:res-native
–fs-license-file /gpfs/group/sjw42/default/sjw42_collab/sw/freesurfer-6.0.1/license.txt
–work /gpfs/group/sjw42/default/ASH/DVAL/work
/gpfs/group/sjw42/default/ASH/DVAL/bids
/gpfs/group/sjw42/default/ASH/DVAL/bids/derivatives
participant
```

### What version of fMRIPrep are you running?

22.0.0

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by burdinskid13** [comment]
In version 22.0.2 I am still experiencing this issue. Is there a timeline for resolving this? I am very excited to use the edge regressors in my analysis!

**Comment by effigies** [comment]
Ah, thanks for bumping this. Let me have a quick look and see how difficult this would be to fix...

**Comment by effigies** [comment]
Okay, I think it's as simple as #2897. Let's let it run and make sure they're in the CI derivatives.
