### ISSUE TITLE
fmriprep 22.0 error in _parcstats0 and _parcstats1

### ISSUE THREAD

**Issue by jvdstock** [nipreps/fmriprep#2832]
command:
/opt/conda/bin/fmriprep /data /out participant --participant-label sub-control01 --use-aroma --skip-bids-validation --output-spaces MNI152NLin6Asym:res-2 MNI152NLin2009cAsym

error 1:

File: /out/sub-control01/log/20220804-133845_ce3d05eb-af3f-483f-b763-b32de1ca9257/crash-20220804-163838-root-_parcstats0-e1124134-a371-4b7f-a10c-82b668d91849.txt
Working Directory: /tmp/work/fmriprep_22_0_wf/single_subject_control01_wf/anat_preproc_wf/surface_recon_wf/autorecon_resume_wf/parcstats/mapflow/_parcstats0
Inputs:
FLAIR_file:
T1_files:
T2_file:
args:
big_ventricles:
brainstem:
directive: autorecon-hemi
environ: {}
expert:
flags: ['-nohyporelabel']
hemi: lh
hippocampal_subfields_T1:
hippocampal_subfields_T2:
hires:
mprage:
mri_aparc2aseg:
mri_ca_label:
mri_ca_normalize:
mri_ca_register:
mri_edit_wm_with_aseg:
mri_em_register:
mri_fill:
mri_mask:
mri_normalize:
mri_pretess:
mri_remove_neck:
mri_segment:
mri_segstats:
mri_tessellate:
mri_watershed:
mris_anatomical_stats:
mris_ca_label:
mris_fix_topology:
mris_inflate:
mris_make_surfaces:
mris_register:
mris_smooth:
mris_sphere:
mris_surf2vol:
mrisp_paint:
openmp: 8
parallel:
steps:
subject_id: sub-control01
subjects_dir: /out/sourcedata/freesurfer
talairach:
use_FLAIR:
use_T2:
xopts:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node _parcstats0.

RuntimeError: subprocess exited with code 1.

Error 2:
File: /out/sub-control01/log/20220804-133845_ce3d05eb-af3f-483f-b763-b32de1ca9257/crash-20220804-164048-root-_parcstats1-dacda919-2fb9-469d-b682-a210e5798d10.txt
Working Directory: /tmp/work/fmriprep_22_0_wf/single_subject_control01_wf/anat_preproc_wf/surface_recon_wf/autorecon_resume_wf/parcstats/mapflow/_parcstats1
Inputs:
FLAIR_file:
T1_files:
T2_file:
args:
big_ventricles:
brainstem:
directive: autorecon-hemi
environ: {}
expert:
flags: ['-nohyporelabel']
hemi: rh
hippocampal_subfields_T1:
hippocampal_subfields_T2:
hires:
mprage:
mri_aparc2aseg:
mri_ca_label:
mri_ca_normalize:
mri_ca_register:
mri_edit_wm_with_aseg:
mri_em_register:
mri_fill:
mri_mask:
mri_normalize:
mri_pretess:
mri_remove_neck:
mri_segment:
mri_segstats:
mri_tessellate:
mri_watershed:
mris_anatomical_stats:
mris_ca_label:
mris_fix_topology:
mris_inflate:
mris_make_surfaces:
mris_register:
mris_smooth:
mris_sphere:
mris_surf2vol:
mrisp_paint:
openmp: 8
parallel:
steps:
subject_id: sub-control01
subjects_dir: /out/sourcedata/freesurfer
talairach:
use_FLAIR:
use_T2:
xopts:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node _parcstats1.

RuntimeError: subprocess exited with code 1.

**Comment by jbwexler** [comment]
I'm getting this error as well for every dataset I've tried with v22.0.0

https://github.com/poldracklab/tacc-openneuro/issues/23

**Comment by mgxd** [comment]
hi @jvdstock - do you happen to be running with older `fsaverage` directories? FS7 cannot reuse any `fsaverage` directories from previous FS versions - If you just remove the fsaverage/fsaverage5 directories, then fMRIPrep can copy the new ones for you.

**Comment by effigies** [comment]
@mgxd Should we look for `FG1.mpm.vpnl` ourselves and issue our own warning? This is pretty nasty to ask users to debug, since it gets hidden in the FS log files.

**Comment by mgxd** [comment]
yes, we should definitely catch this in future versions
