### ISSUE TITLE
TOPUP issues in functionals, even though the topup field looks reasonable

### ISSUE THREAD

**Issue by cmpetty** [nipreps/fmriprep#2835]
We have some pretty severely distorted images because of a protocol mistake, but we're trying to make the best of them.

PEPolar images below:
![Screen Shot 2022-08-15 at 6 11 25 PM](https://user-images.githubusercontent.com/2243287/185400369-0eebfd53-7565-47c8-bfb3-3e615874ba59.png)

The actual SDC correction looks reasonable on the pepolar images: 
<img width="1395" alt="Screen Shot 2022-08-18 at 9 17 47 AM" src="https://user-images.githubusercontent.com/2243287/185404567-83939337-dd08-4d9a-bbbf-7215163d38bb.png">

However, when the field is applied to the functionals things go wrong:
<img width="1395" alt="Screen Shot 2022-08-18 at 9 18 26 AM" src="https://user-images.githubusercontent.com/2243287/185404712-a97efd1e-2dbc-400e-9582-0ff8dfc39499.png">

I've verified the PE directions and the readouts are correct.  I've limited the number of topup volumes to use, just as a test, which didn't matter.  I've tracked that the images look normal up until the "unwarp_wf" stage.

I'm using v21.0.2 via singularity containers with the command below:
`
${PACKDIR}/singularity/bin/singularity run --cleanenv -B $PACKDIR:/mnt/packages \
 ${PACKDIR}/singularity/images/fmriprep-v21.0.2.sif \
 /mnt/munin/Neacsiu/${EXPERIMENT}/Data/BIDS/TMSCR \
 /mnt/munin/Neacsiu/${EXPERIMENT}/Data/BIDS/fmriprep \
 participant --participant-label ${SUBJ} \
 --nthreads 12 --omp-nthreads 12 --skip_bids_validation \
 --use-aroma --aroma-melodic-dimensionality 30 \
 --fs-no-reconall \
 --output-spaces MNI152NLin2009cAsym:res-02 \
 --work-dir /mnt/munin/Neacsiu/${EXPERIMENT}/Analysis/work \
 --topup-max-vols 1 \
`

Outside of fmriprep i have run topup myself, with the same inputs and the resulting images looks as good as can be expected:
`topup --verbose --imain=bud --datain=acq_params.txt --config=$FSLDIR/src/topup/flirtsch/b02b0.cnf --out=rs_topup --fout=topup_field

applytopup --imain=../bia6_00186_004_01.nii.gz --inindex=1 --method=jac --datain=func_params.txt --topup=rs_topup --out=run004 --verbose
`

<img width="693" alt="Screen Shot 2022-08-17 at 9 49 33 AM" src="https://user-images.githubusercontent.com/2243287/185402178-a0095699-017c-4b85-83d4-b784ce25d4c5.png">

If i look at my topup field side-by-side with the fmriprep version, it appears the fmriprep is being stretched and potentially flipped somewhere:
<img width="1395" alt="Screen Shot 2022-08-18 at 9 12 18 AM" src="https://user-images.githubusercontent.com/2243287/185403591-1207a447-429d-43fd-8921-0bea781a65b1.png">

As a sanity check, i went back to v20.#.# where AFNI could be used for pepolar correction and the results seem reasonable with no other variations to my fmriprep call, except the -max-topup-vols:
<img width="1395" alt="Screen Shot 2022-08-18 at 9 19 29 AM" src="https://user-images.githubusercontent.com/2243287/185404967-7b01bffe-a1bb-4c63-9e88-0a48eb17786d.png">

Just looking for some guidance on where the fieldmap correction may be going wrong and how to get a clean run.

**Comment by oesteban** [comment]
Thanks much for reporting @cmpetty.

May I ask you to re-run this participant with the argument ``--debug fieldmaps`` added? Then, please double check the fieldmap report (the one you pasted under _The actual SDC correction looks reasonable on the pepolar images:_).

You're right it seems TOPUP is performing properly. Let's now see whether SDCFlows is doing an appropriate handling of the fieldmap.

**Comment by oesteban** [comment]
Sorry, I'm still digesting all the info in your post (thanks for the thoroughness, it's really useful!)

> If i look at my topup field side-by-side with the fmriprep version, it appears the fmriprep is being stretched and potentially flipped somewhere:

I would not expect any meaningful change, but just to be sure: could you regenerate one of the figures at the same z-slice?

**Comment by cmpetty** [comment]
i ran v22 with the debug fieldmaps option, but i didn't see any debug info in the report

I uploaded the results and my own topup run here:
[https://github.com/cmpetty/fmriprep_debugging](url) 

A couple observations i noticed when debugging.

When i ran topup with the merged fieldmaps that fmriprep produced, my results looked identical ( poor ).  fmriprep merged them as PA, AP.  The functionals were acquired AP.

![Screen Shot 2022-09-02 at 10 22 49 AM](https://user-images.githubusercontent.com/2243287/188221807-29cd4348-8ff8-4c2e-8000-fe428847a156.png)

When i re-ordered the pepolar images to be AP, PA ( like my original post ) my topup results looked better:
![Screen Shot 2022-09-02 at 3 14 09 PM](https://user-images.githubusercontent.com/2243287/188222033-15ff4cd6-5caf-432d-b857-0c94f8afcb58.png)

A side-by-side of my topup_field and fmriprep's "corrected field":
![Screen Shot 2022-09-02 at 10 19 54 AM](https://user-images.githubusercontent.com/2243287/188222326-ff394e58-7f6a-433d-887a-0669219514ec.png)

A side-by-side of my topup field and the results from topup, using the PA/AP ordered blips:
![Screen Shot 2022-09-02 at 3 31 58 PM](https://user-images.githubusercontent.com/2243287/188224503-953c2996-ed61-44cb-9557-7a6de5496c60.png)

`topup --verbose --imain=sub-3152_ses-intake_acq-orig_dir-PA_epi_merged_volreg.nii.gz --datain=acq_params_fmrip.txt --config=$FSLDIR/src/topup/flirtsch/b02b0.cnf --out=rs_topup_fmrip --fout=topup_field_fmrip
`

A side-by-side of the applied topup field AP/PA ( mine ) and PA/AP ( fmriprep ) on the mean image:

![Screen Shot 2022-09-02 at 3 45 40 PM](https://user-images.githubusercontent.com/2243287/188226255-489e8075-f334-4891-be9d-e1ab3f1bf6ea.png)

the 2nd one is consistent with the fmriprep v21+ output and the first is what i would've expected.

**Comment by julfou81** [comment]
Very interesting case and discussion. Thank you for all this reporting. 
I don't have any solution to propose but rather some thinking about all this.
The different behavior of topup depending of the order of the AP/PA merge may have to do with the fact that the first volume of this merge will define the space in which the distorsion field will be calculated. 
Also, in such a strong distorsion case, it could be that the regular topup parameters (defined in the b02b0.cnf file) are not optimal and the topup calculation stopped two soon. I guess that if you look at the corrected AP images, they must be still quite different from the corrected PA images at the end of topup execution.
What could be the solution for you? Using fmriprep, as it stands, as you noticed in such extreme case, 3dQwarp from AFNI may give better results (with standard parameters in both case). One solution could be to feed FMRIPREP v21+ with specific topup configuration file when needed but it is not possible as of now. You could try the Fieldmapless option but I am pessimistic on this,  from personal experience it did not work well for cases with similar extreme distortions (also a mistake in the acquisition with of shimming box much too small).

**Comment by Ludoalevesque** [comment]
Hi,
We are also experimenting a similar issue with our fMRI data. We have some heavily distorted data for some subjects. Here is an example of the raw data for both phase directions (the fMRI was acquired PA) :
  
<img width="956" alt="sub-10_bold_raw" src="https://github.com/nipreps/fmriprep/assets/122315006/28dbe005-2509-4cd7-843c-291b18a135db">
<img width="958" alt="sub-10_rev_raw" src="https://github.com/nipreps/fmriprep/assets/122315006/42a223f8-f7d2-4d2e-922a-a92fe262a1ad">

After running fmriprep we had weird results for the SDC. Here is the bold ref and the preprocessed bold as outputted by fmriprep :
 
<img width="959" alt="sub-10_fmriprep_orig_boldref" src="https://github.com/nipreps/fmriprep/assets/122315006/2742f563-3c86-412b-8d17-326e99dc2dcd">
<img width="957" alt="sub-10_fmriprep_orig_preproc-bold" src="https://github.com/nipreps/fmriprep/assets/122315006/6502f1b6-6526-43c8-8b13-bfb13f36583a">


We also noticed that the fmap outputs were weird, as you can see in the fmap coefficient image :
<img width="956" alt="sub-10_fmriprep_orig_fmap_coef" src="https://github.com/nipreps/fmriprep/assets/122315006/9d5c99f4-4e39-4493-a310-1931475b3b36">
 

We were also told this might have something to do with skull striping, so we tried to run bet on the both the BOLD and the reverse images before fmriprep. Here is what it did.
Fieldmap coefficient:
 
<img width="956" alt="sub-10_fmriprep_bet-both_fmap_coef" src="https://github.com/nipreps/fmriprep/assets/122315006/fbc7c9ea-5ab2-44aa-8a79-ac2b8458043b">

This image seemed better than what we had previously, but the bold ref and the preprocessed bold were still showing some weird artifacts.
Bold ref:  
<img width="958" alt="sub-10_fmriprep_bet-both_boldref" src="https://github.com/nipreps/fmriprep/assets/122315006/8d276174-9b36-4d46-984d-620be9189fb4">

Preprocessed bold:
 
<img width="956" alt="sub-10_fmriprep_bet-both_preproc-bold" src="https://github.com/nipreps/fmriprep/assets/122315006/e57f44f0-23af-48c4-a289-fa6e7f44f6d2">


Considering that functional inputs for fmriprep should not normally be processed data, we tried to run fmriprep on the raw bold, but in the fmap folder, we kept the brain extracted reverse epi, to see if the results were better. 
 
 
<img width="955" alt="sub-10_fmriprep_bet-rev_fmap_coef" src="https://github.com/nipreps/fmriprep/assets/122315006/eaafd6ef-e1af-40d5-9c93-0fe55e47d32f">
<img width="956" alt="sub-10_fmriprep_bet-rev_boldref" src="https://github.com/nipreps/fmriprep/assets/122315006/8a6c6b82-6eff-494b-be79-6021bb07d3da">
<img width="956" alt="sub-10_fmriprep_bet-rev_preproc-bold" src="https://github.com/nipreps/fmriprep/assets/122315006/175ab05f-0194-4777-8a6a-630228667981">

 
Surprisingly, the results look a bit better in the prefrontal cortex, but we don’t really understand why …


We also ran topup on our own and the results also seemed better:
 
<img width="958" alt="sub-10_topup_coef" src="https://github.com/nipreps/fmriprep/assets/122315006/b1e946b4-f213-4732-b620-e53014851744">
<img width="958" alt="sub-10_topup_corrected" src="https://github.com/nipreps/fmriprep/assets/122315006/5428e2f7-d626-40eb-96f9-b73e5aa26190">
*this one looks a bit different from the other fmriprep outputs, but keep in mind that this is in native space while fmriprep outputs are not.

We don’t really understand what is happening. We hope that brings more information to the issue and that someone can give us more insight on where this problem might be coming from. Thank you !

**Comment by effigies** [comment]
This seems to be the same as https://github.com/nipreps/fmriprep/issues/3013. The issue appears to be with the Jacobian correction, which we have been omitting. We need to resolve this soon, because these distortions are part of the correction process, and they need to be attenuated by applying a Jacobian weighting.

**Comment by effigies** [comment]
This should be resolved in 23.2.0a1.
