### ISSUE TITLE
desc-preproc_bold.nii.gz contains more all zero value voxels than the original bold 22.0.0

### ISSUE THREAD

**Issue by zhengchencai** [nipreps/fmriprep#2837]
### What happened?

Hello,

I am not sure if this could be an issue but I couldn't find a good explanation, so just in case your think it's worth checking. 

In one of my BOLD run, ```orig_bold.nii.gz``` (dim 64 x 64 x 25 x 200, res 5 x 5 x 5 x 1.75), there are 1600 voxels whose values are always 0 (200 zeros). This is fine since all these voxels' x index is 1, so it just appears in the first yz slice. However, there are 4913 such voxels after fmriprep, ```space-T1w_desc-preproc_bold.nii.gz``` (dim 31 x 38 x 29 x 200, res 5 x 5 x 5 x 1.75), and they are not only in one or a few slices, but distributed widely (the length of unique values of x, y, z index for these all zeros values are almost the image dim). 

This is a dirty visualization simply overlaid these all zero voxels (black) on ```orig_bold.nii.gz``` in FSLeye, some are around the border of the brain mask
![image](https://user-images.githubusercontent.com/29985544/186491879-8058e9d4-6898-43a5-9328-5c71deee6069.png)

Here is another slice and overlaid on T1w
![image](https://user-images.githubusercontent.com/29985544/186493391-49a38479-2b9c-4c25-8118-0057ca3f64ec.png)

I'm not sure how fmriprep is interpolating BOLD after coregistration, how could we have more all zero value voxels after it, especially ```space-T1w_desc-preproc_bold.nii.gz``` has fewer voxels than the original one? I confirm that the brain mask and registration QC are good. 

This issue only happens in 22.0.0, for 20.2.5 there are no all zero values voxel in ```space-T1w_desc-preproc_bold.nii.gz```. 

Please find the demo files [here](https://drive.google.com/drive/folders/1JML-kdk_Nf1JDNlTT99_EOXYXowNPzij?usp=sharing) 

Thanks

### What command did you use?

```shell
fMRIPrep command: /opt/conda/bin/fmriprep -w /DATA/fmriprep_work --participant-label 055 --bids-filter-file /OUTPUT/bids_filters.json --skull-strip-t1w skip --output-spaces MNI152NLin2009cAsym MNI152NLin6Asym T1w fsnative fsaverage --output-layout bids --notrack --skip_bids_validation --write-graph --omp-nthreads 8 --nprocs 16 --mem_mb 65536 --resource-monitor /DATA/EEGfMRI /DATA/EEGfMRI/derivatives/fmriprep participant
```

### What version of fMRIPrep are you running?

22.0.0

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by effigies** [comment]
Just having a quick look, I'm guessing that the majority are near the superior-anterior and inferior-posterior edges. Note the jagged lines at the bottom and top. The red is probably where your original bounding box was, and the jagged lines are where the new bounding box is disjoint, so the interpolated values there would have had no source data.

**Comment by zhengchencai** [comment]
Thanks @effigies, I agree with your explanation for edges of the FOV, but what about the ones near the brain mask edge? They are sort of surrounded by voxels with non-zero values and become all 0 after interpolation. It seems nearest neighbor interpolation might have resulted in this, for a linear or kernel-based one it would be hard to get exact 0 values by chance unless all neighbors are 0s. 
Here is the same run after 20.2.5, there are no 0 values after interpolation. The min intensity is around -32. FSLeye min intensity is set to be 0 so the black "hole" show negative values voxels. Is it possible that 22.0.0 kind of sets these negative voxels to be 0? Thanks. 

![image](https://user-images.githubusercontent.com/29985544/186740245-0f21652c-02ce-469f-a857-b8f156ee2c13.png)

**Comment by effigies** [comment]
Very likely what's happening there is actually ringing where values went slightly below 0, which can happen with LanczosWindowedSinc interpolation. We do clip any negative values to 0.

**Comment by zhengchencai** [comment]
Thanks @effigies. In case it would be helpful. I checked the original BOLD in which all values across time and space are non-negative. If I assume 20.2.5 and 22.0.0 are doing the same Lanczos interpolation and 22.0.0 adds an extra step to clip negative values to 0, I am not sure this is necessary, or maybe clip or not should be decided by users depending on specific postprocessing? Negative values are just caused by Lanczos which is normal since it changes the value range, but clip negative to 0 will remove voxels that were not negative in the raw image and they will not be effective in later analysis. I am not sure if all these negative voxels are simply low SNR ones, my gut feeling is that they are voxels with low intensity and high contrast to neighbors (sort of Lanczos's behavior). They are very few voxels (in this case ~13 if I remember) inside the brain mask which may or may not influence the final inference. If non-negative values are not preferred, adding a global DC offset back might be safer. For postprocessing using AFNI, the signal will be converted to percentages so negative DC will not influence.
