### ISSUE TITLE
Preprocessing did not finish successfully. Errors occurred while processing data from participants: mp0001 (31)

### ISSUE THREAD

**Issue by roya2022** [nipreps/fmriprep#2838]
Hello,
I'm trying to work with fmriperp through docker on my local cm
runnig this code for one subject;

docker run -ti --rm -v $HOME/sample6/sub-0001:/data:ro\ -v $HOME/output4:/out -v $HOME/freesurfer/license.txt:/opt/freesurfer/license.txt nipreps/fmriprep:latest /data   /out   participant  --participant_label sub-0001 --skip-bids-validation

I faced the first error;

raise BIDSValidationError(
bids.exceptions.BIDSValidationError: 'dataset_description.json' is missing from project root. Every valid BIDS dataset must have this file.
Example contents of 'dataset_description.json': 
{"Name": "Example dataset", "BIDSVersion": "1.0.2"}

after that I try to find a json file to fix this program

I used a json file that I've had already from the past of the data of oppenneuro
and used this code;

 docker run -ti --rm     -v $HOME/emocog:/data:ro     -v $HOME/output5:/out     -v $HOME/freesurfer/license.txt:/opt/freesurfer/license.txt     nipreps/fmriprep:latest     /data   /out     participant --participant_labe mp0001 --skip-bids-validation

now I faced this error

Preprocessing did not finish successfully. Errors occurred while processing data from participants: mp0001 (31). Check the HTML reports for details.

I'm trying to learn working with fmriprep and I dont know how much my question is travial or inappropriate
I'm really appreciative of your time and consideration

Best,
Roya

**Comment by roya2022** [comment]
The error I encountered referred to this statement; Check the HTML reports for details.
but I couldn't find  HTML reports

**Comment by effigies** [comment]
HTML reports are the `sub-*.html` files in the output directory. If this is still an issue, please open a new one with details of the error.
