### ISSUE TITLE
auto-recon error

### ISSUE THREAD

**Issue by juansanchezpena** [nipreps/fmriprep#2861]
### What happened?

Freesurfer failed 

### What command did you use?

```shell
/usr/local/pipelines/subfmri-arg_22.0.0rc2 -i /MRI_DATA/nyspi/patensasc/rawdata -o /MRI_DATA/nyspi/patensasc/derivatives -l /MRI_DATA/nyspi/patensasc/derivatives/fmriprep/logs/patensasc85.log -a "--participant-label patensasc0085  --output-spaces T1w MNI152NLin2009cAsym:res-2 --cifti-output   --output-layout legacy"
```

### What version of fMRIPrep are you running?

version = "22.0.1"

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
[juan@doctor 20220926-165232_81ad38b9-f534-4d34-a5c4-dc2190e64255]$ vi crash-20220926-211012-root-_autorecon_surfs1-ca61ff48-494c-4a5a-9931-22bef4f81957.txt 

mri_fill = <undefined>
mri_mask = <undefined>
mri_normalize = <undefined>
mri_pretess = <undefined>
mri_remove_neck = <undefined>
mri_segment = <undefined>
mri_segstats = <undefined>
mri_tessellate = <undefined>
mri_watershed = <undefined>
mris_anatomical_stats = <undefined>
mris_ca_label = <undefined>
mris_fix_topology = <undefined>
mris_inflate = <undefined>
mris_make_surfaces = <undefined>
mris_register = <undefined>
mris_smooth = <undefined>
mris_sphere = <undefined>
mris_surf2vol = <undefined>
mrisp_paint = <undefined>
openmp = 8
parallel = <undefined>
steps = <undefined>
subject_id = sub-patensasc0085
subjects_dir = /output/freesurfer
talairach = <undefined>
use_FLAIR = <undefined>
use_T2 = <undefined>
xopts = <undefined>

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node _autorecon_surfs1.

RuntimeError: subprocess exited with code 1.
```

**Comment by effigies** [comment]
Thanks for this. Can you check the `freesurfer/sub-patensasc0085/scripts/recon-all-*.log` files and see if there's an error reported by FreeSurfer?

And could you share the contents of `/usr/local/pipelines/subfmri-arg_22.0.0rc2`? I can make suggestions of how to debug the issue in Docker, but not if I don't know the full command.

**Comment by juansanchezpena** [comment]
nohup /usr/bin/docker service create --replicas 1 --reserve-cpu 8 --reserve-memory 16g --mode replicated --restart-condition none  --mount type=bind,source=$indir,destination=/input,readonly=true --mount type=bind,source=$outdir,destination=/output  --mount type=bind,source=/MRI_DATA/freesurferlicense.txt,destination=/opt/freesurfer/license.txt,readonly=true  nipreps/fmriprep:22.0.0rc2  /input /output participant $addarg
11:56<https://nyspimri.slack.com/archives/D02E31U778W/p1664294202034569>
should we try with more reserve memory?


***@***.*** scripts]$ cat recon-all-*.log | grep ERROR

recon-all -s sub-patensasc0085 exited with ERRORS at Mon Sep 26 21:11:58 UTC 2022

recon-all -s sub-patensasc0085 exited with ERRORS at Mon Sep 26 21:10:10 UTC 2022

recon-all -s sub-patensasc0085 exited with ERRORS at Mon Sep 26 21:11:58 UTC 2022

recon-all -s sub-patensasc0085 exited with ERRORS at Mon Sep 26 21:10:10 UTC 2022



***@***.*** scripts]$ cat recon-all-*.log | grep error

inflating to sphere (rms error < 2.00)

000: dt: 0.0000, rms radial error=175.788, avgs=0

005/300: dt: 0.9000, rms radial error=175.527, avgs=0

010/300: dt: 0.9000, rms radial error=174.967, avgs=0

015/300: dt: 0.9000, rms radial error=174.232, avgs=0

020/300: dt: 0.9000, rms radial error=173.396, avgs=0

025/300: dt: 0.9000, rms radial error=172.502, avgs=0

030/300: dt: 0.9000, rms radial error=171.576, avgs=0

035/300: dt: 0.9000, rms radial error=170.633, avgs=0

040/300: dt: 0.9000, rms radial error=169.683, avgs=0

045/300: dt: 0.9000, rms radial error=168.730, avgs=0

050/300: dt: 0.9000, rms radial error=167.777, avgs=0

055/300: dt: 0.9000, rms radial error=166.829, avgs=0

060/300: dt: 0.9000, rms radial error=165.885, avgs=0

065/300: dt: 0.9000, rms radial error=164.947, avgs=0

070/300: dt: 0.9000, rms radial error=164.013, avgs=0

075/300: dt: 0.9000, rms radial error=163.084, avgs=0

080/300: dt: 0.9000, rms radial error=162.161, avgs=0

085/300: dt: 0.9000, rms radial error=161.243, avgs=0

090/300: dt: 0.9000, rms radial error=160.330, avgs=0

095/300: dt: 0.9000, rms radial error=159.423, avgs=0

100/300: dt: 0.9000, rms radial error=158.521, avgs=0

105/300: dt: 0.9000, rms radial error=157.624, avgs=0

110/300: dt: 0.9000, rms radial error=156.732, avgs=0

115/300: dt: 0.9000, rms radial error=155.845, avgs=0

120/300: dt: 0.9000, rms radial error=154.963, avgs=0

125/300: dt: 0.9000, rms radial error=154.086, avgs=0

130/300: dt: 0.9000, rms radial error=153.214, avgs=0

135/300: dt: 0.9000, rms radial error=152.347, avgs=0

140/300: dt: 0.9000, rms radial error=151.485, avgs=0

145/300: dt: 0.9000, rms radial error=150.628, avgs=0

150/300: dt: 0.9000, rms radial error=149.775, avgs=0

155/300: dt: 0.9000, rms radial error=148.928, avgs=0

160/300: dt: 0.9000, rms radial error=148.085, avgs=0

165/300: dt: 0.9000, rms radial error=147.247, avgs=0

170/300: dt: 0.9000, rms radial error=146.413, avgs=0

175/300: dt: 0.9000, rms radial error=145.585, avgs=0

180/300: dt: 0.9000, rms radial error=144.761, avgs=0

185/300: dt: 0.9000, rms radial error=143.941, avgs=0

190/300: dt: 0.9000, rms radial error=143.127, avgs=0

195/300: dt: 0.9000, rms radial error=142.317, avgs=0

200/300: dt: 0.9000, rms radial error=141.511, avgs=0

205/300: dt: 0.9000, rms radial error=140.710, avgs=0

210/300: dt: 0.9000, rms radial error=139.914, avgs=0

215/300: dt: 0.9000, rms radial error=139.122, avgs=0

220/300: dt: 0.9000, rms radial error=138.335, avgs=0

225/300: dt: 0.9000, rms radial error=137.552, avgs=0

230/300: dt: 0.9000, rms radial error=136.773, avgs=0

235/300: dt: 0.9000, rms radial error=135.999, avgs=0

240/300: dt: 0.9000, rms radial error=135.230, avgs=0

245/300: dt: 0.9000, rms radial error=134.464, avgs=0

250/300: dt: 0.9000, rms radial error=133.704, avgs=0

255/300: dt: 0.9000, rms radial error=132.947, avgs=0

260/300: dt: 0.9000, rms radial error=132.195, avgs=0

265/300: dt: 0.9000, rms radial error=131.446, avgs=0

270/300: dt: 0.9000, rms radial error=130.703, avgs=0

275/300: dt: 0.9000, rms radial error=129.963, avgs=0

280/300: dt: 0.9000, rms radial error=129.227, avgs=0

285/300: dt: 0.9000, rms radial error=128.496, avgs=0

290/300: dt: 0.9000, rms radial error=127.769, avgs=0

295/300: dt: 0.9000, rms radial error=127.046, avgs=0

300/300: dt: 0.9000, rms radial error=126.327, avgs=0

final distance error %100000.00

inflating to sphere (rms error < 2.00)

000: dt: 0.0000, rms radial error=175.705, avgs=0

005/300: dt: 0.9000, rms radial error=175.448, avgs=0

010/300: dt: 0.9000, rms radial error=174.897, avgs=0

015/300: dt: 0.9000, rms radial error=174.170, avgs=0

020/300: dt: 0.9000, rms radial error=173.340, avgs=0

025/300: dt: 0.9000, rms radial error=172.452, avgs=0

030/300: dt: 0.9000, rms radial error=171.532, avgs=0

035/300: dt: 0.9000, rms radial error=170.593, avgs=0

040/300: dt: 0.9000, rms radial error=169.647, avgs=0

045/300: dt: 0.9000, rms radial error=168.698, avgs=0

050/300: dt: 0.9000, rms radial error=167.751, avgs=0

055/300: dt: 0.9000, rms radial error=166.806, avgs=0

060/300: dt: 0.9000, rms radial error=165.865, avgs=0

065/300: dt: 0.9000, rms radial error=164.928, avgs=0

070/300: dt: 0.9000, rms radial error=163.996, avgs=0

075/300: dt: 0.9000, rms radial error=163.068, avgs=0

080/300: dt: 0.9000, rms radial error=162.146, avgs=0

085/300: dt: 0.9000, rms radial error=161.229, avgs=0

090/300: dt: 0.9000, rms radial error=160.318, avgs=0

095/300: dt: 0.9000, rms radial error=159.411, avgs=0

100/300: dt: 0.9000, rms radial error=158.510, avgs=0

105/300: dt: 0.9000, rms radial error=157.613, avgs=0

110/300: dt: 0.9000, rms radial error=156.722, avgs=0

115/300: dt: 0.9000, rms radial error=155.836, avgs=0

120/300: dt: 0.9000, rms radial error=154.954, avgs=0

125/300: dt: 0.9000, rms radial error=154.078, avgs=0

130/300: dt: 0.9000, rms radial error=153.207, avgs=0

135/300: dt: 0.9000, rms radial error=152.340, avgs=0

140/300: dt: 0.9000, rms radial error=151.478, avgs=0

145/300: dt: 0.9000, rms radial error=150.622, avgs=0

150/300: dt: 0.9000, rms radial error=149.770, avgs=0

155/300: dt: 0.9000, rms radial error=148.922, avgs=0

160/300: dt: 0.9000, rms radial error=148.080, avgs=0

165/300: dt: 0.9000, rms radial error=147.242, avgs=0

170/300: dt: 0.9000, rms radial error=146.410, avgs=0

175/300: dt: 0.9000, rms radial error=145.581, avgs=0

180/300: dt: 0.9000, rms radial error=144.758, avgs=0

185/300: dt: 0.9000, rms radial error=143.939, avgs=0

190/300: dt: 0.9000, rms radial error=143.125, avgs=0

195/300: dt: 0.9000, rms radial error=142.315, avgs=0

200/300: dt: 0.9000, rms radial error=141.510, avgs=0

205/300: dt: 0.9000, rms radial error=140.710, avgs=0

210/300: dt: 0.9000, rms radial error=139.914, avgs=0

215/300: dt: 0.9000, rms radial error=139.122, avgs=0

220/300: dt: 0.9000, rms radial error=138.335, avgs=0

225/300: dt: 0.9000, rms radial error=137.553, avgs=0

230/300: dt: 0.9000, rms radial error=136.774, avgs=0

235/300: dt: 0.9000, rms radial error=136.001, avgs=0

240/300: dt: 0.9000, rms radial error=135.231, avgs=0

245/300: dt: 0.9000, rms radial error=134.466, avgs=0

250/300: dt: 0.9000, rms radial error=133.706, avgs=0

255/300: dt: 0.9000, rms radial error=132.949, avgs=0

260/300: dt: 0.9000, rms radial error=132.197, avgs=0

265/300: dt: 0.9000, rms radial error=131.449, avgs=0

270/300: dt: 0.9000, rms radial error=130.706, avgs=0

275/300: dt: 0.9000, rms radial error=129.966, avgs=0

280/300: dt: 0.9000, rms radial error=129.231, avgs=0

285/300: dt: 0.9000, rms radial error=128.500, avgs=0

290/300: dt: 0.9000, rms radial error=127.773, avgs=0

295/300: dt: 0.9000, rms radial error=127.051, avgs=0

300/300: dt: 0.9000, rms radial error=126.332, avgs=0

final distance error %100000.00

recon-all -s sub-patensasc0085 finished without error at Mon Sep 26 17:29:13 UTC 2022

recon-all -s sub-patensasc0085 finished without error at Mon Sep 26 20:53:22 UTC 2022

________________________________

**Comment by effigies** [comment]
Copied to a new comment for markdown:

---

```
nohup /usr/bin/docker service create --replicas 1 --reserve-cpu 8 --reserve-memory 16g --mode replicated --restart-condition none  --mount type=bind,source=$indir,destination=/input,readonly=true --mount type=bind,source=$outdir,destination=/output  --mount type=bind,source=/MRI_DATA/freesurferlicense.txt,destination=/opt/freesurfer/license.txt,readonly=true  nipreps/fmriprep:22.0.0rc2  /input /output participant $addarg
```

11:56<https://nyspimri.slack.com/archives/D02E31U778W/p1664294202034569>
should we try with more reserve memory?

```
***@***.*** scripts]$ cat recon-all-*.log | grep ERROR

recon-all -s sub-patensasc0085 exited with ERRORS at Mon Sep 26 21:11:58 UTC 2022

recon-all -s sub-patensasc0085 exited with ERRORS at Mon Sep 26 21:10:10 UTC 2022

recon-all -s sub-patensasc0085 exited with ERRORS at Mon Sep 26 21:11:58 UTC 2022

recon-all -s sub-patensasc0085 exited with ERRORS at Mon Sep 26 21:10:10 UTC 2022



***@***.*** scripts]$ cat recon-all-*.log | grep error

inflating to sphere (rms error < 2.00)

000: dt: 0.0000, rms radial error=175.788, avgs=0

005/300: dt: 0.9000, rms radial error=175.527, avgs=0

010/300: dt: 0.9000, rms radial error=174.967, avgs=0

015/300: dt: 0.9000, rms radial error=174.232, avgs=0

020/300: dt: 0.9000, rms radial error=173.396, avgs=0

025/300: dt: 0.9000, rms radial error=172.502, avgs=0

030/300: dt: 0.9000, rms radial error=171.576, avgs=0

035/300: dt: 0.9000, rms radial error=170.633, avgs=0

040/300: dt: 0.9000, rms radial error=169.683, avgs=0

045/300: dt: 0.9000, rms radial error=168.730, avgs=0

050/300: dt: 0.9000, rms radial error=167.777, avgs=0

055/300: dt: 0.9000, rms radial error=166.829, avgs=0

060/300: dt: 0.9000, rms radial error=165.885, avgs=0

065/300: dt: 0.9000, rms radial error=164.947, avgs=0

070/300: dt: 0.9000, rms radial error=164.013, avgs=0

075/300: dt: 0.9000, rms radial error=163.084, avgs=0

080/300: dt: 0.9000, rms radial error=162.161, avgs=0

085/300: dt: 0.9000, rms radial error=161.243, avgs=0

090/300: dt: 0.9000, rms radial error=160.330, avgs=0

095/300: dt: 0.9000, rms radial error=159.423, avgs=0

100/300: dt: 0.9000, rms radial error=158.521, avgs=0

105/300: dt: 0.9000, rms radial error=157.624, avgs=0

110/300: dt: 0.9000, rms radial error=156.732, avgs=0

115/300: dt: 0.9000, rms radial error=155.845, avgs=0

120/300: dt: 0.9000, rms radial error=154.963, avgs=0

125/300: dt: 0.9000, rms radial error=154.086, avgs=0

130/300: dt: 0.9000, rms radial error=153.214, avgs=0

135/300: dt: 0.9000, rms radial error=152.347, avgs=0

140/300: dt: 0.9000, rms radial error=151.485, avgs=0

145/300: dt: 0.9000, rms radial error=150.628, avgs=0

150/300: dt: 0.9000, rms radial error=149.775, avgs=0

155/300: dt: 0.9000, rms radial error=148.928, avgs=0

160/300: dt: 0.9000, rms radial error=148.085, avgs=0

165/300: dt: 0.9000, rms radial error=147.247, avgs=0

170/300: dt: 0.9000, rms radial error=146.413, avgs=0

175/300: dt: 0.9000, rms radial error=145.585, avgs=0

180/300: dt: 0.9000, rms radial error=144.761, avgs=0

185/300: dt: 0.9000, rms radial error=143.941, avgs=0

190/300: dt: 0.9000, rms radial error=143.127, avgs=0

195/300: dt: 0.9000, rms radial error=142.317, avgs=0

200/300: dt: 0.9000, rms radial error=141.511, avgs=0

205/300: dt: 0.9000, rms radial error=140.710, avgs=0

210/300: dt: 0.9000, rms radial error=139.914, avgs=0

215/300: dt: 0.9000, rms radial error=139.122, avgs=0

220/300: dt: 0.9000, rms radial error=138.335, avgs=0

225/300: dt: 0.9000, rms radial error=137.552, avgs=0

230/300: dt: 0.9000, rms radial error=136.773, avgs=0

235/300: dt: 0.9000, rms radial error=135.999, avgs=0

240/300: dt: 0.9000, rms radial error=135.230, avgs=0

245/300: dt: 0.9000, rms radial error=134.464, avgs=0

250/300: dt: 0.9000, rms radial error=133.704, avgs=0

255/300: dt: 0.9000, rms radial error=132.947, avgs=0

260/300: dt: 0.9000, rms radial error=132.195, avgs=0

265/300: dt: 0.9000, rms radial error=131.446, avgs=0

270/300: dt: 0.9000, rms radial error=130.703, avgs=0

275/300: dt: 0.9000, rms radial error=129.963, avgs=0

280/300: dt: 0.9000, rms radial error=129.227, avgs=0

285/300: dt: 0.9000, rms radial error=128.496, avgs=0

290/300: dt: 0.9000, rms radial error=127.769, avgs=0

295/300: dt: 0.9000, rms radial error=127.046, avgs=0

300/300: dt: 0.9000, rms radial error=126.327, avgs=0

final distance error %100000.00

inflating to sphere (rms error < 2.00)

000: dt: 0.0000, rms radial error=175.705, avgs=0

005/300: dt: 0.9000, rms radial error=175.448, avgs=0

010/300: dt: 0.9000, rms radial error=174.897, avgs=0

015/300: dt: 0.9000, rms radial error=174.170, avgs=0

020/300: dt: 0.9000, rms radial error=173.340, avgs=0

025/300: dt: 0.9000, rms radial error=172.452, avgs=0

030/300: dt: 0.9000, rms radial error=171.532, avgs=0

035/300: dt: 0.9000, rms radial error=170.593, avgs=0

040/300: dt: 0.9000, rms radial error=169.647, avgs=0

045/300: dt: 0.9000, rms radial error=168.698, avgs=0

050/300: dt: 0.9000, rms radial error=167.751, avgs=0

055/300: dt: 0.9000, rms radial error=166.806, avgs=0

060/300: dt: 0.9000, rms radial error=165.865, avgs=0

065/300: dt: 0.9000, rms radial error=164.928, avgs=0

070/300: dt: 0.9000, rms radial error=163.996, avgs=0

075/300: dt: 0.9000, rms radial error=163.068, avgs=0

080/300: dt: 0.9000, rms radial error=162.146, avgs=0

085/300: dt: 0.9000, rms radial error=161.229, avgs=0

090/300: dt: 0.9000, rms radial error=160.318, avgs=0

095/300: dt: 0.9000, rms radial error=159.411, avgs=0

100/300: dt: 0.9000, rms radial error=158.510, avgs=0

105/300: dt: 0.9000, rms radial error=157.613, avgs=0

110/300: dt: 0.9000, rms radial error=156.722, avgs=0

115/300: dt: 0.9000, rms radial error=155.836, avgs=0

120/300: dt: 0.9000, rms radial error=154.954, avgs=0

125/300: dt: 0.9000, rms radial error=154.078, avgs=0

130/300: dt: 0.9000, rms radial error=153.207, avgs=0

135/300: dt: 0.9000, rms radial error=152.340, avgs=0

140/300: dt: 0.9000, rms radial error=151.478, avgs=0

145/300: dt: 0.9000, rms radial error=150.622, avgs=0

150/300: dt: 0.9000, rms radial error=149.770, avgs=0

155/300: dt: 0.9000, rms radial error=148.922, avgs=0

160/300: dt: 0.9000, rms radial error=148.080, avgs=0

165/300: dt: 0.9000, rms radial error=147.242, avgs=0

170/300: dt: 0.9000, rms radial error=146.410, avgs=0

175/300: dt: 0.9000, rms radial error=145.581, avgs=0

180/300: dt: 0.9000, rms radial error=144.758, avgs=0

185/300: dt: 0.9000, rms radial error=143.939, avgs=0

190/300: dt: 0.9000, rms radial error=143.125, avgs=0

195/300: dt: 0.9000, rms radial error=142.315, avgs=0

200/300: dt: 0.9000, rms radial error=141.510, avgs=0

205/300: dt: 0.9000, rms radial error=140.710, avgs=0

210/300: dt: 0.9000, rms radial error=139.914, avgs=0

215/300: dt: 0.9000, rms radial error=139.122, avgs=0

220/300: dt: 0.9000, rms radial error=138.335, avgs=0

225/300: dt: 0.9000, rms radial error=137.553, avgs=0

230/300: dt: 0.9000, rms radial error=136.774, avgs=0

235/300: dt: 0.9000, rms radial error=136.001, avgs=0

240/300: dt: 0.9000, rms radial error=135.231, avgs=0

245/300: dt: 0.9000, rms radial error=134.466, avgs=0

250/300: dt: 0.9000, rms radial error=133.706, avgs=0

255/300: dt: 0.9000, rms radial error=132.949, avgs=0

260/300: dt: 0.9000, rms radial error=132.197, avgs=0

265/300: dt: 0.9000, rms radial error=131.449, avgs=0

270/300: dt: 0.9000, rms radial error=130.706, avgs=0

275/300: dt: 0.9000, rms radial error=129.966, avgs=0

280/300: dt: 0.9000, rms radial error=129.231, avgs=0

285/300: dt: 0.9000, rms radial error=128.500, avgs=0

290/300: dt: 0.9000, rms radial error=127.773, avgs=0

295/300: dt: 0.9000, rms radial error=127.051, avgs=0

300/300: dt: 0.9000, rms radial error=126.332, avgs=0

final distance error %100000.00

recon-all -s sub-patensasc0085 finished without error at Mon Sep 26 17:29:13 UTC 2022

recon-all -s sub-patensasc0085 finished without error at Mon Sep 26 20:53:22 UTC 2022
```

**Comment by effigies** [comment]
Thanks. This isn't enough to go by, as-is. If you could attach one of the logs that shows `recon-all -s sub-patensasc0085 exited with ERRORS`, that would be appreciated. Feel free to email me directly, if you can't share the log publicly.

It does look like you're still using 22.0.0rc2. Could you retry with 22.0.1?

**Comment by juansanchezpena** [comment]
Im going to re run with the LTS and get back to you tomorrow
Thanks Chris
________________________________

**Comment by mgxd** [comment]
@juansanchezpena just to avoid any confusion - the LTS is 20.2.x. FreeSurfer 7 was included 22.0.x, the latest release being 22.0.1. If you want to hold off until later today / tomorrow, we'll be release a new patch release.

**Comment by juansanchezpena** [comment]
Will do thanks

________________________________

**Comment by mgxd** [comment]
I believe this has been addressed
