### ISSUE TITLE
skip skull-strip for scalp conductivity simulations

### ISSUE THREAD

**Issue by ItayHadas** [nipreps/fmriprep#2882]
### What would you like to see added in fMRIPrep?

Dear fMRIPrep crew,
I wonder if there's a way to keep the skin tissue completely intact when using the --output-spaces MNI152NLin6Asym, and --skull-strip skip option.
currently I think the output is skull-striped and in older versions (20) the skin is sometimes cropped out of the output FOV - Please see pasted MR (forehead is cropped away).
this will be helpful for using the T1 product with packages like SimNIBS (utilizing MRI2MESH)
Many thanks for your amazing and valuable work!

### Do you have any interest in helping implement the feature?

Yes, but I would need guidance

### Additional information / screenshots

![image](https://user-images.githubusercontent.com/5610394/197248481-362603b6-2e71-4603-8bdd-cd4f286e9a85.png)

**Comment by effigies** [comment]
You can get what you're looking for by using `antsApplyTransforms` on the outputs that we provide:

```console
antsApplyTransforms --input sub-02/anat/sub-02_desc-preproc_T1w.nii.gz \
    --transform sub-02/anat/sub-02_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm.h5 \
    --reference-image sub-02/anat/sub-02_space-MNI152NLin2009cAsym_desc-preproc_T1w.nii.gz \
    --interpolation LanczosWindowedSinc \
    --output sub-02/anat/sub-02_space-MNI152NLin2009cAsym_desc-withSkull_T1w.nii.gz
```

To install antsApplyTransforms, see https://github.com/ANTsX/ANTs/releases. You can also use the Docker or Singularity images we provide. For example, if you use `fmriprep-docker`, you can add the `--shell` flag:

```console
$ fmriprep-docker /data /outputs participant --shell
> antsApplyTransforms --input /out/sub-02/anat/sub-02_desc-preproc_T1w.nii.gz \
      --transform /out/sub-02/anat/sub-02_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm.h5 \
      --reference-image /out/sub-02/anat/sub-02_space-MNI152NLin2009cAsym_desc-preproc_T1w.nii.gz \
      --interpolation LanczosWindowedSinc \
      --output /out/sub-02/anat/sub-02_space-MNI152NLin2009cAsym_desc-withSkull_T1w.nii.gz
```

**Comment by ItayHadas** [comment]
Dear @effigies ,
Thanks for your support, and I appologize for my late response.

When running `antsApplyTransforms` over our fmriprep (ver 22.0.2) output, I manage to get the skull back.
However, the field of view is still too small for our needs and it crops away the forehead and nose (pasted T1 below) 

I wonder if I can keep the **entire** head tissue inside the field of view?

this is the command I ran (similar to your suggestion): 
`antsApplyTransforms --input ${outdir}/${sub}/${ses}/anat/${sub}_${ses}_desc-preproc_T1w.nii.gz \
    --transform ${outdir}/${sub}/${ses}/anat/${sub}_${ses}_from-T1w_to-MNI152NLin6Asym_mode-image_xfm.h5 \
    --reference-image ${outdir}/${sub}/${ses}/anat/sub-001_space-MNI152NLin6Asym_desc-preproc_T1w.nii.gz \
    --interpolation LanczosWindowedSinc \
    --output ${outdir}/${sub}/${ses}/anat/${sub}_${ses}_space-MNI152NLin6Asym_desc-withSkull_T1w.nii.gz`

Many Thanks!!

![forehead_cut_eyesblur](https://user-images.githubusercontent.com/5610394/203652587-db69b9f3-c276-497b-bf36-43dfd0f63230.png)

**Comment by effigies** [comment]
Hi @ItayHadas you could try a different reference image than `sub-001_space-MNI152NLin6Asym_desc-preproc_T1w.nii.gz`. The original MNI template can be found in https://www.templateflow.org/browse/ (quick link: https://templateflow.s3.amazonaws.com/tpl-MNI152NLin6Asym/tpl-MNI152NLin6Asym_res-01_T1w.nii.gz). That likely has a wider field of view.

**Comment by ItayHadas** [comment]
Thanks for your time @effigies !!!
