### ISSUE TITLE
antsRegistration shrinks lesions in brain - choose different registration method in fmriprep

### ISSUE THREAD

**Issue by StephDocTUM** [nipreps/fmriprep#2886]
Dear all,

I process brain tumor data with fmriprep. But it seems that the registration method used in fmriprep (antsRegistration) shrinks the tumor when registering the patients brain to the template. Is there an option in fmriprep to choose a different registration method such as flirt and fnirt or bbregister. Or give commands to alter the antsRegistration command?

Best,
Step

**Comment by effigies** [comment]
Hi, are you using the method described here? [Cost function masking during spatial normalization](https://fmriprep.org/en/stable/workflows.html#cost-function-masking-during-spatial-normalization)

**Comment by StephDocTUM** [comment]
no, havent used a lesion mask so far.
so "ANTs will use this mask to minimize warping of healthy tissue into damaged areas (or vice-versa)" it should shrink the tumor less?

**Comment by effigies** [comment]
Yes.
