### ISSUE TITLE
fMRIprep preprocessing takes 76 hrs on Mac with M2 chip

### ISSUE THREAD

**Issue by happyamygdala** [nipreps/fmriprep#2887]
### What happened?

Hi everybody, my labmate and I are first time fMRIPrep users. It takes 76 hours to do the preprocessing for one subject on Mac with M2 chip! But, preprocessing of the same participant with same code takes 8 hours on another Mac with Intel 2,8 GHz Quad-Core i7. Is there anything that we can do to make this process any shorter on Mac with M2 chip?

### What command did you use?

```shell
fmriprep-docker /Users/User/Desktop/resting/sub-01 /Users/User/Desktop/resting/sub-01 participant --output-spaces func fsnative MNI152NLin2009cAsym:res-2 MNI152Lin:res-2 MNI152NLin6Asym:res-2 --skip_bids_validation --use-aroma --ignore fieldmaps --cifti-output --use-syn-sdc --fs-license-file /Users/User/Desktop/resting/license.txt --low-mem
```

### What version of fMRIPrep are you running?

20.2.7 

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Additional information / screenshots

<img width="1265" alt="Screen Shot 2022-11-03 at 10 41 59" src="https://user-images.githubusercontent.com/117345115/199673698-fa1fdd35-73f2-4f79-8874-b411d6fbd80b.png">

**Comment by effigies** [comment]
Before trying to build a docker image with binaries optimized for ARM, we would need to demonstrate that it can be done bare metal and realize the speed gains.

Would you be comfortable installing fMRIPrep and the tools it uses on your system directly? You can see the Docker file for the necessary tools.

**Comment by happyamygdala** [comment]
Thank you for your answer Chris!

**Comment by effigies** [comment]
Closing this as nothing to do until we hear more.
