### ISSUE TITLE
Rename .func.gii to .time.gii?

### ISSUE THREAD

**Issue by effigies** [nipreps/fmriprep#2888]
Up to now, fMRIPrep has been generating functional time series as `.func.gii` files based on a probably too-hasty reading several years ago. Re-reading the GIFTI spec,

> The functional file contains one or more DataArrays with Intent set to
NIFTI_INTENT_NONE or one of the statistical intent values. Each
DataArray has DataType set to NIFTI_TYPE_FLOAT32. Dimensionality is
one with the first dimension set to the number of nodes.

> The Time-Series file contains one or more DataArrays with Intent set to
NIFTI_INTENT_TIME_SERIES and DataType set to
NIFTI_TYPE_FLOAT32. Dimensionality is one with the first dimension set
to the number of nodes.

It seems that "functional" to GIFTI means a statistic derived from a functional time series, while the time series itself should be `.time.gii`.

This comes up as we start to add expected extensions for resampled data to the BIDS specification as in https://github.com/bids-standard/bids-specification/pull/1331. It seems like it would be a bad idea to have BIDS endorse a non-standard reading of GIFTI, but it's also unclear if our interpretation is what others have been using as well. Following common practice might be better than a stricter reading of the standard than anybody else does.

I'd be curious to hear the perspectives of representatives of GIFTI-supporting tools, such as @coalsont, @afni-dglen, @dngreve.

----

As an aside, it's not at all clear how many people are using these outputs anyway. CIFTI-2 is a far superior format for functional time series, so the number of downstream pipelines that would need to adjust could be negligible.

**Comment by coalsont** [comment]
The HCP pipelines and workbench use .func.gii for everything except curvature and sulcal depth, which use .shape.gii for historical reasons.  I have never seen a .time.gii, and I wouldn't recommend using that extension (for compatibility and familiarity reasons).  A large number of our processing intermediates are in .func.gii format, because surface algorithms work on one surface (hemisphere) at a time.

**Comment by afni-rickr** [comment]
Hi @effigies.  Some of the original GIFTI authoring packages used .time.gii and .func.gii in their sample data (BrainVisa, BrainVoyager and Caret), but that was just a "desirable" suggestion, and might not be required by them (anymore?), particularly when handling BIDS data.  With AFNI, while programs might have some default extensions for output, generally programs do not care about anything but the .gii extension and the actual Intent code for input.
Given that BIDS uses a 'func' directory for the time series data, I would be surprised by any that could not handle func.gii as a filename suffix for input, particularly when Intent=NIFTI_INTENT_TIME_SERIES.

**Comment by effigies** [comment]
Hi @coalsont @afni-rickr, thanks for your responses. We'll definitely keep going with `.func.gii` for now.

I wonder if it would be worth putting together a sort of addendum to GIFTI that's basically "How GIFTI is actually used, 12 years later". There's a lot in there that's not universally supported, probably some that's not supported at all, and at least some contrary-to-spec behavior (like this usage of `.func.gii`) that is common enough to be the de facto standard that a new implementation should adopt.

**Comment by mgxd** [comment]
Please re-open if further discussion is needed
