### ISSUE TITLE
pepolar scheme using SBRef considered as sophisticated.

### ISSUE THREAD

**Issue by bpinsard** [nipreps/fmriprep#2889]
### What happened?

Running fMRIPrep 21.9.1 on a BIDS dataset with `func/*sbref.nii.gz` and `fmap/*acq-sbref*_epi.nii.gz` paired with B0FieldIdentifier  raises  `NotImplementedError: Sophisticated PEPOLAR schemes are unsupported.`

https://github.com/nipreps/fmriprep/blob/master/fmriprep/workflows/base.py#L511

could be replaced with 
```
            if set(suffices) == {"epi"} or sorted(suffices) == ["bold", "epi"] or sorted(suffices) == ["epi", "sbref"] :
```
(tested with that patch and it seems to run)
or even maybe
```
            if set(suffices) == {"epi"} or set(suffices) == {"sbref"} or set(suffices) == {"bold"}  or sorted(suffices) == ["bold", "epi"] or sorted(suffices) == ["epi", "sbref"] :
```
If we want to allow task ran in both phase-encoding directions to be used for distortion estimation (without any `fmap/*_epi.nii.gz) if SDCFLows supports it.

Let me know if that makes sense and I can submit a small PR. 

### What command did you use?

```shell
apptainer images from repronim-containers, exact command no relevant.
```

### What version of fMRIPrep are you running?

21.0.1

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

Anatomical derivatives

**Comment by effigies** [comment]
This all makes sense to me. I think instead of your second proposal, we want to check that we have two images and that they're some combination of `bold`, `sbref` and `epi`, right?

```Python
if len(suffices) == 2 and set(suffices) - {"epi", "bold", "sbref"} == set():
```

Or possibly less cryptic:

```Python
if len(suffices) == 2 and all(suf in ("epi", "bold", "sbref") for suf in suffices):
```

While these might be less straightforward compared to `dir-{AP,PA}_epi.nii.gz` (how many volumes should be taken from a BOLD series?) I agree these are not sophisticated. It's one AP (or RL) series and one PA (LR), and that's manageable.

**Comment by bpinsard** [comment]
> This all makes sense to me. I think instead of your second proposal, we want to check that we have two images and that they're some combination of bold, sbref and epi, right?

Exactly, however I think `len(suffices) == 2` is not always true, one might combine more than 2 AP/PA files to estimate distortions. Also SDCFLows wrangler auto detection tend to have more than 2 `estimator.sources`  which would explains the original code if I am not mistaken.

**Comment by effigies** [comment]
I guess it would be good to get @oesteban's input here. What were you considering a sophisticated scheme when you put in this limitation?

**Comment by oesteban** [comment]
- I believe the reason `sbref` is not considered is just my ignorance at the time. I think I assumed SBRefs would only be encoded with `acq-sbref_bold`. However, I just checked the specs and that's definitely wrong.
- I would leave having both a "bold" and an "sbref" reference of the same PE polarity as, at the very least, discouraged, and make the sbref have precedence.

**Comment by oesteban** [comment]
> Exactly, however I think `len(suffices) == 2` is not always true, one might combine more than 2 AP/PA files to estimate distortions. Also SDCFLows wrangler auto detection tend to have more than 2 `estimator.sources` which would explains the original code if I am not mistaken.

This seems correct. However the wrangler will need to drop `bold` PEs when one or more `sbref` are available for a given PE direction.
