### ISSUE TITLE
lesion mask: inconsistent documentation ?

### ISSUE THREAD

**Issue by Remi-Gau** [nipreps/fmriprep#2892]
I think there is an inconsistency in the documentation regarding how lesion mask should be named.

### From the normalization section

https://fmriprep.org/en/stable/workflows.html#cost-function-masking-during-spatial-normalization

> Lesion masks should be binary NIfTI images (damaged areas = 1, everywhere else = 0) in the same space and resolution as the T1 image, and follow the naming convention specified in [BIDS Extension Proposal 3: Common Derivatives](https://docs.google.com/document/d/1Wwc4A6Mow4ZPPszDIWfCUCRNstn7d_zzaWPcfcHmgI4/edit#heading=h.9146wuepclkt) (e.g., sub-001_T1w_label-lesion_roi.nii.gz). This file should be placed in the sub-*/anat directory of the BIDS dataset to be run through fMRIPrep. Because lesion masks are not currently part of the BIDS specification, it is also necessary to include a .bidsignore file in the root of your dataset directory. This will prevent [bids-validator](https://github.com/bids-standard/bids-validator#bidsignore) from complaining that your dataset is not valid BIDS, which prevents fMRIPrep from running. Your .bidsignore file should include the following line:
>
>`*lesion_roi.nii.gz`

The name `sub-001_T1w_label-lesion_roi.nii.gz` looks unBIDSish to me.

Shouldn't it be: `sub-001_label-lesion_roi.nii.gz` ?

### From the BEP003 google doc

Linked in the normalization section

https://docs.google.com/document/d/1Wwc4A6Mow4ZPPszDIWfCUCRNstn7d_zzaWPcfcHmgI4/edit#heading=h.9146wuepclkt

```text
manual_masks/
     sub-001/
         anat/
            sub-001_T1w_label-desc_mask.nii.gz
```

This one specifies a mask suffix.

Also shouldn't the doc point to the specification of the derivatives for this? If it makes sense to keep this link here?

### From the bids filter file FAQ section

https://fmriprep.org/en/stable/faq.html#how-do-i-select-only-certain-files-to-be-input-to-fmriprep

```json
{
  "fmap": {"datatype": "fmap"},
  "bold": {"datatype": "func", "suffix": "bold"},
  "sbref": {"datatype": "func", "suffix": "sbref"},
  "flair": {"datatype": "anat", "suffix": "FLAIR"},
  "t2w": {"datatype": "anat", "suffix": "T2w"},
  "t1w": {"datatype": "anat", "suffix": "T1w"},
  "roi": {"datatype": "anat", "suffix": "roi"}
}
```

### Conclusion

So from reading all this I would not be sure how to name my lesion mask.

I would be tempted to make the bids filter file the final authority on this and hence have a file like this one would be fine.

```text
manual_masks/
     sub-001/
         anat/
            sub-001_roi.nii.gz
```

If that is the case, should I edit the doc to fix this?

**Comment by oesteban** [comment]
@effigies - I'm here with @Remi-Gau at BrainHack Donostia, and we have just gone through the layout querying of sMRIPrep to get ROIs.

- We have checked that the documentation is wrong with that `_T1w_` entity in the middle.
- We are unclear on where the ROIs should be placed. First, I kind of recall that we instruct pybids not to index the derivatives. However, having the ROIs in the BIDS-raw would not be compliant (AFAICT).

Since you've had to look at this lately, do you have any quick feedback on how we could best review the documentation and fix this issue?

**Comment by oesteban** [comment]
(obviously, not hoping for a response before next week - happy thanksgiving!)

**Comment by effigies** [comment]
Right now, I'm pretty sure `sub-X/anat/sub-X_<any-entities>_roi.nii.gz` will get picked up. If we did it according to BIDS, we should be looking in `derivatives/<some-deriv>/sub-X/anat/sub-X_label-lesion_mask.nii.gz`, and we can do that in sMRIPrep 0.11.

xref #2715
