### ISSUE TITLE
CifTi files created with --cifti-output are the same regardless of the --use-aroma flag

### ISSUE THREAD

**Issue by narunpat** [nipreps/fmriprep#2896]
### What happened?

We would like to create CifTi files that were cleaned with aroma, so we used both --cifti-output and --use-aroma flags. However, we found that the CifTi files created with --use-aroma is essentially the same as those without the flag. 

For instance, with both flags, we obtained this CifTi file: 
sub-A00029076_ses-BAS1_task-rest_acq-645_space-fsLR_den-91k_bold.dtseries.nii 
and they are very similar to each other (see plots below).       

Note --use-aroma does create two different NifTi files:

without --use aroma we got
sub-A00029076_ses-BAS1_task-rest_acq-645_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
with --use aroma we got
sub-A00029076_ses-BAS1_task-rest_acq-645_space-MNI152NLin6Asym_desc-smoothAROMAnonaggr_bold.nii.gz       
And the time series of these two seem to be different from each other (see plot below), suggesting that aroma was indeed applied to NifTi files. 

Does it mean that aroma cannot be applied to CifTi? 

[seemingly unrelated, note we also saw different space, even though we didn't specify the space: without aroma uses MNI152NLin2009cAsym, while with aroma uses MNI152NLin6Asym. So it appears that --use-aroma also forces the space to be "MNI152NLin6Asym".]

### What command did you use?

```shell
## with aroma

singularity run --cleanenv ${image_path} \
${bids_path} \
${out_path} \
participant --participant_label ${participant_id} \
--write-graph \
--notrack \
--nthreads 10 \
--omp-nthreads 9 \
--mem_mb 52000 \
--skip_bids_validation \
--fs-license-file ${license_path} \
--work-dir ${work_dir_path} \
--ignore=slicetiming \
--cifti-output \
--fs-subjects-dir ${fs_sub_dir} \
--use-aroma

## without aroma
singularity run --cleanenv ${image_path} \
${bids_path} \
${out_path} \
participant --participant_label ${participant_id} \
--write-graph \
--notrack \
--nthreads 12 \
--omp-nthreads 11 \
--mem_mb 64000 \
--skip_bids_validation \
--fs-license-file ${license_path} \
--work-dir ${work_dir_path} \
--ignore=slicetiming \
--cifti-output \
--fs-subjects-dir ${fs_sub_dir}
```

### What version of fMRIPrep are you running?

fmriprep-22.0.2.simg

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

FreeSurfer

### Additional information / screenshots

time series of one roi comparing CifTi files with vs. without use-aroma

![index88](https://user-images.githubusercontent.com/38054414/205024195-76826c95-49da-4fe5-a34a-a5e941478666.png)

time series of one roi comparing NifTi files with vs. without use-aroma
![MicrosoftTeams-image (22)](https://user-images.githubusercontent.com/38054414/205024562-c1c3fca7-8dbb-4571-a2d5-9690588a1e4c.png)

**Comment by effigies** [comment]
This is all as expected.

`desc-smoothAROMAnonaggr` indicates that AROMA denoising was applied. This is only generated in MNI152NLin6Asym space because that's where AROMA is defined and the smoothed and non-aggressively denoised file is a direct output of AROMA.

If you would like to apply AROMA denoising to other outputs, confounds are provided in the `desc-confounds_timeseries.tsv` file.
