### ISSUE TITLE
A question about tCompCor components (top 5% variable voxels within a mask covering the subcortical regions).

### ISSUE THREAD

**Issue by charujing** [nipreps/fmriprep#2925]
### What happened?

Dear experts and users
     I need to perform analysis with "tCompCor components are then calculated from the top 5% variable voxels within a mask covering the subcortical regions.", however, the html file reports this "tCompCor components are then calculated from the top 2% variable voxels within the brain mask". 
    So how can i fix this to get top 5% voxels with subcortical regions NOT the brain.
   Thanks
Best regards.
rujing

### What command did you use?

```shell
fmriprep-docker /home/xx/bids/ /home/xx/bids/derivatives participant --participant-label xx --fs-licnese-file /home/xx/license.txt --nprocs 32 -t xx --use-aroma
```

### What version of fMRIPrep are you running?

22.1.0+0.gce344b39.dirty

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by tsalo** [comment]
@charujing That value is not configurable within fMRIPrep. You could probably use the cosine regressors to high-pass filter your native-space preprocessed BOLD file and then run `niworkflows.interfaces.patches.RobustTCompCor` with the same inputs fMRIPrep uses (see below), except with `percentile_threshold` changed to 0.05.

```python
        TCompCor(
            components_file="tcompcor.tsv",
            header_prefix="t_comp_cor_",
            pre_filter="cosine",
            save_pre_filter=True,
            save_metadata=True,
            percentile_threshold=0.02,
            failure_mode="NaN",
        )
```
However, that is more a general neuro question than a bug in fMRIPrep, so I would recommend opening a topic on [NeuroStars](https://neurostars.org/) if you'd like to go that route.

**Comment by effigies** [comment]
Changing CompCor parameters will be a problem for an fmripost pipeline. Possibly all confounds should be.
