### ISSUE TITLE
Errors in bold_std_trans_wf + bold_confounds_wf

### ISSUE THREAD

**Issue by LuRoe7** [nipreps/fmriprep#2929]
### What happened?

When I run fmriprep as a singularity image on a slurm cluster, I encounter two errors during the following workflows:

 a) bold_std_trans_wf (skullstrip_first_pass):
[crash-20230109-222055-fmriprep-skullstrip_first_pass.a0-e812daf5-3db6-4747-a61c-c06e3483519e.txt](https://github.com/nipreps/fmriprep/files/10382637/crash-20230109-222055-fmriprep-skullstrip_first_pass.a0-e812daf5-3db6-4747-a61c-c06e3483519e.txt)

b) bold_confounds_wf:
[crash-20230109-224710-fmriprep-conf_plot-71204ac9-373c-47d3-9936-b358a83ef191.txt](https://github.com/nipreps/fmriprep/files/10382626/crash-20230109-224710-fmriprep-conf_plot-71204ac9-373c-47d3-9936-b358a83ef191.txt)

Despite these errors, all relevant outputs of fmriprep seem to be produced although the images within the HTML reports are not printed and the slurm job itself fails in the end. Any ideas how to fix this?

### What command did you use?

```shell
Slurm script:

#!/bin/sh
#
#SBATCH --job-name fmriprep-cdp
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=16GB
#SBATCH --mail-user=Lukas.Roell@med.uni-muenchen.de
#SBATCH --mail-type=ALL
#SBATCH --output /data/hpc1/logs/cdp/fmriprep/slurm-%j.log
#SBATCH --error /data/hpc1/logs/cdp/fmriprep/slurm-%j.err

singularity run --cleanenv --home /data/hpc1/tmp/cdp/fmriprep:/home/fmriprep \
-B /data/hpc1/datasets/cdp:/data  \
-B /data/hpc1/datasets/cdp/derivatives/fmriprep:/out \
-B /data/hpc1/fslicense:/freesurfer \
-B /data/hpc1/wd/cdp/fmriprep:/workdir \
-B /data/hpc1/tmp/cdp/fmriprep:/tmp \
/data/hpc1/images/fmriprep-22.1.1.sif /data/ /out participant \
--participant_label CDPC0001 \
--fs-license-file /freesurfer/license.txt \
--skip-bids-validation \
--cifti-output 91k \
--output-spaces MNI152NLin2009cAsym:res-2 \
--bold2t1w-init register \
--bold2t1w-dof 12 \
--force-bbr \
--skull-strip-t1w force \
--medial-surface-nan \
--dummy-scans 10 \
--use-aroma \
--verbose \
--n_cpus 4 \
--mem 16000 \
--debug all \
--output-layout bids \
-w /workdir/ \
```

### What version of fMRIPrep are you running?

22.1.1

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by effigies** [comment]
Hi, sorry I didn't see this earlier. I wonder if the OSError might be due to hitting an OS/filesystem limit on path lengths, since it's over 256 characters and the parent directory's path is less. Could you try just:

```
touch /data/hpc1/wd/cdp/fmriprep/fmriprep_22_1_wf/single_subject_CDPC0001_wf/func_preproc_ses_t1_task_rest_dir_AP_wf/bold_std_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/_std_target_MNI152NLin2009cAsym.res2/skullstrip_first_pass/vol0000_xform-00000_clipped_merged_average_corrected.nii.gz
```

and see if that works?

As to the carpetplot failure, if you're able to provide the input files, we can try debugging it:

```
in_cifti = /workdir/fmriprep_22_1_wf/single_subject_CDPC0001_wf/func_preproc_ses_t1_task_rest_dir_AP_wf/bold_grayords_wf/gen_cifti/vol0000_xform-00000_clipped_merged.dtseries.nii
in_nifti = /workdir/fmriprep_22_1_wf/single_subject_CDPC0001_wf/func_preproc_ses_t1_task_rest_dir_AP_wf/bold_bold_trans_wf/merge/vol0000_xform-00000_clipped_merged.nii.gz
in_segm = /workdir/fmriprep_22_1_wf/single_subject_CDPC0001_wf/func_preproc_ses_t1_task_rest_dir_AP_wf/carpetplot_wf/parcels/segments.nii.gz
```
