### ISSUE TITLE
Bids-Validation non-zero exit status 3. EISDIR: illegal operation on a directory

### ISSUE THREAD

**Issue by jesswood64** [nipreps/fmriprep#2942]
**What happened?**
My data has been BIDS validated per online - no errors. However I am getting a couple of Errors when running my participant:  1. saying that EISDIR: illegal operation on a directory, read. 
2. a CalledProcessError says "Command '['bids-validator', '/data', '-c', '/tmp/tmpbvefz1n9.json']' returned non-zero exit status 3.". Finally, when I use --skip-bids-validation, the code works perfectly. 

**What command did you use?**
fmriprep-docker $BIDS_DIR $DERIVS_DIR \
	participant \
	--participant-label ${subject} \
	--fs-license-file /home/local/freesurfer/license.txt \
	--output-spaces MNI152NLin6Asym:res-2 \
	--fd-spike-threshold 0.2 \
	--fs-no-reconall \
	-w ${WORK_DIR} \

**What version of fMRIPrep are you running?**
22.0.2

**How are you running fMRIPrep?**
Docker

**Is your data BIDS valid?**
Yes

**Are you reusing any previously computed results?**
No

**Please copy and paste any relevant log output.**
```
bash fmriprep_ApexConn.sh 103 1
Begin Preprocessing
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=20.10.21 -it -v /home/local/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v /home/data/ApexConn/ProtocolTesting/BIDS/Nifti:/data:ro -v /home/data/ApexConn/ProtocolTesting/derivatives/preproc_fmriprep-22.0.2:/out -v /home/data/ApexConn/ProtocolTesting/work_fMRIPrep:/scratch nipreps/fmriprep:22.0.2 /data /out participant --participant-label 103 --fd-spike-threshold 0.2 --fs-no-reconall -w /scratch --output-spaces MNI152NLin6Asym:res-2
You are using fMRIPrep-22.0.2, and a newer version of fMRIPrep is available: 22.1.1.
Please check out our documentation about how and when to upgrade:
https://fmriprep.readthedocs.io/en/latest/faq.html#upgrading
bids-validator@1.8.0

Unhandled rejection (
  reason: Error: EISDIR: illegal operation on a directory, read
).

Traceback (most recent call last):
  File "/opt/conda/bin/fmriprep", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/cli/run.py", line 39, in main
    parse_args()
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/cli/parser.py", line 790, in parse_args
    validate_input_dir(config.environment.exec_env, opts.bids_dir, opts.participant_label)
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/utils/bids.py", line 186, in validate_input_dir
    subprocess.check_call(['bids-validator', str(bids_dir), '-c', temp.name])
  File "/opt/conda/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bids-validator', '/data', '-c', '/tmp/tmpbvefz1n9.json']' returned non-zero exit status 3.
fMRIPrep: Please report errors to https://github.com/nipreps/fmriprep/issues
```

**Additional information / screenshots**
No response

**Comment by effigies** [comment]
Seems like a permissions issue. If the dataset passes validation, you can `--skip-bids-validation`. We just can't support non-BIDS datasets, and the validation step is to let people know when they don't have a valid dataset.
