### ISSUE TITLE
Odd ghosting in coreg, dark sdc images, bad roi & carpet plots

### ISSUE THREAD

**Issue by athenahowell** [nipreps/fmriprep#2948]
### What happened?

Our lab is running our multiband, multiecho fmri data through the fmriprep pipeline and we're running into some bizarre errors in the output. The errors look similar between participants, but don't seem to have an obvious cause. Furthermore, they appear to affect only some subjects but not others, and only some runs within the same scan session for that subject, even if the exact same MRI paradigm was run elsewhere in the session.

### What command did you use?

```shell
/opt/conda/bin/fmriprep /fs/ess/PCON0381/MNA/data/Nifti /fs/ess/PCON0381/MNA/data/Preprocessed participant --participant_label sub-3030 --ignore slicetiming sbref --fs-license-file /fs/ess/PCON0381/Scripts/license.txt
```

### What version of fMRIPrep are you running?

21.0.2

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Additional information / screenshots

![sub-3030_ses-1_task-cert1_run-1_desc-coreg_bold](https://user-images.githubusercontent.com/69254727/218158025-611c8e2d-0e84-4851-873e-4cabfa576d1b.svg)
![sub-3030_ses-1_task-cert1_run-1_desc-sdc_bold](https://user-images.githubusercontent.com/69254727/218158032-6bf7d3e0-ede9-42d1-badf-7fad6cdf0494.svg)
![sub-3030_ses-1_task-cert1_run-1_desc-carpetplot_bold](https://user-images.githubusercontent.com/69254727/218158035-b190f548-2697-4f18-a44b-e9efb431dbf1.svg)

**Comment by effigies** [comment]
21.0.2 is no longer supported. Does this occur in 23.0.1?

**Comment by effigies** [comment]
The differences between corrected and distorted in the reports are most likely a result of #3056. Do you see issues in the resulting files?

Apologies for the delay.

**Comment by effigies** [comment]
Please retry with the 23.2.0a1 pre-release and reopen if this is still an issue.
