### ISSUE TITLE
NetworkX version issue

### ISSUE THREAD

**Issue by sanosenx86** [nipreps/fmriprep#2949]
### What happened?

Hi, I am encountering a problem about networkX versions.
![image](https://user-images.githubusercontent.com/44931458/218301908-9fa3312f-5ed4-4837-ad50-3f04122e057a.png)
If not using the docker image but manually install by Python, networkX 3.0 will be used, and the function to_scipy_sparse_matrix has been renamed to to_scipy_sparse_array, and it will crash the program.
Please specify that the networkX dependency version to 2.8.2 in later releases, or to update the function name in fmriprep.
Thanks.

### What command did you use?

```shell
fmriprep /data /out participant -w /tmp
```

### What version of fMRIPrep are you running?

22.1.1

### How are you running fMRIPrep?

Local installation ("bare-metal")

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by effigies** [comment]
This is an issue with nipype. You can either install networkx<3 or you can install nipype from the latest master.

There is nothing to do in fmriprep.
