### ISSUE TITLE
Using inversion recovery image when T1w is not available

### ISSUE THREAD

**Issue by manzouri** [nipreps/fmriprep#2952]
### What would you like to see added in fMRIPrep?

Hi, I have some images that look like inversion recovery sequence images for some of my subjects and I wonder if I can use them instead of T1w images in fmriprep.

### Do you have any interest in helping implement the feature?

No

### Additional information / screenshots

![Screenshot_2023-02-14_11-03-44](https://user-images.githubusercontent.com/36534896/218703597-1abb75de-e837-47a0-b669-f8612f7c3ab5.png)

**Comment by effigies** [comment]
This is not planned. If the contrast is sufficiently close to T1w and you do some skull-stripping in advance, it may be possible with `--skull-strip-t1w skip`.

**Comment by manzouri** [comment]
Thanks @effigies
