### ISSUE TITLE
Limit fieldmap estimation to ones that will be used to correct BOLD files

### ISSUE THREAD

**Issue by G10v4nn1G** [nipreps/fmriprep#2968]
### What happened?

fMRIprep uses both fmap "intended for" fmri and dwi sequences for SDC (susceptibility distortion correction, due to "Inhomogeneities of the B0 field"), instead of using only the fmap relative to fmri. The nifti file used passed without errors the BIDS-validator  check. Note: the fmri dataset analyzed is multi-echo, made up of three echoes (with different TE). The html report end with the sentence: "Errors: No errors to report!". All work fine but fmap. 

Thank you in advance for your help
Giovanni

### What command did you use?

```shell
/opt/conda/bin/fmriprep /data /out participant --participant-label 00244356 --nprocs 16 --md-only-boilerplate --write-graph --me-output-echos -w /scratch --output-spaces MNI152NLin2009cAsym:res-native func
```

### What version of fMRIPrep are you running?

22.1.1

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
You are using fMRIPrep-22.1.1, and a newer version of fMRIPrep is available: 23.0.0.
Please check out our documentation about how and when to upgrade:
https://fmriprep.readthedocs.io/en/latest/faq.html#upgrading
--topup-max-vols input is no longer used and the flag will be removed in a future release.
bids-validator@1.8.0

	 BOLD series will be slice-timing corrected to an offset of 0.442s.
230314-14:22:54,796 nipype.workflow IMPORTANT:
	 Generating T2* map and optimally combined ME-EPI time series.
230314-14:22:55,289 nipype.workflow INFO:
	 Setting-up fieldmap "fmapFMRI" (EstimatorType.PEPOLAR) with <sub-00244356_ses-20230314_acq-SpinEchoFieldMapFMRI_dir-AP_epi.nii.gz, sub-00244356_ses-20230314_acq-SpinEchoFieldMapFMRI_dir-PA_epi.nii.gz>
230314-14:22:55,327 nipype.workflow INFO:
	 Setting-up fieldmap "fmapDWI" (EstimatorType.PEPOLAR) with <sub-00244356_ses-20230314_acq-SpinEchoFieldMapDWI_dir-AP_epi.nii.gz, sub-00244356_ses-20230314_acq-SpinEchoFieldMapDWI_dir-PA_epi.nii.gz>
230314-14:23:23,101 nipype.workflow INFO:
	 fMRIPrep workflow graph with 487 nodes built successfully.
```

**Comment by effigies** [comment]
Yes, we need to limit our fieldmap estimation to ones that will be used to correct BOLD files, regardless of whether we can find them and estimate them.

**Comment by G10v4nn1G** [comment]
Thank you for the quick reply!
Is it planned to resolve this issue in the next release of FMRIPREP? Is there a way to force FMRIPREP to use only fmap_fmri, instead of removing the fmap_dwi?

Thank you for your support.
Giovanni"

**Comment by effigies** [comment]
I had a quick look through, and right now the fieldmap selection process is a bit more complicated than I expected. This won't be high priority unless it causes breakage beyond doing extra unnecessary work.
