### ISSUE TITLE
Location of subject html files

### ISSUE THREAD

**Issue by marcelzwiers** [nipreps/fmriprep#2979]
### What would you like to see added in fMRIPrep?

Both fmriprep and mriqc produce nice-looking subject HTML reports, next to a group report. However, both the subject and group reports are saved in the derivative root folder, whereas I think according to the BIDS standard the subject html files should be stored in the subject folder (next to the json data files or figures that are already in there).

This is a bit of a minor issue, so I understand if you don't have time for this :-) 

### Do you have any interest in helping implement the feature?

No

**Comment by effigies** [comment]
I don't think we're going to change this in the near future. Users can readily reorganize derivatives after running, and nothing should depend on where these non-standard files are.
