### ISSUE TITLE
good voxels masking error

### ISSUE THREAD

**Issue by juansanchezpena** [nipreps/fmriprep#2990]
### What happened?

I was able to run the goodvoxels flag though on fmriprep 23.0.1 and compared the same data to fmriprep 23.0.1 w/o goodvoxels and abcd-dcan 0.1.3

(the abcd, 23.0.1 (no good voxels arg) and the 23.0.1 goodvoxels result are attached. )
There seems to be a masking error on the surface with the goodvoxels.

### What command did you use?

```shell
--participant-label xxxx --output-spaces T1w MNI152NLin2009cAsym:res-2 --cifti-output --output-layout legacy --project-goodvoxels
```

### What version of fMRIPrep are you running?

23.0.1

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
[environment]
cpu_count = 24
exec_env = "docker"
free_mem = 82.8
overcommit_policy = "heuristic"
overcommit_limit = "50%"
nipype_version = "1.8.5"
templateflow_version = "23.0.0"
version = "23.0.1"

[execution]
bids_dir = "/input"
bids_database_dir = "/tmp/work/20230410-172026_c909688d-781d-414e-a9ca-062d24a43f68/bids_db"
bids_description_hash = "f7837453d53f5e81fac160140151ed912fdd1da09e92d853373c6d152bfdae5e"
boilerplate_only = false
sloppy = false
debug = []
fmriprep_dir = "/output/fmriprep"
fs_license_file = "/opt/freesurfer/license.txt"
fs_subjects_dir = "/output/freesurfer"
layout = "BIDS Layout: .../input | Subjects: 4 | Sessions: 4 | Runs: 15"
log_dir = "/output/fmriprep/logs"
log_level = 25
low_mem = false
md_only_boilerplate = false
notrack = false
track_carbon = false
country_code = "CAN"
output_dir = "/output"
me_output_echos = false
output_layout = "legacy"
output_spaces = "T1w MNI152NLin2009cAsym:res-2"
reports_only = false
run_uuid = "20230410-172026_c909688d-781d-414e-a9ca-062d24a43f68"
participant_label = [ "patensasc0089",]
templateflow_home = "/home/fmriprep/.cache/templateflow"
work_dir = "/tmp/work"
write_graph = false

[workflow]
anat_only = false
aroma_err_on_warn = false
aroma_melodic_dim = -200
bold2t1w_dof = 6
bold2t1w_init = "register"
cifti_output = "91k"
fmap_bspline = false
force_syn = false
hires = true
ignore = []
longitudinal = false
medial_surface_nan = false
project_goodvoxels = true
regressors_all_comps = false
regressors_dvars_th = 1.5
regressors_fd_th = 0.5
run_reconall = true
skull_strip_fixed_seed = false
skull_strip_template = "OASIS30ANTs"
skull_strip_t1w = "force"
slice_time_ref = 0.5
spaces = "T1w MNI152NLin2009cAsym:res-2 fsaverage:den-164k MNI152NLin6Asym:res-2"
use_aroma = false
use_syn_sdc = false

[nipype]
crashfile_format = "txt"
get_linked_libs = false
nprocs = 24
omp_nthreads = 8
plugin = "MultiProc"
resource_monitor = false
stop_on_first_crash = false

[seeds]
master = 27307
ants = 55820
numpy = 55599

[nipype.plugin_args]
maxtasksperchild = 1
raise_insufficient = false
```

### Additional information / screenshots

![abcd](https://user-images.githubusercontent.com/72615316/231890437-2a9866cc-9cfe-403b-a325-e8e6507f3d27.png)
![23 0 1nogoodvoxels](https://user-images.githubusercontent.com/72615316/231890439-e90609fc-97c5-4dd9-b971-8c221f763dd2.png)
![goodvoxels](https://user-images.githubusercontent.com/72615316/231890440-dcfba220-81e3-4779-a900-b3700f2b65e9.png)

**Comment by effigies** [comment]
cc @madisoth

**Comment by effigies** [comment]
Because it never got linked in previous issues, the goodvoxels code was originally found in https://github.com/DCAN-Labs/DCAN-HCP/blob/master/fMRISurface/scripts/RibbonVolumeToSurfaceMapping.sh

**Comment by effigies** [comment]
Okay, so it looks like we for some reason were masking the BOLD with just the ribbon and not the broader goodvoxels mask. Here's the result of switching:

![image](https://user-images.githubusercontent.com/83442/234444439-fbaba363-ed9a-4e11-9338-421ca7efeafc.png)

**Comment by juansanchezpena** [comment]
I should be able to  run the patched version

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by effigies** [comment]
@juansanchezpena @ericfeczko Same image after more recent goodvoxels + workbench resampling work:

![image](https://github.com/nipreps/fmriprep/assets/83442/7ea8bd09-a118-4448-aa4a-098fb307572d)

Will post PRs today, but just to give you a look.

**Comment by effigies** [comment]
xref https://github.com/nipreps/smriprep/pull/339
xref https://github.com/nipreps/niworkflows/pull/806

**Comment by ericfeczko** [comment]
This looks fantastic! Aliasing looks like its gone -- @juansanchezpena would be great to see how this compares with ABCD-BIDS, I think we might have it :)

**Comment by juansanchezpena** [comment]
AMAZING!!!!
I would be happy to run the abcd-dcan on these data. Chris let me know how to access the anat epi and fmaps. I will also be happy to test once implemented with infant data
J

**Comment by ericfeczko** [comment]
We're gonna do some added tests and reliability analyses with extended data as well @juansanchezpena -- happy to let y'all know how it goes -- super pumped!!!
