### ISSUE TITLE
I have the a question about freesurfer license.txt but I don't know why. Can you help me?

### ISSUE THREAD

**Issue by ZhyGao** [nipreps/fmriprep#3007]
### What happened?

there's an error ERROR: a valid license file is required for FreeSurfer to run. fMRIPrep looked for an existing license file at several paths, in this order: 1) command line argument --fs-license-file; 2) $FS_LICENSE environment variable; and 3) the $FREESURFER_HOME/license.txt path. Get it (for free) by registering at https://surfer.nmr.mgh.harvard.edu/registration.html

### What command did you use?

```shell
I have the a question about freesurfer license.txt but I don't know why. Can you help me?

docker run -v /home/gzy/tvb-collab-master/input:/data -v /home/gzy/tvb-collab-master/output:/out -v /data/freesurfer/license.txt:/opt/freesurfer/license.txt nipreps/fmriprep:latest /data /out participant --participant-label CON03

there's an error ERROR: a valid license file is required for FreeSurfer to run. fMRIPrep looked for an existing license file at several paths, in this order: 1) command line argument --fs-license-file; 2) $FS_LICENSE environment variable; and 3) the $FREESURFER_HOME/license.txt path. Get it (for free) by registering at https://surfer.nmr.mgh.harvard.edu/registration.html
Thanks for your reply
```

### What version of fMRIPrep are you running?

23.0.2

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by effigies** [comment]
The error message states that we cannot run FreeSurfer because it cannot find a valid license. Do you have a license? Are you able to use it outside of fMRIPrep?

**Comment by effigies** [comment]
If you have FreeSurfer installed locally, you can try doing something like `mri_convert $FILE ${FILE%.nii.gz}.mgz`.

**Comment by effigies** [comment]
If FreeSurfer is installed, that command will access the behavior that requires a license. You can use it to test that you have a valid license that FreeSurfer can find.

**Comment by ZhyGao** [comment]
Thanks for your reply. Maybe is due to my valid license is not valid. I will reply a new license. Thanks again.

**Comment by ZhyGao** [comment]
I have tested the license as your suggestion. It seems well. But when I use docker to run this image, the error shows again.
![1684331423602](https://github.com/nipreps/fmriprep/assets/39367799/4c78162d-25ce-4930-bda0-8bd5df01c564)
![1684331549185](https://github.com/nipreps/fmriprep/assets/39367799/39a5ed05-d211-40cd-95b0-c1e973fc2674)

**Comment by ZhyGao** [comment]
For this command. --fs-license-file /data/freesurfer/license.txt.
![1684331886299](https://github.com/nipreps/fmriprep/assets/39367799/d6dbec86-6b25-4791-aa01-48bd3a2b07bf)
If I make the mistake of the grammar?

**Comment by ZhyGao** [comment]
I will try. Thanks for your time and attention.

**Comment by ZhyGao** [comment]
Soryy again, another problem..........................
![1684332903328](https://github.com/nipreps/fmriprep/assets/39367799/00aed6d8-24d2-470f-adb9-994784744226)
fmriprep-docker: error: Path should point to a file (or symlink of file): </data/freesurfer>.

**Comment by effigies** [comment]
I would guess that you have either `FREESURFER_HOME` or `FS_LICENSE` set to a non-existent location `/data/freesurfer`.

**Comment by ZhyGao** [comment]
I think I am not. So it is very confusing.
![1684391082323](https://github.com/nipreps/fmriprep/assets/39367799/a6c56be2-9c89-484d-8afe-9532fd264bf4)
![1684391108675](https://github.com/nipreps/fmriprep/assets/39367799/29075f7d-329d-4927-a975-a8598fd35b4d)

**Comment by ZhyGao** [comment]
I try it on another machine with another path of FreeSurfer. Also the same error. If any problem with the versions? Waiting for your reply. Thanks very much.

**Comment by ZhyGao** [comment]
Thanks. It seems solved. I use the --fs-license-file and try again. It works.

**Comment by effigies** [comment]
The issue is that `FS_LICENSE` should point to the actual file, like `/data/freesurfer/license.txt` or similar. But passing `--fs-license-file` explicitly should work as well.
