### ISSUE TITLE
Using NORM and non-NORM T1w images

### ISSUE THREAD

**Issue by effigies** [nipreps/fmriprep#3018]
> hi, i used fmriprep to average two T1Ws. The only difference between these two is the NORM tag under IMAGETYPE in the json file:
> 
>```
> "ImageType":[
> "original","PRIMARY","M","ND","NORM"]
> ```
>
> i am just wondering if that would be a problem in subsequent processing or quality of data?

_Originally posted by @shawnyoung23 in https://github.com/nipreps/fmriprep/issues/2227#issuecomment-1566602323_

**Comment by effigies** [comment]
You should not use both NORM and non-NORM T1w images, as they will not have good spatial alignment. If you trust the NORM procedure, use that. If you don't, use non-NORM. You can achieve this either by hiding the data you don't want to use in `sourcedata/` or by using a [bids-filter-file](https://fmriprep.org/en/stable/faq.html#how-do-i-select-only-certain-files-to-be-input-to-fmriprep).

**Comment by shawnyoung23** [comment]
Thank you effigies! the bids-filter-file worked well;

it's quite embarassing that i have completed 300 subjects previously with the averaged T1w...  would you mind give a hint at how much 'damage' this may bring to the result?

**Comment by effigies** [comment]
I would look at the resulting T1w images. My guess is you'll see areas that look like two different images were averaged. If you're lucky, it will all be in the neck.
