### ISSUE TITLE
'dataset_description.json' is missing from project root. 

### ISSUE THREAD

**Issue by gargiris** [nipreps/fmriprep#3019]
Hello, I am trying to preprocess resting state data from my study after having created a dataset folder in BIDS format. I have a folder (project root) inside which I have my subject folders (each containing an "anat" and "func" folder corresponding to the anatomical and functional time series data, respectively) and additionally, the dataset_description.json file where I have info pertaining to my study. The dataset_description.json file is attached below:

{
  "Name": "Hippocampus project",
  "BIDSVersion": "1.2.0",
  "License": "CC0",
  "Authors": [
    "Argiris"
  ],
  "Acknowledgements": "",
  "HowToAcknowledge": "",
  "Funding": [
    "",
    ""
  ],
  "ReferencesAndLinks": [
    "",
    ""
  ],
  "DatasetDOI": ""
}

However, when I tried to run fmriprep-docker, I receive the following error: in validate_root
    raise BIDSValidationError(
bids.exceptions.BIDSValidationError: **'dataset_description.json' is missing from project root**. Every valid BIDS dataset must have this file.
Example contents of 'dataset_description.json': 
{"Name": "Example dataset", "BIDSVersion": "1.0.2"}
fMRIPrep: Please report errors to https://github.com/nipreps/fmriprep/issues

The file is located in the project root, however. Could someone help me to understand why this could be? Could it be that the version of BIDS is incorrect for the fmriprep version that I'm using? Thank you!

**Comment by effigies** [comment]
Hi, please fill in the bug report issue template. That prompts you for the information needed to help you.
