### ISSUE TITLE
Would '--anat-only' crashes with '--use-aroma', or '--ignore slicetiming' option?

### ISSUE THREAD

**Issue by shawnyoung23** [nipreps/fmriprep#3027]
### What happened?

hey i was performing fMRIPREP using the command below, which performs only the ANAT workflow. Im preparing to using this ANAT folder in future, to finish fMRIPREP workflow using icaaroma.

from my understanding, it is ok to NOT use '--use-aroma' or '--ignore slicetiming' at this early anat workflow stage,  but i guess it would be better to confirm this with more professional people first ...

Any opinions would be greatly appreciated!

ps:
just by the way, im a bit curious about how fMRIPREP dues with soft failures in freeesurfer, like the minor incorrectness of surface contouring, etc 
XD

### What command did you use?

```shell
fmriprep /io/inputfolder/ /anatpre/ participant --participant-label subnumber --anat-only --fs-license-file /io/licensefile/input --use-aroma --ignore slicetiming --bids-filter-file /io/filter/input
```

### What version of fMRIPrep are you running?

unstable version released two weeks ago

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by effigies** [comment]
It's generally fine to use any set of flags. As you note, many of them will have no effect on the anatomical workflow, so their presence or absence won't matter to an `--anat-only` run.
