### ISSUE TITLE
Add option to control t2smap fittype

### ISSUE THREAD

**Issue by tsalo** [nipreps/fmriprep#3029]
### What would you like to see added in fMRIPrep?

Users have reported memory issues with the nonlinear T2*/S0 fitting setting (e.g., #2935 and #2827), so it might be worthwhile to give them control over the setting. I don't think it merits a command-line parameter, but is it perhaps something that could be controlled via the config file?

### Do you have any interest in helping implement the feature?

Yes

### Additional information / screenshots

Alternatively, I could change the fittype from nonlinear to the less memory-intensive, but potentially less accurate, `loglin` option.

**Comment by effigies** [comment]
I think it would be okay to add a parameter. `--me-t2s-fit-method` or something. I'd rather it be accessible by CLI than make people start caring about config files.

**Comment by tsalo** [comment]
Sounds good. I can open a PR for that.
