### ISSUE TITLE
Memory issues during gen_avg for high-res fMRI data

### ISSUE THREAD

**Issue by bwinsto2** [nipreps/fmriprep#3036]
### What happened?

For a while now I've been getting memory issues like the following, despite using a machine with 128GB RAM and allowing fMRIprep 24GB. I realize I am using pretty high resolution data and long scans (and fMRIprep is using float64), but I feel like it should still be able to allocate more than 13GB.

<img width="1142" alt="Screen Shot 2023-06-13 at 2 23 38 PM" src="https://github.com/nipreps/fmriprep/assets/61159065/6b176d43-45ae-44da-b31f-fb5acd68db3e">

### What command did you use?

```shell
running the following in python using os.system:

docker run --rm -v /data2/Brian/random/license.txt:/opt/freesurfer/license.txt -v /data/2104/raw_data:/data/2104/raw_data -v /data/2104/derivatives:/data/2104/derivatives -v /data/2104/ignore/temp_21040017:/data/2104/ignore/temp_21040017 nipreps/fmriprep:latest /data/2104/raw_data /data/2104/derivatives participant --participant-label 21040017 -w /data/2104/ignore/temp_21040017 --output-spaces anat MNI152NLin6Asym:res-2 --fs-license-file /opt/freesurfer/license.txt --mem 24000 --output-layout legacy')
```

### What version of fMRIPrep are you running?

23.0.1

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

FreeSurfer, Anatomical derivatives, Work directory

### Additional information / screenshots

I am using previously computed results in the sense that I've tried running it multiple times after the crashes. Would be grateful for any help. Thank you!

**Comment by effigies** [comment]
A few things:

1) Have you checked that your Docker containers have access to all the RAM you need? https://docs.docker.com/config/containers/resource_constraints/#memory
2) Assuming you do have access to 128GB of RAM, the 13GB allocation is probably not the problem in itself so much as that it is happening while other nodes are also making large allocations. We may have some badly tagged nodes that are using much more RAM than they claim. Watching the system with `htop` can be enlightening.
3)  I think we need to rewrite this interface. There's absolutely no reason that we can't take an average voxel-by-voxel without loading the whole file into RAM.

**Comment by bwinsto2** [comment]
Thanks for the suggestions. fMRIprep continued crashing when I supplied --mem 32GB of RAM, however I've run it twice now with 64GB of RAM and it hasn't crashed. Given that the[ docs say about 8GB of RAM/subject is necessary](https://fmriprep.org/en/stable/faq.html#how-much-cpu-time-and-ram-should-i-allocate-for-a-typical-fmriprep-run), well, that definitely wasn't true in my case.
