### ISSUE TITLE
DOC: Update outputs.rst to indicate hemi entity precedes space

### ISSUE THREAD

**Issue by askieslinger** [nipreps/fmriprep#3054]
Hi,

I have noticed the order of the bids identifiers 'hemi' and 'space' for func.gii outputs is swapped in the documentation compared to my real output and compared to the BIDS [guidelines.](https://bids-specification.readthedocs.io/en/stable/05-derivatives/03-imaging.html#discrete-surface-segmentations)
https://github.com/nipreps/fmriprep/blob/0ed3a93e4ab6c694743e7314b4753065a39b8334/docs/outputs.rst?plain=1#L192
`Discrete surface segmentations (sometimes called parcellations) of cortical structures MUST be stored as GIFTI label files, with the extension .label.gii. For combined volume/surface spaces, discrete segmentations MUST be stored as CIFTI-2 dense label files, with the extension .dlabel.nii.

Template:

<pipeline_name>/
    sub-<label>/
        anat/
            <source_entities>[_hemi-{L|R}][_space-<space>][_atlas-<label>][_res-<label>][_den-<label>]_dseg.{label.gii|dlabel.nii}

`(https://bids-specification.readthedocs.io/en/stable/05-derivatives/03-imaging.html#discrete-surface-segmentations)

This has possibly led to difficulties with the nilearn fmriprep interface and the order should perhaps be made clearer.
Thank you.

**Comment by effigies** [comment]
That's unfortunate. I think hemi makes sense after space, as you'd want to group pairs of related images together lexically.

**Comment by effigies** [comment]
Ah, unfortunate or not, we do write `hemi-` first: https://github.com/nipreps/fmriprep/blob/master/.circleci/ds005_bids_outputs.txt

So as you say, we just need to update our docs.

xref https://github.com/nipreps/fmriprep/issues/2620
