### ISSUE TITLE
fMRIPrep on TBI data

### ISSUE THREAD

**Issue by shilpitju1** [nipreps/fmriprep#3065]
Hi,

I used https://fmriprep.org/en/stable/workflows.html#cost-function-masking-during-spatial-normalization approach.
 I ran two analysis, one with lesion nii in the anat folder and one without. The fMRIPrep output nowhere points to the lesion file, so I am not able to understand if lesion is taken care of or not. Attaching here the output files. It would be great if you can guide me in this.
![bidsignore](https://github.com/nipreps/fmriprep/assets/141302543/37cd4e00-7cc8-4f96-bfb2-264ec18ddc0e)
**With lesion**
![0001_withlesion](https://github.com/nipreps/fmriprep/assets/141302543/58ae2259-089f-4500-90e5-a583534d4b62)
**Without lesion**
![0001_withoutlesion](https://github.com/nipreps/fmriprep/assets/141302543/0c3211b3-0d07-4a22-ac60-a79170f66a2d)
**With lesion**
![0004_withlesion](https://github.com/nipreps/fmriprep/assets/141302543/d1eb57ca-9743-495d-b232-832ce832f376)
**Without lesion**
![0004_withoutlesion](https://github.com/nipreps/fmriprep/assets/141302543/c2763f4a-a7a2-4f64-a703-524b08838927)

Thanks and regards,

Shilpi

**Comment by effigies** [comment]
The effect of a lesion mask should be visible in the template normalization. Without the lesion mask, you will typically see significant shrinking of the lesion.

We do not currently plot the lesion ROI, which would be a good addition.

**Comment by shilpitju1** [comment]
Template normalization for both with and without lesion input in the 'anat' folder
[sub-S0001_without_lesion_Roi_compressed.pdf](https://github.com/nipreps/fmriprep/files/12287184/sub-S0001_without_lesion_Roi_compressed.pdf)
 is appearing similar. Attaching
[sub-S001_with_Lesion_nii_compressed.pdf](https://github.com/nipreps/fmriprep/files/12287149/sub-S001_with_Lesion_nii_compressed.pdf)
 the entire fMRIPrep output.

**Comment by shilpitju1** [comment]
Attaching here the entire fMRIPrep output (for both with and without lesion files in the anat folder).

Kindly comment if with lesion approach is giving correct output.

[sub-S001_with_Lesion_nii_compressed.pdf](https://github.com/nipreps/fmriprep/files/12287227/sub-S001_with_Lesion_nii_compressed.pdf)

[sub-S0001_without_lesion_Roi_compressed.pdf](https://github.com/nipreps/fmriprep/files/12287237/sub-S0001_without_lesion_Roi_compressed.pdf)

**Comment by shilpitju1** [comment]
Kindly check the template normalization in the attached pdfs above.

**Comment by effigies** [comment]
Yeah, neither of those looks good to me, and it's probably down to the bad mask. I would suggest skull-stripping on your own and passing the skull-stripped brain to fMRIPrep, and then using `--skull-strip-t1w skip`. I would try `antsBrainExtraction.sh`.

**Comment by shilpitju1** [comment]
Hi,

As per your suggestion, I did skull stripping using antsBrainExtraction.sh and then passed skull-stripped brain to fMRIPrep and used --skull-strip-t1w skip
Attached here are the results on 2 subjects. Please comment.

[sub-S2_compressed.pdf](https://github.com/nipreps/fmriprep/files/12509436/sub-S2_compressed.pdf)

[sub-S01_compressed.pdf](https://github.com/nipreps/fmriprep/files/12509435/sub-S01_compressed.pdf)

**Comment by shilpitju1** [comment]
Hi,

Kindly comment on the above fMRIPrep outputs.

Thanks,
Shilpi

**Comment by effigies** [comment]
It looks like the tissue segmentation and surface reconstruction around the lesion is bad, as expected. The brain mask looks reasonable. The susceptibility distortion correction does not look good.

**Comment by shilpitju1** [comment]
Thanks so much.
