### ISSUE TITLE
Running fmriprep on M2 chip Mac using Docker

### ISSUE THREAD

**Issue by Momo-516** [nipreps/fmriprep#3068]
### What's the problem?

I am trying to use fmriprep in M2 chip Mac using docker.
I installed fmriprep via 
`pip install --user --upgrade fmriprep-docker`

Than I run
` fmriprep-docker /Users/kanamatsuyanagi/Downloads/cupcake/sub-1301 /Users/kanamatsuyanagi/Downloads/sub-1301/output participant --participant-label 1301 --fs-license-file /Users/kanamatsuyanagi/Downloads/license.txt`
but I got this error 
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Warning: <8GB of RAM is available within your Docker environment.
Some parts of fMRIPrep may fail to complete.
Continue anyway? [y/N]y
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=24.0.5 -it -v /Users/kanamatsuyanagi/Downloads/license.txt:/opt/freesurfer/license.txt:ro -v /Users/kanamatsuyanagi/Downloads/cupcake/sub-1301:/data:ro -v /Users/kanamatsuyanagi/Downloads/sub-1301/output:/out nipreps/fmriprep:23.1.4 /data /out participant --participant-label 1301
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Traceback (most recent call last):
  File "/opt/conda/envs/fmriprep/bin/fmriprep", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/cli/run.py", line 43, in main
    parse_args()
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/cli/parser.py", line 786, in parse_args
    config.from_dict({})
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/config.py", line 678, in from_dict
    execution.load(settings, init=initialize('execution'), ignore=ignore)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/config.py", line 232, in load
    cls.init()
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/config.py", line 476, in init
    cls._layout = BIDSLayout(
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/bids/layout/layout.py", line 135, in __init__
    root, description = validate_root(root, validate)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/bids/layout/validation.py", line 75, in validate_root
    raise BIDSValidationError(
bids.exceptions.BIDSValidationError: 'dataset_description.json' is missing from project root. Every valid BIDS dataset must have this file.
Example contents of 'dataset_description.json': 
{"Name": "Example dataset", "BIDSVersion": "1.0.2"}
fMRIPrep: Please report errors to https://github.com/nipreps/fmriprep/issues
```

So based on the conversation on #2431, I tried this
```
git clone https://github.com/nipreps/fmriprep.git
git -C fmriprep fetch origin pull/2435/head
git -C fmriprep checkout FETCH_HEAD
```
and run again with this
`fmriprep-docker /Users/kanamatsuyanagi/Downloads/cupcake/sub-1301 /Users/kanamatsuyanagi/Downloads/sub-1301/output participant --participant-label 1301 --fs-license-file /Users/kanamatsuyanagi/Downloads/license.txt --patch fmriprep=fmriprep/fmriprep`

But now I get this error 
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Warning: <8GB of RAM is available within your Docker environment.
Some parts of fMRIPrep may fail to complete.
Continue anyway? [y/N]y
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=24.0.5 -it -v /Users/kanamatsuyanagi/fmriprep/fmriprep:/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep:ro -v /Users/kanamatsuyanagi/Downloads/license.txt:/opt/freesurfer/license.txt:ro -v /Users/kanamatsuyanagi/Downloads/cupcake/sub-1301:/data:ro -v /Users/kanamatsuyanagi/Downloads/sub-1301/output:/out nipreps/fmriprep:23.1.4 /data /out participant --participant-label 1301
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
/opt/conda/envs/fmriprep/lib/python3.10/site-packages/bids/config.py:38: FutureWarning: Setting 'extension_initial_dot' will be removed in pybids 0.16.
  warnings.warn("Setting 'extension_initial_dot' will be removed in pybids 0.16.",
You are using fMRIPrep-0+unknown, and a newer version of fMRIPrep is available: 23.1.4.
Please check out our documentation about how and when to upgrade:
https://fmriprep.readthedocs.io/en/latest/faq.html#upgrading
/opt/conda/envs/fmriprep/lib/python3.10/site-packages/bids/layout/validation.py:48: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
Traceback (most recent call last):
  File "/opt/conda/envs/fmriprep/bin/fmriprep", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/cli/run.py", line 17, in main
    parse_args()
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/cli/parser.py", line 710, in parse_args
    validate_input_dir(
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/utils/bids.py", line 145, in validate_input_dir
    raise RuntimeError(error_msg % ','.join(bad_labels))
RuntimeError: Data for requested participant(s) label(s) not found. Could not find data for participant(s): 1301. Please verify the requested participant labels. This error can be caused by the input data not being accessible inside the singularity container. Please make sure all paths are mapped properly (see https://www.sylabs.io/guides/3.0/user-guide/bind_paths_and_mounts.html)
fMRIPrep: Please report errors to https://github.com/nipreps/fmriprep/issues
```

In case,,,
when I try this 
`fmriprep-docker --version`
I get this 
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
fMRIPrep v23.1.4
```

What would be the problem?

(The dataset is from openneuro and is BIDS validated)

### What command did you use?

```shell
fmriprep-docker /Users/kanamatsuyanagi/Downloads/cupcake/sub-1301 /Users/kanamatsuyanagi/Downloads/sub-1301/output participant --participant-label 1301 --fs-license-file /Users/kanamatsuyanagi/Downloads/license.txt --patch fmriprep=fmriprep/fmriprep
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=24.0.5 -it -v /Users/kanamatsuyanagi/fmriprep/fmriprep:/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep:ro -v /Users/kanamatsuyanagi/Downloads/license.txt:/opt/freesurfer/license.txt:ro -v /Users/kanamatsuyanagi/Downloads/cupcake/sub-1301:/data:ro -v /Users/kanamatsuyanagi/Downloads/sub-1301/output:/out nipreps/fmriprep:23.1.4 /data /out participant --participant-label 1301
```

### What version of fMRIPrep are you running?

v23.1.4

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by effigies** [comment]
> `fmriprep-docker /Users/kanamatsuyanagi/Downloads/cupcake/sub-1301`

You are passing an individual subject instead of a dataset.

**Comment by Momo-516** [comment]
Thank you @effigies.

I actually uninstalled everything and reinstalled it and tried it again incorporating your point. Now I can run it without having to clone it from GitHub. (Which I am not sure why it got fixed. Anyways, ) So I can start the fmriprep with this code now :) :
`fmriprep-docker ~/ds003242 ~/ds003242_preprocessed/sub1 participant --participant-label SAXSISO01b --fs-license-file ~/license.txt -w ~/fmri_working `

But after a few hours (3 ~ 8 hrs), I always get this error (I have tried it 4 times and I get approximately similar error messages):
`230812-13:29:20,519 nipype.workflow INFO:
	 [Node] Finished "sdc_report", elapsed time 86.041331s.
exception calling callback for <Future at 0x40245f6320 state=finished raised BrokenProcessPool>
Traceback (most recent call last):
  File "/opt/conda/envs/fmriprep/lib/python3.10/concurrent/futures/_base.py", line 342, in _invoke_callbacks
    callback(self)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/opt/conda/envs/fmriprep/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/opt/conda/envs/fmriprep/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.`

According to previous issues, I figured it out to be a memory issue. So I tried adding, 
`--omp-nthreads 8 --nthreads 8`
But I still got the same issue so next I also added, 
`--mem-mb 30000`
But still I get the same issue.

I have allocated 8 CPU, 8GB RAM, and 4GB Swap memory to docker which is all the maximum value I can allocate. Virtual disk limit is set to 216GB. My pc itself has 360.2 GB left in Macintosh HD.

What do you think the problem is?

I was also wondering if this
`File "/opt/conda/envs/fmriprep/lib/python3.10/concurrent/futures/_base.py"`
would be the problem.
What does
`/opt/conda/envs/fmriprep`
point to? I don't have such conda environment called fmriprep but would this be related to the error I get?

**Comment by effigies** [comment]
That's definitely a memory error. If you only have 10GB, I might try running with `--nthreads 1`, which should let you still run some parallel tasks with `--omp-nthreads 8`, but will only run one task at a time.

**Comment by MtKana** [comment]
Sorry for the late reply.

Unfortunately, I couldn't run it even with --nthreads 1.

But I tried it with another dataset (lighter one) with --nthreads 1 and it worked! Maybe my PC is not capable of processing a large dataset.

Thank you very much for your help. It helped me very much.
