### ISSUE TITLE
One visual report per session for dataset with many sessions for a single subject

### ISSUE THREAD

**Issue by celprov** [nipreps/fmriprep#3080]
### What would you like to see added in fMRIPrep?

With @oesteban, we are currently piloting the acquisition of a deep sampling dataset that will contain 72 sessions for a single subject.
As such, the current implementation that renders all the sessions on a single report will be intractable for our project.

Would it be possible to implement an option that generates one visual report per session? 

One way we could do it is by setting a threshold on the number of sessions per subject, and in case there are more sessions than that threshold, fMRIPrep generates one visual report per session.

Feel free to suggest alternative implementation.

Alternatively, I suppose people working on the MyConnectome dataset faced the same issue, how was it addressed? 

### Do you have any interest in helping implement the feature?

Yes

**Comment by effigies** [comment]
That all sounds good to me.  Please feel free to open a PR, and don't hesitate to ask any questions.
