### ISSUE TITLE
ERROR: a valid license file is required for FreeSurfer to run.

### ISSUE THREAD

**Issue by AnnJingLyu** [nipreps/fmriprep#3104]
### What happened?

The code is error. But I couldn't find the same problem in google. So I want to ask for help in here.

### What command did you use?

```shell
fmriprep-docker /home/lijiayue/fearspace/bids /home/lijiayue/fearspace/output  --participant-label YANGPENG  --output-spaces
MNI152NLin6Asym:res-2  --fs-license-file/home/lijiayue/license.txt
```

### What version of fMRIPrep are you running?

20.2.1

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

Work directory

### Please copy and paste any relevant log output.

```shell
ERROR: a valid license file is required for FreeSurfer to run. fMRIPrep looked for an existing license file at several paths, in this order: 1) command line argument ``--fs-license-file``; 2) ``$FS_LICENSE`` environment variable; and 3) the ``$FREESURFER_HOME/license.txt`` path. Get it (for free) by registering at https://surfer.nmr.mgh.harvard.edu/registration.html
fMRIPrep: Please report errors to https://github.com/nipreps/fmriprep/issues
```

### Additional information / screenshots

![ddc7689a3cfaf807b9d9f3db8a438c7](https://github.com/nipreps/fmriprep/assets/147573549/4347f203-eef7-43ec-b9e7-b92c15342330)
![a6a27b9db34df6f72f930fa0bb4e45b](https://github.com/nipreps/fmriprep/assets/147573549/756f5604-7d38-4868-b199-4a7e2faea353)

**Comment by effigies** [comment]
You're missing a space or equals:

```diff
- --fs-license-file/home/lijiayue/license.txt
+ --fs-license-file /home/lijiayue/license.txt
```

**Comment by AnnJingLyu** [comment]
> 您缺少一个空格或等于：
> 
> ```diff
> - --fs-license-file/home/lijiayue/license.txt
> + --fs-license-file /home/lijiayue/license.txt
> ```

Thank you for your answer. I plus the spacing. But it still same error.

**Comment by effigies** [comment]
Try:

```
fmriprep-docker /home/lijiayue/fearspace/bids /home/lijiayue/fearspace/output --participant-label YANGPENG --output-spaces MNI152NLin6Asym:res-2 --fs-license-file /home/lijiayue/license.txt
```

**Comment by AnnJingLyu** [comment]
> 尝试：
> 
> ```
> fmriprep-docker /home/lijiayue/fearspace/bids /home/lijiayue/fearspace/output --participant-label YANGPENG --output-spaces MNI152NLin6Asym:res-2 --fs-license-file /home/lijiayue/license.txt
> ```

I'm so sorry. I busied in other projects this week. I try again in your way, and it's running. I can't thank you enough for your help.
