### ISSUE TITLE
BOLD reference to T1w transforms are mislabeled

### ISSUE THREAD

**Issue by tsalo** [nipreps/fmriprep#3117]
### What happened?

The transform file `<source_entities>_from-scanner_to-boldref_mode-image_xfm.txt` has the motion correction transform for each volume. However, the transform `<source_entities>_from-scanner_to-T1w_mode-image_xfm.txt` has a single ITK transform, so it must the transform from the bold reference space to the T1w.

It seems like `<source_entities>_from-scanner_to-T1w_mode-image_xfm.txt` should be renamed to `<source_entities>_from-boldref_to-T1w_mode-image_xfm.txt`.

### What command did you use?

```shell
singularity run --home $HOME --cleanenv \
    -B $BIDS_DIR:/data \
    /cbica/home/salot/datasets/mobile-phenomics/singularity/fmriprep-23_1_5dev.simg \
    /data \
    /data/derivatives/fmriprep \
    participant \
    --participant-label 01 \
    -w /cbica/home/salot/datasets/mobile-phenomics/work \
    --nprocs 1 \
    --omp-nthreads 1 \
    --output-spaces func T1w MNI152NLin6Asym \
    --me-t2s-fit-method curvefit \
    --output-layout bids \
    --me-output-echos \
    --project-goodvoxels \
    --cifti-output \
    --bids-filter-file /cbica/home/salot/datasets/mobile-phenomics/code/bids_filter.json \
    --fs-license-file /cbica/home/salot/datasets/mobile-phenomics/freesurfer_license.txt \
    --skip_bids_validation
```

### What version of fMRIPrep are you running?

23.2.0.dev39+g36404281

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by effigies** [comment]
Done in 23.2.0a1.
