### ISSUE TITLE
Ability to Change the High Pass Filter Cosine Basis Function in FMRIprep

### ISSUE THREAD

**Issue by danielsazhin** [nipreps/fmriprep#3124]
### What would you like to see added in fMRIPrep?

Hello,

Would it be possible to make it possible to change the default discrete cosine basis function for the high-pass filter (cut-off 128 seconds, HZ=.008) to a different value in FMRIprep? We have some events in our design that are ~100 seconds apart, and we would like to lengthen the cut-off to over 200 seconds. It looks like this request may have come up before: https://github.com/nipreps/fmriprep/issues/2963, though we would like to also ask for this feature.

Thank you,
Daniel Sazhin

### Do you have any interest in helping implement the feature?

Yes, but I would need guidance

**Comment by effigies** [comment]
Could you explain more about your use case, such as sharing your design matrix? It's unclear how your case differs from that in the linked discussion, so I'm not sure that we've actually hit a situation where our using a 128s cutoff for CompCor calculation really matters.

Did you have a look at @jmumford's https://github.com/nipreps/fmriprep/issues/2963#issuecomment-1466858267 and check whether your regressors actually have problems with a cosine basis?
