### ISSUE TITLE
When I started fmriprep using the docker command, I couldn't resolve error "AttributeError: type object 'loggers' has no attribute 'warning'"

### ISSUE THREAD

**Issue by Naoki-Take** [nipreps/fmriprep#3127]
### What happened?

When I executed the following command, I encountered the error shown below and can't resolve it. I would appreciate any advice.

```
`> docker run -ti --rm `
>>   -v C:/Users/natakegami/fmriprep/Nifti:/input `
>>   -v C:/Users/natakegami/fmriprep/output:/output `
>>   -v C:/Users/natakegami/fmriprep/license.txt:/license `
>>   poldracklab/fmriprep:latest `
>>   /input /output participant `
>>   --participant-label sub-2023 `
>>   --fs-license-file /license `
>>   --skip-bids-validation `
>>   --n-cpus 4 `
>>   --fs-no-reconall`

-----------

`Unable to find image 'poldracklab/fmriprep:latest' locally
latest: Pulling from poldracklab/fmriprep
0a01a72a686c: Pulling fs layer
cc899a5544da: Pulling fs layer
19197c550755: Pulling fs layer
716d454e56b6: Pull complete
b5bf898e214a: Pull complete
42da0942cc0e: Pull complete
14f5757104e9: Pull complete
611fe4f705a5: Pull complete
ac0b78389510: Pull complete
9e499ad45d56: Pull complete
d9fe4a797d63: Pull complete
0096e55d11c8: Pull complete
8edcf0ca7093: Pull complete
4d1c726a5a26: Pull complete
6a13c4f0f499: Pull complete
4041fab309df: Pull complete
76cb4738a4de: Pull complete
9f64cb20b123: Pull complete
59feaf5d0228: Pull complete
bf2e5cea3f0a: Pull complete
b4ba13fe1476: Pull complete
31a70e08417a: Pull complete
fdd6ba96cc6b: Pull complete
39bb0bc52b4b: Pull complete
8d4583aa23d3: Pull complete
4ac066736182: Pull complete
378885e5b53c: Pull complete
Digest: sha256:4dafc01ffe3f36c9bc5557dfe6fc3dc6ec38b046cd6c41c34a958474096cef8a
Status: Downloaded newer image for poldracklab/fmriprep:latest
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
You are using fMRIPrep-20.2.0, and a newer version of fMRIPrep is available: 23.1.4.
Please check out our documentation about how and when to upgrade:
https://fmriprep.readthedocs.io/en/latest/faq.html#upgrading
WARNING: Version 20.2.0 of fMRIPrep (current) has been FLAGGED
(reason: Functional outputs in standard space can be wrong depending on the original data's orientation headers - see https://github.com/nipreps/fmriprep/issues/2307).
That means some severe flaw was found in it and we strongly
discourage its usage.
231104-02:12:05,474 nipype.workflow IMPORTANT:

    Running fMRIPREP version 20.2.0:
      * BIDS dataset path: /input.
      * Participant list: ['2023'].
      * Run identifier: 20231104-021202_30bb688c-f490-4c00-a7d3-eea8b5e54c8c.
      * Output spaces: MNI152NLin2009cAsym:res-native.
      * Pre-run FreeSurfer's SUBJECTS_DIR: /output/freesurfer.
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/workflow.py", line 84, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 64, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 304, in init_single_subject_wf
    func_preproc_wf = init_func_preproc_wf(bold_file)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/bold/base.py", line 167, in init_func_preproc_wf
    config.loggers.warning(
AttributeError: type object 'loggers' has no attribute 'warning'`
```

### What command did you use?

```shell
> docker run -ti --rm `
>>   -v C:/Users/natakegami/fmriprep/Nifti:/input `
>>   -v C:/Users/natakegami/fmriprep/output:/output `
>>   -v C:/Users/natakegami/fmriprep/license.txt:/license `
>>   poldracklab/fmriprep:latest `
>>   /input /output participant `
>>   --participant-label sub-20230808 `
>>   --fs-license-file /license `
>>   --skip-bids-validation `
>>   --n-cpus 4 `
>>   --fs-no-reconall
```

### What version of fMRIPrep are you running?

20.2.0

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by effigies** [comment]
Please do not use `poldracklab/fmriprep` or `:latest`. Use `nipreps/fmriprep` and a specific version. I would recommend using `fmriprep-docker` to help construct your command.

It looks like our docs are a bit sparser than they used to be, but instructions can still be found here: https://fmriprep.org/en/20.2.2/installation.html#the-fmriprep-docker-wrapper

In any case, the latest versions are 20.2.7 (LTS) and 23.1.4.

**Comment by Naoki-Take** [comment]
Thank you for your prompt reply!
I am using Windows, but I cannot successfully set the path for fmriprep-docker. 
Therefore, I am trying the following command now:

`docker run -ti --rm `
  -v C:/Users/natakegami/fmriprep/Nifti:/input `
  -v C:/Users/natakegami/fmriprep/output:/output `
  -v C:/Users/natakegami/fmriprep/license.txt:/license `
   nipreps/fmriprep:latest `
  /input /output participant `
  --participant-label sub-20230808 `
  --fs-license-file /license `
  --skip-bids-validation `
  --n-cpus 4 `
  --fs-no-reconall`

I have two questions:

①Is there a difference in behavior between using the fmriprep-docker command and pulling fmriprep-docker using the docker command?

②There are two latest versions, but why is there such a difference in their numbers? Is there any difference between them?

Thank you for your support

**Comment by effigies** [comment]
> ①Is there a difference in behavior between using the fmriprep-docker command and pulling fmriprep-docker using the docker command?

No.

> ②There are two latest versions, but why is there such a difference in their numbers? Is there any difference between them?

Yes. 20.2.7 is the long term support (LTS) release. 23.1.4 is the latest release. The older one does not have some newer features, but will also not have new bugs. I would try latest, and if that doesn't work well, then try the LTS.

**Comment by Naoki-Take** [comment]
After changing the repository to nipreps, the process was completed!
It seems that NiPreps is an active community that currently oversees several preprocessing software. 
I wasn't aware of that.

I was recommended by others not to include —fs-no-reconall and to specify a working directory with -w. 
If I include —fs-no-reconall, will the output change?

Thank you!

**Comment by effigies** [comment]
> If I include —fs-no-reconall, will the output change?

Yes. BOLD-T1w coregistration is significantly better with FreeSurfer reconstruction.

**Comment by Naoki-Take** [comment]
Thank you for your response.
Is it correct to understand that if I don't include the `—fs-no-reconall` argument,  the reconstruction will be done by FreeSurfer and the image quality will improve?

**Comment by effigies** [comment]
> the reconstruction will be done by FreeSurfer and

Yes.

> the image quality will improve?

No. The quality of [registration](https://en.wikipedia.org/wiki/Image_registration) should improve, but this will not change the quality of the image for better or worse.

**Comment by Naoki-Take** [comment]
I'm not quite familiar with the term 'registration', but I'll look into it. 

Ultimately, is it recommended to use` —fs-no-reconall` or not?

**Comment by effigies** [comment]
No, we do not recommend using that. The defaults are the recommended options, so running recon-all is recommended.

**Comment by Naoki-Take** [comment]
Thank you.
In that case, I'll try running it without specifying `—fs-no-reconall`.
