### ISSUE TITLE
fieldmap-less SDC in v. 23.2.0a2 producing odd/distorted results

### ISSUE THREAD

**Issue by atkinsonap** [nipreps/fmriprep#3158]
### What happened?

Version 23.2.0a2 of fMRIPrep is producing good-looking (non-distorted) susceptibility distortion corrected functional images for my dataset, when the SDC is based on acquired fieldmaps, which is great. But I've several subjects in this dataset for whom we don't have fieldmaps, so for them I tried the fieldmap-less SDC option (via the --use-syn-sdc option). Unfortunately this produced unusual-looking images, as shown in the attached files. (These are of my own brain, which I am happy to share.)
![sub-CC07_run-1_fmapid-auto00000_desc-anat_fieldmap](https://github.com/nipreps/fmriprep/assets/43091872/e64ab654-f535-4dcb-a54e-29246a4294ba)
<img width="1798" alt="Screenshot 2023-11-24 at 11 30 55" src="https://github.com/nipreps/fmriprep/assets/43091872/6d2669ca-4d04-40e3-babf-b91ae60e36d8">

### What command did you use?

```shell
cmd="${SINGULARITY_CMD} ${SING_BIDS_DIR} ${SING_BIDS_DIR}/${DERIVS_DIR} participant --participant-label $subject -w /work/ -vv --omp-nthreads 8 --nthreads 12 --mem_mb 30000 --output-spaces MNI152NLin2009cAsym MNI152NLin6Asym --ignore slicetiming --skip-bids-validation --use-syn-sdc --fs-no-reconall"
```

### What version of fMRIPrep are you running?

23.2.0a2

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by effigies** [comment]
Yes, I thought this would come up. I've been focusing on the other methods to the exclusion of syn. I'm not positive I'll have time to track this down before the release. Possibly we should just disable it until we have time to fix it.

**Comment by YuchuanQiao** [comment]
Hi @effigies, I also met the same problem as @atkinsonap  with  --use-syn-sdc option using fmriprep v. 23.2.0a2. The problem presents in the final image and in the "desc-coreg_boldref" image but NOT in the "desc-hmc_boldref" image. I think the problem is related to the fieldmap estimation from sdcflow.

**Comment by mgxd** [comment]
Should have been fixed - please reopen if not
