### ISSUE TITLE
output preprocessed T2 in anat derivatives directory

### ISSUE THREAD

**Issue by moser297** [nipreps/fmriprep#3164]
### What would you like to see added in fMRIPrep?

Would it be possible to additionally output the processed T2 in the anat derivatives folder if a T1 and T2 is inputted for data preprocessing?
Ideally, it would follow the same principle as in Nibabies. 

### Do you have any interest in helping implement the feature?

No

**Comment by effigies** [comment]
This should be implemented. What version are you using?

**Comment by moser297** [comment]
We used 23.2.0a2. We'll double-check. Thanks for your quick reply!

**Comment by moser297** [comment]
Never mind, found it. There was a bit of confusion on our side because of the different naming conventions between Nibabies and fMRIprep
