### ISSUE TITLE
Goodvoxels mask no longer written out in 23.2.0a2

### ISSUE THREAD

**Issue by tsalo** [nipreps/fmriprep#3168]
### What happened?

It looks like `ds_goodvoxels_mask` no longer exists, so the goodvoxels mask won't be written out.

It also doesn't look like the goodvoxels mask is used to actually mask the data at all. Is that correct?

### What command did you use?

```shell
This was based on looking at the code.
```

### What version of fMRIPrep are you running?

23.2.0a2

### How are you running fMRIPrep?

Other

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by effigies** [comment]
The goodvoxels mask is used when resampling the BOLD series to the subject mesh during CIFTI generation:

https://github.com/nipreps/fmriprep/blob/3c836e8278ba3efe47982513997c166c9fd7fb06/fmriprep/workflows/bold/resampling.py#L716-L735

Is it a useful thing to have after the fact? I figured since it's deterministic and cheap, it's not really a problem to regenerate on the fly.

**Comment by tsalo** [comment]
Ah, sorry about that. I missed the part where the goodvoxels mask is passed into `volume_to_surface`. Does that mean that other steps you added in #3011 (e.g., `CreateROI`) are not necessary? I assumed they were accidentally removed as part of the fit/apply refactor, but it seems like I misunderstood the changes.

FWIW, I think it's useful to have access to the goodvoxels mask to apply it to derived maps I'd like to run through `init_bold_fsLR_resampling_wf` (in my case, CBF maps calculated from the aslref-space ASL time series), but that's a different issue.

**Comment by effigies** [comment]
Those were moved into smriprep in nipreps/smriprep#388: [`init_hcp_morphometrics_wf()`](https://www.nipreps.org/smriprep/api/smriprep.workflows.surfaces.html#smriprep.workflows.surfaces.init_hcp_morphometrics_wf)

**Comment by effigies** [comment]
No worries. There's a lot that's changed!
