### ISSUE TITLE
Support predefined goodvoxels mask in `init_bold_fsLR_resampling_wf`

### ISSUE THREAD

**Issue by tsalo** [nipreps/fmriprep#3169]
### What would you like to see added in fMRIPrep?

I am currently using fMRIPrep as a dependency for ASLPrep, and, while the currently version of `init_bold_fsLR_resampling_wf` allows me to convert preprocessed ASL files to CIFTIs, I can't use the goodvoxels mask generated from the ASL file when converting derived CBF maps to CIFTIs.

It might even be worth it to move `init_bold_fsLR_resampling_wf` to niworkflows, since it's useful beyond just BOLD data.

### Do you have any interest in helping implement the feature?

Yes

### Additional information / screenshots

This might be useful for PET as well (I'm not sure what PET processing looks like).

**Comment by mnoergaard** [comment]
Yes - there will be a PET use for resampling volumes to fsLR grayordinates. But no wrinkles :-)
