### ISSUE TITLE
Bash is not running and gives no output

### ISSUE THREAD

**Issue by connectomeclara** [nipreps/fmriprep#3174]
Hello fellow fMRIPrep users! 

*I apologize for any trivial mistakes as I am just a high school student and computer science is very new to me*

I am trying to use fMRIPrep for my science fair project on connectomes. It is crucial that I get it up and running as soon as possible. Thus, I am in dire need of assistance. 

Background: I use a Windows 11 Pro computer that was just converted from Windows 11 S. I run all my commands in terminal using Ubuntu 22.04.3 LTS. I downloaded Docker version 24.0.6, build ed223bc. I have the fMRIPrep version v23.1.4. I downloaded the fmriprep_singleSubj.sh script and successfully moved it to code (the file the instructional video told me to create). When I enter the code directory and run ls I get fmriprep_singleSubj.sh in green as I made it executable. I also have Docker Desktop open and running while I attempt bash.

Problem: When I run bash fmriprep_singleSubj.sh I get absolutely no output. I've seen that this is a common issue (YT video comment section), but no one has listed a reply. I am unsure of what to do and would greatly appreciate assistance. I am open to any and all suggestions!
![Screenshot 2023-12-06 171749](https://github.com/nipreps/fmriprep/assets/153136333/65e3f403-8342-47c9-9c9b-55d844d9e9c5)

**Comment by effigies** [comment]
Hi there. This issue tracker is mostly for bugs and features. Please use neurostars.org for user support.

If you're using a bash script, you'll want to share the full contents. There's a prompt that will help you right a good support request over there.

**Comment by connectomeclara** [comment]
#!/bin/bash
#Template provided by Daniel Levitas of Indiana University
#Edits by Andrew Jahn, University of Michigan, 07.22.2020

#User inputs:
bids_root_dir=$HOME/Desktop/Flanker
subj=08
nthreads=4
mem=20 #gb
container=docker #docker or singularity

#Begin:

#Convert virtual memory from gb to mb
mem=`echo "${mem//[!0-9]/}"` #remove gb at end
mem_mb=`echo $(((mem*1000)-5000))` #reduce some memory for buffer space during pre-processing

#export TEMPLATEFLOW_HOME=$HOME/.cache/templateflow
export FS_LICENSE=$HOME/Desktop/Flanker/derivatives/license.txt

#Run fmriprep
if [ $container == singularity ]; then
  unset PYTHONPATH; singularity run -B $HOME/.cache/templateflow:/opt/templateflow $HOME/fmriprep.simg \
    $bids_root_dir $bids_root_dir/derivatives \
    participant \
    --participant-label $subj \
    --skip-bids-validation \
    --md-only-boilerplate \
    --fs-license-file $HOME/Desktop/Flanker/derivatives/license.txt \
    --fs-no-reconall \
    --output-spaces MNI152NLin2009cAsym:res-2 \
    --nthreads $nthreads \
    --stop-on-first-crash \
    --mem_mb $mem_mb \
else
  fmriprep-docker $bids_root_dir $bids_root_dir/derivatives \
    participant \
    --participant-label $subj \
    --skip-bids-validation \
    --md-only-boilerplate \
    --fs-license-file $HOME/Desktop/Flanker/derivatives/license.txt \
    --fs-no-reconall \
    --output-spaces MNI152NLin2009cAsym:res-2 \
    --nthreads $nthreads \
    --stop-on-first-crash \
    --mem_mb $mem_mb
fi
