### ISSUE TITLE
Clarify: `--dvars-spike-threshold` uses standardised dvars rather than dvars in online docs

### ISSUE THREAD

**Issue by htwangtw** [nipreps/fmriprep#3204]
The current online documentation gives an impression that fMRIPrep uses DVARS as the metric but in the CLI doc  and the method's boiler template said using *standardised* DVARS. In the code it's also using standardised DVARS.

It would be great to correct the online documentation to prevent users (mostly myself) second guessing themselves.

**Comment by effigies** [comment]
Agreed. Mind opening a PR?
