### ISSUE TITLE
Support `null` and `*` in lists in `--bids-filter-file`

### ISSUE THREAD

**Issue by tsalo** [nipreps/fmriprep#3214]
### What would you like to see added in fMRIPrep?

At the moment, it looks like the `--bids-filter-file` won't convert `null` and `*` to Queries when they're in lists within the JSON.

### Do you have any interest in helping implement the feature?

Yes

### Additional information / screenshots

For example, the following won't work:

```json
{
    "bold": {
        "task": ["rest"],
        "run": [null, "01", "02"],
    }
}
```

**Comment by mgxd** [comment]
Good catch - we should expand the custom decoding in https://github.com/nipreps/fmriprep/blob/70327827d2da9c157547197c1fe3302104ab35d3/fmriprep/cli/parser.py#L96-L99
to expand lists (probably recursively)

**Comment by tsalo** [comment]
I'm adding the same thing to ASLPrep in https://github.com/PennLINC/aslprep/pull/388, so I'm happy to copy it over to an fMRIPrep PR.
