### ISSUE TITLE
add citation generator for various citation styles

### ISSUE THREAD

**Issue by burdinskid13** [nipreps/fmriprep#3217]
### What would you like to see added in fMRIPrep?

As you request in your documentation, I wanted to include the summary paragraphs and corresponding references in my paper. However, I require them in a different reference format from the one you provide. 

I tried for over two hours to work with the .tex and .bib file in overleaf to change the citation style to AMA and kept running into errors. I know that I can copy the .bib into a citation manager and then manually link the in-text citations, but that seems quite tedious. 

It would be super helpful to have an option on your website or within the fmriprep call to select among the top 5-10 common citation styles and produce the citation paragraphs and corresponding reference section accordingly. I think it would also encourage others to cite fmriprep in this way. Thanks so much! 

### Do you have any interest in helping implement the feature?

No

**Comment by effigies** [comment]
While I grant this would be useful, I don't think we'll have time to work on it. In general if one is using LaTeX, the LaTeX snippet we generate should be fairly easily dropped into an existing document. But if you are targeting other formats, I would suggest converting directly with [pandoc](https://pandoc.org/).

To select a citation style, the https://github.com/citation-style-language/styles/ repository is the best resource.

Example usage:

```console
pandoc --bibliography CITATION.bib \
    --csl american-medical-association.csl --citeproc \
    CITATION.md -o CITATION.odt
```

xref https://neurostars.org/t/fmriprep-citation-with-different-reference-style/27997/2
