### ISSUE TITLE
Flag to align Freesurfer T1w and fMRIPrep T1w spaces

### ISSUE THREAD

**Issue by butellyn** [nipreps/fmriprep#3225]
### What would you like to see added in fMRIPrep?

Would it be possible to add a flag that puts the freesurfer T1w image and the fMRIPrep T1w image in the same space before processing? I am running into a lot of problems projecting the BOLD data to the native surface because the T1w image used in fMRIPrep is shifted in space from the T1w image used in freesurfer. See [this neurostars post](https://neurostars.org/t/getting-fmriprep-outputs-into-fslr32k-space-viewing-issue/27052) for an example problem. 

### Do you have any interest in helping implement the feature?

Yes, but I would need guidance

**Comment by effigies** [comment]
How are you projecting your volume data to surface? If you're using mri_vol2surf, then you could concatenate your registrations BOLD-to-T1w registration with your T1w to fsnative registration with `mri_concatenate_lta` (you'll first need to convert from ITK format with `lta_convert`). This can be passed with `mri_vol2surf --reg`.

If you need to use `wb_command`, instead you'll want to project the surfaces into the BOLD space and then use `wb_command -volume-to-surface-mapping`. I'd need to look up how to do that with workbench, but it's pretty easy in Python.

**Comment by butellyn** [comment]
Hi @effigies! I have tried a few different ways, including `mri_vol2surf` and `wb_command -volume-to-surface-mapping`. I'll look into these options. Thanks!
