### ISSUE TITLE
Add motion parameter units to confounds sidecar

### ISSUE THREAD

**Issue by tsalo** [nipreps/fmriprep#3231]
### What would you like to see added in fMRIPrep?

I think it would be nice if the confounds JSON file included the units of motion-related columns.

This could be done for all motion-related confounds, but I think it's most important for the rotation columns.

### Do you have any interest in helping implement the feature?

Yes

### Additional information / screenshots

This stems from https://github.com/PennLINC/xcp_d/issues/1053. Basically, a user wants me to include metadata for the motion parameters in XCP-D. I'm happy to do that, but I thought it would make more sense to inherit the metadata from the preprocessing pipeline (i.e., fMRIPrep).

**Comment by tsalo** [comment]
I know that the units of the motion parameters (mm for translations and radians for rotations) is enforced in BEP012 (Functional Derivatives) (see [here](https://bids-specification--519.org.readthedocs.build/en/519/derivatives/functional-derivatives.html#column-names_2)) and the units are documented in the [`init_bold_confs_wf ` docstring](https://fmriprep.org/en/23.2.0/api.html#fmriprep.workflows.bold.confounds.init_bold_confs_wf), but neither location is particularly obvious to users.

**Comment by effigies** [comment]
I'm fine with this.
