### ISSUE TITLE
Susceptibility distortion correction fails

### ISSUE THREAD

**Issue by kerkelae** [nipreps/fmriprep#3250]
### What happened?

I'm trying to use fMRIPrep to preprocess my fMRI data, but the susceptibility distortion correction keeps failing. The results are always more distorted than the original image. Even if the brain looks relatively normal, the eyes are elongated. These results are using the blip-up blip-down method, but I get similar results using magnitude and phase difference maps as well.

Is this a bug in fMRIPrep, or am I doing something wrong? Any help is greatly appreciated. 🙏

![image](https://github.com/nipreps/fmriprep/assets/15076450/e8a3a271-e9a4-4f25-9591-0d601a21bf89)

![image](https://github.com/nipreps/fmriprep/assets/15076450/0b7f99e0-1353-41cd-baf5-b71c090ce724)

### What command did you use?

```shell
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=24.0.6 -it -v /home/leevi/.freesurfer_license/freesurfer_license.txt:/opt/freesurfer/license.txt:ro -v /home/leevi/ucl/new-bind/bids_datasets/london:/data:ro -v /home/leevi/ucl/new-bind/fmriprep:/out nipreps/fmriprep:23.1.4 /data /out participant --participant-label 6002a --nthreads 16 --omp-nthreads 16 --mem_mb 24000 --sloppy --fs-no-reconall
```
```


### What version of fMRIPrep are you running?

23.1.4

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
No errors to report!
```

**Comment by effigies** [comment]
Do you still see this issue in 23.2.0?

**Comment by kerkelae** [comment]
Seems to work much better with version 23.2.0. Thank you!

![image](https://github.com/nipreps/fmriprep/assets/15076450/765461c8-3ba7-4336-beff-aa4912523d60)
