### ISSUE TITLE
Track sources with DatasetLinks and BIDS-URIs

### ISSUE THREAD

**Issue by tsalo** [nipreps/fmriprep#3252]
### What would you like to see added in fMRIPrep?

I was thinking it would be nice to output `Sources` metadata fields for all outputs, using `DatasetLinks` and BIDS URIs to track the files.

`DatasetLinks` and BIDS URIs were added in 1.8.0, so we would need to increase the `BIDSVersion` to at least 1.8.0.

### Do you have any interest in helping implement the feature?

Yes

### Additional information / screenshots

I've had some success doing this in XCP-D, and I think it would be even easier in fMRIPrep since we could put a `DatasetLinks` field in the Config object.

**Comment by effigies** [comment]
@tsalo Could you redo #3255 with the latest changes in #3292 merged into master? I didn't want to try to do it in a merge commit.

**Comment by tsalo** [comment]
Sorry, I'm a little confused. It doesn't look like the changes in #3255 were reverted in master when you merged in #3292. Am I missing something?

**Comment by effigies** [comment]
The `ds_boldmask_wf` workflow that got pulled out in `maint/23.2.x` still has `RawSources`. When I merged the latest release into master (2e863b777c79a320597c5628783b4ac0a3f1321e), I did not try to merge it "as if" you had split the workflow out from the current state of `master`.

**Comment by tsalo** [comment]
Ohhh okay. I'll take a look at that then.
