### ISSUE TITLE
Allow `--derivatives` to be named

### ISSUE THREAD

**Issue by tsalo** [nipreps/fmriprep#3260]
### What would you like to see added in fMRIPrep?

In #3252, we started creating DatasetLinks for derivative datasets passed through the `--derivatives` parameter. However, because there's no easy way to infer what each derivative dataset actually is, we're labeling them as `deriv-<index>` in the DatasetLinks. I think the DatasetLinks and BIDS URIs throughout the derivatives would be more interpretable if users could label their input derivative datsets.

### Do you have any interest in helping implement the feature?

Yes

### Additional information / screenshots

I was thinking something like:

```
fmriprep ... --derivatives smriprep=/path/to/smriprep
```

**Comment by effigies** [comment]
Yes. I believe I actually implemented this in the wrapper but not the actual cli. I agree this is where we should go.
