### ISSUE TITLE
Issues in final preprocessing run

### ISSUE THREAD

**Issue by NeuroJo-RA** [nipreps/fmriprep#3317]
### What happened?

I'm very new to fmriprep. I followed a tutorial to have it installed with docker and then after running our BIDS formatted data, i didn't receive any images. I used ezBIDS to format the raw data from the scan. I could really use some guidance on anything that you all could tell me about where I went wrong. 

[crash-20240624-203327-root-rotime-84ae02c3-66b0-41cd-9d14-3b36da1df16e.txt](https://github.com/user-attachments/files/16074432/crash-20240624-203327-root-rotime-84ae02c3-66b0-41cd-9d14-3b36da1df16e.txt)

### What command did you use?

```shell
#User inputs:
bids_root_dir=$HOME/Downloads/bids2
subj=01
nthreads=4
mem=20 #gb
container=docker 

#Begin:

#Convert virtual memory from gb to mb
mem=`echo "${mem//[!0-9]/}"` #remove gb at end
mem_mb=`echo $(((mem*1000)-5000))` #reduce some memory for buffer space during pre-processing

#export TEMPLATEFLOW_HOME=$HOME/.cache/templateflow
export FS_LICENSE=$HOME/Downloads/freesurferlicense.txt

#Run fmriprep
  fmriprep-docker $bids_root_dir $bids_root_dir/derivatives \
    participant \
    --participant-label $subj \
    --skip-bids-validation \
    --md-only-boilerplate \
    --fs-license-file $HOME/Downloads/license.txt \
    --fs-no-reconall \
    --output-spaces MNI152NLin2009cAsym:res-2 \
    --nthreads $nthreads \
    --stop-on-first-crash \
    --mem_mb $mem_mb
```

### What version of fMRIPrep are you running?

fMRIPrep 23.2.3

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by tsalo** [comment]
It looks like your field maps or BOLD scans are missing the PhaseEncodingDirection metadata field. For what it's worth, the validator would probably catch that for you, since it's a recommended field for BOLD data and required for PEPOLAR-style field maps. If you don't absolutely have to, I'd recommend dropping `--skip-bids-validation` when you run fMRIPrep.

**Comment by NeuroJo-RA** [comment]
Great! I'll drop the skip from the bash file. Could you tell me where I could acquire the PhaseEncodingDirection metadata field? Is that something that I enter manually or is it acquired at the time of the scan? Sorry, if that's very obvious information.

**Comment by tsalo** [comment]
It's typically extracted from the DICOMs and added automatically to the JSON files by dcm2niix (or whatever dicom-to-nifti conversion tool you use). You can find it in the DICOMs if you have them, or the protocol PDF (at least for Siemens scans).

**Comment by mgxd** [comment]
Please reopen if not resolved
