### ISSUE TITLE
20.2.8 release?

### ISSUE THREAD

**Issue by effigies** [nipreps/fmriprep#3329]
I've updated the LTS changelog post-20.2.7 (Jan 2022):

https://github.com/nipreps/fmriprep/blob/51cbfedfb4d18ced05a44b40b8f920749c02ba8f/CHANGES.rst?plain=1#L1-L21

Bug-fix PRs:

* #3257
* https://github.com/nipreps/sdcflows/pull/431
* https://github.com/nipreps/sdcflows/pull/371
* https://github.com/nipreps/sdcflows/pull/128
* nipreps/niworkflows#747
* nipreps/niworkflows#703
* nipreps/niworkflows#679

Most of the fixes affect tests, resolve bugs discovered in our own uses (which abandoned 20.2.x a long time ago), or fix problems for users building their own environments (and the niworkflows/sdcflows releases resolved those).

Only nipreps/niworkflows#679 addresses a specific user-reported bug in our published containers. Given that it came 2 months after the 20.2.7 release, we were probably expecting more, but it's been two more years and almost all PRs are just keeping the thing building.

Should we go ahead and release? Or is 20.2.7 demonstrably "fine" at this point? @bpinsard @mgxd @HippocampusGirl?

Diffs:

* fMRIPrep: https://github.com/nipreps/fmriprep/compare/20.2.7...maint/20.2.x
* SDCFlows: https://github.com/nipreps/sdcflows/compare/1.3.3...1.3.5
* Niworkflows: https://github.com/nipreps/niworkflows/compare/1.3.5...1.3.10

**Comment by HippocampusGirl** [comment]
This sounds like a great idea! I'm all in favor of keeping the LTS going with new patch releases (at least until there is a new major LTS release)

**Comment by mgxd** [comment]
Agreed on cutting a new release - no bug fix left behind!

**Comment by effigies** [comment]
We would like to have a new LTS by the end of the year. I don't think I want to extend 20.2.x beyond the original Sept 2024 support period, given the difficulty of keeping images building with the same versions of Python packages.

That said, we've been able to sit on 20.2.7 for two years, so I think we can tentatively count on 20.2.8 being a final release.

**Comment by bpinsard** [comment]
It's a great idea to have a final release.

**Comment by effigies** [comment]
https://github.com/nipreps/fmriprep/releases/tag/20.2.8
