### ISSUE TITLE
Replace `config.execution.fmriprep_dir` uses in BIDSURI calls with `output_dir` parameter

### ISSUE THREAD

**Issue by tsalo** [nipreps/fmriprep#3337]
### What would you like to see added in fMRIPrep?

All of the workflows in fMRIPrep that currently use `BIDSURI` to track sources currently rely on `config.execution.fmriprep_dir` for the output directory, and yet all of those functions have an `output_dir` parameter.

It would be easier for other preps that use fMRIPrep as a dependency (i.e., ASLPrep) if we used `output_dir` instead of the config object's package-specific `fmriprep_dir` field.

### Do you have any interest in helping implement the feature?

Yes

### Additional information / screenshots

I think I completely overlooked the `output_dir` parameter when I started implementing `BIDSURI`-based source tracking (#3255, #3262, #3263, #3297) because I originally wanted to reference the config object directly _within_ the `BIDSURI` interface, which ended up not working.

**Comment by effigies** [comment]
Sounds good to me.
