### ISSUE TITLE
inflated.surf.gii and smoothwm.surf.gii are missing

### ISSUE THREAD

**Issue by hx-mao** [nipreps/fmriprep#3339]
I use the freesurfer dev and fMRIPrep 23.1.4 to preprocess the functional MRI data by singularity. But it does not generate the files sub-001_hemi-L_inflated.surf.gii ,sub-001_hemi-R_inflated.surf.gii, sub-001_hemi-L_smoothwm.surf.gii, and sub-001_hemi-R_smoothwm.surf.gii.
the script is as follows:
singularity run --cleanenv \
    --bind /autofs/cluster/neuromind/haixia/data/BIDS:/data \
    --bind /autofs/cluster/neuromind/haixia/output:/out \
    --bind /autofs/vast/freesurfer/.license:/fs-license \
    fmriprep.sif \
    /data /out participant \
    --participant-label sub-001 \
    --fs-license-file /fs-license \
    --nthreads 8 \
    --mem-mb 16000 \
--work-dir /out/work \
--output-spaces T1w MNI152NLin6Asym:res-2 fsLR \
--cifti-output 91k
The result of freesurfer is in picture1.
![freesurfer](https://github.com/user-attachments/assets/2e5a0078-aa6f-47ac-8e89-ea1534a0607d)
The result of fMRIPrep is in picture2.
![fMRIPrep](https://github.com/user-attachments/assets/0b461e8f-2634-4a4b-b645-a691c7f621ea)

**Comment by tsalo** [comment]
They changed smoothwm to white. I don't think the inflated surface is written out by fmriprep.
