### ISSUE TITLE
nipreps/fmriprep:20.2.8 missing

### ISSUE THREAD

**Issue by gdevenyi** [nipreps/fmriprep#3345]
While there is a 20.2.8 release, the container on dockerhub appears to be misisng.

**Comment by effigies** [comment]
I can't remember if we chose not to do this for some reason or if the process just failed. Assigning myself to remind me to look into this next week. Please bump this issue if I haven't gotten back to it by the end of next week.

**Comment by bpinsard** [comment]
Oh that's part of the reason repronim isn't getting it  https://github.com/ReproNim/containers/issues/128 
I don't remember any decision to not release on dockerhub, so it is likely a failed job.

**Comment by bpinsard** [comment]
Out of curiosity, where does the docker build+push occurs? It's not on GH-action, nor CircleCI. 
Where does the mysterious _niprepsbot_ lives?

**Comment by effigies** [comment]
It is in CircleCI. It didn't seem to do anything: https://app.circleci.com/pipelines/github/nipreps/fmriprep/2285/workflows/c987eca0-cc9e-47b3-8427-5d779d0df4c3/jobs/11923

**Comment by effigies** [comment]
@oesteban I was going to upload manually, but my user (`markiewicz`) doesn't have permissions on the nipreps organization. Could you either Signal me the `niprepsbot` credentials or push, yourself?

```bash
git clone --filter=blob:none https://github.com/nipreps/fmriprep
cd fmriprep
git checkout 20.2.8
docker build --cache-from=nipreps/fmriprep:20.2.7 -t nipreps/fmriprep:20.2.8 \
    --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
    --build-arg VCS_REF=`git rev-parse --short HEAD` \
    --build-arg VERSION="20.2.8" .
docker push nipreps/fmriprep:20.2.8
```

**Comment by effigies** [comment]
In the short term, I've pushed one to `markiewicz/fmriprep:20.2.8`.

@oesteban The fastest thing would just be

```
docker pull markiewicz/fmriprep:20.2.8
docker tag markiewicz/fmriprep:20.2.8 nipreps/fmriprep:20.2.8
docker push nipreps/fmriprep:20.2.8
```

**Comment by oesteban** [comment]
done

**Comment by effigies** [comment]
Thanks!
