### ISSUE TITLE
Issue: Data Orientation Bug in Preprocessed Functional Data 'preproc_bold'

### ISSUE THREAD

**Issue by caroleguedj** [nipreps/fmriprep#3385]
### What happened?

I have encountered a data orientation bug affecting the preprocessed functional data in multiple participants. The issue is particularly unusual because:
- The .html reports do not show any anomalies; everything appears normal.
- No errors or warnings are flagged during processing.
- The masks and anatomical data are correctly oriented.
I have been using fMRIPrep for several years without facing this issue previously. This is the first time I have encountered a data orientation problem in the functional outputs. An other point is that the fieldmaps seems to be ignore even though I do mention the 'IntendedFor' param in their .json .

### What command did you use?

```shell
docker context use rootless
bids_root_dir="my_path"
subjects=("001")

for subj in "${subjects[@]}"; do
  echo "Processing subject $subj"
  docker run --rm -it -v $bids_root_dir/sourcedata:/data:ro \
    -v $bids_root_dir/derivatives:/out \
    -v $FREESURFER_HOME:/freesurfer nipreps/fmriprep:latest \
    /data /out participant \
    --participant-label $subj \
    --fs-license-file /freesurfer/license.txt \
    --md-only-boilerplate \
    --output-spaces MNIPediatricAsym:cohort-2:res-native \
    --stop-on-first-crash \
    --fd-spike-threshold 2 \
    --dvars-spike-threshold 6 \
	--fs-no-reconall \
    -w /scratch
done
```

### What version of fMRIPrep are you running?

fMRIPrep-24.1.0rc0

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
For bids, if I use the command-line BIDS validator I have no error, if I use the website BIDS validator, I have the error below and some warnings about sidecars.
ERROR: REPETITION_TIME_AND_ACQUISITION_DURATION_MUTUALLY_EXCLUSIVE
```

**Comment by effigies** [comment]
Thanks for the report! Could you share logs and/or screenshots of the errors you're seeing?

**Comment by tsalo** [comment]
@effigies I think this is probably the result of the nitransforms 24.0.0 bug that affected fMRIPrep 24.1.0rc0.

**Comment by effigies** [comment]
Seems plausible. @caroleguedj Please upgrade to the latest release and see if you get the same result.

**Comment by caroleguedj** [comment]
Many thanks, updating fmriprep with the version 24.1.1. solved the issue!!
However, it still ignore the field maps in the preprocessing.

**Comment by effigies** [comment]
Can you share the file layout for a subject, and the contents of a fieldmap's JSON sidecar that's failing to be applied?

**Comment by effigies** [comment]
Ah, the BIDS-URI support has a bug in that version. Should be fixed in the next release. In the meantime, you can revert to subject-relative paths, so:

```yaml
"IntendedFor": [
        "ses-t0/func/sub-001_ses-t0_task-visuoWM_run-01_bold.nii.gz",
        "ses-t0/func/sub-001_ses-t0_task-rest_run-01_bold.nii.gz"
    ]
```

**Comment by caroleguedj** [comment]
thanks!! :-)
