### ISSUE TITLE
Missing preproc bold series nifti when running with fsnative space

### ISSUE THREAD

**Issue by nicklbch** [nipreps/fmriprep#3405]
### What happened?

Hello, I am trying to run fmriprep to get outputs within the native space. Particularity I am interested in getting the preproc bold  output in the fsnative space. I have successfully gotten this output in the MNI152 space under the func folder as  sub-[ID]_ses-[SESSION]_task-rest_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz. However when using the --output-spaces=fsnative flag, I no longer get a bold preproc output in the func folder.

### What command did you use?

```shell
docker run --rm -e DOCKER_VERSION_8395080871=24.0.5 -it -v <LICENSE FILE PATH>:ro -v <BIDS FORMATTED DATA FILE PATH>:/data:ro -v <OUTPUT PATH>:/out nipreps/fmriprep:24.1.0 --output-spaces=fsnative -vvv /data /out participant --participant-label <LABEL>
```

### What version of fMRIPrep are you running?

24.1.0

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by nicklbch** [comment]
I just ran this through with the --output-spaces fsnative MNI152NLin2009cAsym tag and I am only getting the preproc nifti MNI152NLin2009cAsym space. Is it possible to also get the fsnative preproc nifti? Attached below are the func outputs from the pipeline

sub-[ID]_ses-[SESSION]_task-rest_desc-brain_mask.json                                sub-[ID]_ses-[SESSION]_task-rest_from-orig_to-boldref_mode-image_desc-hmc_xfm.txt
sub-[ID]_ses-[SESSION]_task-rest_desc-brain_mask.nii.gz                              sub-[ID]_ses-[SESSION]_task-rest_hemi-L_space-fsnative_bold.func.gii
sub-[ID]_ses-[SESSION]_task-rest_desc-confounds_timeseries.json                      sub-[ID]_ses-[SESSION]_task-rest_hemi-L_space-fsnative_bold.json
sub-[ID]_ses-[SESSION]_task-rest_desc-confounds_timeseries.tsv                       sub-[ID]_ses-[SESSION]_task-rest_hemi-R_space-fsnative_bold.func.gii
sub-[ID]_ses-[SESSION]_task-rest_desc-coreg_boldref.json                             sub-[ID]_ses-[SESSION]_task-rest_hemi-R_space-fsnative_bold.json
sub-[ID]_ses-[SESSION]_task-rest_desc-coreg_boldref.nii.gz                           sub-[ID]_ses-[SESSION]_task-rest_space-MNI152NLin2009cAsym_boldref.json
sub-[ID]_ses-[SESSION]_task-rest_desc-hmc_boldref.json                               sub-[ID]_ses-[SESSION]_task-rest_space-MNI152NLin2009cAsym_boldref.nii.gz
sub-[ID]_ses-[SESSION]_task-rest_desc-hmc_boldref.nii.gz                             sub-[ID]_ses-[SESSION]_task-rest_space-MNI152NLin2009cAsym_desc-brain_mask.json
sub-[ID]_ses-[SESSION]_task-rest_from-boldref_to-T1w_mode-image_desc-coreg_xfm.json  sub-[ID]_ses-[SESSION]_task-rest_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
sub-[ID]_ses-[SESSION]_task-rest_from-boldref_to-T1w_mode-image_desc-coreg_xfm.txt   sub-[ID]_ses-[SESSION]_task-rest_space-MNI152NLin2009cAsym_desc-preproc_bold.json
sub-[ID]_ses-[SESSION]_task-rest_from-orig_to-boldref_mode-image_desc-hmc_xfm.json   sub-[ID]_ses-[SESSION]_task-rest_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz

**Comment by tsalo** [comment]
You have preprocessed data in fsnative space though? fsnative isn't a volumetric space, so you won't get NIfTIs in fsnative space.

```
sub-[ID]_ses-[SESSION]_task-rest_hemi-L_space-fsnative_bold.func.gii
sub-[ID]_ses-[SESSION]_task-rest_hemi-R_space-fsnative_bold.func.gii
```

**Comment by nicklbch** [comment]
Thank you, My goal is to get nifti outputs based upon the native space of the original data passed through fmriprep so perhaps fsnative is not the correct output space I was looking for. Does fmriprep have this capability?

**Comment by tsalo** [comment]
You probably want either the BOLD run's native space (set `--output-spaces` to func, bold, run, boldref or sbref) or the anatomical data's native space (set `--output-spaces` to T1w or anat). See https://fmriprep.org/en/stable/spaces.html#nonstandard-spaces for more info on those.
